// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agreements.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAgreement = `-- name: CreateAgreement :one
INSERT INTO hrms.agreements (
    tenant_id, agreement_type, title, template_id, worker_profile_id, engagement_id, project_id,
    subject, rendered_html, status, issue_date, effective_date, end_date, pdf_path, signature_token,
    signature_requested_at, signer_email, metadata, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $19
)
RETURNING id, tenant_id, agreement_type, title, template_id, worker_profile_id, engagement_id, project_id, subject, rendered_html, status, issue_date, effective_date, end_date, pdf_path, version, is_latest, sent_at, revoked_at, signature_token, signature_requested_at, signature_completed_at, signer_name, signer_email, signer_ip, signer_user_agent, signature_hash, audit_certificate_url, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateAgreementParams struct {
	TenantID             uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	AgreementType        string             `db:"agreement_type" json:"agreement_type"`
	Title                string             `db:"title" json:"title"`
	TemplateID           pgtype.UUID        `db:"template_id" json:"template_id"`
	WorkerProfileID      pgtype.UUID        `db:"worker_profile_id" json:"worker_profile_id"`
	EngagementID         pgtype.UUID        `db:"engagement_id" json:"engagement_id"`
	ProjectID            pgtype.UUID        `db:"project_id" json:"project_id"`
	Subject              pgtype.Text        `db:"subject" json:"subject"`
	RenderedHtml         pgtype.Text        `db:"rendered_html" json:"rendered_html"`
	Status               string             `db:"status" json:"status"`
	IssueDate            pgtype.Date        `db:"issue_date" json:"issue_date"`
	EffectiveDate        pgtype.Date        `db:"effective_date" json:"effective_date"`
	EndDate              pgtype.Date        `db:"end_date" json:"end_date"`
	PdfPath              pgtype.Text        `db:"pdf_path" json:"pdf_path"`
	SignatureToken       pgtype.Text        `db:"signature_token" json:"signature_token"`
	SignatureRequestedAt pgtype.Timestamptz `db:"signature_requested_at" json:"signature_requested_at"`
	SignerEmail          pgtype.Text        `db:"signer_email" json:"signer_email"`
	Metadata             []byte             `db:"metadata" json:"metadata"`
	CreatedBy            pgtype.UUID        `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAgreement(ctx context.Context, arg CreateAgreementParams) (HrmsAgreement, error) {
	row := q.db.QueryRow(ctx, createAgreement,
		arg.TenantID,
		arg.AgreementType,
		arg.Title,
		arg.TemplateID,
		arg.WorkerProfileID,
		arg.EngagementID,
		arg.ProjectID,
		arg.Subject,
		arg.RenderedHtml,
		arg.Status,
		arg.IssueDate,
		arg.EffectiveDate,
		arg.EndDate,
		arg.PdfPath,
		arg.SignatureToken,
		arg.SignatureRequestedAt,
		arg.SignerEmail,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsAgreement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementType,
		&i.Title,
		&i.TemplateID,
		&i.WorkerProfileID,
		&i.EngagementID,
		&i.ProjectID,
		&i.Subject,
		&i.RenderedHtml,
		&i.Status,
		&i.IssueDate,
		&i.EffectiveDate,
		&i.EndDate,
		&i.PdfPath,
		&i.Version,
		&i.IsLatest,
		&i.SentAt,
		&i.RevokedAt,
		&i.SignatureToken,
		&i.SignatureRequestedAt,
		&i.SignatureCompletedAt,
		&i.SignerName,
		&i.SignerEmail,
		&i.SignerIp,
		&i.SignerUserAgent,
		&i.SignatureHash,
		&i.AuditCertificateUrl,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createAgreementEvent = `-- name: CreateAgreementEvent :one
INSERT INTO hrms.agreement_events (
    tenant_id, agreement_id, from_status, to_status, action, remarks, actor_email,
    ip_address, user_agent, metadata, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $11
)
RETURNING id, tenant_id, agreement_id, from_status, to_status, action, remarks, actor_email, ip_address, user_agent, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateAgreementEventParams struct {
	TenantID    uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	AgreementID uuid.UUID   `db:"agreement_id" json:"agreement_id"`
	FromStatus  pgtype.Text `db:"from_status" json:"from_status"`
	ToStatus    string      `db:"to_status" json:"to_status"`
	Action      string      `db:"action" json:"action"`
	Remarks     pgtype.Text `db:"remarks" json:"remarks"`
	ActorEmail  pgtype.Text `db:"actor_email" json:"actor_email"`
	IpAddress   *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent   pgtype.Text `db:"user_agent" json:"user_agent"`
	Metadata    []byte      `db:"metadata" json:"metadata"`
	CreatedBy   pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAgreementEvent(ctx context.Context, arg CreateAgreementEventParams) (HrmsAgreementEvent, error) {
	row := q.db.QueryRow(ctx, createAgreementEvent,
		arg.TenantID,
		arg.AgreementID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Action,
		arg.Remarks,
		arg.ActorEmail,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsAgreementEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Action,
		&i.Remarks,
		&i.ActorEmail,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createAgreementTemplate = `-- name: CreateAgreementTemplate :one
INSERT INTO hrms.agreement_templates (
    tenant_id, agreement_type, name, description, subject, body_html, footer_html,
    locale, is_default, is_active, metadata, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12
)
RETURNING id, tenant_id, agreement_type, name, description, subject, body_html, footer_html, locale, is_default, is_active, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateAgreementTemplateParams struct {
	TenantID      uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	AgreementType string      `db:"agreement_type" json:"agreement_type"`
	Name          string      `db:"name" json:"name"`
	Description   pgtype.Text `db:"description" json:"description"`
	Subject       pgtype.Text `db:"subject" json:"subject"`
	BodyHtml      string      `db:"body_html" json:"body_html"`
	FooterHtml    pgtype.Text `db:"footer_html" json:"footer_html"`
	Locale        string      `db:"locale" json:"locale"`
	IsDefault     bool        `db:"is_default" json:"is_default"`
	IsActive      bool        `db:"is_active" json:"is_active"`
	Metadata      []byte      `db:"metadata" json:"metadata"`
	CreatedBy     pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAgreementTemplate(ctx context.Context, arg CreateAgreementTemplateParams) (HrmsAgreementTemplate, error) {
	row := q.db.QueryRow(ctx, createAgreementTemplate,
		arg.TenantID,
		arg.AgreementType,
		arg.Name,
		arg.Description,
		arg.Subject,
		arg.BodyHtml,
		arg.FooterHtml,
		arg.Locale,
		arg.IsDefault,
		arg.IsActive,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsAgreementTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementType,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.BodyHtml,
		&i.FooterHtml,
		&i.Locale,
		&i.IsDefault,
		&i.IsActive,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAgreement = `-- name: GetAgreement :one
SELECT id, tenant_id, agreement_type, title, template_id, worker_profile_id, engagement_id, project_id, subject, rendered_html, status, issue_date, effective_date, end_date, pdf_path, version, is_latest, sent_at, revoked_at, signature_token, signature_requested_at, signature_completed_at, signer_name, signer_email, signer_ip, signer_user_agent, signature_hash, audit_certificate_url, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.agreements
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetAgreementParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAgreement(ctx context.Context, arg GetAgreementParams) (HrmsAgreement, error) {
	row := q.db.QueryRow(ctx, getAgreement, arg.TenantID, arg.ID)
	var i HrmsAgreement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementType,
		&i.Title,
		&i.TemplateID,
		&i.WorkerProfileID,
		&i.EngagementID,
		&i.ProjectID,
		&i.Subject,
		&i.RenderedHtml,
		&i.Status,
		&i.IssueDate,
		&i.EffectiveDate,
		&i.EndDate,
		&i.PdfPath,
		&i.Version,
		&i.IsLatest,
		&i.SentAt,
		&i.RevokedAt,
		&i.SignatureToken,
		&i.SignatureRequestedAt,
		&i.SignatureCompletedAt,
		&i.SignerName,
		&i.SignerEmail,
		&i.SignerIp,
		&i.SignerUserAgent,
		&i.SignatureHash,
		&i.AuditCertificateUrl,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAgreementBySignatureToken = `-- name: GetAgreementBySignatureToken :one
SELECT id, tenant_id, agreement_type, title, template_id, worker_profile_id, engagement_id, project_id, subject, rendered_html, status, issue_date, effective_date, end_date, pdf_path, version, is_latest, sent_at, revoked_at, signature_token, signature_requested_at, signature_completed_at, signer_name, signer_email, signer_ip, signer_user_agent, signature_hash, audit_certificate_url, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.agreements
WHERE signature_token = $1 AND NOT inactive
`

func (q *Queries) GetAgreementBySignatureToken(ctx context.Context, signatureToken pgtype.Text) (HrmsAgreement, error) {
	row := q.db.QueryRow(ctx, getAgreementBySignatureToken, signatureToken)
	var i HrmsAgreement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementType,
		&i.Title,
		&i.TemplateID,
		&i.WorkerProfileID,
		&i.EngagementID,
		&i.ProjectID,
		&i.Subject,
		&i.RenderedHtml,
		&i.Status,
		&i.IssueDate,
		&i.EffectiveDate,
		&i.EndDate,
		&i.PdfPath,
		&i.Version,
		&i.IsLatest,
		&i.SentAt,
		&i.RevokedAt,
		&i.SignatureToken,
		&i.SignatureRequestedAt,
		&i.SignatureCompletedAt,
		&i.SignerName,
		&i.SignerEmail,
		&i.SignerIp,
		&i.SignerUserAgent,
		&i.SignatureHash,
		&i.AuditCertificateUrl,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAgreementTemplate = `-- name: GetAgreementTemplate :one
SELECT id, tenant_id, agreement_type, name, description, subject, body_html, footer_html, locale, is_default, is_active, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.agreement_templates
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetAgreementTemplateParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAgreementTemplate(ctx context.Context, arg GetAgreementTemplateParams) (HrmsAgreementTemplate, error) {
	row := q.db.QueryRow(ctx, getAgreementTemplate, arg.TenantID, arg.ID)
	var i HrmsAgreementTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementType,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.BodyHtml,
		&i.FooterHtml,
		&i.Locale,
		&i.IsDefault,
		&i.IsActive,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getDefaultAgreementTemplate = `-- name: GetDefaultAgreementTemplate :one
SELECT id, tenant_id, agreement_type, name, description, subject, body_html, footer_html, locale, is_default, is_active, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.agreement_templates
WHERE tenant_id = $1 AND agreement_type = $2 AND is_default AND is_active AND NOT inactive
ORDER BY updated_at DESC
LIMIT 1
`

type GetDefaultAgreementTemplateParams struct {
	TenantID      uuid.UUID `db:"tenant_id" json:"tenant_id"`
	AgreementType string    `db:"agreement_type" json:"agreement_type"`
}

func (q *Queries) GetDefaultAgreementTemplate(ctx context.Context, arg GetDefaultAgreementTemplateParams) (HrmsAgreementTemplate, error) {
	row := q.db.QueryRow(ctx, getDefaultAgreementTemplate, arg.TenantID, arg.AgreementType)
	var i HrmsAgreementTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementType,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.BodyHtml,
		&i.FooterHtml,
		&i.Locale,
		&i.IsDefault,
		&i.IsActive,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listAgreementEvents = `-- name: ListAgreementEvents :many
SELECT id, tenant_id, agreement_id, from_status, to_status, action, remarks, actor_email, ip_address, user_agent, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.agreement_events
WHERE tenant_id = $1 AND agreement_id = $2 AND NOT inactive
ORDER BY created_at DESC
`

type ListAgreementEventsParams struct {
	TenantID    uuid.UUID `db:"tenant_id" json:"tenant_id"`
	AgreementID uuid.UUID `db:"agreement_id" json:"agreement_id"`
}

func (q *Queries) ListAgreementEvents(ctx context.Context, arg ListAgreementEventsParams) ([]HrmsAgreementEvent, error) {
	rows, err := q.db.Query(ctx, listAgreementEvents, arg.TenantID, arg.AgreementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAgreementEvent
	for rows.Next() {
		var i HrmsAgreementEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgreementID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Action,
			&i.Remarks,
			&i.ActorEmail,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgreementTemplates = `-- name: ListAgreementTemplates :many
SELECT id, tenant_id, agreement_type, name, description, subject, body_html, footer_html, locale, is_default, is_active, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.agreement_templates
WHERE tenant_id = $1
  AND ($2::text IS NULL OR agreement_type = $2::text)
  AND NOT inactive
ORDER BY agreement_type, is_default DESC, name
`

type ListAgreementTemplatesParams struct {
	TenantID      uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	AgreementType pgtype.Text `db:"agreement_type" json:"agreement_type"`
}

func (q *Queries) ListAgreementTemplates(ctx context.Context, arg ListAgreementTemplatesParams) ([]HrmsAgreementTemplate, error) {
	rows, err := q.db.Query(ctx, listAgreementTemplates, arg.TenantID, arg.AgreementType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAgreementTemplate
	for rows.Next() {
		var i HrmsAgreementTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgreementType,
			&i.Name,
			&i.Description,
			&i.Subject,
			&i.BodyHtml,
			&i.FooterHtml,
			&i.Locale,
			&i.IsDefault,
			&i.IsActive,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgreements = `-- name: ListAgreements :many
SELECT
    a.id,
    a.tenant_id,
    a.agreement_type,
    a.title,
    a.template_id,
    t.name AS template_name,
    a.worker_profile_id,
    wp.display_name AS worker_display_name,
    wp.worker_code,
    a.engagement_id,
    e.title AS engagement_title,
    e.engagement_code,
    a.project_id,
    p.name AS project_name,
    p.project_code,
    a.subject,
    a.rendered_html,
    a.status,
    a.issue_date,
    a.effective_date,
    a.end_date,
    a.pdf_path,
    a.version,
    a.is_latest,
    a.sent_at,
    a.revoked_at,
    a.signature_token,
    a.signature_requested_at,
    a.signature_completed_at,
    a.signer_name,
    a.signer_email,
    a.signer_ip,
    a.signer_user_agent,
    a.signature_hash,
    a.audit_certificate_url,
    a.metadata,
    a.inactive,
    a.created_at,
    a.created_by,
    a.updated_at,
    a.updated_by
FROM hrms.agreements a
LEFT JOIN hrms.agreement_templates t ON t.tenant_id = a.tenant_id AND t.id = a.template_id AND NOT t.inactive
LEFT JOIN hrms.worker_profiles wp ON wp.tenant_id = a.tenant_id AND wp.id = a.worker_profile_id AND NOT wp.inactive
LEFT JOIN hrms.engagements e ON e.tenant_id = a.tenant_id AND e.id = a.engagement_id AND NOT e.inactive
LEFT JOIN hrms.projects p ON p.tenant_id = a.tenant_id AND p.id = a.project_id AND NOT p.inactive
WHERE a.tenant_id = $1
  AND ($2::text IS NULL OR a.agreement_type = $2::text)
  AND ($3::text IS NULL OR a.status = $3::text)
  AND ($4::uuid IS NULL OR a.worker_profile_id = $4::uuid)
  AND ($5::uuid IS NULL OR a.engagement_id = $5::uuid)
  AND ($6::uuid IS NULL OR a.project_id = $6::uuid)
  AND (
      $7::text IS NULL
      OR a.title ILIKE '%' || $7::text || '%'
      OR a.subject ILIKE '%' || $7::text || '%'
      OR wp.display_name ILIKE '%' || $7::text || '%'
      OR e.title ILIKE '%' || $7::text || '%'
      OR p.name ILIKE '%' || $7::text || '%'
  )
  AND NOT a.inactive
ORDER BY
    CASE a.status WHEN 'Generated' THEN 0 WHEN 'Approved' THEN 1 WHEN 'Sent' THEN 2 WHEN 'Signed' THEN 3 ELSE 4 END,
    a.updated_at DESC
`

type ListAgreementsParams struct {
	TenantID        uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	AgreementType   pgtype.Text `db:"agreement_type" json:"agreement_type"`
	Status          pgtype.Text `db:"status" json:"status"`
	WorkerProfileID pgtype.UUID `db:"worker_profile_id" json:"worker_profile_id"`
	EngagementID    pgtype.UUID `db:"engagement_id" json:"engagement_id"`
	ProjectID       pgtype.UUID `db:"project_id" json:"project_id"`
	Search          pgtype.Text `db:"search" json:"search"`
}

type ListAgreementsRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	TenantID             uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	AgreementType        string             `db:"agreement_type" json:"agreement_type"`
	Title                string             `db:"title" json:"title"`
	TemplateID           pgtype.UUID        `db:"template_id" json:"template_id"`
	TemplateName         pgtype.Text        `db:"template_name" json:"template_name"`
	WorkerProfileID      pgtype.UUID        `db:"worker_profile_id" json:"worker_profile_id"`
	WorkerDisplayName    pgtype.Text        `db:"worker_display_name" json:"worker_display_name"`
	WorkerCode           pgtype.Text        `db:"worker_code" json:"worker_code"`
	EngagementID         pgtype.UUID        `db:"engagement_id" json:"engagement_id"`
	EngagementTitle      pgtype.Text        `db:"engagement_title" json:"engagement_title"`
	EngagementCode       pgtype.Text        `db:"engagement_code" json:"engagement_code"`
	ProjectID            pgtype.UUID        `db:"project_id" json:"project_id"`
	ProjectName          pgtype.Text        `db:"project_name" json:"project_name"`
	ProjectCode          pgtype.Text        `db:"project_code" json:"project_code"`
	Subject              pgtype.Text        `db:"subject" json:"subject"`
	RenderedHtml         pgtype.Text        `db:"rendered_html" json:"rendered_html"`
	Status               string             `db:"status" json:"status"`
	IssueDate            pgtype.Date        `db:"issue_date" json:"issue_date"`
	EffectiveDate        pgtype.Date        `db:"effective_date" json:"effective_date"`
	EndDate              pgtype.Date        `db:"end_date" json:"end_date"`
	PdfPath              pgtype.Text        `db:"pdf_path" json:"pdf_path"`
	Version              int32              `db:"version" json:"version"`
	IsLatest             bool               `db:"is_latest" json:"is_latest"`
	SentAt               pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	SignatureToken       pgtype.Text        `db:"signature_token" json:"signature_token"`
	SignatureRequestedAt pgtype.Timestamptz `db:"signature_requested_at" json:"signature_requested_at"`
	SignatureCompletedAt pgtype.Timestamptz `db:"signature_completed_at" json:"signature_completed_at"`
	SignerName           pgtype.Text        `db:"signer_name" json:"signer_name"`
	SignerEmail          pgtype.Text        `db:"signer_email" json:"signer_email"`
	SignerIp             *netip.Addr        `db:"signer_ip" json:"signer_ip"`
	SignerUserAgent      pgtype.Text        `db:"signer_user_agent" json:"signer_user_agent"`
	SignatureHash        pgtype.Text        `db:"signature_hash" json:"signature_hash"`
	AuditCertificateUrl  pgtype.Text        `db:"audit_certificate_url" json:"audit_certificate_url"`
	Metadata             []byte             `db:"metadata" json:"metadata"`
	Inactive             bool               `db:"inactive" json:"inactive"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy            pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy            pgtype.UUID        `db:"updated_by" json:"updated_by"`
}

func (q *Queries) ListAgreements(ctx context.Context, arg ListAgreementsParams) ([]ListAgreementsRow, error) {
	rows, err := q.db.Query(ctx, listAgreements,
		arg.TenantID,
		arg.AgreementType,
		arg.Status,
		arg.WorkerProfileID,
		arg.EngagementID,
		arg.ProjectID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgreementsRow
	for rows.Next() {
		var i ListAgreementsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgreementType,
			&i.Title,
			&i.TemplateID,
			&i.TemplateName,
			&i.WorkerProfileID,
			&i.WorkerDisplayName,
			&i.WorkerCode,
			&i.EngagementID,
			&i.EngagementTitle,
			&i.EngagementCode,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectCode,
			&i.Subject,
			&i.RenderedHtml,
			&i.Status,
			&i.IssueDate,
			&i.EffectiveDate,
			&i.EndDate,
			&i.PdfPath,
			&i.Version,
			&i.IsLatest,
			&i.SentAt,
			&i.RevokedAt,
			&i.SignatureToken,
			&i.SignatureRequestedAt,
			&i.SignatureCompletedAt,
			&i.SignerName,
			&i.SignerEmail,
			&i.SignerIp,
			&i.SignerUserAgent,
			&i.SignatureHash,
			&i.AuditCertificateUrl,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signAgreement = `-- name: SignAgreement :one
UPDATE hrms.agreements
SET status = 'Signed',
    signature_completed_at = now(),
    signer_name = $2,
    signer_email = $3,
    signer_ip = $4,
    signer_user_agent = $5,
    signature_hash = $6
WHERE signature_token = $1 AND NOT inactive
RETURNING id, tenant_id, agreement_type, title, template_id, worker_profile_id, engagement_id, project_id, subject, rendered_html, status, issue_date, effective_date, end_date, pdf_path, version, is_latest, sent_at, revoked_at, signature_token, signature_requested_at, signature_completed_at, signer_name, signer_email, signer_ip, signer_user_agent, signature_hash, audit_certificate_url, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type SignAgreementParams struct {
	SignatureToken  pgtype.Text `db:"signature_token" json:"signature_token"`
	SignerName      pgtype.Text `db:"signer_name" json:"signer_name"`
	SignerEmail     pgtype.Text `db:"signer_email" json:"signer_email"`
	SignerIp        *netip.Addr `db:"signer_ip" json:"signer_ip"`
	SignerUserAgent pgtype.Text `db:"signer_user_agent" json:"signer_user_agent"`
	SignatureHash   pgtype.Text `db:"signature_hash" json:"signature_hash"`
}

func (q *Queries) SignAgreement(ctx context.Context, arg SignAgreementParams) (HrmsAgreement, error) {
	row := q.db.QueryRow(ctx, signAgreement,
		arg.SignatureToken,
		arg.SignerName,
		arg.SignerEmail,
		arg.SignerIp,
		arg.SignerUserAgent,
		arg.SignatureHash,
	)
	var i HrmsAgreement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementType,
		&i.Title,
		&i.TemplateID,
		&i.WorkerProfileID,
		&i.EngagementID,
		&i.ProjectID,
		&i.Subject,
		&i.RenderedHtml,
		&i.Status,
		&i.IssueDate,
		&i.EffectiveDate,
		&i.EndDate,
		&i.PdfPath,
		&i.Version,
		&i.IsLatest,
		&i.SentAt,
		&i.RevokedAt,
		&i.SignatureToken,
		&i.SignatureRequestedAt,
		&i.SignatureCompletedAt,
		&i.SignerName,
		&i.SignerEmail,
		&i.SignerIp,
		&i.SignerUserAgent,
		&i.SignatureHash,
		&i.AuditCertificateUrl,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const softDeleteAgreement = `-- name: SoftDeleteAgreement :exec
UPDATE hrms.agreements
SET inactive = TRUE,
    status = 'Revoked',
    updated_by = $3
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type SoftDeleteAgreementParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteAgreement(ctx context.Context, arg SoftDeleteAgreementParams) error {
	_, err := q.db.Exec(ctx, softDeleteAgreement, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteAgreementTemplate = `-- name: SoftDeleteAgreementTemplate :exec
UPDATE hrms.agreement_templates
SET inactive = TRUE,
    is_active = FALSE,
    updated_by = $3
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type SoftDeleteAgreementTemplateParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteAgreementTemplate(ctx context.Context, arg SoftDeleteAgreementTemplateParams) error {
	_, err := q.db.Exec(ctx, softDeleteAgreementTemplate, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const updateAgreementPDF = `-- name: UpdateAgreementPDF :one
UPDATE hrms.agreements
SET pdf_path = $3,
    updated_by = $4
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, agreement_type, title, template_id, worker_profile_id, engagement_id, project_id, subject, rendered_html, status, issue_date, effective_date, end_date, pdf_path, version, is_latest, sent_at, revoked_at, signature_token, signature_requested_at, signature_completed_at, signer_name, signer_email, signer_ip, signer_user_agent, signature_hash, audit_certificate_url, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateAgreementPDFParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	PdfPath   pgtype.Text `db:"pdf_path" json:"pdf_path"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateAgreementPDF(ctx context.Context, arg UpdateAgreementPDFParams) (HrmsAgreement, error) {
	row := q.db.QueryRow(ctx, updateAgreementPDF,
		arg.TenantID,
		arg.ID,
		arg.PdfPath,
		arg.UpdatedBy,
	)
	var i HrmsAgreement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementType,
		&i.Title,
		&i.TemplateID,
		&i.WorkerProfileID,
		&i.EngagementID,
		&i.ProjectID,
		&i.Subject,
		&i.RenderedHtml,
		&i.Status,
		&i.IssueDate,
		&i.EffectiveDate,
		&i.EndDate,
		&i.PdfPath,
		&i.Version,
		&i.IsLatest,
		&i.SentAt,
		&i.RevokedAt,
		&i.SignatureToken,
		&i.SignatureRequestedAt,
		&i.SignatureCompletedAt,
		&i.SignerName,
		&i.SignerEmail,
		&i.SignerIp,
		&i.SignerUserAgent,
		&i.SignatureHash,
		&i.AuditCertificateUrl,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateAgreementStatus = `-- name: UpdateAgreementStatus :one
UPDATE hrms.agreements
SET status = $3,
    sent_at = CASE WHEN $3 = 'Sent' THEN now() ELSE sent_at END,
    revoked_at = CASE WHEN $3 = 'Revoked' THEN now() ELSE revoked_at END,
    signature_requested_at = CASE WHEN $3 = 'Sent' AND signature_token IS NOT NULL THEN now() ELSE signature_requested_at END,
    updated_by = $4
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, agreement_type, title, template_id, worker_profile_id, engagement_id, project_id, subject, rendered_html, status, issue_date, effective_date, end_date, pdf_path, version, is_latest, sent_at, revoked_at, signature_token, signature_requested_at, signature_completed_at, signer_name, signer_email, signer_ip, signer_user_agent, signature_hash, audit_certificate_url, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateAgreementStatusParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	Status    string      `db:"status" json:"status"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateAgreementStatus(ctx context.Context, arg UpdateAgreementStatusParams) (HrmsAgreement, error) {
	row := q.db.QueryRow(ctx, updateAgreementStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
	)
	var i HrmsAgreement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementType,
		&i.Title,
		&i.TemplateID,
		&i.WorkerProfileID,
		&i.EngagementID,
		&i.ProjectID,
		&i.Subject,
		&i.RenderedHtml,
		&i.Status,
		&i.IssueDate,
		&i.EffectiveDate,
		&i.EndDate,
		&i.PdfPath,
		&i.Version,
		&i.IsLatest,
		&i.SentAt,
		&i.RevokedAt,
		&i.SignatureToken,
		&i.SignatureRequestedAt,
		&i.SignatureCompletedAt,
		&i.SignerName,
		&i.SignerEmail,
		&i.SignerIp,
		&i.SignerUserAgent,
		&i.SignatureHash,
		&i.AuditCertificateUrl,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateAgreementTemplate = `-- name: UpdateAgreementTemplate :one
UPDATE hrms.agreement_templates
SET agreement_type = $3,
    name = $4,
    description = $5,
    subject = $6,
    body_html = $7,
    footer_html = $8,
    locale = $9,
    is_default = $10,
    is_active = $11,
    metadata = $12,
    updated_by = $13
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, agreement_type, name, description, subject, body_html, footer_html, locale, is_default, is_active, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateAgreementTemplateParams struct {
	TenantID      uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID            uuid.UUID   `db:"id" json:"id"`
	AgreementType string      `db:"agreement_type" json:"agreement_type"`
	Name          string      `db:"name" json:"name"`
	Description   pgtype.Text `db:"description" json:"description"`
	Subject       pgtype.Text `db:"subject" json:"subject"`
	BodyHtml      string      `db:"body_html" json:"body_html"`
	FooterHtml    pgtype.Text `db:"footer_html" json:"footer_html"`
	Locale        string      `db:"locale" json:"locale"`
	IsDefault     bool        `db:"is_default" json:"is_default"`
	IsActive      bool        `db:"is_active" json:"is_active"`
	Metadata      []byte      `db:"metadata" json:"metadata"`
	UpdatedBy     pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateAgreementTemplate(ctx context.Context, arg UpdateAgreementTemplateParams) (HrmsAgreementTemplate, error) {
	row := q.db.QueryRow(ctx, updateAgreementTemplate,
		arg.TenantID,
		arg.ID,
		arg.AgreementType,
		arg.Name,
		arg.Description,
		arg.Subject,
		arg.BodyHtml,
		arg.FooterHtml,
		arg.Locale,
		arg.IsDefault,
		arg.IsActive,
		arg.Metadata,
		arg.UpdatedBy,
	)
	var i HrmsAgreementTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgreementType,
		&i.Name,
		&i.Description,
		&i.Subject,
		&i.BodyHtml,
		&i.FooterHtml,
		&i.Locale,
		&i.IsDefault,
		&i.IsActive,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
