// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance_exception_workflows.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAttendanceExceptionEvent = `-- name: CreateAttendanceExceptionEvent :one
INSERT INTO hrms.attendance_exception_events (
    tenant_id, attendance_request_id, workflow_id, action, from_status,
    to_status, routed_to, remarks, metadata, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $10
)
RETURNING id, tenant_id, attendance_request_id, workflow_id, action, from_status, to_status, routed_to, remarks, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateAttendanceExceptionEventParams struct {
	TenantID            uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	AttendanceRequestID uuid.UUID   `db:"attendance_request_id" json:"attendance_request_id"`
	WorkflowID          pgtype.UUID `db:"workflow_id" json:"workflow_id"`
	Action              string      `db:"action" json:"action"`
	FromStatus          pgtype.Text `db:"from_status" json:"from_status"`
	ToStatus            pgtype.Text `db:"to_status" json:"to_status"`
	RoutedTo            pgtype.Text `db:"routed_to" json:"routed_to"`
	Remarks             pgtype.Text `db:"remarks" json:"remarks"`
	Metadata            []byte      `db:"metadata" json:"metadata"`
	CreatedBy           pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAttendanceExceptionEvent(ctx context.Context, arg CreateAttendanceExceptionEventParams) (HrmsAttendanceExceptionEvent, error) {
	row := q.db.QueryRow(ctx, createAttendanceExceptionEvent,
		arg.TenantID,
		arg.AttendanceRequestID,
		arg.WorkflowID,
		arg.Action,
		arg.FromStatus,
		arg.ToStatus,
		arg.RoutedTo,
		arg.Remarks,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsAttendanceExceptionEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AttendanceRequestID,
		&i.WorkflowID,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.RoutedTo,
		&i.Remarks,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createAttendanceExceptionWorkflow = `-- name: CreateAttendanceExceptionWorkflow :one
INSERT INTO hrms.attendance_exception_workflows (
    tenant_id, code, name, description, branch_id, department_id, request_type,
    route_mode, max_requests_per_month, escalation_hours, escalation_route_mode,
    block_payroll_when_pending, auto_approve, is_active, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14, $15, $15
)
RETURNING id, tenant_id, code, name, description, branch_id, department_id, request_type, route_mode, max_requests_per_month, escalation_hours, escalation_route_mode, block_payroll_when_pending, auto_approve, is_active, inactive, created_at, created_by, updated_at, updated_by
`

type CreateAttendanceExceptionWorkflowParams struct {
	TenantID                uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Code                    string      `db:"code" json:"code"`
	Name                    string      `db:"name" json:"name"`
	Description             pgtype.Text `db:"description" json:"description"`
	BranchID                pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID            pgtype.UUID `db:"department_id" json:"department_id"`
	RequestType             string      `db:"request_type" json:"request_type"`
	RouteMode               string      `db:"route_mode" json:"route_mode"`
	MaxRequestsPerMonth     int32       `db:"max_requests_per_month" json:"max_requests_per_month"`
	EscalationHours         int32       `db:"escalation_hours" json:"escalation_hours"`
	EscalationRouteMode     pgtype.Text `db:"escalation_route_mode" json:"escalation_route_mode"`
	BlockPayrollWhenPending bool        `db:"block_payroll_when_pending" json:"block_payroll_when_pending"`
	AutoApprove             bool        `db:"auto_approve" json:"auto_approve"`
	IsActive                bool        `db:"is_active" json:"is_active"`
	CreatedBy               pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAttendanceExceptionWorkflow(ctx context.Context, arg CreateAttendanceExceptionWorkflowParams) (HrmsAttendanceExceptionWorkflow, error) {
	row := q.db.QueryRow(ctx, createAttendanceExceptionWorkflow,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.BranchID,
		arg.DepartmentID,
		arg.RequestType,
		arg.RouteMode,
		arg.MaxRequestsPerMonth,
		arg.EscalationHours,
		arg.EscalationRouteMode,
		arg.BlockPayrollWhenPending,
		arg.AutoApprove,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i HrmsAttendanceExceptionWorkflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.BranchID,
		&i.DepartmentID,
		&i.RequestType,
		&i.RouteMode,
		&i.MaxRequestsPerMonth,
		&i.EscalationHours,
		&i.EscalationRouteMode,
		&i.BlockPayrollWhenPending,
		&i.AutoApprove,
		&i.IsActive,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAttendanceExceptionWorkflow = `-- name: GetAttendanceExceptionWorkflow :one
SELECT id, tenant_id, code, name, description, branch_id, department_id, request_type, route_mode, max_requests_per_month, escalation_hours, escalation_route_mode, block_payroll_when_pending, auto_approve, is_active, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_exception_workflows
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetAttendanceExceptionWorkflowParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAttendanceExceptionWorkflow(ctx context.Context, arg GetAttendanceExceptionWorkflowParams) (HrmsAttendanceExceptionWorkflow, error) {
	row := q.db.QueryRow(ctx, getAttendanceExceptionWorkflow, arg.TenantID, arg.ID)
	var i HrmsAttendanceExceptionWorkflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.BranchID,
		&i.DepartmentID,
		&i.RequestType,
		&i.RouteMode,
		&i.MaxRequestsPerMonth,
		&i.EscalationHours,
		&i.EscalationRouteMode,
		&i.BlockPayrollWhenPending,
		&i.AutoApprove,
		&i.IsActive,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listAttendanceExceptionEvents = `-- name: ListAttendanceExceptionEvents :many
SELECT id, tenant_id, attendance_request_id, workflow_id, action, from_status, to_status, routed_to, remarks, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_exception_events
WHERE tenant_id = $1 AND attendance_request_id = $2 AND NOT inactive
ORDER BY created_at DESC
`

type ListAttendanceExceptionEventsParams struct {
	TenantID            uuid.UUID `db:"tenant_id" json:"tenant_id"`
	AttendanceRequestID uuid.UUID `db:"attendance_request_id" json:"attendance_request_id"`
}

func (q *Queries) ListAttendanceExceptionEvents(ctx context.Context, arg ListAttendanceExceptionEventsParams) ([]HrmsAttendanceExceptionEvent, error) {
	rows, err := q.db.Query(ctx, listAttendanceExceptionEvents, arg.TenantID, arg.AttendanceRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendanceExceptionEvent
	for rows.Next() {
		var i HrmsAttendanceExceptionEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AttendanceRequestID,
			&i.WorkflowID,
			&i.Action,
			&i.FromStatus,
			&i.ToStatus,
			&i.RoutedTo,
			&i.Remarks,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceExceptionWorkflows = `-- name: ListAttendanceExceptionWorkflows :many
SELECT id, tenant_id, code, name, description, branch_id, department_id, request_type, route_mode, max_requests_per_month, escalation_hours, escalation_route_mode, block_payroll_when_pending, auto_approve, is_active, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_exception_workflows
WHERE tenant_id = $1 AND NOT inactive
ORDER BY is_active DESC, request_type ASC, name ASC
`

func (q *Queries) ListAttendanceExceptionWorkflows(ctx context.Context, tenantID uuid.UUID) ([]HrmsAttendanceExceptionWorkflow, error) {
	rows, err := q.db.Query(ctx, listAttendanceExceptionWorkflows, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendanceExceptionWorkflow
	for rows.Next() {
		var i HrmsAttendanceExceptionWorkflow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.BranchID,
			&i.DepartmentID,
			&i.RequestType,
			&i.RouteMode,
			&i.MaxRequestsPerMonth,
			&i.EscalationHours,
			&i.EscalationRouteMode,
			&i.BlockPayrollWhenPending,
			&i.AutoApprove,
			&i.IsActive,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollBlockingAttendanceRequests = `-- name: ListPayrollBlockingAttendanceRequests :many
SELECT id, tenant_id, user_id, date, requested_type, reason, status, reviewed_by, reviewed_at, remarks, inactive, created_at, created_by, updated_at, updated_by, request_type, requested_checkin_at, requested_checkout_at, requested_work_mode, policy_id, roster_id, workflow_id, route_mode, escalation_due_at, escalated_at, payroll_blocking FROM hrms.attendance_requests
WHERE tenant_id = $1
  AND date >= $2
  AND date <= $3
  AND payroll_blocking
  AND status = 'pending'
  AND NOT inactive
ORDER BY date ASC, created_at ASC
`

type ListPayrollBlockingAttendanceRequestsParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Date     pgtype.Date `db:"date" json:"date"`
	Date_2   pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) ListPayrollBlockingAttendanceRequests(ctx context.Context, arg ListPayrollBlockingAttendanceRequestsParams) ([]HrmsAttendanceRequest, error) {
	rows, err := q.db.Query(ctx, listPayrollBlockingAttendanceRequests, arg.TenantID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendanceRequest
	for rows.Next() {
		var i HrmsAttendanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Date,
			&i.RequestedType,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Remarks,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RequestType,
			&i.RequestedCheckinAt,
			&i.RequestedCheckoutAt,
			&i.RequestedWorkMode,
			&i.PolicyID,
			&i.RosterID,
			&i.WorkflowID,
			&i.RouteMode,
			&i.EscalationDueAt,
			&i.EscalatedAt,
			&i.PayrollBlocking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAttendanceExceptionWorkflow = `-- name: ResolveAttendanceExceptionWorkflow :one
SELECT id, tenant_id, code, name, description, branch_id, department_id, request_type, route_mode, max_requests_per_month, escalation_hours, escalation_route_mode, block_payroll_when_pending, auto_approve, is_active, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_exception_workflows
WHERE tenant_id = $1
  AND request_type = $2
  AND is_active
  AND NOT inactive
  AND (
    (department_id = $3)
    OR (department_id IS NULL AND branch_id = $4)
    OR (department_id IS NULL AND branch_id IS NULL)
  )
ORDER BY
  CASE
    WHEN department_id = $3 THEN 1
    WHEN branch_id = $4 THEN 2
    ELSE 3
  END,
  updated_at DESC
LIMIT 1
`

type ResolveAttendanceExceptionWorkflowParams struct {
	TenantID     uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	RequestType  string      `db:"request_type" json:"request_type"`
	DepartmentID pgtype.UUID `db:"department_id" json:"department_id"`
	BranchID     pgtype.UUID `db:"branch_id" json:"branch_id"`
}

func (q *Queries) ResolveAttendanceExceptionWorkflow(ctx context.Context, arg ResolveAttendanceExceptionWorkflowParams) (HrmsAttendanceExceptionWorkflow, error) {
	row := q.db.QueryRow(ctx, resolveAttendanceExceptionWorkflow,
		arg.TenantID,
		arg.RequestType,
		arg.DepartmentID,
		arg.BranchID,
	)
	var i HrmsAttendanceExceptionWorkflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.BranchID,
		&i.DepartmentID,
		&i.RequestType,
		&i.RouteMode,
		&i.MaxRequestsPerMonth,
		&i.EscalationHours,
		&i.EscalationRouteMode,
		&i.BlockPayrollWhenPending,
		&i.AutoApprove,
		&i.IsActive,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const setAttendanceRequestWorkflow = `-- name: SetAttendanceRequestWorkflow :one
UPDATE hrms.attendance_requests
SET workflow_id = $3,
    route_mode = $4,
    escalation_due_at = $5,
    payroll_blocking = $6,
    updated_by = $7,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, user_id, date, requested_type, reason, status, reviewed_by, reviewed_at, remarks, inactive, created_at, created_by, updated_at, updated_by, request_type, requested_checkin_at, requested_checkout_at, requested_work_mode, policy_id, roster_id, workflow_id, route_mode, escalation_due_at, escalated_at, payroll_blocking
`

type SetAttendanceRequestWorkflowParams struct {
	TenantID        uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	ID              uuid.UUID          `db:"id" json:"id"`
	WorkflowID      pgtype.UUID        `db:"workflow_id" json:"workflow_id"`
	RouteMode       pgtype.Text        `db:"route_mode" json:"route_mode"`
	EscalationDueAt pgtype.Timestamptz `db:"escalation_due_at" json:"escalation_due_at"`
	PayrollBlocking bool               `db:"payroll_blocking" json:"payroll_blocking"`
	UpdatedBy       pgtype.UUID        `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SetAttendanceRequestWorkflow(ctx context.Context, arg SetAttendanceRequestWorkflowParams) (HrmsAttendanceRequest, error) {
	row := q.db.QueryRow(ctx, setAttendanceRequestWorkflow,
		arg.TenantID,
		arg.ID,
		arg.WorkflowID,
		arg.RouteMode,
		arg.EscalationDueAt,
		arg.PayrollBlocking,
		arg.UpdatedBy,
	)
	var i HrmsAttendanceRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Date,
		&i.RequestedType,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Remarks,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RequestType,
		&i.RequestedCheckinAt,
		&i.RequestedCheckoutAt,
		&i.RequestedWorkMode,
		&i.PolicyID,
		&i.RosterID,
		&i.WorkflowID,
		&i.RouteMode,
		&i.EscalationDueAt,
		&i.EscalatedAt,
		&i.PayrollBlocking,
	)
	return i, err
}

const softDeleteAttendanceExceptionWorkflow = `-- name: SoftDeleteAttendanceExceptionWorkflow :exec
UPDATE hrms.attendance_exception_workflows
SET inactive = TRUE, updated_by = $3, updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteAttendanceExceptionWorkflowParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteAttendanceExceptionWorkflow(ctx context.Context, arg SoftDeleteAttendanceExceptionWorkflowParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttendanceExceptionWorkflow, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const updateAttendanceExceptionWorkflow = `-- name: UpdateAttendanceExceptionWorkflow :one
UPDATE hrms.attendance_exception_workflows
SET
    code = $3,
    name = $4,
    description = $5,
    branch_id = $6,
    department_id = $7,
    request_type = $8,
    route_mode = $9,
    max_requests_per_month = $10,
    escalation_hours = $11,
    escalation_route_mode = $12,
    block_payroll_when_pending = $13,
    auto_approve = $14,
    is_active = $15,
    updated_by = $16,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, code, name, description, branch_id, department_id, request_type, route_mode, max_requests_per_month, escalation_hours, escalation_route_mode, block_payroll_when_pending, auto_approve, is_active, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateAttendanceExceptionWorkflowParams struct {
	TenantID                uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID                      uuid.UUID   `db:"id" json:"id"`
	Code                    string      `db:"code" json:"code"`
	Name                    string      `db:"name" json:"name"`
	Description             pgtype.Text `db:"description" json:"description"`
	BranchID                pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID            pgtype.UUID `db:"department_id" json:"department_id"`
	RequestType             string      `db:"request_type" json:"request_type"`
	RouteMode               string      `db:"route_mode" json:"route_mode"`
	MaxRequestsPerMonth     int32       `db:"max_requests_per_month" json:"max_requests_per_month"`
	EscalationHours         int32       `db:"escalation_hours" json:"escalation_hours"`
	EscalationRouteMode     pgtype.Text `db:"escalation_route_mode" json:"escalation_route_mode"`
	BlockPayrollWhenPending bool        `db:"block_payroll_when_pending" json:"block_payroll_when_pending"`
	AutoApprove             bool        `db:"auto_approve" json:"auto_approve"`
	IsActive                bool        `db:"is_active" json:"is_active"`
	UpdatedBy               pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateAttendanceExceptionWorkflow(ctx context.Context, arg UpdateAttendanceExceptionWorkflowParams) (HrmsAttendanceExceptionWorkflow, error) {
	row := q.db.QueryRow(ctx, updateAttendanceExceptionWorkflow,
		arg.TenantID,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.BranchID,
		arg.DepartmentID,
		arg.RequestType,
		arg.RouteMode,
		arg.MaxRequestsPerMonth,
		arg.EscalationHours,
		arg.EscalationRouteMode,
		arg.BlockPayrollWhenPending,
		arg.AutoApprove,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i HrmsAttendanceExceptionWorkflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.BranchID,
		&i.DepartmentID,
		&i.RequestType,
		&i.RouteMode,
		&i.MaxRequestsPerMonth,
		&i.EscalationHours,
		&i.EscalationRouteMode,
		&i.BlockPayrollWhenPending,
		&i.AutoApprove,
		&i.IsActive,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
