// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance_tracking.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAttendance = `-- name: CreateAttendance :one
INSERT INTO hrms.attendances (
    tenant_id,
    user_id,
    date,
    time,
    type,
    status,
    source,
    latitude,
    longitude,
    work_mode,
    remarks,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12
)
RETURNING id, tenant_id, user_id, date, time, type, status, source, latitude, longitude, work_mode, remarks, inactive, created_at, created_by, updated_at, updated_by, attendance_location_id, attendance_device_id, raw_attendance_event_id, location_accuracy_meters, location_verification_status
`

type CreateAttendanceParams struct {
	TenantID  uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Date      pgtype.Date        `db:"date" json:"date"`
	Time      pgtype.Timestamptz `db:"time" json:"time"`
	Type      pgtype.Text        `db:"type" json:"type"`
	Status    pgtype.Text        `db:"status" json:"status"`
	Source    pgtype.Text        `db:"source" json:"source"`
	Latitude  pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude pgtype.Numeric     `db:"longitude" json:"longitude"`
	WorkMode  pgtype.Text        `db:"work_mode" json:"work_mode"`
	Remarks   pgtype.Text        `db:"remarks" json:"remarks"`
	CreatedBy pgtype.UUID        `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAttendance(ctx context.Context, arg CreateAttendanceParams) (HrmsAttendance, error) {
	row := q.db.QueryRow(ctx, createAttendance,
		arg.TenantID,
		arg.UserID,
		arg.Date,
		arg.Time,
		arg.Type,
		arg.Status,
		arg.Source,
		arg.Latitude,
		arg.Longitude,
		arg.WorkMode,
		arg.Remarks,
		arg.CreatedBy,
	)
	var i HrmsAttendance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Date,
		&i.Time,
		&i.Type,
		&i.Status,
		&i.Source,
		&i.Latitude,
		&i.Longitude,
		&i.WorkMode,
		&i.Remarks,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.AttendanceLocationID,
		&i.AttendanceDeviceID,
		&i.RawAttendanceEventID,
		&i.LocationAccuracyMeters,
		&i.LocationVerificationStatus,
	)
	return i, err
}

const createAttendanceDevice = `-- name: CreateAttendanceDevice :one
INSERT INTO hrms.attendance_devices (
    tenant_id, attendance_location_id, branch_id, code, name, vendor, model, serial_number,
    device_identifier, integration_type, direction_mode, timezone, status, config, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $15
)
RETURNING id, tenant_id, attendance_location_id, branch_id, code, name, vendor, model, serial_number, device_identifier, integration_type, direction_mode, timezone, status, last_seen_at, config, inactive, created_at, created_by, updated_at, updated_by
`

type CreateAttendanceDeviceParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	AttendanceLocationID pgtype.UUID `db:"attendance_location_id" json:"attendance_location_id"`
	BranchID             pgtype.UUID `db:"branch_id" json:"branch_id"`
	Code                 string      `db:"code" json:"code"`
	Name                 string      `db:"name" json:"name"`
	Vendor               pgtype.Text `db:"vendor" json:"vendor"`
	Model                pgtype.Text `db:"model" json:"model"`
	SerialNumber         pgtype.Text `db:"serial_number" json:"serial_number"`
	DeviceIdentifier     pgtype.Text `db:"device_identifier" json:"device_identifier"`
	IntegrationType      string      `db:"integration_type" json:"integration_type"`
	DirectionMode        string      `db:"direction_mode" json:"direction_mode"`
	Timezone             string      `db:"timezone" json:"timezone"`
	Status               string      `db:"status" json:"status"`
	Config               []byte      `db:"config" json:"config"`
	CreatedBy            pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAttendanceDevice(ctx context.Context, arg CreateAttendanceDeviceParams) (HrmsAttendanceDevice, error) {
	row := q.db.QueryRow(ctx, createAttendanceDevice,
		arg.TenantID,
		arg.AttendanceLocationID,
		arg.BranchID,
		arg.Code,
		arg.Name,
		arg.Vendor,
		arg.Model,
		arg.SerialNumber,
		arg.DeviceIdentifier,
		arg.IntegrationType,
		arg.DirectionMode,
		arg.Timezone,
		arg.Status,
		arg.Config,
		arg.CreatedBy,
	)
	var i HrmsAttendanceDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AttendanceLocationID,
		&i.BranchID,
		&i.Code,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceIdentifier,
		&i.IntegrationType,
		&i.DirectionMode,
		&i.Timezone,
		&i.Status,
		&i.LastSeenAt,
		&i.Config,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createAttendanceLocation = `-- name: CreateAttendanceLocation :one
INSERT INTO hrms.attendance_locations (
    tenant_id, branch_id, code, name, location_type, latitude, longitude, radius_meters,
    address, city, state, country, pincode, effective_from, effective_to, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16, $16
)
RETURNING id, tenant_id, branch_id, code, name, location_type, latitude, longitude, radius_meters, address, city, state, country, pincode, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by
`

type CreateAttendanceLocationParams struct {
	TenantID      uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	BranchID      pgtype.UUID    `db:"branch_id" json:"branch_id"`
	Code          string         `db:"code" json:"code"`
	Name          string         `db:"name" json:"name"`
	LocationType  string         `db:"location_type" json:"location_type"`
	Latitude      pgtype.Numeric `db:"latitude" json:"latitude"`
	Longitude     pgtype.Numeric `db:"longitude" json:"longitude"`
	RadiusMeters  int32          `db:"radius_meters" json:"radius_meters"`
	Address       pgtype.Text    `db:"address" json:"address"`
	City          pgtype.Text    `db:"city" json:"city"`
	State         pgtype.Text    `db:"state" json:"state"`
	Country       pgtype.Text    `db:"country" json:"country"`
	Pincode       pgtype.Text    `db:"pincode" json:"pincode"`
	EffectiveFrom pgtype.Date    `db:"effective_from" json:"effective_from"`
	EffectiveTo   pgtype.Date    `db:"effective_to" json:"effective_to"`
	CreatedBy     pgtype.UUID    `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAttendanceLocation(ctx context.Context, arg CreateAttendanceLocationParams) (HrmsAttendanceLocation, error) {
	row := q.db.QueryRow(ctx, createAttendanceLocation,
		arg.TenantID,
		arg.BranchID,
		arg.Code,
		arg.Name,
		arg.LocationType,
		arg.Latitude,
		arg.Longitude,
		arg.RadiusMeters,
		arg.Address,
		arg.City,
		arg.State,
		arg.Country,
		arg.Pincode,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.CreatedBy,
	)
	var i HrmsAttendanceLocation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Code,
		&i.Name,
		&i.LocationType,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.Address,
		&i.City,
		&i.State,
		&i.Country,
		&i.Pincode,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createAttendanceLocationAssignment = `-- name: CreateAttendanceLocationAssignment :one
INSERT INTO hrms.attendance_location_assignments (
    tenant_id, location_id, branch_id, department_id, user_id, effective_from, effective_to, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8
)
RETURNING id, tenant_id, location_id, branch_id, department_id, user_id, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by
`

type CreateAttendanceLocationAssignmentParams struct {
	TenantID      uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	LocationID    uuid.UUID   `db:"location_id" json:"location_id"`
	BranchID      pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID  pgtype.UUID `db:"department_id" json:"department_id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
	EffectiveFrom pgtype.Date `db:"effective_from" json:"effective_from"`
	EffectiveTo   pgtype.Date `db:"effective_to" json:"effective_to"`
	CreatedBy     pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAttendanceLocationAssignment(ctx context.Context, arg CreateAttendanceLocationAssignmentParams) (HrmsAttendanceLocationAssignment, error) {
	row := q.db.QueryRow(ctx, createAttendanceLocationAssignment,
		arg.TenantID,
		arg.LocationID,
		arg.BranchID,
		arg.DepartmentID,
		arg.UserID,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.CreatedBy,
	)
	var i HrmsAttendanceLocationAssignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.BranchID,
		&i.DepartmentID,
		&i.UserID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createAttendancePolicy = `-- name: CreateAttendancePolicy :one
INSERT INTO hrms.attendance_policies (
    tenant_id, name, code, description, branch_id, department_id, user_id, schedule_type, is_default,
    standard_work_minutes, min_half_day_minutes, min_full_day_minutes, grace_late_minutes, grace_early_minutes,
    half_day_late_after_minutes, absent_late_after_minutes, half_day_early_before_minutes, absent_early_before_minutes,
    allow_flexi_hours, core_start_time, core_end_time, allow_wfh, wfh_days_per_week, allow_permanent_remote,
    require_geo, require_device, regularization_window_days, max_regularizations_per_month, approval_mode,
    effective_from, effective_to, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21, $22, $23, $24,
    $25, $26, $27, $28, $29,
    $30, $31, $32, $32
)
RETURNING id, tenant_id, name, code, description, branch_id, department_id, user_id, schedule_type, is_default, standard_work_minutes, min_half_day_minutes, min_full_day_minutes, grace_late_minutes, grace_early_minutes, half_day_late_after_minutes, absent_late_after_minutes, half_day_early_before_minutes, absent_early_before_minutes, allow_flexi_hours, core_start_time, core_end_time, allow_wfh, wfh_days_per_week, allow_permanent_remote, require_geo, require_device, regularization_window_days, max_regularizations_per_month, approval_mode, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by
`

type CreateAttendancePolicyParams struct {
	TenantID                   uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Name                       string      `db:"name" json:"name"`
	Code                       string      `db:"code" json:"code"`
	Description                pgtype.Text `db:"description" json:"description"`
	BranchID                   pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID               pgtype.UUID `db:"department_id" json:"department_id"`
	UserID                     pgtype.UUID `db:"user_id" json:"user_id"`
	ScheduleType               string      `db:"schedule_type" json:"schedule_type"`
	IsDefault                  bool        `db:"is_default" json:"is_default"`
	StandardWorkMinutes        int32       `db:"standard_work_minutes" json:"standard_work_minutes"`
	MinHalfDayMinutes          int32       `db:"min_half_day_minutes" json:"min_half_day_minutes"`
	MinFullDayMinutes          int32       `db:"min_full_day_minutes" json:"min_full_day_minutes"`
	GraceLateMinutes           int32       `db:"grace_late_minutes" json:"grace_late_minutes"`
	GraceEarlyMinutes          int32       `db:"grace_early_minutes" json:"grace_early_minutes"`
	HalfDayLateAfterMinutes    pgtype.Int4 `db:"half_day_late_after_minutes" json:"half_day_late_after_minutes"`
	AbsentLateAfterMinutes     pgtype.Int4 `db:"absent_late_after_minutes" json:"absent_late_after_minutes"`
	HalfDayEarlyBeforeMinutes  pgtype.Int4 `db:"half_day_early_before_minutes" json:"half_day_early_before_minutes"`
	AbsentEarlyBeforeMinutes   pgtype.Int4 `db:"absent_early_before_minutes" json:"absent_early_before_minutes"`
	AllowFlexiHours            bool        `db:"allow_flexi_hours" json:"allow_flexi_hours"`
	CoreStartTime              pgtype.Time `db:"core_start_time" json:"core_start_time"`
	CoreEndTime                pgtype.Time `db:"core_end_time" json:"core_end_time"`
	AllowWfh                   bool        `db:"allow_wfh" json:"allow_wfh"`
	WfhDaysPerWeek             int32       `db:"wfh_days_per_week" json:"wfh_days_per_week"`
	AllowPermanentRemote       bool        `db:"allow_permanent_remote" json:"allow_permanent_remote"`
	RequireGeo                 bool        `db:"require_geo" json:"require_geo"`
	RequireDevice              bool        `db:"require_device" json:"require_device"`
	RegularizationWindowDays   int32       `db:"regularization_window_days" json:"regularization_window_days"`
	MaxRegularizationsPerMonth int32       `db:"max_regularizations_per_month" json:"max_regularizations_per_month"`
	ApprovalMode               string      `db:"approval_mode" json:"approval_mode"`
	EffectiveFrom              pgtype.Date `db:"effective_from" json:"effective_from"`
	EffectiveTo                pgtype.Date `db:"effective_to" json:"effective_to"`
	CreatedBy                  pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAttendancePolicy(ctx context.Context, arg CreateAttendancePolicyParams) (HrmsAttendancePolicy, error) {
	row := q.db.QueryRow(ctx, createAttendancePolicy,
		arg.TenantID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.BranchID,
		arg.DepartmentID,
		arg.UserID,
		arg.ScheduleType,
		arg.IsDefault,
		arg.StandardWorkMinutes,
		arg.MinHalfDayMinutes,
		arg.MinFullDayMinutes,
		arg.GraceLateMinutes,
		arg.GraceEarlyMinutes,
		arg.HalfDayLateAfterMinutes,
		arg.AbsentLateAfterMinutes,
		arg.HalfDayEarlyBeforeMinutes,
		arg.AbsentEarlyBeforeMinutes,
		arg.AllowFlexiHours,
		arg.CoreStartTime,
		arg.CoreEndTime,
		arg.AllowWfh,
		arg.WfhDaysPerWeek,
		arg.AllowPermanentRemote,
		arg.RequireGeo,
		arg.RequireDevice,
		arg.RegularizationWindowDays,
		arg.MaxRegularizationsPerMonth,
		arg.ApprovalMode,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.CreatedBy,
	)
	var i HrmsAttendancePolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.BranchID,
		&i.DepartmentID,
		&i.UserID,
		&i.ScheduleType,
		&i.IsDefault,
		&i.StandardWorkMinutes,
		&i.MinHalfDayMinutes,
		&i.MinFullDayMinutes,
		&i.GraceLateMinutes,
		&i.GraceEarlyMinutes,
		&i.HalfDayLateAfterMinutes,
		&i.AbsentLateAfterMinutes,
		&i.HalfDayEarlyBeforeMinutes,
		&i.AbsentEarlyBeforeMinutes,
		&i.AllowFlexiHours,
		&i.CoreStartTime,
		&i.CoreEndTime,
		&i.AllowWfh,
		&i.WfhDaysPerWeek,
		&i.AllowPermanentRemote,
		&i.RequireGeo,
		&i.RequireDevice,
		&i.RegularizationWindowDays,
		&i.MaxRegularizationsPerMonth,
		&i.ApprovalMode,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createAttendanceRequest = `-- name: CreateAttendanceRequest :one
INSERT INTO hrms.attendance_requests (
    tenant_id, user_id, date, requested_type, request_type, requested_checkin_at, requested_checkout_at,
    requested_work_mode, policy_id, roster_id, reason, status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'pending', $12, $12
)
RETURNING id, tenant_id, user_id, date, requested_type, reason, status, reviewed_by, reviewed_at, remarks, inactive, created_at, created_by, updated_at, updated_by, request_type, requested_checkin_at, requested_checkout_at, requested_work_mode, policy_id, roster_id, workflow_id, route_mode, escalation_due_at, escalated_at, payroll_blocking
`

type CreateAttendanceRequestParams struct {
	TenantID            uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	UserID              uuid.UUID          `db:"user_id" json:"user_id"`
	Date                pgtype.Date        `db:"date" json:"date"`
	RequestedType       pgtype.Text        `db:"requested_type" json:"requested_type"`
	RequestType         string             `db:"request_type" json:"request_type"`
	RequestedCheckinAt  pgtype.Timestamptz `db:"requested_checkin_at" json:"requested_checkin_at"`
	RequestedCheckoutAt pgtype.Timestamptz `db:"requested_checkout_at" json:"requested_checkout_at"`
	RequestedWorkMode   pgtype.Text        `db:"requested_work_mode" json:"requested_work_mode"`
	PolicyID            pgtype.UUID        `db:"policy_id" json:"policy_id"`
	RosterID            pgtype.UUID        `db:"roster_id" json:"roster_id"`
	Reason              pgtype.Text        `db:"reason" json:"reason"`
	CreatedBy           pgtype.UUID        `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAttendanceRequest(ctx context.Context, arg CreateAttendanceRequestParams) (HrmsAttendanceRequest, error) {
	row := q.db.QueryRow(ctx, createAttendanceRequest,
		arg.TenantID,
		arg.UserID,
		arg.Date,
		arg.RequestedType,
		arg.RequestType,
		arg.RequestedCheckinAt,
		arg.RequestedCheckoutAt,
		arg.RequestedWorkMode,
		arg.PolicyID,
		arg.RosterID,
		arg.Reason,
		arg.CreatedBy,
	)
	var i HrmsAttendanceRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Date,
		&i.RequestedType,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Remarks,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RequestType,
		&i.RequestedCheckinAt,
		&i.RequestedCheckoutAt,
		&i.RequestedWorkMode,
		&i.PolicyID,
		&i.RosterID,
		&i.WorkflowID,
		&i.RouteMode,
		&i.EscalationDueAt,
		&i.EscalatedAt,
		&i.PayrollBlocking,
	)
	return i, err
}

const createAttendanceRoster = `-- name: CreateAttendanceRoster :one
INSERT INTO hrms.attendance_rosters (
    tenant_id, user_id, policy_id, date, start_time, end_time, break_minutes, work_mode, location_type, remarks, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $11
)
RETURNING id, tenant_id, user_id, policy_id, date, start_time, end_time, break_minutes, work_mode, location_type, remarks, inactive, created_at, created_by, updated_at, updated_by
`

type CreateAttendanceRosterParams struct {
	TenantID     uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	UserID       uuid.UUID   `db:"user_id" json:"user_id"`
	PolicyID     pgtype.UUID `db:"policy_id" json:"policy_id"`
	Date         pgtype.Date `db:"date" json:"date"`
	StartTime    pgtype.Time `db:"start_time" json:"start_time"`
	EndTime      pgtype.Time `db:"end_time" json:"end_time"`
	BreakMinutes int32       `db:"break_minutes" json:"break_minutes"`
	WorkMode     string      `db:"work_mode" json:"work_mode"`
	LocationType string      `db:"location_type" json:"location_type"`
	Remarks      pgtype.Text `db:"remarks" json:"remarks"`
	CreatedBy    pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAttendanceRoster(ctx context.Context, arg CreateAttendanceRosterParams) (HrmsAttendanceRoster, error) {
	row := q.db.QueryRow(ctx, createAttendanceRoster,
		arg.TenantID,
		arg.UserID,
		arg.PolicyID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMinutes,
		arg.WorkMode,
		arg.LocationType,
		arg.Remarks,
		arg.CreatedBy,
	)
	var i HrmsAttendanceRoster
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PolicyID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.WorkMode,
		&i.LocationType,
		&i.Remarks,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createDeviceLog = `-- name: CreateDeviceLog :one
INSERT INTO hrms.device_logs (
    tenant_id,
    user_id,
    device_id,
    device_type,
    ip_address,
    action,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $7
)
RETURNING id, tenant_id, user_id, device_id, device_type, ip_address, action, inactive, logged_at, created_at, created_by, updated_at, updated_by
`

type CreateDeviceLogParams struct {
	TenantID   uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	UserID     uuid.UUID   `db:"user_id" json:"user_id"`
	DeviceID   pgtype.Text `db:"device_id" json:"device_id"`
	DeviceType pgtype.Text `db:"device_type" json:"device_type"`
	IpAddress  pgtype.Text `db:"ip_address" json:"ip_address"`
	Action     pgtype.Text `db:"action" json:"action"`
	CreatedBy  pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateDeviceLog(ctx context.Context, arg CreateDeviceLogParams) (HrmsDeviceLog, error) {
	row := q.db.QueryRow(ctx, createDeviceLog,
		arg.TenantID,
		arg.UserID,
		arg.DeviceID,
		arg.DeviceType,
		arg.IpAddress,
		arg.Action,
		arg.CreatedBy,
	)
	var i HrmsDeviceLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceType,
		&i.IpAddress,
		&i.Action,
		&i.Inactive,
		&i.LoggedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createEmployeeAttendanceDevice = `-- name: CreateEmployeeAttendanceDevice :one
INSERT INTO hrms.employee_attendance_devices (
    tenant_id, user_id, device_id, device_user_id, credential_type, card_number, effective_from, effective_to, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $9
)
RETURNING id, tenant_id, user_id, device_id, device_user_id, credential_type, card_number, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by
`

type CreateEmployeeAttendanceDeviceParams struct {
	TenantID       uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	UserID         uuid.UUID   `db:"user_id" json:"user_id"`
	DeviceID       uuid.UUID   `db:"device_id" json:"device_id"`
	DeviceUserID   string      `db:"device_user_id" json:"device_user_id"`
	CredentialType string      `db:"credential_type" json:"credential_type"`
	CardNumber     pgtype.Text `db:"card_number" json:"card_number"`
	EffectiveFrom  pgtype.Date `db:"effective_from" json:"effective_from"`
	EffectiveTo    pgtype.Date `db:"effective_to" json:"effective_to"`
	CreatedBy      pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateEmployeeAttendanceDevice(ctx context.Context, arg CreateEmployeeAttendanceDeviceParams) (HrmsEmployeeAttendanceDevice, error) {
	row := q.db.QueryRow(ctx, createEmployeeAttendanceDevice,
		arg.TenantID,
		arg.UserID,
		arg.DeviceID,
		arg.DeviceUserID,
		arg.CredentialType,
		arg.CardNumber,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.CreatedBy,
	)
	var i HrmsEmployeeAttendanceDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceUserID,
		&i.CredentialType,
		&i.CardNumber,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createRawAttendanceEvent = `-- name: CreateRawAttendanceEvent :one
INSERT INTO hrms.raw_attendance_events (
    tenant_id, device_id, employee_device_mapping_id, external_event_id, device_user_id, event_time,
    event_type, attendance_type, import_batch_id, raw_payload, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $11
)
RETURNING id, tenant_id, device_id, employee_device_mapping_id, attendance_id, external_event_id, device_user_id, event_time, event_type, attendance_type, import_batch_id, processing_status, processing_error, raw_payload, processed_at, inactive, created_at, created_by, updated_at, updated_by
`

type CreateRawAttendanceEventParams struct {
	TenantID                uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	DeviceID                uuid.UUID          `db:"device_id" json:"device_id"`
	EmployeeDeviceMappingID pgtype.UUID        `db:"employee_device_mapping_id" json:"employee_device_mapping_id"`
	ExternalEventID         pgtype.Text        `db:"external_event_id" json:"external_event_id"`
	DeviceUserID            pgtype.Text        `db:"device_user_id" json:"device_user_id"`
	EventTime               pgtype.Timestamptz `db:"event_time" json:"event_time"`
	EventType               pgtype.Text        `db:"event_type" json:"event_type"`
	AttendanceType          pgtype.Text        `db:"attendance_type" json:"attendance_type"`
	ImportBatchID           pgtype.Text        `db:"import_batch_id" json:"import_batch_id"`
	RawPayload              []byte             `db:"raw_payload" json:"raw_payload"`
	CreatedBy               pgtype.UUID        `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateRawAttendanceEvent(ctx context.Context, arg CreateRawAttendanceEventParams) (HrmsRawAttendanceEvent, error) {
	row := q.db.QueryRow(ctx, createRawAttendanceEvent,
		arg.TenantID,
		arg.DeviceID,
		arg.EmployeeDeviceMappingID,
		arg.ExternalEventID,
		arg.DeviceUserID,
		arg.EventTime,
		arg.EventType,
		arg.AttendanceType,
		arg.ImportBatchID,
		arg.RawPayload,
		arg.CreatedBy,
	)
	var i HrmsRawAttendanceEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeviceID,
		&i.EmployeeDeviceMappingID,
		&i.AttendanceID,
		&i.ExternalEventID,
		&i.DeviceUserID,
		&i.EventTime,
		&i.EventType,
		&i.AttendanceType,
		&i.ImportBatchID,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.RawPayload,
		&i.ProcessedAt,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAttendance = `-- name: GetAttendance :one
SELECT id, tenant_id, user_id, date, time, type, status, source, latitude, longitude, work_mode, remarks, inactive, created_at, created_by, updated_at, updated_by, attendance_location_id, attendance_device_id, raw_attendance_event_id, location_accuracy_meters, location_verification_status FROM hrms.attendances
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetAttendanceParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAttendance(ctx context.Context, arg GetAttendanceParams) (HrmsAttendance, error) {
	row := q.db.QueryRow(ctx, getAttendance, arg.TenantID, arg.ID)
	var i HrmsAttendance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Date,
		&i.Time,
		&i.Type,
		&i.Status,
		&i.Source,
		&i.Latitude,
		&i.Longitude,
		&i.WorkMode,
		&i.Remarks,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.AttendanceLocationID,
		&i.AttendanceDeviceID,
		&i.RawAttendanceEventID,
		&i.LocationAccuracyMeters,
		&i.LocationVerificationStatus,
	)
	return i, err
}

const getAttendanceDevice = `-- name: GetAttendanceDevice :one
SELECT id, tenant_id, attendance_location_id, branch_id, code, name, vendor, model, serial_number, device_identifier, integration_type, direction_mode, timezone, status, last_seen_at, config, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_devices
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetAttendanceDeviceParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAttendanceDevice(ctx context.Context, arg GetAttendanceDeviceParams) (HrmsAttendanceDevice, error) {
	row := q.db.QueryRow(ctx, getAttendanceDevice, arg.TenantID, arg.ID)
	var i HrmsAttendanceDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AttendanceLocationID,
		&i.BranchID,
		&i.Code,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceIdentifier,
		&i.IntegrationType,
		&i.DirectionMode,
		&i.Timezone,
		&i.Status,
		&i.LastSeenAt,
		&i.Config,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAttendanceLocation = `-- name: GetAttendanceLocation :one
SELECT id, tenant_id, branch_id, code, name, location_type, latitude, longitude, radius_meters, address, city, state, country, pincode, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_locations
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetAttendanceLocationParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAttendanceLocation(ctx context.Context, arg GetAttendanceLocationParams) (HrmsAttendanceLocation, error) {
	row := q.db.QueryRow(ctx, getAttendanceLocation, arg.TenantID, arg.ID)
	var i HrmsAttendanceLocation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Code,
		&i.Name,
		&i.LocationType,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.Address,
		&i.City,
		&i.State,
		&i.Country,
		&i.Pincode,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAttendancePolicy = `-- name: GetAttendancePolicy :one
SELECT id, tenant_id, name, code, description, branch_id, department_id, user_id, schedule_type, is_default, standard_work_minutes, min_half_day_minutes, min_full_day_minutes, grace_late_minutes, grace_early_minutes, half_day_late_after_minutes, absent_late_after_minutes, half_day_early_before_minutes, absent_early_before_minutes, allow_flexi_hours, core_start_time, core_end_time, allow_wfh, wfh_days_per_week, allow_permanent_remote, require_geo, require_device, regularization_window_days, max_regularizations_per_month, approval_mode, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_policies
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetAttendancePolicyParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAttendancePolicy(ctx context.Context, arg GetAttendancePolicyParams) (HrmsAttendancePolicy, error) {
	row := q.db.QueryRow(ctx, getAttendancePolicy, arg.TenantID, arg.ID)
	var i HrmsAttendancePolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.BranchID,
		&i.DepartmentID,
		&i.UserID,
		&i.ScheduleType,
		&i.IsDefault,
		&i.StandardWorkMinutes,
		&i.MinHalfDayMinutes,
		&i.MinFullDayMinutes,
		&i.GraceLateMinutes,
		&i.GraceEarlyMinutes,
		&i.HalfDayLateAfterMinutes,
		&i.AbsentLateAfterMinutes,
		&i.HalfDayEarlyBeforeMinutes,
		&i.AbsentEarlyBeforeMinutes,
		&i.AllowFlexiHours,
		&i.CoreStartTime,
		&i.CoreEndTime,
		&i.AllowWfh,
		&i.WfhDaysPerWeek,
		&i.AllowPermanentRemote,
		&i.RequireGeo,
		&i.RequireDevice,
		&i.RegularizationWindowDays,
		&i.MaxRegularizationsPerMonth,
		&i.ApprovalMode,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAttendanceRequest = `-- name: GetAttendanceRequest :one
SELECT id, tenant_id, user_id, date, requested_type, reason, status, reviewed_by, reviewed_at, remarks, inactive, created_at, created_by, updated_at, updated_by, request_type, requested_checkin_at, requested_checkout_at, requested_work_mode, policy_id, roster_id, workflow_id, route_mode, escalation_due_at, escalated_at, payroll_blocking FROM hrms.attendance_requests
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetAttendanceRequestParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAttendanceRequest(ctx context.Context, arg GetAttendanceRequestParams) (HrmsAttendanceRequest, error) {
	row := q.db.QueryRow(ctx, getAttendanceRequest, arg.TenantID, arg.ID)
	var i HrmsAttendanceRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Date,
		&i.RequestedType,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Remarks,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RequestType,
		&i.RequestedCheckinAt,
		&i.RequestedCheckoutAt,
		&i.RequestedWorkMode,
		&i.PolicyID,
		&i.RosterID,
		&i.WorkflowID,
		&i.RouteMode,
		&i.EscalationDueAt,
		&i.EscalatedAt,
		&i.PayrollBlocking,
	)
	return i, err
}

const getAttendanceRosterByUserDate = `-- name: GetAttendanceRosterByUserDate :one
SELECT id, tenant_id, user_id, policy_id, date, start_time, end_time, break_minutes, work_mode, location_type, remarks, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_rosters
WHERE tenant_id = $1 AND user_id = $2 AND date = $3 AND NOT inactive
`

type GetAttendanceRosterByUserDateParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID   `db:"user_id" json:"user_id"`
	Date     pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) GetAttendanceRosterByUserDate(ctx context.Context, arg GetAttendanceRosterByUserDateParams) (HrmsAttendanceRoster, error) {
	row := q.db.QueryRow(ctx, getAttendanceRosterByUserDate, arg.TenantID, arg.UserID, arg.Date)
	var i HrmsAttendanceRoster
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PolicyID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.WorkMode,
		&i.LocationType,
		&i.Remarks,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getDeviceLog = `-- name: GetDeviceLog :one
SELECT id, tenant_id, user_id, device_id, device_type, ip_address, action, inactive, logged_at, created_at, created_by, updated_at, updated_by FROM hrms.device_logs
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetDeviceLogParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetDeviceLog(ctx context.Context, arg GetDeviceLogParams) (HrmsDeviceLog, error) {
	row := q.db.QueryRow(ctx, getDeviceLog, arg.TenantID, arg.ID)
	var i HrmsDeviceLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceType,
		&i.IpAddress,
		&i.Action,
		&i.Inactive,
		&i.LoggedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getEmployeeAttendanceDevice = `-- name: GetEmployeeAttendanceDevice :one
SELECT id, tenant_id, user_id, device_id, device_user_id, credential_type, card_number, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by FROM hrms.employee_attendance_devices
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetEmployeeAttendanceDeviceParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetEmployeeAttendanceDevice(ctx context.Context, arg GetEmployeeAttendanceDeviceParams) (HrmsEmployeeAttendanceDevice, error) {
	row := q.db.QueryRow(ctx, getEmployeeAttendanceDevice, arg.TenantID, arg.ID)
	var i HrmsEmployeeAttendanceDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceUserID,
		&i.CredentialType,
		&i.CardNumber,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listAttendanceDevices = `-- name: ListAttendanceDevices :many
SELECT id, tenant_id, attendance_location_id, branch_id, code, name, vendor, model, serial_number, device_identifier, integration_type, direction_mode, timezone, status, last_seen_at, config, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_devices
WHERE tenant_id = $1 AND NOT inactive
ORDER BY name ASC
`

func (q *Queries) ListAttendanceDevices(ctx context.Context, tenantID uuid.UUID) ([]HrmsAttendanceDevice, error) {
	rows, err := q.db.Query(ctx, listAttendanceDevices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendanceDevice
	for rows.Next() {
		var i HrmsAttendanceDevice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AttendanceLocationID,
			&i.BranchID,
			&i.Code,
			&i.Name,
			&i.Vendor,
			&i.Model,
			&i.SerialNumber,
			&i.DeviceIdentifier,
			&i.IntegrationType,
			&i.DirectionMode,
			&i.Timezone,
			&i.Status,
			&i.LastSeenAt,
			&i.Config,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceLocationAssignments = `-- name: ListAttendanceLocationAssignments :many
SELECT id, tenant_id, location_id, branch_id, department_id, user_id, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_location_assignments
WHERE tenant_id = $1 AND NOT inactive
ORDER BY created_at DESC
`

func (q *Queries) ListAttendanceLocationAssignments(ctx context.Context, tenantID uuid.UUID) ([]HrmsAttendanceLocationAssignment, error) {
	rows, err := q.db.Query(ctx, listAttendanceLocationAssignments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendanceLocationAssignment
	for rows.Next() {
		var i HrmsAttendanceLocationAssignment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LocationID,
			&i.BranchID,
			&i.DepartmentID,
			&i.UserID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceLocationAssignmentsByLocation = `-- name: ListAttendanceLocationAssignmentsByLocation :many
SELECT id, tenant_id, location_id, branch_id, department_id, user_id, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_location_assignments
WHERE tenant_id = $1 AND location_id = $2 AND NOT inactive
ORDER BY created_at DESC
`

type ListAttendanceLocationAssignmentsByLocationParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	LocationID uuid.UUID `db:"location_id" json:"location_id"`
}

func (q *Queries) ListAttendanceLocationAssignmentsByLocation(ctx context.Context, arg ListAttendanceLocationAssignmentsByLocationParams) ([]HrmsAttendanceLocationAssignment, error) {
	rows, err := q.db.Query(ctx, listAttendanceLocationAssignmentsByLocation, arg.TenantID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendanceLocationAssignment
	for rows.Next() {
		var i HrmsAttendanceLocationAssignment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LocationID,
			&i.BranchID,
			&i.DepartmentID,
			&i.UserID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceLocations = `-- name: ListAttendanceLocations :many
SELECT id, tenant_id, branch_id, code, name, location_type, latitude, longitude, radius_meters, address, city, state, country, pincode, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_locations
WHERE tenant_id = $1 AND NOT inactive
ORDER BY name ASC
`

func (q *Queries) ListAttendanceLocations(ctx context.Context, tenantID uuid.UUID) ([]HrmsAttendanceLocation, error) {
	rows, err := q.db.Query(ctx, listAttendanceLocations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendanceLocation
	for rows.Next() {
		var i HrmsAttendanceLocation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Code,
			&i.Name,
			&i.LocationType,
			&i.Latitude,
			&i.Longitude,
			&i.RadiusMeters,
			&i.Address,
			&i.City,
			&i.State,
			&i.Country,
			&i.Pincode,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendancePolicies = `-- name: ListAttendancePolicies :many
SELECT id, tenant_id, name, code, description, branch_id, department_id, user_id, schedule_type, is_default, standard_work_minutes, min_half_day_minutes, min_full_day_minutes, grace_late_minutes, grace_early_minutes, half_day_late_after_minutes, absent_late_after_minutes, half_day_early_before_minutes, absent_early_before_minutes, allow_flexi_hours, core_start_time, core_end_time, allow_wfh, wfh_days_per_week, allow_permanent_remote, require_geo, require_device, regularization_window_days, max_regularizations_per_month, approval_mode, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_policies
WHERE tenant_id = $1 AND NOT inactive
ORDER BY is_default DESC, name ASC
`

func (q *Queries) ListAttendancePolicies(ctx context.Context, tenantID uuid.UUID) ([]HrmsAttendancePolicy, error) {
	rows, err := q.db.Query(ctx, listAttendancePolicies, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendancePolicy
	for rows.Next() {
		var i HrmsAttendancePolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.BranchID,
			&i.DepartmentID,
			&i.UserID,
			&i.ScheduleType,
			&i.IsDefault,
			&i.StandardWorkMinutes,
			&i.MinHalfDayMinutes,
			&i.MinFullDayMinutes,
			&i.GraceLateMinutes,
			&i.GraceEarlyMinutes,
			&i.HalfDayLateAfterMinutes,
			&i.AbsentLateAfterMinutes,
			&i.HalfDayEarlyBeforeMinutes,
			&i.AbsentEarlyBeforeMinutes,
			&i.AllowFlexiHours,
			&i.CoreStartTime,
			&i.CoreEndTime,
			&i.AllowWfh,
			&i.WfhDaysPerWeek,
			&i.AllowPermanentRemote,
			&i.RequireGeo,
			&i.RequireDevice,
			&i.RegularizationWindowDays,
			&i.MaxRegularizationsPerMonth,
			&i.ApprovalMode,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceRequestsByStatus = `-- name: ListAttendanceRequestsByStatus :many
SELECT id, tenant_id, user_id, date, requested_type, reason, status, reviewed_by, reviewed_at, remarks, inactive, created_at, created_by, updated_at, updated_by, request_type, requested_checkin_at, requested_checkout_at, requested_work_mode, policy_id, roster_id, workflow_id, route_mode, escalation_due_at, escalated_at, payroll_blocking FROM hrms.attendance_requests
WHERE tenant_id = $1 AND status = $2 AND NOT inactive
ORDER BY created_at DESC
`

type ListAttendanceRequestsByStatusParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Status   string    `db:"status" json:"status"`
}

func (q *Queries) ListAttendanceRequestsByStatus(ctx context.Context, arg ListAttendanceRequestsByStatusParams) ([]HrmsAttendanceRequest, error) {
	rows, err := q.db.Query(ctx, listAttendanceRequestsByStatus, arg.TenantID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendanceRequest
	for rows.Next() {
		var i HrmsAttendanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Date,
			&i.RequestedType,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Remarks,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RequestType,
			&i.RequestedCheckinAt,
			&i.RequestedCheckoutAt,
			&i.RequestedWorkMode,
			&i.PolicyID,
			&i.RosterID,
			&i.WorkflowID,
			&i.RouteMode,
			&i.EscalationDueAt,
			&i.EscalatedAt,
			&i.PayrollBlocking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceRequestsByUser = `-- name: ListAttendanceRequestsByUser :many
SELECT id, tenant_id, user_id, date, requested_type, reason, status, reviewed_by, reviewed_at, remarks, inactive, created_at, created_by, updated_at, updated_by, request_type, requested_checkin_at, requested_checkout_at, requested_work_mode, policy_id, roster_id, workflow_id, route_mode, escalation_due_at, escalated_at, payroll_blocking FROM hrms.attendance_requests
WHERE tenant_id = $1 AND user_id = $2 AND NOT inactive
ORDER BY created_at DESC
`

type ListAttendanceRequestsByUserParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ListAttendanceRequestsByUser(ctx context.Context, arg ListAttendanceRequestsByUserParams) ([]HrmsAttendanceRequest, error) {
	rows, err := q.db.Query(ctx, listAttendanceRequestsByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendanceRequest
	for rows.Next() {
		var i HrmsAttendanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Date,
			&i.RequestedType,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Remarks,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RequestType,
			&i.RequestedCheckinAt,
			&i.RequestedCheckoutAt,
			&i.RequestedWorkMode,
			&i.PolicyID,
			&i.RosterID,
			&i.WorkflowID,
			&i.RouteMode,
			&i.EscalationDueAt,
			&i.EscalatedAt,
			&i.PayrollBlocking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceRostersByDateRange = `-- name: ListAttendanceRostersByDateRange :many
SELECT id, tenant_id, user_id, policy_id, date, start_time, end_time, break_minutes, work_mode, location_type, remarks, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_rosters
WHERE tenant_id = $1 AND date BETWEEN $2 AND $3 AND NOT inactive
ORDER BY date ASC, user_id ASC
`

type ListAttendanceRostersByDateRangeParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Date     pgtype.Date `db:"date" json:"date"`
	Date_2   pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) ListAttendanceRostersByDateRange(ctx context.Context, arg ListAttendanceRostersByDateRangeParams) ([]HrmsAttendanceRoster, error) {
	rows, err := q.db.Query(ctx, listAttendanceRostersByDateRange, arg.TenantID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendanceRoster
	for rows.Next() {
		var i HrmsAttendanceRoster
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.PolicyID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.BreakMinutes,
			&i.WorkMode,
			&i.LocationType,
			&i.Remarks,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceRostersByUser = `-- name: ListAttendanceRostersByUser :many
SELECT id, tenant_id, user_id, policy_id, date, start_time, end_time, break_minutes, work_mode, location_type, remarks, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_rosters
WHERE tenant_id = $1 AND user_id = $2 AND date BETWEEN $3 AND $4 AND NOT inactive
ORDER BY date ASC
`

type ListAttendanceRostersByUserParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID   `db:"user_id" json:"user_id"`
	Date     pgtype.Date `db:"date" json:"date"`
	Date_2   pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) ListAttendanceRostersByUser(ctx context.Context, arg ListAttendanceRostersByUserParams) ([]HrmsAttendanceRoster, error) {
	rows, err := q.db.Query(ctx, listAttendanceRostersByUser,
		arg.TenantID,
		arg.UserID,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendanceRoster
	for rows.Next() {
		var i HrmsAttendanceRoster
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.PolicyID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.BreakMinutes,
			&i.WorkMode,
			&i.LocationType,
			&i.Remarks,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendancesByDate = `-- name: ListAttendancesByDate :many
SELECT id, tenant_id, user_id, date, time, type, status, source, latitude, longitude, work_mode, remarks, inactive, created_at, created_by, updated_at, updated_by, attendance_location_id, attendance_device_id, raw_attendance_event_id, location_accuracy_meters, location_verification_status FROM hrms.attendances
WHERE tenant_id = $1 AND date = $2 AND NOT inactive
ORDER BY time ASC NULLS LAST
`

type ListAttendancesByDateParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Date     pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) ListAttendancesByDate(ctx context.Context, arg ListAttendancesByDateParams) ([]HrmsAttendance, error) {
	rows, err := q.db.Query(ctx, listAttendancesByDate, arg.TenantID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendance
	for rows.Next() {
		var i HrmsAttendance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Date,
			&i.Time,
			&i.Type,
			&i.Status,
			&i.Source,
			&i.Latitude,
			&i.Longitude,
			&i.WorkMode,
			&i.Remarks,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.AttendanceLocationID,
			&i.AttendanceDeviceID,
			&i.RawAttendanceEventID,
			&i.LocationAccuracyMeters,
			&i.LocationVerificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendancesByUser = `-- name: ListAttendancesByUser :many
SELECT id, tenant_id, user_id, date, time, type, status, source, latitude, longitude, work_mode, remarks, inactive, created_at, created_by, updated_at, updated_by, attendance_location_id, attendance_device_id, raw_attendance_event_id, location_accuracy_meters, location_verification_status FROM hrms.attendances
WHERE tenant_id = $1 AND user_id = $2 AND date BETWEEN $3 AND $4 AND NOT inactive
ORDER BY date ASC, time ASC NULLS LAST
`

type ListAttendancesByUserParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID   `db:"user_id" json:"user_id"`
	Date     pgtype.Date `db:"date" json:"date"`
	Date_2   pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) ListAttendancesByUser(ctx context.Context, arg ListAttendancesByUserParams) ([]HrmsAttendance, error) {
	rows, err := q.db.Query(ctx, listAttendancesByUser,
		arg.TenantID,
		arg.UserID,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendance
	for rows.Next() {
		var i HrmsAttendance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Date,
			&i.Time,
			&i.Type,
			&i.Status,
			&i.Source,
			&i.Latitude,
			&i.Longitude,
			&i.WorkMode,
			&i.Remarks,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.AttendanceLocationID,
			&i.AttendanceDeviceID,
			&i.RawAttendanceEventID,
			&i.LocationAccuracyMeters,
			&i.LocationVerificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendancesByUserDate = `-- name: ListAttendancesByUserDate :many
SELECT id, tenant_id, user_id, date, time, type, status, source, latitude, longitude, work_mode, remarks, inactive, created_at, created_by, updated_at, updated_by, attendance_location_id, attendance_device_id, raw_attendance_event_id, location_accuracy_meters, location_verification_status FROM hrms.attendances
WHERE tenant_id = $1 AND user_id = $2 AND date = $3 AND NOT inactive
ORDER BY time ASC NULLS LAST, created_at ASC
`

type ListAttendancesByUserDateParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID   `db:"user_id" json:"user_id"`
	Date     pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) ListAttendancesByUserDate(ctx context.Context, arg ListAttendancesByUserDateParams) ([]HrmsAttendance, error) {
	rows, err := q.db.Query(ctx, listAttendancesByUserDate, arg.TenantID, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsAttendance
	for rows.Next() {
		var i HrmsAttendance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Date,
			&i.Time,
			&i.Type,
			&i.Status,
			&i.Source,
			&i.Latitude,
			&i.Longitude,
			&i.WorkMode,
			&i.Remarks,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.AttendanceLocationID,
			&i.AttendanceDeviceID,
			&i.RawAttendanceEventID,
			&i.LocationAccuracyMeters,
			&i.LocationVerificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceLogsByUser = `-- name: ListDeviceLogsByUser :many
SELECT id, tenant_id, user_id, device_id, device_type, ip_address, action, inactive, logged_at, created_at, created_by, updated_at, updated_by FROM hrms.device_logs
WHERE tenant_id = $1 AND user_id = $2 AND NOT inactive
ORDER BY logged_at DESC
`

type ListDeviceLogsByUserParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ListDeviceLogsByUser(ctx context.Context, arg ListDeviceLogsByUserParams) ([]HrmsDeviceLog, error) {
	rows, err := q.db.Query(ctx, listDeviceLogsByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsDeviceLog
	for rows.Next() {
		var i HrmsDeviceLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.DeviceID,
			&i.DeviceType,
			&i.IpAddress,
			&i.Action,
			&i.Inactive,
			&i.LoggedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeAttendanceDevices = `-- name: ListEmployeeAttendanceDevices :many
SELECT id, tenant_id, user_id, device_id, device_user_id, credential_type, card_number, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by FROM hrms.employee_attendance_devices
WHERE tenant_id = $1 AND NOT inactive
ORDER BY created_at DESC
`

func (q *Queries) ListEmployeeAttendanceDevices(ctx context.Context, tenantID uuid.UUID) ([]HrmsEmployeeAttendanceDevice, error) {
	rows, err := q.db.Query(ctx, listEmployeeAttendanceDevices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsEmployeeAttendanceDevice
	for rows.Next() {
		var i HrmsEmployeeAttendanceDevice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.DeviceID,
			&i.DeviceUserID,
			&i.CredentialType,
			&i.CardNumber,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeAttendanceDevicesByUser = `-- name: ListEmployeeAttendanceDevicesByUser :many
SELECT id, tenant_id, user_id, device_id, device_user_id, credential_type, card_number, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by FROM hrms.employee_attendance_devices
WHERE tenant_id = $1 AND user_id = $2 AND NOT inactive
ORDER BY created_at DESC
`

type ListEmployeeAttendanceDevicesByUserParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ListEmployeeAttendanceDevicesByUser(ctx context.Context, arg ListEmployeeAttendanceDevicesByUserParams) ([]HrmsEmployeeAttendanceDevice, error) {
	rows, err := q.db.Query(ctx, listEmployeeAttendanceDevicesByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsEmployeeAttendanceDevice
	for rows.Next() {
		var i HrmsEmployeeAttendanceDevice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.DeviceID,
			&i.DeviceUserID,
			&i.CredentialType,
			&i.CardNumber,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRawAttendanceEvents = `-- name: ListRawAttendanceEvents :many
SELECT id, tenant_id, device_id, employee_device_mapping_id, attendance_id, external_event_id, device_user_id, event_time, event_type, attendance_type, import_batch_id, processing_status, processing_error, raw_payload, processed_at, inactive, created_at, created_by, updated_at, updated_by FROM hrms.raw_attendance_events
WHERE tenant_id = $1 AND NOT inactive
ORDER BY event_time DESC
LIMIT $2
`

type ListRawAttendanceEventsParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListRawAttendanceEvents(ctx context.Context, arg ListRawAttendanceEventsParams) ([]HrmsRawAttendanceEvent, error) {
	rows, err := q.db.Query(ctx, listRawAttendanceEvents, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsRawAttendanceEvent
	for rows.Next() {
		var i HrmsRawAttendanceEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DeviceID,
			&i.EmployeeDeviceMappingID,
			&i.AttendanceID,
			&i.ExternalEventID,
			&i.DeviceUserID,
			&i.EventTime,
			&i.EventType,
			&i.AttendanceType,
			&i.ImportBatchID,
			&i.ProcessingStatus,
			&i.ProcessingError,
			&i.RawPayload,
			&i.ProcessedAt,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAttendancePolicy = `-- name: ResolveAttendancePolicy :one
SELECT id, tenant_id, name, code, description, branch_id, department_id, user_id, schedule_type, is_default, standard_work_minutes, min_half_day_minutes, min_full_day_minutes, grace_late_minutes, grace_early_minutes, half_day_late_after_minutes, absent_late_after_minutes, half_day_early_before_minutes, absent_early_before_minutes, allow_flexi_hours, core_start_time, core_end_time, allow_wfh, wfh_days_per_week, allow_permanent_remote, require_geo, require_device, regularization_window_days, max_regularizations_per_month, approval_mode, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by FROM hrms.attendance_policies
WHERE tenant_id = $1
  AND NOT inactive
  AND (effective_from IS NULL OR effective_from <= $5)
  AND (effective_to IS NULL OR effective_to >= $5)
  AND (
    user_id = $2
    OR (user_id IS NULL AND department_id = $3)
    OR (user_id IS NULL AND department_id IS NULL AND branch_id = $4)
    OR (user_id IS NULL AND department_id IS NULL AND branch_id IS NULL AND is_default)
  )
ORDER BY
  CASE
    WHEN user_id = $2 THEN 1
    WHEN department_id = $3 THEN 2
    WHEN branch_id = $4 THEN 3
    WHEN is_default THEN 4
    ELSE 5
  END,
  updated_at DESC
LIMIT 1
`

type ResolveAttendancePolicyParams struct {
	TenantID      uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
	DepartmentID  pgtype.UUID `db:"department_id" json:"department_id"`
	BranchID      pgtype.UUID `db:"branch_id" json:"branch_id"`
	EffectiveFrom pgtype.Date `db:"effective_from" json:"effective_from"`
}

func (q *Queries) ResolveAttendancePolicy(ctx context.Context, arg ResolveAttendancePolicyParams) (HrmsAttendancePolicy, error) {
	row := q.db.QueryRow(ctx, resolveAttendancePolicy,
		arg.TenantID,
		arg.UserID,
		arg.DepartmentID,
		arg.BranchID,
		arg.EffectiveFrom,
	)
	var i HrmsAttendancePolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.BranchID,
		&i.DepartmentID,
		&i.UserID,
		&i.ScheduleType,
		&i.IsDefault,
		&i.StandardWorkMinutes,
		&i.MinHalfDayMinutes,
		&i.MinFullDayMinutes,
		&i.GraceLateMinutes,
		&i.GraceEarlyMinutes,
		&i.HalfDayLateAfterMinutes,
		&i.AbsentLateAfterMinutes,
		&i.HalfDayEarlyBeforeMinutes,
		&i.AbsentEarlyBeforeMinutes,
		&i.AllowFlexiHours,
		&i.CoreStartTime,
		&i.CoreEndTime,
		&i.AllowWfh,
		&i.WfhDaysPerWeek,
		&i.AllowPermanentRemote,
		&i.RequireGeo,
		&i.RequireDevice,
		&i.RegularizationWindowDays,
		&i.MaxRegularizationsPerMonth,
		&i.ApprovalMode,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const softDeleteAttendance = `-- name: SoftDeleteAttendance :exec
UPDATE hrms.attendances
SET inactive = TRUE, updated_by = $3
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteAttendanceParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteAttendance(ctx context.Context, arg SoftDeleteAttendanceParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttendance, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteAttendanceDevice = `-- name: SoftDeleteAttendanceDevice :exec
UPDATE hrms.attendance_devices
SET inactive = TRUE, updated_by = $3, updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteAttendanceDeviceParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteAttendanceDevice(ctx context.Context, arg SoftDeleteAttendanceDeviceParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttendanceDevice, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteAttendanceLocation = `-- name: SoftDeleteAttendanceLocation :exec
UPDATE hrms.attendance_locations
SET inactive = TRUE, updated_by = $3, updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteAttendanceLocationParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteAttendanceLocation(ctx context.Context, arg SoftDeleteAttendanceLocationParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttendanceLocation, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteAttendanceLocationAssignment = `-- name: SoftDeleteAttendanceLocationAssignment :exec
UPDATE hrms.attendance_location_assignments
SET inactive = TRUE, updated_by = $3, updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteAttendanceLocationAssignmentParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteAttendanceLocationAssignment(ctx context.Context, arg SoftDeleteAttendanceLocationAssignmentParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttendanceLocationAssignment, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteAttendancePolicy = `-- name: SoftDeleteAttendancePolicy :exec
UPDATE hrms.attendance_policies
SET inactive = TRUE, updated_by = $3, updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteAttendancePolicyParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteAttendancePolicy(ctx context.Context, arg SoftDeleteAttendancePolicyParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttendancePolicy, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteAttendanceRequest = `-- name: SoftDeleteAttendanceRequest :exec
UPDATE hrms.attendance_requests
SET inactive = TRUE, updated_by = $3
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteAttendanceRequestParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteAttendanceRequest(ctx context.Context, arg SoftDeleteAttendanceRequestParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttendanceRequest, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteAttendanceRoster = `-- name: SoftDeleteAttendanceRoster :exec
UPDATE hrms.attendance_rosters
SET inactive = TRUE, updated_by = $3, updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteAttendanceRosterParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteAttendanceRoster(ctx context.Context, arg SoftDeleteAttendanceRosterParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttendanceRoster, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteDeviceLog = `-- name: SoftDeleteDeviceLog :exec
UPDATE hrms.device_logs
SET inactive = TRUE, updated_by = $3
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteDeviceLogParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteDeviceLog(ctx context.Context, arg SoftDeleteDeviceLogParams) error {
	_, err := q.db.Exec(ctx, softDeleteDeviceLog, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteEmployeeAttendanceDevice = `-- name: SoftDeleteEmployeeAttendanceDevice :exec
UPDATE hrms.employee_attendance_devices
SET inactive = TRUE, updated_by = $3, updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteEmployeeAttendanceDeviceParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteEmployeeAttendanceDevice(ctx context.Context, arg SoftDeleteEmployeeAttendanceDeviceParams) error {
	_, err := q.db.Exec(ctx, softDeleteEmployeeAttendanceDevice, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const updateAttendance = `-- name: UpdateAttendance :one
UPDATE hrms.attendances
SET
    time = $3,
    type = $4,
    status = $5,
    source = $6,
    latitude = $7,
    longitude = $8,
    work_mode = $9,
    remarks = $10,
    updated_by = $11,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, user_id, date, time, type, status, source, latitude, longitude, work_mode, remarks, inactive, created_at, created_by, updated_at, updated_by, attendance_location_id, attendance_device_id, raw_attendance_event_id, location_accuracy_meters, location_verification_status
`

type UpdateAttendanceParams struct {
	TenantID  uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID          `db:"id" json:"id"`
	Time      pgtype.Timestamptz `db:"time" json:"time"`
	Type      pgtype.Text        `db:"type" json:"type"`
	Status    pgtype.Text        `db:"status" json:"status"`
	Source    pgtype.Text        `db:"source" json:"source"`
	Latitude  pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude pgtype.Numeric     `db:"longitude" json:"longitude"`
	WorkMode  pgtype.Text        `db:"work_mode" json:"work_mode"`
	Remarks   pgtype.Text        `db:"remarks" json:"remarks"`
	UpdatedBy pgtype.UUID        `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateAttendance(ctx context.Context, arg UpdateAttendanceParams) (HrmsAttendance, error) {
	row := q.db.QueryRow(ctx, updateAttendance,
		arg.TenantID,
		arg.ID,
		arg.Time,
		arg.Type,
		arg.Status,
		arg.Source,
		arg.Latitude,
		arg.Longitude,
		arg.WorkMode,
		arg.Remarks,
		arg.UpdatedBy,
	)
	var i HrmsAttendance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Date,
		&i.Time,
		&i.Type,
		&i.Status,
		&i.Source,
		&i.Latitude,
		&i.Longitude,
		&i.WorkMode,
		&i.Remarks,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.AttendanceLocationID,
		&i.AttendanceDeviceID,
		&i.RawAttendanceEventID,
		&i.LocationAccuracyMeters,
		&i.LocationVerificationStatus,
	)
	return i, err
}

const updateAttendanceDevice = `-- name: UpdateAttendanceDevice :one
UPDATE hrms.attendance_devices
SET attendance_location_id = $3,
    branch_id = $4,
    code = $5,
    name = $6,
    vendor = $7,
    model = $8,
    serial_number = $9,
    device_identifier = $10,
    integration_type = $11,
    direction_mode = $12,
    timezone = $13,
    status = $14,
    config = $15,
    updated_by = $16,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, attendance_location_id, branch_id, code, name, vendor, model, serial_number, device_identifier, integration_type, direction_mode, timezone, status, last_seen_at, config, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateAttendanceDeviceParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID                   uuid.UUID   `db:"id" json:"id"`
	AttendanceLocationID pgtype.UUID `db:"attendance_location_id" json:"attendance_location_id"`
	BranchID             pgtype.UUID `db:"branch_id" json:"branch_id"`
	Code                 string      `db:"code" json:"code"`
	Name                 string      `db:"name" json:"name"`
	Vendor               pgtype.Text `db:"vendor" json:"vendor"`
	Model                pgtype.Text `db:"model" json:"model"`
	SerialNumber         pgtype.Text `db:"serial_number" json:"serial_number"`
	DeviceIdentifier     pgtype.Text `db:"device_identifier" json:"device_identifier"`
	IntegrationType      string      `db:"integration_type" json:"integration_type"`
	DirectionMode        string      `db:"direction_mode" json:"direction_mode"`
	Timezone             string      `db:"timezone" json:"timezone"`
	Status               string      `db:"status" json:"status"`
	Config               []byte      `db:"config" json:"config"`
	UpdatedBy            pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateAttendanceDevice(ctx context.Context, arg UpdateAttendanceDeviceParams) (HrmsAttendanceDevice, error) {
	row := q.db.QueryRow(ctx, updateAttendanceDevice,
		arg.TenantID,
		arg.ID,
		arg.AttendanceLocationID,
		arg.BranchID,
		arg.Code,
		arg.Name,
		arg.Vendor,
		arg.Model,
		arg.SerialNumber,
		arg.DeviceIdentifier,
		arg.IntegrationType,
		arg.DirectionMode,
		arg.Timezone,
		arg.Status,
		arg.Config,
		arg.UpdatedBy,
	)
	var i HrmsAttendanceDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AttendanceLocationID,
		&i.BranchID,
		&i.Code,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.DeviceIdentifier,
		&i.IntegrationType,
		&i.DirectionMode,
		&i.Timezone,
		&i.Status,
		&i.LastSeenAt,
		&i.Config,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateAttendanceLocation = `-- name: UpdateAttendanceLocation :one
UPDATE hrms.attendance_locations
SET branch_id = $3,
    code = $4,
    name = $5,
    location_type = $6,
    latitude = $7,
    longitude = $8,
    radius_meters = $9,
    address = $10,
    city = $11,
    state = $12,
    country = $13,
    pincode = $14,
    effective_from = $15,
    effective_to = $16,
    updated_by = $17,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, branch_id, code, name, location_type, latitude, longitude, radius_meters, address, city, state, country, pincode, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateAttendanceLocationParams struct {
	TenantID      uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	ID            uuid.UUID      `db:"id" json:"id"`
	BranchID      pgtype.UUID    `db:"branch_id" json:"branch_id"`
	Code          string         `db:"code" json:"code"`
	Name          string         `db:"name" json:"name"`
	LocationType  string         `db:"location_type" json:"location_type"`
	Latitude      pgtype.Numeric `db:"latitude" json:"latitude"`
	Longitude     pgtype.Numeric `db:"longitude" json:"longitude"`
	RadiusMeters  int32          `db:"radius_meters" json:"radius_meters"`
	Address       pgtype.Text    `db:"address" json:"address"`
	City          pgtype.Text    `db:"city" json:"city"`
	State         pgtype.Text    `db:"state" json:"state"`
	Country       pgtype.Text    `db:"country" json:"country"`
	Pincode       pgtype.Text    `db:"pincode" json:"pincode"`
	EffectiveFrom pgtype.Date    `db:"effective_from" json:"effective_from"`
	EffectiveTo   pgtype.Date    `db:"effective_to" json:"effective_to"`
	UpdatedBy     pgtype.UUID    `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateAttendanceLocation(ctx context.Context, arg UpdateAttendanceLocationParams) (HrmsAttendanceLocation, error) {
	row := q.db.QueryRow(ctx, updateAttendanceLocation,
		arg.TenantID,
		arg.ID,
		arg.BranchID,
		arg.Code,
		arg.Name,
		arg.LocationType,
		arg.Latitude,
		arg.Longitude,
		arg.RadiusMeters,
		arg.Address,
		arg.City,
		arg.State,
		arg.Country,
		arg.Pincode,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.UpdatedBy,
	)
	var i HrmsAttendanceLocation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Code,
		&i.Name,
		&i.LocationType,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.Address,
		&i.City,
		&i.State,
		&i.Country,
		&i.Pincode,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateAttendanceLocationAssignment = `-- name: UpdateAttendanceLocationAssignment :one
UPDATE hrms.attendance_location_assignments
SET location_id = $3,
    branch_id = $4,
    department_id = $5,
    user_id = $6,
    effective_from = $7,
    effective_to = $8,
    updated_by = $9,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, location_id, branch_id, department_id, user_id, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateAttendanceLocationAssignmentParams struct {
	TenantID      uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID            uuid.UUID   `db:"id" json:"id"`
	LocationID    uuid.UUID   `db:"location_id" json:"location_id"`
	BranchID      pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID  pgtype.UUID `db:"department_id" json:"department_id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
	EffectiveFrom pgtype.Date `db:"effective_from" json:"effective_from"`
	EffectiveTo   pgtype.Date `db:"effective_to" json:"effective_to"`
	UpdatedBy     pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateAttendanceLocationAssignment(ctx context.Context, arg UpdateAttendanceLocationAssignmentParams) (HrmsAttendanceLocationAssignment, error) {
	row := q.db.QueryRow(ctx, updateAttendanceLocationAssignment,
		arg.TenantID,
		arg.ID,
		arg.LocationID,
		arg.BranchID,
		arg.DepartmentID,
		arg.UserID,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.UpdatedBy,
	)
	var i HrmsAttendanceLocationAssignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.BranchID,
		&i.DepartmentID,
		&i.UserID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateAttendancePolicy = `-- name: UpdateAttendancePolicy :one
UPDATE hrms.attendance_policies
SET
    name = $3,
    code = $4,
    description = $5,
    branch_id = $6,
    department_id = $7,
    user_id = $8,
    schedule_type = $9,
    is_default = $10,
    standard_work_minutes = $11,
    min_half_day_minutes = $12,
    min_full_day_minutes = $13,
    grace_late_minutes = $14,
    grace_early_minutes = $15,
    half_day_late_after_minutes = $16,
    absent_late_after_minutes = $17,
    half_day_early_before_minutes = $18,
    absent_early_before_minutes = $19,
    allow_flexi_hours = $20,
    core_start_time = $21,
    core_end_time = $22,
    allow_wfh = $23,
    wfh_days_per_week = $24,
    allow_permanent_remote = $25,
    require_geo = $26,
    require_device = $27,
    regularization_window_days = $28,
    max_regularizations_per_month = $29,
    approval_mode = $30,
    effective_from = $31,
    effective_to = $32,
    updated_by = $33,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, name, code, description, branch_id, department_id, user_id, schedule_type, is_default, standard_work_minutes, min_half_day_minutes, min_full_day_minutes, grace_late_minutes, grace_early_minutes, half_day_late_after_minutes, absent_late_after_minutes, half_day_early_before_minutes, absent_early_before_minutes, allow_flexi_hours, core_start_time, core_end_time, allow_wfh, wfh_days_per_week, allow_permanent_remote, require_geo, require_device, regularization_window_days, max_regularizations_per_month, approval_mode, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateAttendancePolicyParams struct {
	TenantID                   uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID                         uuid.UUID   `db:"id" json:"id"`
	Name                       string      `db:"name" json:"name"`
	Code                       string      `db:"code" json:"code"`
	Description                pgtype.Text `db:"description" json:"description"`
	BranchID                   pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID               pgtype.UUID `db:"department_id" json:"department_id"`
	UserID                     pgtype.UUID `db:"user_id" json:"user_id"`
	ScheduleType               string      `db:"schedule_type" json:"schedule_type"`
	IsDefault                  bool        `db:"is_default" json:"is_default"`
	StandardWorkMinutes        int32       `db:"standard_work_minutes" json:"standard_work_minutes"`
	MinHalfDayMinutes          int32       `db:"min_half_day_minutes" json:"min_half_day_minutes"`
	MinFullDayMinutes          int32       `db:"min_full_day_minutes" json:"min_full_day_minutes"`
	GraceLateMinutes           int32       `db:"grace_late_minutes" json:"grace_late_minutes"`
	GraceEarlyMinutes          int32       `db:"grace_early_minutes" json:"grace_early_minutes"`
	HalfDayLateAfterMinutes    pgtype.Int4 `db:"half_day_late_after_minutes" json:"half_day_late_after_minutes"`
	AbsentLateAfterMinutes     pgtype.Int4 `db:"absent_late_after_minutes" json:"absent_late_after_minutes"`
	HalfDayEarlyBeforeMinutes  pgtype.Int4 `db:"half_day_early_before_minutes" json:"half_day_early_before_minutes"`
	AbsentEarlyBeforeMinutes   pgtype.Int4 `db:"absent_early_before_minutes" json:"absent_early_before_minutes"`
	AllowFlexiHours            bool        `db:"allow_flexi_hours" json:"allow_flexi_hours"`
	CoreStartTime              pgtype.Time `db:"core_start_time" json:"core_start_time"`
	CoreEndTime                pgtype.Time `db:"core_end_time" json:"core_end_time"`
	AllowWfh                   bool        `db:"allow_wfh" json:"allow_wfh"`
	WfhDaysPerWeek             int32       `db:"wfh_days_per_week" json:"wfh_days_per_week"`
	AllowPermanentRemote       bool        `db:"allow_permanent_remote" json:"allow_permanent_remote"`
	RequireGeo                 bool        `db:"require_geo" json:"require_geo"`
	RequireDevice              bool        `db:"require_device" json:"require_device"`
	RegularizationWindowDays   int32       `db:"regularization_window_days" json:"regularization_window_days"`
	MaxRegularizationsPerMonth int32       `db:"max_regularizations_per_month" json:"max_regularizations_per_month"`
	ApprovalMode               string      `db:"approval_mode" json:"approval_mode"`
	EffectiveFrom              pgtype.Date `db:"effective_from" json:"effective_from"`
	EffectiveTo                pgtype.Date `db:"effective_to" json:"effective_to"`
	UpdatedBy                  pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateAttendancePolicy(ctx context.Context, arg UpdateAttendancePolicyParams) (HrmsAttendancePolicy, error) {
	row := q.db.QueryRow(ctx, updateAttendancePolicy,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.BranchID,
		arg.DepartmentID,
		arg.UserID,
		arg.ScheduleType,
		arg.IsDefault,
		arg.StandardWorkMinutes,
		arg.MinHalfDayMinutes,
		arg.MinFullDayMinutes,
		arg.GraceLateMinutes,
		arg.GraceEarlyMinutes,
		arg.HalfDayLateAfterMinutes,
		arg.AbsentLateAfterMinutes,
		arg.HalfDayEarlyBeforeMinutes,
		arg.AbsentEarlyBeforeMinutes,
		arg.AllowFlexiHours,
		arg.CoreStartTime,
		arg.CoreEndTime,
		arg.AllowWfh,
		arg.WfhDaysPerWeek,
		arg.AllowPermanentRemote,
		arg.RequireGeo,
		arg.RequireDevice,
		arg.RegularizationWindowDays,
		arg.MaxRegularizationsPerMonth,
		arg.ApprovalMode,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.UpdatedBy,
	)
	var i HrmsAttendancePolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.BranchID,
		&i.DepartmentID,
		&i.UserID,
		&i.ScheduleType,
		&i.IsDefault,
		&i.StandardWorkMinutes,
		&i.MinHalfDayMinutes,
		&i.MinFullDayMinutes,
		&i.GraceLateMinutes,
		&i.GraceEarlyMinutes,
		&i.HalfDayLateAfterMinutes,
		&i.AbsentLateAfterMinutes,
		&i.HalfDayEarlyBeforeMinutes,
		&i.AbsentEarlyBeforeMinutes,
		&i.AllowFlexiHours,
		&i.CoreStartTime,
		&i.CoreEndTime,
		&i.AllowWfh,
		&i.WfhDaysPerWeek,
		&i.AllowPermanentRemote,
		&i.RequireGeo,
		&i.RequireDevice,
		&i.RegularizationWindowDays,
		&i.MaxRegularizationsPerMonth,
		&i.ApprovalMode,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateAttendanceRequestReview = `-- name: UpdateAttendanceRequestReview :one
UPDATE hrms.attendance_requests
SET status = $3,
    reviewed_by = $4,
    reviewed_at = NOW(),
    remarks = $5,
    updated_by = $4,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, user_id, date, requested_type, reason, status, reviewed_by, reviewed_at, remarks, inactive, created_at, created_by, updated_at, updated_by, request_type, requested_checkin_at, requested_checkout_at, requested_work_mode, policy_id, roster_id, workflow_id, route_mode, escalation_due_at, escalated_at, payroll_blocking
`

type UpdateAttendanceRequestReviewParams struct {
	TenantID   uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID         uuid.UUID   `db:"id" json:"id"`
	Status     string      `db:"status" json:"status"`
	ReviewedBy pgtype.UUID `db:"reviewed_by" json:"reviewed_by"`
	Remarks    pgtype.Text `db:"remarks" json:"remarks"`
}

func (q *Queries) UpdateAttendanceRequestReview(ctx context.Context, arg UpdateAttendanceRequestReviewParams) (HrmsAttendanceRequest, error) {
	row := q.db.QueryRow(ctx, updateAttendanceRequestReview,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.Remarks,
	)
	var i HrmsAttendanceRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Date,
		&i.RequestedType,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Remarks,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RequestType,
		&i.RequestedCheckinAt,
		&i.RequestedCheckoutAt,
		&i.RequestedWorkMode,
		&i.PolicyID,
		&i.RosterID,
		&i.WorkflowID,
		&i.RouteMode,
		&i.EscalationDueAt,
		&i.EscalatedAt,
		&i.PayrollBlocking,
	)
	return i, err
}

const updateAttendanceRoster = `-- name: UpdateAttendanceRoster :one
UPDATE hrms.attendance_rosters
SET policy_id = $3,
    date = $4,
    start_time = $5,
    end_time = $6,
    break_minutes = $7,
    work_mode = $8,
    location_type = $9,
    remarks = $10,
    updated_by = $11,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, user_id, policy_id, date, start_time, end_time, break_minutes, work_mode, location_type, remarks, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateAttendanceRosterParams struct {
	TenantID     uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID           uuid.UUID   `db:"id" json:"id"`
	PolicyID     pgtype.UUID `db:"policy_id" json:"policy_id"`
	Date         pgtype.Date `db:"date" json:"date"`
	StartTime    pgtype.Time `db:"start_time" json:"start_time"`
	EndTime      pgtype.Time `db:"end_time" json:"end_time"`
	BreakMinutes int32       `db:"break_minutes" json:"break_minutes"`
	WorkMode     string      `db:"work_mode" json:"work_mode"`
	LocationType string      `db:"location_type" json:"location_type"`
	Remarks      pgtype.Text `db:"remarks" json:"remarks"`
	UpdatedBy    pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateAttendanceRoster(ctx context.Context, arg UpdateAttendanceRosterParams) (HrmsAttendanceRoster, error) {
	row := q.db.QueryRow(ctx, updateAttendanceRoster,
		arg.TenantID,
		arg.ID,
		arg.PolicyID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMinutes,
		arg.WorkMode,
		arg.LocationType,
		arg.Remarks,
		arg.UpdatedBy,
	)
	var i HrmsAttendanceRoster
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PolicyID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.WorkMode,
		&i.LocationType,
		&i.Remarks,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateEmployeeAttendanceDevice = `-- name: UpdateEmployeeAttendanceDevice :one
UPDATE hrms.employee_attendance_devices
SET user_id = $3,
    device_id = $4,
    device_user_id = $5,
    credential_type = $6,
    card_number = $7,
    effective_from = $8,
    effective_to = $9,
    updated_by = $10,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, user_id, device_id, device_user_id, credential_type, card_number, effective_from, effective_to, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateEmployeeAttendanceDeviceParams struct {
	TenantID       uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID             uuid.UUID   `db:"id" json:"id"`
	UserID         uuid.UUID   `db:"user_id" json:"user_id"`
	DeviceID       uuid.UUID   `db:"device_id" json:"device_id"`
	DeviceUserID   string      `db:"device_user_id" json:"device_user_id"`
	CredentialType string      `db:"credential_type" json:"credential_type"`
	CardNumber     pgtype.Text `db:"card_number" json:"card_number"`
	EffectiveFrom  pgtype.Date `db:"effective_from" json:"effective_from"`
	EffectiveTo    pgtype.Date `db:"effective_to" json:"effective_to"`
	UpdatedBy      pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateEmployeeAttendanceDevice(ctx context.Context, arg UpdateEmployeeAttendanceDeviceParams) (HrmsEmployeeAttendanceDevice, error) {
	row := q.db.QueryRow(ctx, updateEmployeeAttendanceDevice,
		arg.TenantID,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.DeviceUserID,
		arg.CredentialType,
		arg.CardNumber,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.UpdatedBy,
	)
	var i HrmsEmployeeAttendanceDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceUserID,
		&i.CredentialType,
		&i.CardNumber,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateRawAttendanceEventProcessed = `-- name: UpdateRawAttendanceEventProcessed :one
UPDATE hrms.raw_attendance_events
SET attendance_id = $3,
    processing_status = $4,
    processing_error = $5,
    processed_at = NOW(),
    updated_by = $6,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, device_id, employee_device_mapping_id, attendance_id, external_event_id, device_user_id, event_time, event_type, attendance_type, import_batch_id, processing_status, processing_error, raw_payload, processed_at, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateRawAttendanceEventProcessedParams struct {
	TenantID         uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID               uuid.UUID   `db:"id" json:"id"`
	AttendanceID     pgtype.UUID `db:"attendance_id" json:"attendance_id"`
	ProcessingStatus string      `db:"processing_status" json:"processing_status"`
	ProcessingError  pgtype.Text `db:"processing_error" json:"processing_error"`
	UpdatedBy        pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateRawAttendanceEventProcessed(ctx context.Context, arg UpdateRawAttendanceEventProcessedParams) (HrmsRawAttendanceEvent, error) {
	row := q.db.QueryRow(ctx, updateRawAttendanceEventProcessed,
		arg.TenantID,
		arg.ID,
		arg.AttendanceID,
		arg.ProcessingStatus,
		arg.ProcessingError,
		arg.UpdatedBy,
	)
	var i HrmsRawAttendanceEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeviceID,
		&i.EmployeeDeviceMappingID,
		&i.AttendanceID,
		&i.ExternalEventID,
		&i.DeviceUserID,
		&i.EventTime,
		&i.EventType,
		&i.AttendanceType,
		&i.ImportBatchID,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.RawPayload,
		&i.ProcessedAt,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
