// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: celebrations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCelebration = `-- name: CreateCelebration :one
INSERT INTO hrms.celebrations (tenant_id, branch_id, user_id, celebration_type_id, celebration_date, custom_title, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, branch_id, user_id, celebration_type_id, celebration_date, custom_title, description, inactive, created_at, created_by, updated_at, updated_by
`

type CreateCelebrationParams struct {
	TenantID          uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	BranchID          pgtype.UUID `db:"branch_id" json:"branch_id"`
	UserID            pgtype.UUID `db:"user_id" json:"user_id"`
	CelebrationTypeID uuid.UUID   `db:"celebration_type_id" json:"celebration_type_id"`
	CelebrationDate   pgtype.Date `db:"celebration_date" json:"celebration_date"`
	CustomTitle       pgtype.Text `db:"custom_title" json:"custom_title"`
	Description       pgtype.Text `db:"description" json:"description"`
	CreatedBy         pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateCelebration(ctx context.Context, arg CreateCelebrationParams) (HrmsCelebration, error) {
	row := q.db.QueryRow(ctx, createCelebration,
		arg.TenantID,
		arg.BranchID,
		arg.UserID,
		arg.CelebrationTypeID,
		arg.CelebrationDate,
		arg.CustomTitle,
		arg.Description,
		arg.CreatedBy,
	)
	var i HrmsCelebration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.UserID,
		&i.CelebrationTypeID,
		&i.CelebrationDate,
		&i.CustomTitle,
		&i.Description,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createCelebrationType = `-- name: CreateCelebrationType :one
INSERT INTO hrms.celebration_types (tenant_id, name, is_yearly, is_user_celebration, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, is_yearly, is_user_celebration, inactive, created_at, created_by, updated_at, updated_by
`

type CreateCelebrationTypeParams struct {
	TenantID          uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Name              string      `db:"name" json:"name"`
	IsYearly          bool        `db:"is_yearly" json:"is_yearly"`
	IsUserCelebration bool        `db:"is_user_celebration" json:"is_user_celebration"`
	CreatedBy         pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateCelebrationType(ctx context.Context, arg CreateCelebrationTypeParams) (HrmsCelebrationType, error) {
	row := q.db.QueryRow(ctx, createCelebrationType,
		arg.TenantID,
		arg.Name,
		arg.IsYearly,
		arg.IsUserCelebration,
		arg.CreatedBy,
	)
	var i HrmsCelebrationType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IsYearly,
		&i.IsUserCelebration,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCelebration = `-- name: GetCelebration :one
SELECT id, tenant_id, branch_id, user_id, celebration_type_id, celebration_date, custom_title, description, inactive, created_at, created_by, updated_at, updated_by FROM hrms.celebrations
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetCelebrationParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetCelebration(ctx context.Context, arg GetCelebrationParams) (HrmsCelebration, error) {
	row := q.db.QueryRow(ctx, getCelebration, arg.TenantID, arg.ID)
	var i HrmsCelebration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.UserID,
		&i.CelebrationTypeID,
		&i.CelebrationDate,
		&i.CustomTitle,
		&i.Description,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCelebrationType = `-- name: GetCelebrationType :one
SELECT id, tenant_id, name, is_yearly, is_user_celebration, inactive, created_at, created_by, updated_at, updated_by FROM hrms.celebration_types
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetCelebrationTypeParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetCelebrationType(ctx context.Context, arg GetCelebrationTypeParams) (HrmsCelebrationType, error) {
	row := q.db.QueryRow(ctx, getCelebrationType, arg.TenantID, arg.ID)
	var i HrmsCelebrationType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IsYearly,
		&i.IsUserCelebration,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listCelebrationTypes = `-- name: ListCelebrationTypes :many
SELECT id, tenant_id, name, is_yearly, is_user_celebration, inactive, created_at, created_by, updated_at, updated_by FROM hrms.celebration_types
WHERE tenant_id = $1 AND NOT inactive
ORDER BY name ASC
`

func (q *Queries) ListCelebrationTypes(ctx context.Context, tenantID uuid.UUID) ([]HrmsCelebrationType, error) {
	rows, err := q.db.Query(ctx, listCelebrationTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsCelebrationType
	for rows.Next() {
		var i HrmsCelebrationType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.IsYearly,
			&i.IsUserCelebration,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCelebrations = `-- name: ListCelebrations :many
SELECT id, tenant_id, branch_id, user_id, celebration_type_id, celebration_date, custom_title, description, inactive, created_at, created_by, updated_at, updated_by FROM hrms.celebrations
WHERE tenant_id = $1 AND NOT inactive
ORDER BY celebration_date ASC NULLS LAST, created_at DESC
`

func (q *Queries) ListCelebrations(ctx context.Context, tenantID uuid.UUID) ([]HrmsCelebration, error) {
	rows, err := q.db.Query(ctx, listCelebrations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsCelebration
	for rows.Next() {
		var i HrmsCelebration
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.UserID,
			&i.CelebrationTypeID,
			&i.CelebrationDate,
			&i.CustomTitle,
			&i.Description,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCelebrationsByUser = `-- name: ListCelebrationsByUser :many
SELECT id, tenant_id, branch_id, user_id, celebration_type_id, celebration_date, custom_title, description, inactive, created_at, created_by, updated_at, updated_by FROM hrms.celebrations
WHERE tenant_id = $1 AND user_id = $2 AND NOT inactive
ORDER BY celebration_date ASC NULLS LAST
`

type ListCelebrationsByUserParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ListCelebrationsByUser(ctx context.Context, arg ListCelebrationsByUserParams) ([]HrmsCelebration, error) {
	rows, err := q.db.Query(ctx, listCelebrationsByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsCelebration
	for rows.Next() {
		var i HrmsCelebration
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.UserID,
			&i.CelebrationTypeID,
			&i.CelebrationDate,
			&i.CustomTitle,
			&i.Description,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCelebration = `-- name: SoftDeleteCelebration :exec
UPDATE hrms.celebrations
SET inactive = TRUE, updated_at = NOW(), updated_by = $3
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteCelebrationParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteCelebration(ctx context.Context, arg SoftDeleteCelebrationParams) error {
	_, err := q.db.Exec(ctx, softDeleteCelebration, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteCelebrationType = `-- name: SoftDeleteCelebrationType :exec
UPDATE hrms.celebration_types
SET inactive = TRUE, updated_by = $3
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteCelebrationTypeParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteCelebrationType(ctx context.Context, arg SoftDeleteCelebrationTypeParams) error {
	_, err := q.db.Exec(ctx, softDeleteCelebrationType, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const updateCelebration = `-- name: UpdateCelebration :one
UPDATE hrms.celebrations
SET branch_id = $3,
    user_id = $4,
    celebration_type_id = $5,
    celebration_date = $6,
    custom_title = $7,
    description = $8,
    updated_at = NOW(),
    updated_by = $9
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, branch_id, user_id, celebration_type_id, celebration_date, custom_title, description, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateCelebrationParams struct {
	TenantID          uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID                uuid.UUID   `db:"id" json:"id"`
	BranchID          pgtype.UUID `db:"branch_id" json:"branch_id"`
	UserID            pgtype.UUID `db:"user_id" json:"user_id"`
	CelebrationTypeID uuid.UUID   `db:"celebration_type_id" json:"celebration_type_id"`
	CelebrationDate   pgtype.Date `db:"celebration_date" json:"celebration_date"`
	CustomTitle       pgtype.Text `db:"custom_title" json:"custom_title"`
	Description       pgtype.Text `db:"description" json:"description"`
	UpdatedBy         pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateCelebration(ctx context.Context, arg UpdateCelebrationParams) (HrmsCelebration, error) {
	row := q.db.QueryRow(ctx, updateCelebration,
		arg.TenantID,
		arg.ID,
		arg.BranchID,
		arg.UserID,
		arg.CelebrationTypeID,
		arg.CelebrationDate,
		arg.CustomTitle,
		arg.Description,
		arg.UpdatedBy,
	)
	var i HrmsCelebration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.UserID,
		&i.CelebrationTypeID,
		&i.CelebrationDate,
		&i.CustomTitle,
		&i.Description,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateCelebrationType = `-- name: UpdateCelebrationType :one
UPDATE hrms.celebration_types
SET name = $3,
    is_yearly = $4,
    is_user_celebration = $5,
    updated_at = NOW(),
    updated_by = $6
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, name, is_yearly, is_user_celebration, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateCelebrationTypeParams struct {
	TenantID          uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID                uuid.UUID   `db:"id" json:"id"`
	Name              string      `db:"name" json:"name"`
	IsYearly          bool        `db:"is_yearly" json:"is_yearly"`
	IsUserCelebration bool        `db:"is_user_celebration" json:"is_user_celebration"`
	UpdatedBy         pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateCelebrationType(ctx context.Context, arg UpdateCelebrationTypeParams) (HrmsCelebrationType, error) {
	row := q.db.QueryRow(ctx, updateCelebrationType,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.IsYearly,
		arg.IsUserCelebration,
		arg.UpdatedBy,
	)
	var i HrmsCelebrationType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IsYearly,
		&i.IsUserCelebration,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
