// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compensation_review.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompensationBudgetPool = `-- name: CreateCompensationBudgetPool :one
INSERT INTO hrms.compensation_budget_pools (
    tenant_id, cycle_id, name, pool_type, owner_user_id, department_id, branch_id,
    budget_amount, allocated_amount, notes, created_by, updated_by
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11)
RETURNING id, tenant_id, cycle_id, name, pool_type, owner_user_id, department_id, branch_id, budget_amount, allocated_amount, notes, inactive, created_at, created_by, updated_at, updated_by
`

type CreateCompensationBudgetPoolParams struct {
	TenantID        uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	CycleID         uuid.UUID      `db:"cycle_id" json:"cycle_id"`
	Name            string         `db:"name" json:"name"`
	PoolType        string         `db:"pool_type" json:"pool_type"`
	OwnerUserID     pgtype.UUID    `db:"owner_user_id" json:"owner_user_id"`
	DepartmentID    pgtype.UUID    `db:"department_id" json:"department_id"`
	BranchID        pgtype.UUID    `db:"branch_id" json:"branch_id"`
	BudgetAmount    pgtype.Numeric `db:"budget_amount" json:"budget_amount"`
	AllocatedAmount pgtype.Numeric `db:"allocated_amount" json:"allocated_amount"`
	Notes           pgtype.Text    `db:"notes" json:"notes"`
	CreatedBy       pgtype.UUID    `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateCompensationBudgetPool(ctx context.Context, arg CreateCompensationBudgetPoolParams) (HrmsCompensationBudgetPool, error) {
	row := q.db.QueryRow(ctx, createCompensationBudgetPool,
		arg.TenantID,
		arg.CycleID,
		arg.Name,
		arg.PoolType,
		arg.OwnerUserID,
		arg.DepartmentID,
		arg.BranchID,
		arg.BudgetAmount,
		arg.AllocatedAmount,
		arg.Notes,
		arg.CreatedBy,
	)
	var i HrmsCompensationBudgetPool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CycleID,
		&i.Name,
		&i.PoolType,
		&i.OwnerUserID,
		&i.DepartmentID,
		&i.BranchID,
		&i.BudgetAmount,
		&i.AllocatedAmount,
		&i.Notes,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createCompensationCycle = `-- name: CreateCompensationCycle :one
INSERT INTO hrms.compensation_cycles (
    tenant_id, code, name, fiscal_year_id, status, cycle_type, starts_on, ends_on,
    effective_date, currency_code, budget_amount, planning_guidance, approval_policy, metadata,
    created_by, updated_by
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$15)
RETURNING id, tenant_id, code, name, fiscal_year_id, status, cycle_type, starts_on, ends_on, effective_date, currency_code, budget_amount, planning_guidance, approval_policy, finalized_at, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateCompensationCycleParams struct {
	TenantID         uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	Code             string         `db:"code" json:"code"`
	Name             string         `db:"name" json:"name"`
	FiscalYearID     pgtype.UUID    `db:"fiscal_year_id" json:"fiscal_year_id"`
	Status           string         `db:"status" json:"status"`
	CycleType        string         `db:"cycle_type" json:"cycle_type"`
	StartsOn         pgtype.Date    `db:"starts_on" json:"starts_on"`
	EndsOn           pgtype.Date    `db:"ends_on" json:"ends_on"`
	EffectiveDate    pgtype.Date    `db:"effective_date" json:"effective_date"`
	CurrencyCode     string         `db:"currency_code" json:"currency_code"`
	BudgetAmount     pgtype.Numeric `db:"budget_amount" json:"budget_amount"`
	PlanningGuidance pgtype.Text    `db:"planning_guidance" json:"planning_guidance"`
	ApprovalPolicy   pgtype.Text    `db:"approval_policy" json:"approval_policy"`
	Metadata         []byte         `db:"metadata" json:"metadata"`
	CreatedBy        pgtype.UUID    `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateCompensationCycle(ctx context.Context, arg CreateCompensationCycleParams) (HrmsCompensationCycle, error) {
	row := q.db.QueryRow(ctx, createCompensationCycle,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.FiscalYearID,
		arg.Status,
		arg.CycleType,
		arg.StartsOn,
		arg.EndsOn,
		arg.EffectiveDate,
		arg.CurrencyCode,
		arg.BudgetAmount,
		arg.PlanningGuidance,
		arg.ApprovalPolicy,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsCompensationCycle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.FiscalYearID,
		&i.Status,
		&i.CycleType,
		&i.StartsOn,
		&i.EndsOn,
		&i.EffectiveDate,
		&i.CurrencyCode,
		&i.BudgetAmount,
		&i.PlanningGuidance,
		&i.ApprovalPolicy,
		&i.FinalizedAt,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createCompensationEvent = `-- name: CreateCompensationEvent :one
INSERT INTO hrms.compensation_events (
    tenant_id, cycle_id, source_type, source_id, action, from_status, to_status, remarks, metadata, created_by
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, tenant_id, cycle_id, source_type, source_id, action, from_status, to_status, remarks, metadata, created_at, created_by
`

type CreateCompensationEventParams struct {
	TenantID   uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	CycleID    pgtype.UUID `db:"cycle_id" json:"cycle_id"`
	SourceType string      `db:"source_type" json:"source_type"`
	SourceID   pgtype.UUID `db:"source_id" json:"source_id"`
	Action     string      `db:"action" json:"action"`
	FromStatus pgtype.Text `db:"from_status" json:"from_status"`
	ToStatus   pgtype.Text `db:"to_status" json:"to_status"`
	Remarks    pgtype.Text `db:"remarks" json:"remarks"`
	Metadata   []byte      `db:"metadata" json:"metadata"`
	CreatedBy  pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateCompensationEvent(ctx context.Context, arg CreateCompensationEventParams) (HrmsCompensationEvent, error) {
	row := q.db.QueryRow(ctx, createCompensationEvent,
		arg.TenantID,
		arg.CycleID,
		arg.SourceType,
		arg.SourceID,
		arg.Action,
		arg.FromStatus,
		arg.ToStatus,
		arg.Remarks,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsCompensationEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CycleID,
		&i.SourceType,
		&i.SourceID,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.Remarks,
		&i.Metadata,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createCompensationPayBand = `-- name: CreateCompensationPayBand :one
INSERT INTO hrms.compensation_pay_bands (
    tenant_id, code, name, job_family, level_code, location_label, currency_code,
    min_pay, midpoint_pay, max_pay, effective_from, effective_to, is_active, notes, metadata,
    created_by, updated_by
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$16)
RETURNING id, tenant_id, code, name, job_family, level_code, location_label, currency_code, min_pay, midpoint_pay, max_pay, effective_from, effective_to, is_active, notes, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateCompensationPayBandParams struct {
	TenantID      uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	Code          string         `db:"code" json:"code"`
	Name          string         `db:"name" json:"name"`
	JobFamily     pgtype.Text    `db:"job_family" json:"job_family"`
	LevelCode     pgtype.Text    `db:"level_code" json:"level_code"`
	LocationLabel pgtype.Text    `db:"location_label" json:"location_label"`
	CurrencyCode  string         `db:"currency_code" json:"currency_code"`
	MinPay        pgtype.Numeric `db:"min_pay" json:"min_pay"`
	MidpointPay   pgtype.Numeric `db:"midpoint_pay" json:"midpoint_pay"`
	MaxPay        pgtype.Numeric `db:"max_pay" json:"max_pay"`
	EffectiveFrom pgtype.Date    `db:"effective_from" json:"effective_from"`
	EffectiveTo   pgtype.Date    `db:"effective_to" json:"effective_to"`
	IsActive      bool           `db:"is_active" json:"is_active"`
	Notes         pgtype.Text    `db:"notes" json:"notes"`
	Metadata      []byte         `db:"metadata" json:"metadata"`
	CreatedBy     pgtype.UUID    `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateCompensationPayBand(ctx context.Context, arg CreateCompensationPayBandParams) (HrmsCompensationPayBand, error) {
	row := q.db.QueryRow(ctx, createCompensationPayBand,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.JobFamily,
		arg.LevelCode,
		arg.LocationLabel,
		arg.CurrencyCode,
		arg.MinPay,
		arg.MidpointPay,
		arg.MaxPay,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.IsActive,
		arg.Notes,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsCompensationPayBand
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.JobFamily,
		&i.LevelCode,
		&i.LocationLabel,
		&i.CurrencyCode,
		&i.MinPay,
		&i.MidpointPay,
		&i.MaxPay,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.Notes,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createCompensationRecommendation = `-- name: CreateCompensationRecommendation :one
INSERT INTO hrms.compensation_recommendations (
    tenant_id, cycle_id, worker_profile_id, pay_band_id, budget_pool_id, current_salary,
    current_compa_ratio, recommended_salary, recommended_increment_amount,
    recommended_increment_percent, promotion_recommended, recommended_designation_id,
    reason, performance_rating, equity_flag, equity_notes, status, effective_date, metadata,
    created_by, updated_by
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$20)
RETURNING id, tenant_id, cycle_id, worker_profile_id, pay_band_id, budget_pool_id, current_salary, current_compa_ratio, recommended_salary, recommended_increment_amount, recommended_increment_percent, promotion_recommended, recommended_designation_id, reason, performance_rating, equity_flag, equity_notes, status, effective_date, payroll_handoff_at, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateCompensationRecommendationParams struct {
	TenantID                    uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	CycleID                     uuid.UUID      `db:"cycle_id" json:"cycle_id"`
	WorkerProfileID             uuid.UUID      `db:"worker_profile_id" json:"worker_profile_id"`
	PayBandID                   pgtype.UUID    `db:"pay_band_id" json:"pay_band_id"`
	BudgetPoolID                pgtype.UUID    `db:"budget_pool_id" json:"budget_pool_id"`
	CurrentSalary               pgtype.Numeric `db:"current_salary" json:"current_salary"`
	CurrentCompaRatio           pgtype.Numeric `db:"current_compa_ratio" json:"current_compa_ratio"`
	RecommendedSalary           pgtype.Numeric `db:"recommended_salary" json:"recommended_salary"`
	RecommendedIncrementAmount  pgtype.Numeric `db:"recommended_increment_amount" json:"recommended_increment_amount"`
	RecommendedIncrementPercent pgtype.Numeric `db:"recommended_increment_percent" json:"recommended_increment_percent"`
	PromotionRecommended        bool           `db:"promotion_recommended" json:"promotion_recommended"`
	RecommendedDesignationID    pgtype.UUID    `db:"recommended_designation_id" json:"recommended_designation_id"`
	Reason                      pgtype.Text    `db:"reason" json:"reason"`
	PerformanceRating           pgtype.Text    `db:"performance_rating" json:"performance_rating"`
	EquityFlag                  bool           `db:"equity_flag" json:"equity_flag"`
	EquityNotes                 pgtype.Text    `db:"equity_notes" json:"equity_notes"`
	Status                      string         `db:"status" json:"status"`
	EffectiveDate               pgtype.Date    `db:"effective_date" json:"effective_date"`
	Metadata                    []byte         `db:"metadata" json:"metadata"`
	CreatedBy                   pgtype.UUID    `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateCompensationRecommendation(ctx context.Context, arg CreateCompensationRecommendationParams) (HrmsCompensationRecommendation, error) {
	row := q.db.QueryRow(ctx, createCompensationRecommendation,
		arg.TenantID,
		arg.CycleID,
		arg.WorkerProfileID,
		arg.PayBandID,
		arg.BudgetPoolID,
		arg.CurrentSalary,
		arg.CurrentCompaRatio,
		arg.RecommendedSalary,
		arg.RecommendedIncrementAmount,
		arg.RecommendedIncrementPercent,
		arg.PromotionRecommended,
		arg.RecommendedDesignationID,
		arg.Reason,
		arg.PerformanceRating,
		arg.EquityFlag,
		arg.EquityNotes,
		arg.Status,
		arg.EffectiveDate,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsCompensationRecommendation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CycleID,
		&i.WorkerProfileID,
		&i.PayBandID,
		&i.BudgetPoolID,
		&i.CurrentSalary,
		&i.CurrentCompaRatio,
		&i.RecommendedSalary,
		&i.RecommendedIncrementAmount,
		&i.RecommendedIncrementPercent,
		&i.PromotionRecommended,
		&i.RecommendedDesignationID,
		&i.Reason,
		&i.PerformanceRating,
		&i.EquityFlag,
		&i.EquityNotes,
		&i.Status,
		&i.EffectiveDate,
		&i.PayrollHandoffAt,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const generateCompensationEquityChecks = `-- name: GenerateCompensationEquityChecks :many
WITH inserted AS (
    INSERT INTO hrms.compensation_equity_checks (
        tenant_id, cycle_id, worker_profile_id, pay_band_id, check_type, severity,
        current_salary, band_min, band_midpoint, band_max, variance_percent,
        finding, recommendation, created_by, updated_by
    )
    SELECT cr.tenant_id,
           cr.cycle_id,
           cr.worker_profile_id,
           cr.pay_band_id,
           CASE
               WHEN cr.current_salary < pb.min_pay THEN 'below_band'
               WHEN cr.current_salary > pb.max_pay THEN 'above_band'
               WHEN pb.midpoint_pay > 0 AND cr.current_salary / pb.midpoint_pay < 0.80 THEN 'low_compa_ratio'
               WHEN pb.midpoint_pay > 0 AND cr.current_salary / pb.midpoint_pay > 1.20 THEN 'high_compa_ratio'
               ELSE 'band_position'
           END,
           CASE
               WHEN cr.current_salary < pb.min_pay * 0.90 OR cr.current_salary > pb.max_pay * 1.10 THEN 'critical'
               WHEN cr.current_salary < pb.min_pay OR cr.current_salary > pb.max_pay THEN 'high'
               ELSE 'medium'
           END,
           cr.current_salary,
           pb.min_pay,
           pb.midpoint_pay,
           pb.max_pay,
           CASE WHEN pb.midpoint_pay > 0 THEN round(((cr.current_salary - pb.midpoint_pay) / pb.midpoint_pay) * 100, 4) ELSE 0 END,
           CASE
               WHEN cr.current_salary < pb.min_pay THEN 'Current salary is below band minimum.'
               WHEN cr.current_salary > pb.max_pay THEN 'Current salary is above band maximum.'
               WHEN pb.midpoint_pay > 0 AND cr.current_salary / pb.midpoint_pay < 0.80 THEN 'Compa-ratio is materially below midpoint.'
               WHEN pb.midpoint_pay > 0 AND cr.current_salary / pb.midpoint_pay > 1.20 THEN 'Compa-ratio is materially above midpoint.'
               ELSE 'Current salary is inside the band but should be reviewed for equity.'
           END,
           CASE
               WHEN cr.current_salary < pb.min_pay THEN 'Review correction adjustment to bring pay within band.'
               WHEN cr.current_salary > pb.max_pay THEN 'Review role leveling, promotion history, or red-circle handling.'
               ELSE 'Review peer equity and performance context before approval.'
           END,
           $2,
           $2
    FROM hrms.compensation_recommendations cr
    JOIN hrms.compensation_pay_bands pb ON pb.tenant_id = cr.tenant_id AND pb.id = cr.pay_band_id
    WHERE cr.tenant_id = $1
      AND cr.cycle_id = $3
      AND cr.inactive = FALSE
      AND pb.inactive = FALSE
      AND (
          cr.current_salary < pb.min_pay
          OR cr.current_salary > pb.max_pay
          OR (pb.midpoint_pay > 0 AND (cr.current_salary / pb.midpoint_pay < 0.80 OR cr.current_salary / pb.midpoint_pay > 1.20))
      )
    RETURNING id, tenant_id, cycle_id, worker_profile_id, pay_band_id, check_type, severity, current_salary, band_min, band_midpoint, band_max, variance_percent, finding, recommendation, status, inactive, created_at, created_by, updated_at, updated_by
)
SELECT id, tenant_id, cycle_id, worker_profile_id, pay_band_id, check_type, severity, current_salary, band_min, band_midpoint, band_max, variance_percent, finding, recommendation, status, inactive, created_at, created_by, updated_at, updated_by FROM inserted
ORDER BY severity DESC, created_at DESC
`

type GenerateCompensationEquityChecksParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	CreatedBy pgtype.UUID `db:"created_by" json:"created_by"`
	CycleID   uuid.UUID   `db:"cycle_id" json:"cycle_id"`
}

type GenerateCompensationEquityChecksRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	TenantID        uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CycleID         uuid.UUID          `db:"cycle_id" json:"cycle_id"`
	WorkerProfileID uuid.UUID          `db:"worker_profile_id" json:"worker_profile_id"`
	PayBandID       pgtype.UUID        `db:"pay_band_id" json:"pay_band_id"`
	CheckType       string             `db:"check_type" json:"check_type"`
	Severity        string             `db:"severity" json:"severity"`
	CurrentSalary   pgtype.Numeric     `db:"current_salary" json:"current_salary"`
	BandMin         pgtype.Numeric     `db:"band_min" json:"band_min"`
	BandMidpoint    pgtype.Numeric     `db:"band_midpoint" json:"band_midpoint"`
	BandMax         pgtype.Numeric     `db:"band_max" json:"band_max"`
	VariancePercent pgtype.Numeric     `db:"variance_percent" json:"variance_percent"`
	Finding         string             `db:"finding" json:"finding"`
	Recommendation  pgtype.Text        `db:"recommendation" json:"recommendation"`
	Status          string             `db:"status" json:"status"`
	Inactive        bool               `db:"inactive" json:"inactive"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy       pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy       pgtype.UUID        `db:"updated_by" json:"updated_by"`
}

func (q *Queries) GenerateCompensationEquityChecks(ctx context.Context, arg GenerateCompensationEquityChecksParams) ([]GenerateCompensationEquityChecksRow, error) {
	rows, err := q.db.Query(ctx, generateCompensationEquityChecks, arg.TenantID, arg.CreatedBy, arg.CycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerateCompensationEquityChecksRow
	for rows.Next() {
		var i GenerateCompensationEquityChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CycleID,
			&i.WorkerProfileID,
			&i.PayBandID,
			&i.CheckType,
			&i.Severity,
			&i.CurrentSalary,
			&i.BandMin,
			&i.BandMidpoint,
			&i.BandMax,
			&i.VariancePercent,
			&i.Finding,
			&i.Recommendation,
			&i.Status,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompensationCycle = `-- name: GetCompensationCycle :one
SELECT id, tenant_id, code, name, fiscal_year_id, status, cycle_type, starts_on, ends_on, effective_date, currency_code, budget_amount, planning_guidance, approval_policy, finalized_at, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.compensation_cycles
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
`

type GetCompensationCycleParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetCompensationCycle(ctx context.Context, arg GetCompensationCycleParams) (HrmsCompensationCycle, error) {
	row := q.db.QueryRow(ctx, getCompensationCycle, arg.TenantID, arg.ID)
	var i HrmsCompensationCycle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.FiscalYearID,
		&i.Status,
		&i.CycleType,
		&i.StartsOn,
		&i.EndsOn,
		&i.EffectiveDate,
		&i.CurrencyCode,
		&i.BudgetAmount,
		&i.PlanningGuidance,
		&i.ApprovalPolicy,
		&i.FinalizedAt,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCompensationPayBand = `-- name: GetCompensationPayBand :one
SELECT id, tenant_id, code, name, job_family, level_code, location_label, currency_code, min_pay, midpoint_pay, max_pay, effective_from, effective_to, is_active, notes, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.compensation_pay_bands
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
`

type GetCompensationPayBandParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetCompensationPayBand(ctx context.Context, arg GetCompensationPayBandParams) (HrmsCompensationPayBand, error) {
	row := q.db.QueryRow(ctx, getCompensationPayBand, arg.TenantID, arg.ID)
	var i HrmsCompensationPayBand
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.JobFamily,
		&i.LevelCode,
		&i.LocationLabel,
		&i.CurrencyCode,
		&i.MinPay,
		&i.MidpointPay,
		&i.MaxPay,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.Notes,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCompensationRecommendation = `-- name: GetCompensationRecommendation :one
SELECT cr.id, cr.tenant_id, cr.cycle_id, cr.worker_profile_id, cr.pay_band_id, cr.budget_pool_id, cr.current_salary, cr.current_compa_ratio, cr.recommended_salary, cr.recommended_increment_amount, cr.recommended_increment_percent, cr.promotion_recommended, cr.recommended_designation_id, cr.reason, cr.performance_rating, cr.equity_flag, cr.equity_notes, cr.status, cr.effective_date, cr.payroll_handoff_at, cr.metadata, cr.inactive, cr.created_at, cr.created_by, cr.updated_at, cr.updated_by, wp.display_name AS worker_display_name, wp.worker_code, pb.code AS pay_band_code, pb.name AS pay_band_name, bp.name AS budget_pool_name
FROM hrms.compensation_recommendations cr
JOIN hrms.worker_profiles wp ON wp.tenant_id = cr.tenant_id AND wp.id = cr.worker_profile_id
LEFT JOIN hrms.compensation_pay_bands pb ON pb.tenant_id = cr.tenant_id AND pb.id = cr.pay_band_id
LEFT JOIN hrms.compensation_budget_pools bp ON bp.tenant_id = cr.tenant_id AND bp.id = cr.budget_pool_id
WHERE cr.tenant_id = $1 AND cr.id = $2 AND cr.inactive = FALSE
`

type GetCompensationRecommendationParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

type GetCompensationRecommendationRow struct {
	ID                          uuid.UUID          `db:"id" json:"id"`
	TenantID                    uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CycleID                     uuid.UUID          `db:"cycle_id" json:"cycle_id"`
	WorkerProfileID             uuid.UUID          `db:"worker_profile_id" json:"worker_profile_id"`
	PayBandID                   pgtype.UUID        `db:"pay_band_id" json:"pay_band_id"`
	BudgetPoolID                pgtype.UUID        `db:"budget_pool_id" json:"budget_pool_id"`
	CurrentSalary               pgtype.Numeric     `db:"current_salary" json:"current_salary"`
	CurrentCompaRatio           pgtype.Numeric     `db:"current_compa_ratio" json:"current_compa_ratio"`
	RecommendedSalary           pgtype.Numeric     `db:"recommended_salary" json:"recommended_salary"`
	RecommendedIncrementAmount  pgtype.Numeric     `db:"recommended_increment_amount" json:"recommended_increment_amount"`
	RecommendedIncrementPercent pgtype.Numeric     `db:"recommended_increment_percent" json:"recommended_increment_percent"`
	PromotionRecommended        bool               `db:"promotion_recommended" json:"promotion_recommended"`
	RecommendedDesignationID    pgtype.UUID        `db:"recommended_designation_id" json:"recommended_designation_id"`
	Reason                      pgtype.Text        `db:"reason" json:"reason"`
	PerformanceRating           pgtype.Text        `db:"performance_rating" json:"performance_rating"`
	EquityFlag                  bool               `db:"equity_flag" json:"equity_flag"`
	EquityNotes                 pgtype.Text        `db:"equity_notes" json:"equity_notes"`
	Status                      string             `db:"status" json:"status"`
	EffectiveDate               pgtype.Date        `db:"effective_date" json:"effective_date"`
	PayrollHandoffAt            pgtype.Timestamptz `db:"payroll_handoff_at" json:"payroll_handoff_at"`
	Metadata                    []byte             `db:"metadata" json:"metadata"`
	Inactive                    bool               `db:"inactive" json:"inactive"`
	CreatedAt                   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy                   pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy                   pgtype.UUID        `db:"updated_by" json:"updated_by"`
	WorkerDisplayName           string             `db:"worker_display_name" json:"worker_display_name"`
	WorkerCode                  pgtype.Text        `db:"worker_code" json:"worker_code"`
	PayBandCode                 pgtype.Text        `db:"pay_band_code" json:"pay_band_code"`
	PayBandName                 pgtype.Text        `db:"pay_band_name" json:"pay_band_name"`
	BudgetPoolName              pgtype.Text        `db:"budget_pool_name" json:"budget_pool_name"`
}

func (q *Queries) GetCompensationRecommendation(ctx context.Context, arg GetCompensationRecommendationParams) (GetCompensationRecommendationRow, error) {
	row := q.db.QueryRow(ctx, getCompensationRecommendation, arg.TenantID, arg.ID)
	var i GetCompensationRecommendationRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CycleID,
		&i.WorkerProfileID,
		&i.PayBandID,
		&i.BudgetPoolID,
		&i.CurrentSalary,
		&i.CurrentCompaRatio,
		&i.RecommendedSalary,
		&i.RecommendedIncrementAmount,
		&i.RecommendedIncrementPercent,
		&i.PromotionRecommended,
		&i.RecommendedDesignationID,
		&i.Reason,
		&i.PerformanceRating,
		&i.EquityFlag,
		&i.EquityNotes,
		&i.Status,
		&i.EffectiveDate,
		&i.PayrollHandoffAt,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.WorkerDisplayName,
		&i.WorkerCode,
		&i.PayBandCode,
		&i.PayBandName,
		&i.BudgetPoolName,
	)
	return i, err
}

const getCompensationSummary = `-- name: GetCompensationSummary :many
SELECT 'cycles'::text AS metric, COUNT(*)::bigint AS metric_count, COALESCE(SUM(budget_amount), 0)::numeric AS metric_amount
FROM hrms.compensation_cycles cc
WHERE cc.tenant_id = $1 AND cc.inactive = FALSE
UNION ALL
SELECT 'open_cycles', COUNT(*)::bigint, COALESCE(SUM(budget_amount), 0)::numeric
FROM hrms.compensation_cycles cc
WHERE cc.tenant_id = $1 AND cc.inactive = FALSE AND cc.status IN ('draft','open','submitted')
UNION ALL
SELECT 'recommendations', COUNT(*)::bigint, COALESCE(SUM(recommended_increment_amount), 0)::numeric
FROM hrms.compensation_recommendations cr
WHERE cr.tenant_id = $1 AND cr.inactive = FALSE
UNION ALL
SELECT 'approved_recommendations', COUNT(*)::bigint, COALESCE(SUM(recommended_increment_amount), 0)::numeric
FROM hrms.compensation_recommendations cr
WHERE cr.tenant_id = $1 AND cr.inactive = FALSE AND cr.status IN ('approved','finalized','handed_to_payroll')
UNION ALL
SELECT 'equity_flags', COUNT(*)::bigint, 0::numeric
FROM hrms.compensation_equity_checks ec
WHERE ec.tenant_id = $1 AND ec.inactive = FALSE AND ec.status = 'open'
`

type GetCompensationSummaryRow struct {
	Metric       string         `db:"metric" json:"metric"`
	MetricCount  int64          `db:"metric_count" json:"metric_count"`
	MetricAmount pgtype.Numeric `db:"metric_amount" json:"metric_amount"`
}

func (q *Queries) GetCompensationSummary(ctx context.Context, tenantID uuid.UUID) ([]GetCompensationSummaryRow, error) {
	rows, err := q.db.Query(ctx, getCompensationSummary, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompensationSummaryRow
	for rows.Next() {
		var i GetCompensationSummaryRow
		if err := rows.Scan(&i.Metric, &i.MetricCount, &i.MetricAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompensationBudgetPools = `-- name: ListCompensationBudgetPools :many
SELECT bp.id, bp.tenant_id, bp.cycle_id, bp.name, bp.pool_type, bp.owner_user_id, bp.department_id, bp.branch_id, bp.budget_amount, bp.allocated_amount, bp.notes, bp.inactive, bp.created_at, bp.created_by, bp.updated_at, bp.updated_by,
       COALESCE(SUM(cr.recommended_increment_amount) FILTER (WHERE cr.inactive = FALSE AND cr.status IN ('submitted','approved','finalized','handed_to_payroll')), 0)::numeric AS committed_amount,
       COALESCE(COUNT(cr.id) FILTER (WHERE cr.inactive = FALSE), 0)::bigint AS recommendation_count
FROM hrms.compensation_budget_pools bp
LEFT JOIN hrms.compensation_recommendations cr ON cr.tenant_id = bp.tenant_id AND cr.budget_pool_id = bp.id
WHERE bp.tenant_id = $1 AND bp.cycle_id = $2 AND bp.inactive = FALSE
GROUP BY bp.id
ORDER BY bp.pool_type ASC, bp.name ASC
`

type ListCompensationBudgetPoolsParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	CycleID  uuid.UUID `db:"cycle_id" json:"cycle_id"`
}

type ListCompensationBudgetPoolsRow struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	TenantID            uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CycleID             uuid.UUID          `db:"cycle_id" json:"cycle_id"`
	Name                string             `db:"name" json:"name"`
	PoolType            string             `db:"pool_type" json:"pool_type"`
	OwnerUserID         pgtype.UUID        `db:"owner_user_id" json:"owner_user_id"`
	DepartmentID        pgtype.UUID        `db:"department_id" json:"department_id"`
	BranchID            pgtype.UUID        `db:"branch_id" json:"branch_id"`
	BudgetAmount        pgtype.Numeric     `db:"budget_amount" json:"budget_amount"`
	AllocatedAmount     pgtype.Numeric     `db:"allocated_amount" json:"allocated_amount"`
	Notes               pgtype.Text        `db:"notes" json:"notes"`
	Inactive            bool               `db:"inactive" json:"inactive"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy           pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy           pgtype.UUID        `db:"updated_by" json:"updated_by"`
	CommittedAmount     pgtype.Numeric     `db:"committed_amount" json:"committed_amount"`
	RecommendationCount int64              `db:"recommendation_count" json:"recommendation_count"`
}

func (q *Queries) ListCompensationBudgetPools(ctx context.Context, arg ListCompensationBudgetPoolsParams) ([]ListCompensationBudgetPoolsRow, error) {
	rows, err := q.db.Query(ctx, listCompensationBudgetPools, arg.TenantID, arg.CycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompensationBudgetPoolsRow
	for rows.Next() {
		var i ListCompensationBudgetPoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CycleID,
			&i.Name,
			&i.PoolType,
			&i.OwnerUserID,
			&i.DepartmentID,
			&i.BranchID,
			&i.BudgetAmount,
			&i.AllocatedAmount,
			&i.Notes,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.CommittedAmount,
			&i.RecommendationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompensationCycles = `-- name: ListCompensationCycles :many
SELECT id, tenant_id, code, name, fiscal_year_id, status, cycle_type, starts_on, ends_on, effective_date, currency_code, budget_amount, planning_guidance, approval_policy, finalized_at, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.compensation_cycles
WHERE tenant_id = $1
  AND inactive = FALSE
  AND ($4::text IS NULL OR status = $4::text)
  AND ($5::text IS NULL OR code ILIKE '%' || $5::text || '%' OR name ILIKE '%' || $5::text || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCompensationCyclesParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
	Status   pgtype.Text `db:"status" json:"status"`
	Search   pgtype.Text `db:"search" json:"search"`
}

func (q *Queries) ListCompensationCycles(ctx context.Context, arg ListCompensationCyclesParams) ([]HrmsCompensationCycle, error) {
	rows, err := q.db.Query(ctx, listCompensationCycles,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsCompensationCycle
	for rows.Next() {
		var i HrmsCompensationCycle
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.FiscalYearID,
			&i.Status,
			&i.CycleType,
			&i.StartsOn,
			&i.EndsOn,
			&i.EffectiveDate,
			&i.CurrencyCode,
			&i.BudgetAmount,
			&i.PlanningGuidance,
			&i.ApprovalPolicy,
			&i.FinalizedAt,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompensationEquityChecks = `-- name: ListCompensationEquityChecks :many
SELECT ec.id, ec.tenant_id, ec.cycle_id, ec.worker_profile_id, ec.pay_band_id, ec.check_type, ec.severity, ec.current_salary, ec.band_min, ec.band_midpoint, ec.band_max, ec.variance_percent, ec.finding, ec.recommendation, ec.status, ec.inactive, ec.created_at, ec.created_by, ec.updated_at, ec.updated_by, wp.display_name AS worker_display_name, wp.worker_code, pb.code AS pay_band_code, pb.name AS pay_band_name
FROM hrms.compensation_equity_checks ec
JOIN hrms.worker_profiles wp ON wp.tenant_id = ec.tenant_id AND wp.id = ec.worker_profile_id
LEFT JOIN hrms.compensation_pay_bands pb ON pb.tenant_id = ec.tenant_id AND pb.id = ec.pay_band_id
WHERE ec.tenant_id = $1
  AND ec.inactive = FALSE
  AND ($4::uuid IS NULL OR ec.cycle_id = $4::uuid)
  AND ($5::text IS NULL OR ec.status = $5::text)
ORDER BY ec.created_at DESC
LIMIT $2 OFFSET $3
`

type ListCompensationEquityChecksParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
	CycleID  pgtype.UUID `db:"cycle_id" json:"cycle_id"`
	Status   pgtype.Text `db:"status" json:"status"`
}

type ListCompensationEquityChecksRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	TenantID          uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CycleID           uuid.UUID          `db:"cycle_id" json:"cycle_id"`
	WorkerProfileID   uuid.UUID          `db:"worker_profile_id" json:"worker_profile_id"`
	PayBandID         pgtype.UUID        `db:"pay_band_id" json:"pay_band_id"`
	CheckType         string             `db:"check_type" json:"check_type"`
	Severity          string             `db:"severity" json:"severity"`
	CurrentSalary     pgtype.Numeric     `db:"current_salary" json:"current_salary"`
	BandMin           pgtype.Numeric     `db:"band_min" json:"band_min"`
	BandMidpoint      pgtype.Numeric     `db:"band_midpoint" json:"band_midpoint"`
	BandMax           pgtype.Numeric     `db:"band_max" json:"band_max"`
	VariancePercent   pgtype.Numeric     `db:"variance_percent" json:"variance_percent"`
	Finding           string             `db:"finding" json:"finding"`
	Recommendation    pgtype.Text        `db:"recommendation" json:"recommendation"`
	Status            string             `db:"status" json:"status"`
	Inactive          bool               `db:"inactive" json:"inactive"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy         pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy         pgtype.UUID        `db:"updated_by" json:"updated_by"`
	WorkerDisplayName string             `db:"worker_display_name" json:"worker_display_name"`
	WorkerCode        pgtype.Text        `db:"worker_code" json:"worker_code"`
	PayBandCode       pgtype.Text        `db:"pay_band_code" json:"pay_band_code"`
	PayBandName       pgtype.Text        `db:"pay_band_name" json:"pay_band_name"`
}

func (q *Queries) ListCompensationEquityChecks(ctx context.Context, arg ListCompensationEquityChecksParams) ([]ListCompensationEquityChecksRow, error) {
	rows, err := q.db.Query(ctx, listCompensationEquityChecks,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.CycleID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompensationEquityChecksRow
	for rows.Next() {
		var i ListCompensationEquityChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CycleID,
			&i.WorkerProfileID,
			&i.PayBandID,
			&i.CheckType,
			&i.Severity,
			&i.CurrentSalary,
			&i.BandMin,
			&i.BandMidpoint,
			&i.BandMax,
			&i.VariancePercent,
			&i.Finding,
			&i.Recommendation,
			&i.Status,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.WorkerDisplayName,
			&i.WorkerCode,
			&i.PayBandCode,
			&i.PayBandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompensationEvents = `-- name: ListCompensationEvents :many
SELECT id, tenant_id, cycle_id, source_type, source_id, action, from_status, to_status, remarks, metadata, created_at, created_by FROM hrms.compensation_events
WHERE tenant_id = $1
  AND ($4::uuid IS NULL OR cycle_id = $4::uuid)
  AND ($5::text IS NULL OR source_type = $5::text)
  AND ($6::uuid IS NULL OR source_id = $6::uuid)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCompensationEventsParams struct {
	TenantID   uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
	CycleID    pgtype.UUID `db:"cycle_id" json:"cycle_id"`
	SourceType pgtype.Text `db:"source_type" json:"source_type"`
	SourceID   pgtype.UUID `db:"source_id" json:"source_id"`
}

func (q *Queries) ListCompensationEvents(ctx context.Context, arg ListCompensationEventsParams) ([]HrmsCompensationEvent, error) {
	rows, err := q.db.Query(ctx, listCompensationEvents,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.CycleID,
		arg.SourceType,
		arg.SourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsCompensationEvent
	for rows.Next() {
		var i HrmsCompensationEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CycleID,
			&i.SourceType,
			&i.SourceID,
			&i.Action,
			&i.FromStatus,
			&i.ToStatus,
			&i.Remarks,
			&i.Metadata,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompensationPayBands = `-- name: ListCompensationPayBands :many
SELECT id, tenant_id, code, name, job_family, level_code, location_label, currency_code, min_pay, midpoint_pay, max_pay, effective_from, effective_to, is_active, notes, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.compensation_pay_bands
WHERE tenant_id = $1
  AND inactive = FALSE
  AND ($4::boolean IS NULL OR is_active = $4::boolean)
  AND ($5::text IS NULL OR currency_code = $5::text)
  AND ($6::text IS NULL OR code ILIKE '%' || $6::text || '%' OR name ILIKE '%' || $6::text || '%' OR COALESCE(job_family, '') ILIKE '%' || $6::text || '%')
ORDER BY is_active DESC, level_code NULLS LAST, name ASC
LIMIT $2 OFFSET $3
`

type ListCompensationPayBandsParams struct {
	TenantID     uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit        int32       `db:"limit" json:"limit"`
	Offset       int32       `db:"offset" json:"offset"`
	IsActive     pgtype.Bool `db:"is_active" json:"is_active"`
	CurrencyCode pgtype.Text `db:"currency_code" json:"currency_code"`
	Search       pgtype.Text `db:"search" json:"search"`
}

func (q *Queries) ListCompensationPayBands(ctx context.Context, arg ListCompensationPayBandsParams) ([]HrmsCompensationPayBand, error) {
	rows, err := q.db.Query(ctx, listCompensationPayBands,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.IsActive,
		arg.CurrencyCode,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsCompensationPayBand
	for rows.Next() {
		var i HrmsCompensationPayBand
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.JobFamily,
			&i.LevelCode,
			&i.LocationLabel,
			&i.CurrencyCode,
			&i.MinPay,
			&i.MidpointPay,
			&i.MaxPay,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.IsActive,
			&i.Notes,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompensationRecommendations = `-- name: ListCompensationRecommendations :many
SELECT cr.id, cr.tenant_id, cr.cycle_id, cr.worker_profile_id, cr.pay_band_id, cr.budget_pool_id, cr.current_salary, cr.current_compa_ratio, cr.recommended_salary, cr.recommended_increment_amount, cr.recommended_increment_percent, cr.promotion_recommended, cr.recommended_designation_id, cr.reason, cr.performance_rating, cr.equity_flag, cr.equity_notes, cr.status, cr.effective_date, cr.payroll_handoff_at, cr.metadata, cr.inactive, cr.created_at, cr.created_by, cr.updated_at, cr.updated_by, wp.display_name AS worker_display_name, wp.worker_code, pb.code AS pay_band_code, pb.name AS pay_band_name, bp.name AS budget_pool_name
FROM hrms.compensation_recommendations cr
JOIN hrms.worker_profiles wp ON wp.tenant_id = cr.tenant_id AND wp.id = cr.worker_profile_id
LEFT JOIN hrms.compensation_pay_bands pb ON pb.tenant_id = cr.tenant_id AND pb.id = cr.pay_band_id
LEFT JOIN hrms.compensation_budget_pools bp ON bp.tenant_id = cr.tenant_id AND bp.id = cr.budget_pool_id
WHERE cr.tenant_id = $1
  AND cr.inactive = FALSE
  AND ($4::uuid IS NULL OR cr.cycle_id = $4::uuid)
  AND ($5::text IS NULL OR cr.status = $5::text)
  AND ($6::text IS NULL OR wp.display_name ILIKE '%' || $6::text || '%' OR COALESCE(wp.worker_code, '') ILIKE '%' || $6::text || '%')
ORDER BY cr.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListCompensationRecommendationsParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
	CycleID  pgtype.UUID `db:"cycle_id" json:"cycle_id"`
	Status   pgtype.Text `db:"status" json:"status"`
	Search   pgtype.Text `db:"search" json:"search"`
}

type ListCompensationRecommendationsRow struct {
	ID                          uuid.UUID          `db:"id" json:"id"`
	TenantID                    uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	CycleID                     uuid.UUID          `db:"cycle_id" json:"cycle_id"`
	WorkerProfileID             uuid.UUID          `db:"worker_profile_id" json:"worker_profile_id"`
	PayBandID                   pgtype.UUID        `db:"pay_band_id" json:"pay_band_id"`
	BudgetPoolID                pgtype.UUID        `db:"budget_pool_id" json:"budget_pool_id"`
	CurrentSalary               pgtype.Numeric     `db:"current_salary" json:"current_salary"`
	CurrentCompaRatio           pgtype.Numeric     `db:"current_compa_ratio" json:"current_compa_ratio"`
	RecommendedSalary           pgtype.Numeric     `db:"recommended_salary" json:"recommended_salary"`
	RecommendedIncrementAmount  pgtype.Numeric     `db:"recommended_increment_amount" json:"recommended_increment_amount"`
	RecommendedIncrementPercent pgtype.Numeric     `db:"recommended_increment_percent" json:"recommended_increment_percent"`
	PromotionRecommended        bool               `db:"promotion_recommended" json:"promotion_recommended"`
	RecommendedDesignationID    pgtype.UUID        `db:"recommended_designation_id" json:"recommended_designation_id"`
	Reason                      pgtype.Text        `db:"reason" json:"reason"`
	PerformanceRating           pgtype.Text        `db:"performance_rating" json:"performance_rating"`
	EquityFlag                  bool               `db:"equity_flag" json:"equity_flag"`
	EquityNotes                 pgtype.Text        `db:"equity_notes" json:"equity_notes"`
	Status                      string             `db:"status" json:"status"`
	EffectiveDate               pgtype.Date        `db:"effective_date" json:"effective_date"`
	PayrollHandoffAt            pgtype.Timestamptz `db:"payroll_handoff_at" json:"payroll_handoff_at"`
	Metadata                    []byte             `db:"metadata" json:"metadata"`
	Inactive                    bool               `db:"inactive" json:"inactive"`
	CreatedAt                   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy                   pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy                   pgtype.UUID        `db:"updated_by" json:"updated_by"`
	WorkerDisplayName           string             `db:"worker_display_name" json:"worker_display_name"`
	WorkerCode                  pgtype.Text        `db:"worker_code" json:"worker_code"`
	PayBandCode                 pgtype.Text        `db:"pay_band_code" json:"pay_band_code"`
	PayBandName                 pgtype.Text        `db:"pay_band_name" json:"pay_band_name"`
	BudgetPoolName              pgtype.Text        `db:"budget_pool_name" json:"budget_pool_name"`
}

func (q *Queries) ListCompensationRecommendations(ctx context.Context, arg ListCompensationRecommendationsParams) ([]ListCompensationRecommendationsRow, error) {
	rows, err := q.db.Query(ctx, listCompensationRecommendations,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.CycleID,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompensationRecommendationsRow
	for rows.Next() {
		var i ListCompensationRecommendationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CycleID,
			&i.WorkerProfileID,
			&i.PayBandID,
			&i.BudgetPoolID,
			&i.CurrentSalary,
			&i.CurrentCompaRatio,
			&i.RecommendedSalary,
			&i.RecommendedIncrementAmount,
			&i.RecommendedIncrementPercent,
			&i.PromotionRecommended,
			&i.RecommendedDesignationID,
			&i.Reason,
			&i.PerformanceRating,
			&i.EquityFlag,
			&i.EquityNotes,
			&i.Status,
			&i.EffectiveDate,
			&i.PayrollHandoffAt,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.WorkerDisplayName,
			&i.WorkerCode,
			&i.PayBandCode,
			&i.PayBandName,
			&i.BudgetPoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCompensationBudgetPool = `-- name: SoftDeleteCompensationBudgetPool :exec
UPDATE hrms.compensation_budget_pools
SET inactive = TRUE, updated_by = $4, updated_at = now()
WHERE tenant_id = $1 AND cycle_id = $2 AND id = $3
`

type SoftDeleteCompensationBudgetPoolParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	CycleID   uuid.UUID   `db:"cycle_id" json:"cycle_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteCompensationBudgetPool(ctx context.Context, arg SoftDeleteCompensationBudgetPoolParams) error {
	_, err := q.db.Exec(ctx, softDeleteCompensationBudgetPool,
		arg.TenantID,
		arg.CycleID,
		arg.ID,
		arg.UpdatedBy,
	)
	return err
}

const softDeleteCompensationPayBand = `-- name: SoftDeleteCompensationPayBand :exec
UPDATE hrms.compensation_pay_bands
SET inactive = TRUE, is_active = FALSE, updated_by = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteCompensationPayBandParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteCompensationPayBand(ctx context.Context, arg SoftDeleteCompensationPayBandParams) error {
	_, err := q.db.Exec(ctx, softDeleteCompensationPayBand, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteCompensationRecommendation = `-- name: SoftDeleteCompensationRecommendation :exec
UPDATE hrms.compensation_recommendations
SET inactive = TRUE, updated_by = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteCompensationRecommendationParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteCompensationRecommendation(ctx context.Context, arg SoftDeleteCompensationRecommendationParams) error {
	_, err := q.db.Exec(ctx, softDeleteCompensationRecommendation, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const updateCompensationBudgetPool = `-- name: UpdateCompensationBudgetPool :one
UPDATE hrms.compensation_budget_pools
SET name = $4,
    pool_type = $5,
    owner_user_id = $6,
    department_id = $7,
    branch_id = $8,
    budget_amount = $9,
    allocated_amount = $10,
    notes = $11,
    updated_by = $12,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND cycle_id = $3 AND inactive = FALSE
RETURNING id, tenant_id, cycle_id, name, pool_type, owner_user_id, department_id, branch_id, budget_amount, allocated_amount, notes, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateCompensationBudgetPoolParams struct {
	TenantID        uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	ID              uuid.UUID      `db:"id" json:"id"`
	CycleID         uuid.UUID      `db:"cycle_id" json:"cycle_id"`
	Name            string         `db:"name" json:"name"`
	PoolType        string         `db:"pool_type" json:"pool_type"`
	OwnerUserID     pgtype.UUID    `db:"owner_user_id" json:"owner_user_id"`
	DepartmentID    pgtype.UUID    `db:"department_id" json:"department_id"`
	BranchID        pgtype.UUID    `db:"branch_id" json:"branch_id"`
	BudgetAmount    pgtype.Numeric `db:"budget_amount" json:"budget_amount"`
	AllocatedAmount pgtype.Numeric `db:"allocated_amount" json:"allocated_amount"`
	Notes           pgtype.Text    `db:"notes" json:"notes"`
	UpdatedBy       pgtype.UUID    `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateCompensationBudgetPool(ctx context.Context, arg UpdateCompensationBudgetPoolParams) (HrmsCompensationBudgetPool, error) {
	row := q.db.QueryRow(ctx, updateCompensationBudgetPool,
		arg.TenantID,
		arg.ID,
		arg.CycleID,
		arg.Name,
		arg.PoolType,
		arg.OwnerUserID,
		arg.DepartmentID,
		arg.BranchID,
		arg.BudgetAmount,
		arg.AllocatedAmount,
		arg.Notes,
		arg.UpdatedBy,
	)
	var i HrmsCompensationBudgetPool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CycleID,
		&i.Name,
		&i.PoolType,
		&i.OwnerUserID,
		&i.DepartmentID,
		&i.BranchID,
		&i.BudgetAmount,
		&i.AllocatedAmount,
		&i.Notes,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateCompensationCycle = `-- name: UpdateCompensationCycle :one
UPDATE hrms.compensation_cycles
SET code = $3,
    name = $4,
    fiscal_year_id = $5,
    cycle_type = $6,
    starts_on = $7,
    ends_on = $8,
    effective_date = $9,
    currency_code = $10,
    budget_amount = $11,
    planning_guidance = $12,
    approval_policy = $13,
    metadata = $14,
    updated_by = $15,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
RETURNING id, tenant_id, code, name, fiscal_year_id, status, cycle_type, starts_on, ends_on, effective_date, currency_code, budget_amount, planning_guidance, approval_policy, finalized_at, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateCompensationCycleParams struct {
	TenantID         uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	ID               uuid.UUID      `db:"id" json:"id"`
	Code             string         `db:"code" json:"code"`
	Name             string         `db:"name" json:"name"`
	FiscalYearID     pgtype.UUID    `db:"fiscal_year_id" json:"fiscal_year_id"`
	CycleType        string         `db:"cycle_type" json:"cycle_type"`
	StartsOn         pgtype.Date    `db:"starts_on" json:"starts_on"`
	EndsOn           pgtype.Date    `db:"ends_on" json:"ends_on"`
	EffectiveDate    pgtype.Date    `db:"effective_date" json:"effective_date"`
	CurrencyCode     string         `db:"currency_code" json:"currency_code"`
	BudgetAmount     pgtype.Numeric `db:"budget_amount" json:"budget_amount"`
	PlanningGuidance pgtype.Text    `db:"planning_guidance" json:"planning_guidance"`
	ApprovalPolicy   pgtype.Text    `db:"approval_policy" json:"approval_policy"`
	Metadata         []byte         `db:"metadata" json:"metadata"`
	UpdatedBy        pgtype.UUID    `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateCompensationCycle(ctx context.Context, arg UpdateCompensationCycleParams) (HrmsCompensationCycle, error) {
	row := q.db.QueryRow(ctx, updateCompensationCycle,
		arg.TenantID,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.FiscalYearID,
		arg.CycleType,
		arg.StartsOn,
		arg.EndsOn,
		arg.EffectiveDate,
		arg.CurrencyCode,
		arg.BudgetAmount,
		arg.PlanningGuidance,
		arg.ApprovalPolicy,
		arg.Metadata,
		arg.UpdatedBy,
	)
	var i HrmsCompensationCycle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.FiscalYearID,
		&i.Status,
		&i.CycleType,
		&i.StartsOn,
		&i.EndsOn,
		&i.EffectiveDate,
		&i.CurrencyCode,
		&i.BudgetAmount,
		&i.PlanningGuidance,
		&i.ApprovalPolicy,
		&i.FinalizedAt,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateCompensationCycleStatus = `-- name: UpdateCompensationCycleStatus :one
UPDATE hrms.compensation_cycles
SET status = $3,
    finalized_at = CASE WHEN $3 = 'finalized' THEN now() ELSE finalized_at END,
    updated_by = $4,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
RETURNING id, tenant_id, code, name, fiscal_year_id, status, cycle_type, starts_on, ends_on, effective_date, currency_code, budget_amount, planning_guidance, approval_policy, finalized_at, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateCompensationCycleStatusParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	Status    string      `db:"status" json:"status"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateCompensationCycleStatus(ctx context.Context, arg UpdateCompensationCycleStatusParams) (HrmsCompensationCycle, error) {
	row := q.db.QueryRow(ctx, updateCompensationCycleStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
	)
	var i HrmsCompensationCycle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.FiscalYearID,
		&i.Status,
		&i.CycleType,
		&i.StartsOn,
		&i.EndsOn,
		&i.EffectiveDate,
		&i.CurrencyCode,
		&i.BudgetAmount,
		&i.PlanningGuidance,
		&i.ApprovalPolicy,
		&i.FinalizedAt,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateCompensationEquityCheckStatus = `-- name: UpdateCompensationEquityCheckStatus :one
UPDATE hrms.compensation_equity_checks
SET status = $3,
    updated_by = $4,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
RETURNING id, tenant_id, cycle_id, worker_profile_id, pay_band_id, check_type, severity, current_salary, band_min, band_midpoint, band_max, variance_percent, finding, recommendation, status, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateCompensationEquityCheckStatusParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	Status    string      `db:"status" json:"status"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateCompensationEquityCheckStatus(ctx context.Context, arg UpdateCompensationEquityCheckStatusParams) (HrmsCompensationEquityCheck, error) {
	row := q.db.QueryRow(ctx, updateCompensationEquityCheckStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
	)
	var i HrmsCompensationEquityCheck
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CycleID,
		&i.WorkerProfileID,
		&i.PayBandID,
		&i.CheckType,
		&i.Severity,
		&i.CurrentSalary,
		&i.BandMin,
		&i.BandMidpoint,
		&i.BandMax,
		&i.VariancePercent,
		&i.Finding,
		&i.Recommendation,
		&i.Status,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateCompensationPayBand = `-- name: UpdateCompensationPayBand :one
UPDATE hrms.compensation_pay_bands
SET code = $3,
    name = $4,
    job_family = $5,
    level_code = $6,
    location_label = $7,
    currency_code = $8,
    min_pay = $9,
    midpoint_pay = $10,
    max_pay = $11,
    effective_from = $12,
    effective_to = $13,
    is_active = $14,
    notes = $15,
    metadata = $16,
    updated_by = $17,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
RETURNING id, tenant_id, code, name, job_family, level_code, location_label, currency_code, min_pay, midpoint_pay, max_pay, effective_from, effective_to, is_active, notes, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateCompensationPayBandParams struct {
	TenantID      uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	ID            uuid.UUID      `db:"id" json:"id"`
	Code          string         `db:"code" json:"code"`
	Name          string         `db:"name" json:"name"`
	JobFamily     pgtype.Text    `db:"job_family" json:"job_family"`
	LevelCode     pgtype.Text    `db:"level_code" json:"level_code"`
	LocationLabel pgtype.Text    `db:"location_label" json:"location_label"`
	CurrencyCode  string         `db:"currency_code" json:"currency_code"`
	MinPay        pgtype.Numeric `db:"min_pay" json:"min_pay"`
	MidpointPay   pgtype.Numeric `db:"midpoint_pay" json:"midpoint_pay"`
	MaxPay        pgtype.Numeric `db:"max_pay" json:"max_pay"`
	EffectiveFrom pgtype.Date    `db:"effective_from" json:"effective_from"`
	EffectiveTo   pgtype.Date    `db:"effective_to" json:"effective_to"`
	IsActive      bool           `db:"is_active" json:"is_active"`
	Notes         pgtype.Text    `db:"notes" json:"notes"`
	Metadata      []byte         `db:"metadata" json:"metadata"`
	UpdatedBy     pgtype.UUID    `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateCompensationPayBand(ctx context.Context, arg UpdateCompensationPayBandParams) (HrmsCompensationPayBand, error) {
	row := q.db.QueryRow(ctx, updateCompensationPayBand,
		arg.TenantID,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.JobFamily,
		arg.LevelCode,
		arg.LocationLabel,
		arg.CurrencyCode,
		arg.MinPay,
		arg.MidpointPay,
		arg.MaxPay,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.IsActive,
		arg.Notes,
		arg.Metadata,
		arg.UpdatedBy,
	)
	var i HrmsCompensationPayBand
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.JobFamily,
		&i.LevelCode,
		&i.LocationLabel,
		&i.CurrencyCode,
		&i.MinPay,
		&i.MidpointPay,
		&i.MaxPay,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.Notes,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateCompensationRecommendation = `-- name: UpdateCompensationRecommendation :one
UPDATE hrms.compensation_recommendations
SET pay_band_id = $4,
    budget_pool_id = $5,
    current_salary = $6,
    current_compa_ratio = $7,
    recommended_salary = $8,
    recommended_increment_amount = $9,
    recommended_increment_percent = $10,
    promotion_recommended = $11,
    recommended_designation_id = $12,
    reason = $13,
    performance_rating = $14,
    equity_flag = $15,
    equity_notes = $16,
    effective_date = $17,
    metadata = $18,
    updated_by = $19,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND cycle_id = $3 AND inactive = FALSE
RETURNING id, tenant_id, cycle_id, worker_profile_id, pay_band_id, budget_pool_id, current_salary, current_compa_ratio, recommended_salary, recommended_increment_amount, recommended_increment_percent, promotion_recommended, recommended_designation_id, reason, performance_rating, equity_flag, equity_notes, status, effective_date, payroll_handoff_at, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateCompensationRecommendationParams struct {
	TenantID                    uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	ID                          uuid.UUID      `db:"id" json:"id"`
	CycleID                     uuid.UUID      `db:"cycle_id" json:"cycle_id"`
	PayBandID                   pgtype.UUID    `db:"pay_band_id" json:"pay_band_id"`
	BudgetPoolID                pgtype.UUID    `db:"budget_pool_id" json:"budget_pool_id"`
	CurrentSalary               pgtype.Numeric `db:"current_salary" json:"current_salary"`
	CurrentCompaRatio           pgtype.Numeric `db:"current_compa_ratio" json:"current_compa_ratio"`
	RecommendedSalary           pgtype.Numeric `db:"recommended_salary" json:"recommended_salary"`
	RecommendedIncrementAmount  pgtype.Numeric `db:"recommended_increment_amount" json:"recommended_increment_amount"`
	RecommendedIncrementPercent pgtype.Numeric `db:"recommended_increment_percent" json:"recommended_increment_percent"`
	PromotionRecommended        bool           `db:"promotion_recommended" json:"promotion_recommended"`
	RecommendedDesignationID    pgtype.UUID    `db:"recommended_designation_id" json:"recommended_designation_id"`
	Reason                      pgtype.Text    `db:"reason" json:"reason"`
	PerformanceRating           pgtype.Text    `db:"performance_rating" json:"performance_rating"`
	EquityFlag                  bool           `db:"equity_flag" json:"equity_flag"`
	EquityNotes                 pgtype.Text    `db:"equity_notes" json:"equity_notes"`
	EffectiveDate               pgtype.Date    `db:"effective_date" json:"effective_date"`
	Metadata                    []byte         `db:"metadata" json:"metadata"`
	UpdatedBy                   pgtype.UUID    `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateCompensationRecommendation(ctx context.Context, arg UpdateCompensationRecommendationParams) (HrmsCompensationRecommendation, error) {
	row := q.db.QueryRow(ctx, updateCompensationRecommendation,
		arg.TenantID,
		arg.ID,
		arg.CycleID,
		arg.PayBandID,
		arg.BudgetPoolID,
		arg.CurrentSalary,
		arg.CurrentCompaRatio,
		arg.RecommendedSalary,
		arg.RecommendedIncrementAmount,
		arg.RecommendedIncrementPercent,
		arg.PromotionRecommended,
		arg.RecommendedDesignationID,
		arg.Reason,
		arg.PerformanceRating,
		arg.EquityFlag,
		arg.EquityNotes,
		arg.EffectiveDate,
		arg.Metadata,
		arg.UpdatedBy,
	)
	var i HrmsCompensationRecommendation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CycleID,
		&i.WorkerProfileID,
		&i.PayBandID,
		&i.BudgetPoolID,
		&i.CurrentSalary,
		&i.CurrentCompaRatio,
		&i.RecommendedSalary,
		&i.RecommendedIncrementAmount,
		&i.RecommendedIncrementPercent,
		&i.PromotionRecommended,
		&i.RecommendedDesignationID,
		&i.Reason,
		&i.PerformanceRating,
		&i.EquityFlag,
		&i.EquityNotes,
		&i.Status,
		&i.EffectiveDate,
		&i.PayrollHandoffAt,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateCompensationRecommendationStatus = `-- name: UpdateCompensationRecommendationStatus :one
UPDATE hrms.compensation_recommendations
SET status = $3,
    payroll_handoff_at = CASE WHEN $3 = 'handed_to_payroll' THEN now() ELSE payroll_handoff_at END,
    updated_by = $4,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
RETURNING id, tenant_id, cycle_id, worker_profile_id, pay_band_id, budget_pool_id, current_salary, current_compa_ratio, recommended_salary, recommended_increment_amount, recommended_increment_percent, promotion_recommended, recommended_designation_id, reason, performance_rating, equity_flag, equity_notes, status, effective_date, payroll_handoff_at, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateCompensationRecommendationStatusParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	Status    string      `db:"status" json:"status"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateCompensationRecommendationStatus(ctx context.Context, arg UpdateCompensationRecommendationStatusParams) (HrmsCompensationRecommendation, error) {
	row := q.db.QueryRow(ctx, updateCompensationRecommendationStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
	)
	var i HrmsCompensationRecommendation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CycleID,
		&i.WorkerProfileID,
		&i.PayBandID,
		&i.BudgetPoolID,
		&i.CurrentSalary,
		&i.CurrentCompaRatio,
		&i.RecommendedSalary,
		&i.RecommendedIncrementAmount,
		&i.RecommendedIncrementPercent,
		&i.PromotionRecommended,
		&i.RecommendedDesignationID,
		&i.Reason,
		&i.PerformanceRating,
		&i.EquityFlag,
		&i.EquityNotes,
		&i.Status,
		&i.EffectiveDate,
		&i.PayrollHandoffAt,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
