// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: designations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDesignation = `-- name: CreateDesignation :one
INSERT INTO hrms.designations (
    tenant_id,
    name,
    level_code,
    seniority_rank,
    description,
    attendance_required,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $7
)
RETURNING id, tenant_id, name, description, inactive, created_at, created_by, updated_at, updated_by, level_code, seniority_rank, attendance_required
`

type CreateDesignationParams struct {
	TenantID           uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Name               string      `db:"name" json:"name"`
	LevelCode          string      `db:"level_code" json:"level_code"`
	SeniorityRank      int32       `db:"seniority_rank" json:"seniority_rank"`
	Description        pgtype.Text `db:"description" json:"description"`
	AttendanceRequired bool        `db:"attendance_required" json:"attendance_required"`
	CreatedBy          pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateDesignation(ctx context.Context, arg CreateDesignationParams) (HrmsDesignation, error) {
	row := q.db.QueryRow(ctx, createDesignation,
		arg.TenantID,
		arg.Name,
		arg.LevelCode,
		arg.SeniorityRank,
		arg.Description,
		arg.AttendanceRequired,
		arg.CreatedBy,
	)
	var i HrmsDesignation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.LevelCode,
		&i.SeniorityRank,
		&i.AttendanceRequired,
	)
	return i, err
}

const getDesignation = `-- name: GetDesignation :one
SELECT id, tenant_id, name, description, inactive, created_at, created_by, updated_at, updated_by, level_code, seniority_rank, attendance_required FROM hrms.designations
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetDesignationParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetDesignation(ctx context.Context, arg GetDesignationParams) (HrmsDesignation, error) {
	row := q.db.QueryRow(ctx, getDesignation, arg.TenantID, arg.ID)
	var i HrmsDesignation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.LevelCode,
		&i.SeniorityRank,
		&i.AttendanceRequired,
	)
	return i, err
}

const listDesignations = `-- name: ListDesignations :many
SELECT id, tenant_id, name, description, inactive, created_at, created_by, updated_at, updated_by, level_code, seniority_rank, attendance_required FROM hrms.designations
WHERE tenant_id = $1 AND NOT inactive
ORDER BY seniority_rank DESC, name ASC
`

func (q *Queries) ListDesignations(ctx context.Context, tenantID uuid.UUID) ([]HrmsDesignation, error) {
	rows, err := q.db.Query(ctx, listDesignations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsDesignation
	for rows.Next() {
		var i HrmsDesignation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.LevelCode,
			&i.SeniorityRank,
			&i.AttendanceRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDesignation = `-- name: SoftDeleteDesignation :exec
UPDATE hrms.designations
SET inactive = TRUE,
    updated_by = $3
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type SoftDeleteDesignationParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteDesignation(ctx context.Context, arg SoftDeleteDesignationParams) error {
	_, err := q.db.Exec(ctx, softDeleteDesignation, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const updateDesignation = `-- name: UpdateDesignation :one
UPDATE hrms.designations
SET name = $3,
    level_code = $4,
    seniority_rank = $5,
    description = $6,
    attendance_required = $7,
    updated_by = $8
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, name, description, inactive, created_at, created_by, updated_at, updated_by, level_code, seniority_rank, attendance_required
`

type UpdateDesignationParams struct {
	TenantID           uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID                 uuid.UUID   `db:"id" json:"id"`
	Name               string      `db:"name" json:"name"`
	LevelCode          string      `db:"level_code" json:"level_code"`
	SeniorityRank      int32       `db:"seniority_rank" json:"seniority_rank"`
	Description        pgtype.Text `db:"description" json:"description"`
	AttendanceRequired bool        `db:"attendance_required" json:"attendance_required"`
	UpdatedBy          pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateDesignation(ctx context.Context, arg UpdateDesignationParams) (HrmsDesignation, error) {
	row := q.db.QueryRow(ctx, updateDesignation,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.LevelCode,
		arg.SeniorityRank,
		arg.Description,
		arg.AttendanceRequired,
		arg.UpdatedBy,
	)
	var i HrmsDesignation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.LevelCode,
		&i.SeniorityRank,
		&i.AttendanceRequired,
	)
	return i, err
}
