// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee_credentials.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployeeCredentialEvent = `-- name: CreateEmployeeCredentialEvent :one
INSERT INTO hrms.employee_credential_events (
    tenant_id, employee_id, user_id, event_type, delivery_channel, delivery_target, status, failure_reason, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, tenant_id, employee_id, user_id, event_type, delivery_channel, delivery_target, status, failure_reason, created_at, created_by
`

type CreateEmployeeCredentialEventParams struct {
	TenantID        uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	EmployeeID      uuid.UUID   `db:"employee_id" json:"employee_id"`
	UserID          uuid.UUID   `db:"user_id" json:"user_id"`
	EventType       string      `db:"event_type" json:"event_type"`
	DeliveryChannel string      `db:"delivery_channel" json:"delivery_channel"`
	DeliveryTarget  string      `db:"delivery_target" json:"delivery_target"`
	Status          string      `db:"status" json:"status"`
	FailureReason   pgtype.Text `db:"failure_reason" json:"failure_reason"`
	CreatedBy       pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateEmployeeCredentialEvent(ctx context.Context, arg CreateEmployeeCredentialEventParams) (HrmsEmployeeCredentialEvent, error) {
	row := q.db.QueryRow(ctx, createEmployeeCredentialEvent,
		arg.TenantID,
		arg.EmployeeID,
		arg.UserID,
		arg.EventType,
		arg.DeliveryChannel,
		arg.DeliveryTarget,
		arg.Status,
		arg.FailureReason,
		arg.CreatedBy,
	)
	var i HrmsEmployeeCredentialEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.UserID,
		&i.EventType,
		&i.DeliveryChannel,
		&i.DeliveryTarget,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listEmployeeCredentialEvents = `-- name: ListEmployeeCredentialEvents :many
SELECT id, tenant_id, employee_id, user_id, event_type, delivery_channel, delivery_target, status, failure_reason, created_at, created_by
FROM hrms.employee_credential_events
WHERE tenant_id = $1 AND employee_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListEmployeeCredentialEventsParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	EmployeeID uuid.UUID `db:"employee_id" json:"employee_id"`
	LimitRows  int32     `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListEmployeeCredentialEvents(ctx context.Context, arg ListEmployeeCredentialEventsParams) ([]HrmsEmployeeCredentialEvent, error) {
	rows, err := q.db.Query(ctx, listEmployeeCredentialEvents, arg.TenantID, arg.EmployeeID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsEmployeeCredentialEvent
	for rows.Next() {
		var i HrmsEmployeeCredentialEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.UserID,
			&i.EventType,
			&i.DeliveryChannel,
			&i.DeliveryTarget,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
