// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insights.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInsightEvent = `-- name: CreateInsightEvent :one
INSERT INTO hrms.insight_events (
    tenant_id, insight_id, action, from_status, to_status, remarks, metadata, created_by, updated_by
) VALUES (
    $1, $2, $3, $5::text, $6::text,
    $7::text, $4, $8::uuid, $8::uuid
)
RETURNING id, tenant_id, insight_id, action, from_status, to_status, remarks, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateInsightEventParams struct {
	TenantID   uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	InsightID  uuid.UUID   `db:"insight_id" json:"insight_id"`
	Action     string      `db:"action" json:"action"`
	Metadata   []byte      `db:"metadata" json:"metadata"`
	FromStatus pgtype.Text `db:"from_status" json:"from_status"`
	ToStatus   pgtype.Text `db:"to_status" json:"to_status"`
	Remarks    pgtype.Text `db:"remarks" json:"remarks"`
	ActorID    pgtype.UUID `db:"actor_id" json:"actor_id"`
}

func (q *Queries) CreateInsightEvent(ctx context.Context, arg CreateInsightEventParams) (HrmsInsightEvent, error) {
	row := q.db.QueryRow(ctx, createInsightEvent,
		arg.TenantID,
		arg.InsightID,
		arg.Action,
		arg.Metadata,
		arg.FromStatus,
		arg.ToStatus,
		arg.Remarks,
		arg.ActorID,
	)
	var i HrmsInsightEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InsightID,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.Remarks,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getInsight = `-- name: GetInsight :one
SELECT id, tenant_id, insight_key, insight_type, category, severity, status, title, summary, confidence_score, score, source, model_version, entity_type, entity_id, employee_user_id, reasons, recommendations, context, explainability, detected_at, due_at, assigned_to, reviewed_by, reviewed_at, resolved_at, resolution_note, inactive, created_at, created_by, updated_at, updated_by, visibility_scope, human_review_required, action_state, employee_safe_summary
FROM hrms.insights
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetInsightParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetInsight(ctx context.Context, arg GetInsightParams) (HrmsInsight, error) {
	row := q.db.QueryRow(ctx, getInsight, arg.TenantID, arg.ID)
	var i HrmsInsight
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InsightKey,
		&i.InsightType,
		&i.Category,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Summary,
		&i.ConfidenceScore,
		&i.Score,
		&i.Source,
		&i.ModelVersion,
		&i.EntityType,
		&i.EntityID,
		&i.EmployeeUserID,
		&i.Reasons,
		&i.Recommendations,
		&i.Context,
		&i.Explainability,
		&i.DetectedAt,
		&i.DueAt,
		&i.AssignedTo,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.VisibilityScope,
		&i.HumanReviewRequired,
		&i.ActionState,
		&i.EmployeeSafeSummary,
	)
	return i, err
}

const listInsightEvents = `-- name: ListInsightEvents :many
SELECT id, tenant_id, insight_id, action, from_status, to_status, remarks, metadata, inactive, created_at, created_by, updated_at, updated_by
FROM hrms.insight_events
WHERE tenant_id = $1 AND insight_id = $2 AND NOT inactive
ORDER BY created_at DESC
`

type ListInsightEventsParams struct {
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	InsightID uuid.UUID `db:"insight_id" json:"insight_id"`
}

func (q *Queries) ListInsightEvents(ctx context.Context, arg ListInsightEventsParams) ([]HrmsInsightEvent, error) {
	rows, err := q.db.Query(ctx, listInsightEvents, arg.TenantID, arg.InsightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsInsightEvent
	for rows.Next() {
		var i HrmsInsightEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InsightID,
			&i.Action,
			&i.FromStatus,
			&i.ToStatus,
			&i.Remarks,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsights = `-- name: ListInsights :many
SELECT id, tenant_id, insight_key, insight_type, category, severity, status, title, summary, confidence_score, score, source, model_version, entity_type, entity_id, employee_user_id, reasons, recommendations, context, explainability, detected_at, due_at, assigned_to, reviewed_by, reviewed_at, resolved_at, resolution_note, inactive, created_at, created_by, updated_at, updated_by, visibility_scope, human_review_required, action_state, employee_safe_summary
FROM hrms.insights
WHERE tenant_id = $1
  AND NOT inactive
  AND ($4::text IS NULL OR status = $4::text)
  AND ($5::text IS NULL OR severity = $5::text)
  AND ($6::text IS NULL OR category = $6::text)
  AND ($7::text IS NULL OR insight_type = $7::text)
  AND ($8::uuid IS NULL OR assigned_to = $8::uuid)
ORDER BY
  CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END,
  detected_at DESC
LIMIT $2 OFFSET $3
`

type ListInsightsParams struct {
	TenantID    uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit       int32       `db:"limit" json:"limit"`
	Offset      int32       `db:"offset" json:"offset"`
	Status      pgtype.Text `db:"status" json:"status"`
	Severity    pgtype.Text `db:"severity" json:"severity"`
	Category    pgtype.Text `db:"category" json:"category"`
	InsightType pgtype.Text `db:"insight_type" json:"insight_type"`
	AssignedTo  pgtype.UUID `db:"assigned_to" json:"assigned_to"`
}

func (q *Queries) ListInsights(ctx context.Context, arg ListInsightsParams) ([]HrmsInsight, error) {
	rows, err := q.db.Query(ctx, listInsights,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Severity,
		arg.Category,
		arg.InsightType,
		arg.AssignedTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsInsight
	for rows.Next() {
		var i HrmsInsight
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InsightKey,
			&i.InsightType,
			&i.Category,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.Summary,
			&i.ConfidenceScore,
			&i.Score,
			&i.Source,
			&i.ModelVersion,
			&i.EntityType,
			&i.EntityID,
			&i.EmployeeUserID,
			&i.Reasons,
			&i.Recommendations,
			&i.Context,
			&i.Explainability,
			&i.DetectedAt,
			&i.DueAt,
			&i.AssignedTo,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ResolvedAt,
			&i.ResolutionNote,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.VisibilityScope,
			&i.HumanReviewRequired,
			&i.ActionState,
			&i.EmployeeSafeSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInsightStatus = `-- name: UpdateInsightStatus :one
UPDATE hrms.insights
SET status = $3,
    assigned_to = COALESCE($4::uuid, assigned_to),
    reviewed_by = COALESCE($5::uuid, reviewed_by),
    reviewed_at = CASE WHEN $3 IN ('reviewing', 'dismissed', 'overridden', 'resolved') THEN COALESCE($6::timestamptz, NOW()) ELSE reviewed_at END,
    resolved_at = CASE WHEN $3 IN ('resolved', 'dismissed', 'overridden') THEN COALESCE($7::timestamptz, NOW()) ELSE NULL END,
    resolution_note = $8::text,
    updated_at = NOW(),
    updated_by = $9::uuid
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, insight_key, insight_type, category, severity, status, title, summary, confidence_score, score, source, model_version, entity_type, entity_id, employee_user_id, reasons, recommendations, context, explainability, detected_at, due_at, assigned_to, reviewed_by, reviewed_at, resolved_at, resolution_note, inactive, created_at, created_by, updated_at, updated_by, visibility_scope, human_review_required, action_state, employee_safe_summary
`

type UpdateInsightStatusParams struct {
	TenantID       uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	ID             uuid.UUID          `db:"id" json:"id"`
	Status         string             `db:"status" json:"status"`
	AssignedTo     pgtype.UUID        `db:"assigned_to" json:"assigned_to"`
	ReviewedBy     pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt     pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ResolvedAt     pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	ResolutionNote pgtype.Text        `db:"resolution_note" json:"resolution_note"`
	ActorID        pgtype.UUID        `db:"actor_id" json:"actor_id"`
}

func (q *Queries) UpdateInsightStatus(ctx context.Context, arg UpdateInsightStatusParams) (HrmsInsight, error) {
	row := q.db.QueryRow(ctx, updateInsightStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.AssignedTo,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.ResolvedAt,
		arg.ResolutionNote,
		arg.ActorID,
	)
	var i HrmsInsight
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InsightKey,
		&i.InsightType,
		&i.Category,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Summary,
		&i.ConfidenceScore,
		&i.Score,
		&i.Source,
		&i.ModelVersion,
		&i.EntityType,
		&i.EntityID,
		&i.EmployeeUserID,
		&i.Reasons,
		&i.Recommendations,
		&i.Context,
		&i.Explainability,
		&i.DetectedAt,
		&i.DueAt,
		&i.AssignedTo,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.VisibilityScope,
		&i.HumanReviewRequired,
		&i.ActionState,
		&i.EmployeeSafeSummary,
	)
	return i, err
}

const upsertInsight = `-- name: UpsertInsight :one
INSERT INTO hrms.insights (
    id, tenant_id, insight_key, insight_type, category, severity, status, title, summary,
    confidence_score, score, source, model_version, entity_type, entity_id, employee_user_id,
    reasons, recommendations, context, explainability, detected_at, due_at, assigned_to,
    reviewed_by, reviewed_at, resolved_at, resolution_note, created_by, updated_by
) VALUES (
    COALESCE($17::uuid, gen_random_uuid()),
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $18::text, $19::text,
    $20::uuid, $21::uuid,
    $12, $13, $14, $15, $16, $22::timestamptz, $23::uuid,
    $24::uuid, $25::timestamptz,
    $26::timestamptz, $27::text, $28::uuid, $28::uuid
)
ON CONFLICT (tenant_id, insight_key) DO UPDATE SET
    insight_type = EXCLUDED.insight_type,
    category = EXCLUDED.category,
    severity = EXCLUDED.severity,
    status = CASE WHEN hrms.insights.status IN ('resolved', 'dismissed', 'overridden') THEN hrms.insights.status ELSE EXCLUDED.status END,
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    confidence_score = EXCLUDED.confidence_score,
    score = EXCLUDED.score,
    source = EXCLUDED.source,
    model_version = EXCLUDED.model_version,
    entity_type = EXCLUDED.entity_type,
    entity_id = EXCLUDED.entity_id,
    employee_user_id = EXCLUDED.employee_user_id,
    reasons = EXCLUDED.reasons,
    recommendations = EXCLUDED.recommendations,
    context = EXCLUDED.context,
    explainability = EXCLUDED.explainability,
    detected_at = EXCLUDED.detected_at,
    due_at = EXCLUDED.due_at,
    updated_at = NOW(),
    updated_by = EXCLUDED.updated_by,
    inactive = FALSE
RETURNING id, tenant_id, insight_key, insight_type, category, severity, status, title, summary, confidence_score, score, source, model_version, entity_type, entity_id, employee_user_id, reasons, recommendations, context, explainability, detected_at, due_at, assigned_to, reviewed_by, reviewed_at, resolved_at, resolution_note, inactive, created_at, created_by, updated_at, updated_by, visibility_scope, human_review_required, action_state, employee_safe_summary
`

type UpsertInsightParams struct {
	TenantID        uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	InsightKey      string             `db:"insight_key" json:"insight_key"`
	InsightType     string             `db:"insight_type" json:"insight_type"`
	Category        string             `db:"category" json:"category"`
	Severity        string             `db:"severity" json:"severity"`
	Status          string             `db:"status" json:"status"`
	Title           string             `db:"title" json:"title"`
	Summary         string             `db:"summary" json:"summary"`
	ConfidenceScore pgtype.Numeric     `db:"confidence_score" json:"confidence_score"`
	Score           pgtype.Numeric     `db:"score" json:"score"`
	Source          string             `db:"source" json:"source"`
	Reasons         []byte             `db:"reasons" json:"reasons"`
	Recommendations []byte             `db:"recommendations" json:"recommendations"`
	Context         []byte             `db:"context" json:"context"`
	Explainability  []byte             `db:"explainability" json:"explainability"`
	DetectedAt      pgtype.Timestamptz `db:"detected_at" json:"detected_at"`
	ID              pgtype.UUID        `db:"id" json:"id"`
	ModelVersion    pgtype.Text        `db:"model_version" json:"model_version"`
	EntityType      pgtype.Text        `db:"entity_type" json:"entity_type"`
	EntityID        pgtype.UUID        `db:"entity_id" json:"entity_id"`
	EmployeeUserID  pgtype.UUID        `db:"employee_user_id" json:"employee_user_id"`
	DueAt           pgtype.Timestamptz `db:"due_at" json:"due_at"`
	AssignedTo      pgtype.UUID        `db:"assigned_to" json:"assigned_to"`
	ReviewedBy      pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ResolvedAt      pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	ResolutionNote  pgtype.Text        `db:"resolution_note" json:"resolution_note"`
	ActorID         pgtype.UUID        `db:"actor_id" json:"actor_id"`
}

func (q *Queries) UpsertInsight(ctx context.Context, arg UpsertInsightParams) (HrmsInsight, error) {
	row := q.db.QueryRow(ctx, upsertInsight,
		arg.TenantID,
		arg.InsightKey,
		arg.InsightType,
		arg.Category,
		arg.Severity,
		arg.Status,
		arg.Title,
		arg.Summary,
		arg.ConfidenceScore,
		arg.Score,
		arg.Source,
		arg.Reasons,
		arg.Recommendations,
		arg.Context,
		arg.Explainability,
		arg.DetectedAt,
		arg.ID,
		arg.ModelVersion,
		arg.EntityType,
		arg.EntityID,
		arg.EmployeeUserID,
		arg.DueAt,
		arg.AssignedTo,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.ResolvedAt,
		arg.ResolutionNote,
		arg.ActorID,
	)
	var i HrmsInsight
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InsightKey,
		&i.InsightType,
		&i.Category,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Summary,
		&i.ConfidenceScore,
		&i.Score,
		&i.Source,
		&i.ModelVersion,
		&i.EntityType,
		&i.EntityID,
		&i.EmployeeUserID,
		&i.Reasons,
		&i.Recommendations,
		&i.Context,
		&i.Explainability,
		&i.DetectedAt,
		&i.DueAt,
		&i.AssignedTo,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.VisibilityScope,
		&i.HumanReviewRequired,
		&i.ActionState,
		&i.EmployeeSafeSummary,
	)
	return i, err
}
