// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overtime_requests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOvertimeRequest = `-- name: CreateOvertimeRequest :one
INSERT INTO hrms.overtime_requests (
    tenant_id,
    user_id,
    work_date,
    requested_minutes,
    reason,
    calculation_type,
    rate_multiplier,
    payroll_component_code,
    source_attendance_id,
    source_segment_id,
    metadata,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12
)
RETURNING id, tenant_id, user_id, work_date, requested_minutes, approved_minutes, reason, status, reviewed_by, reviewed_at, review_remarks, calculation_type, rate_multiplier, payroll_component_code, payroll_export_status, payroll_exported_at, payroll_exported_by, source_attendance_id, source_segment_id, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateOvertimeRequestParams struct {
	TenantID             uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	UserID               uuid.UUID      `db:"user_id" json:"user_id"`
	WorkDate             pgtype.Date    `db:"work_date" json:"work_date"`
	RequestedMinutes     int32          `db:"requested_minutes" json:"requested_minutes"`
	Reason               pgtype.Text    `db:"reason" json:"reason"`
	CalculationType      string         `db:"calculation_type" json:"calculation_type"`
	RateMultiplier       pgtype.Numeric `db:"rate_multiplier" json:"rate_multiplier"`
	PayrollComponentCode pgtype.Text    `db:"payroll_component_code" json:"payroll_component_code"`
	SourceAttendanceID   pgtype.UUID    `db:"source_attendance_id" json:"source_attendance_id"`
	SourceSegmentID      pgtype.UUID    `db:"source_segment_id" json:"source_segment_id"`
	Metadata             []byte         `db:"metadata" json:"metadata"`
	CreatedBy            pgtype.UUID    `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateOvertimeRequest(ctx context.Context, arg CreateOvertimeRequestParams) (HrmsOvertimeRequest, error) {
	row := q.db.QueryRow(ctx, createOvertimeRequest,
		arg.TenantID,
		arg.UserID,
		arg.WorkDate,
		arg.RequestedMinutes,
		arg.Reason,
		arg.CalculationType,
		arg.RateMultiplier,
		arg.PayrollComponentCode,
		arg.SourceAttendanceID,
		arg.SourceSegmentID,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsOvertimeRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.WorkDate,
		&i.RequestedMinutes,
		&i.ApprovedMinutes,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewRemarks,
		&i.CalculationType,
		&i.RateMultiplier,
		&i.PayrollComponentCode,
		&i.PayrollExportStatus,
		&i.PayrollExportedAt,
		&i.PayrollExportedBy,
		&i.SourceAttendanceID,
		&i.SourceSegmentID,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getOvertimeRequest = `-- name: GetOvertimeRequest :one
SELECT id, tenant_id, user_id, work_date, requested_minutes, approved_minutes, reason, status, reviewed_by, reviewed_at, review_remarks, calculation_type, rate_multiplier, payroll_component_code, payroll_export_status, payroll_exported_at, payroll_exported_by, source_attendance_id, source_segment_id, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.overtime_requests
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type GetOvertimeRequestParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetOvertimeRequest(ctx context.Context, arg GetOvertimeRequestParams) (HrmsOvertimeRequest, error) {
	row := q.db.QueryRow(ctx, getOvertimeRequest, arg.TenantID, arg.ID)
	var i HrmsOvertimeRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.WorkDate,
		&i.RequestedMinutes,
		&i.ApprovedMinutes,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewRemarks,
		&i.CalculationType,
		&i.RateMultiplier,
		&i.PayrollComponentCode,
		&i.PayrollExportStatus,
		&i.PayrollExportedAt,
		&i.PayrollExportedBy,
		&i.SourceAttendanceID,
		&i.SourceSegmentID,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listOvertimeRequestsByPayrollExportStatus = `-- name: ListOvertimeRequestsByPayrollExportStatus :many
SELECT id, tenant_id, user_id, work_date, requested_minutes, approved_minutes, reason, status, reviewed_by, reviewed_at, review_remarks, calculation_type, rate_multiplier, payroll_component_code, payroll_export_status, payroll_exported_at, payroll_exported_by, source_attendance_id, source_segment_id, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.overtime_requests
WHERE tenant_id = $1
  AND payroll_export_status = $2
  AND NOT inactive
ORDER BY work_date ASC, created_at ASC
`

type ListOvertimeRequestsByPayrollExportStatusParams struct {
	TenantID            uuid.UUID `db:"tenant_id" json:"tenant_id"`
	PayrollExportStatus string    `db:"payroll_export_status" json:"payroll_export_status"`
}

func (q *Queries) ListOvertimeRequestsByPayrollExportStatus(ctx context.Context, arg ListOvertimeRequestsByPayrollExportStatusParams) ([]HrmsOvertimeRequest, error) {
	rows, err := q.db.Query(ctx, listOvertimeRequestsByPayrollExportStatus, arg.TenantID, arg.PayrollExportStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsOvertimeRequest
	for rows.Next() {
		var i HrmsOvertimeRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.WorkDate,
			&i.RequestedMinutes,
			&i.ApprovedMinutes,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewRemarks,
			&i.CalculationType,
			&i.RateMultiplier,
			&i.PayrollComponentCode,
			&i.PayrollExportStatus,
			&i.PayrollExportedAt,
			&i.PayrollExportedBy,
			&i.SourceAttendanceID,
			&i.SourceSegmentID,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOvertimeRequestsByStatus = `-- name: ListOvertimeRequestsByStatus :many
SELECT id, tenant_id, user_id, work_date, requested_minutes, approved_minutes, reason, status, reviewed_by, reviewed_at, review_remarks, calculation_type, rate_multiplier, payroll_component_code, payroll_export_status, payroll_exported_at, payroll_exported_by, source_attendance_id, source_segment_id, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.overtime_requests
WHERE tenant_id = $1
  AND status = $2
  AND NOT inactive
ORDER BY created_at ASC
`

type ListOvertimeRequestsByStatusParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Status   string    `db:"status" json:"status"`
}

func (q *Queries) ListOvertimeRequestsByStatus(ctx context.Context, arg ListOvertimeRequestsByStatusParams) ([]HrmsOvertimeRequest, error) {
	rows, err := q.db.Query(ctx, listOvertimeRequestsByStatus, arg.TenantID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsOvertimeRequest
	for rows.Next() {
		var i HrmsOvertimeRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.WorkDate,
			&i.RequestedMinutes,
			&i.ApprovedMinutes,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewRemarks,
			&i.CalculationType,
			&i.RateMultiplier,
			&i.PayrollComponentCode,
			&i.PayrollExportStatus,
			&i.PayrollExportedAt,
			&i.PayrollExportedBy,
			&i.SourceAttendanceID,
			&i.SourceSegmentID,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOvertimeRequestsByUser = `-- name: ListOvertimeRequestsByUser :many
SELECT id, tenant_id, user_id, work_date, requested_minutes, approved_minutes, reason, status, reviewed_by, reviewed_at, review_remarks, calculation_type, rate_multiplier, payroll_component_code, payroll_export_status, payroll_exported_at, payroll_exported_by, source_attendance_id, source_segment_id, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.overtime_requests
WHERE tenant_id = $1
  AND user_id = $2
  AND NOT inactive
ORDER BY created_at DESC
`

type ListOvertimeRequestsByUserParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ListOvertimeRequestsByUser(ctx context.Context, arg ListOvertimeRequestsByUserParams) ([]HrmsOvertimeRequest, error) {
	rows, err := q.db.Query(ctx, listOvertimeRequestsByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsOvertimeRequest
	for rows.Next() {
		var i HrmsOvertimeRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.WorkDate,
			&i.RequestedMinutes,
			&i.ApprovedMinutes,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewRemarks,
			&i.CalculationType,
			&i.RateMultiplier,
			&i.PayrollComponentCode,
			&i.PayrollExportStatus,
			&i.PayrollExportedAt,
			&i.PayrollExportedBy,
			&i.SourceAttendanceID,
			&i.SourceSegmentID,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewOvertimeRequest = `-- name: ReviewOvertimeRequest :one
UPDATE hrms.overtime_requests
SET
    status = $3,
    approved_minutes = $4,
    review_remarks = $5,
    calculation_type = $6,
    rate_multiplier = $7,
    payroll_component_code = $8,
    payroll_export_status = $9,
    reviewed_by = $10,
    reviewed_at = NOW(),
    metadata = $11,
    updated_by = $10,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
  AND status = 'pending'
  AND NOT inactive
RETURNING id, tenant_id, user_id, work_date, requested_minutes, approved_minutes, reason, status, reviewed_by, reviewed_at, review_remarks, calculation_type, rate_multiplier, payroll_component_code, payroll_export_status, payroll_exported_at, payroll_exported_by, source_attendance_id, source_segment_id, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type ReviewOvertimeRequestParams struct {
	TenantID             uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	ID                   uuid.UUID      `db:"id" json:"id"`
	Status               string         `db:"status" json:"status"`
	ApprovedMinutes      pgtype.Int4    `db:"approved_minutes" json:"approved_minutes"`
	ReviewRemarks        pgtype.Text    `db:"review_remarks" json:"review_remarks"`
	CalculationType      string         `db:"calculation_type" json:"calculation_type"`
	RateMultiplier       pgtype.Numeric `db:"rate_multiplier" json:"rate_multiplier"`
	PayrollComponentCode pgtype.Text    `db:"payroll_component_code" json:"payroll_component_code"`
	PayrollExportStatus  string         `db:"payroll_export_status" json:"payroll_export_status"`
	ReviewedBy           pgtype.UUID    `db:"reviewed_by" json:"reviewed_by"`
	Metadata             []byte         `db:"metadata" json:"metadata"`
}

func (q *Queries) ReviewOvertimeRequest(ctx context.Context, arg ReviewOvertimeRequestParams) (HrmsOvertimeRequest, error) {
	row := q.db.QueryRow(ctx, reviewOvertimeRequest,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.ApprovedMinutes,
		arg.ReviewRemarks,
		arg.CalculationType,
		arg.RateMultiplier,
		arg.PayrollComponentCode,
		arg.PayrollExportStatus,
		arg.ReviewedBy,
		arg.Metadata,
	)
	var i HrmsOvertimeRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.WorkDate,
		&i.RequestedMinutes,
		&i.ApprovedMinutes,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewRemarks,
		&i.CalculationType,
		&i.RateMultiplier,
		&i.PayrollComponentCode,
		&i.PayrollExportStatus,
		&i.PayrollExportedAt,
		&i.PayrollExportedBy,
		&i.SourceAttendanceID,
		&i.SourceSegmentID,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
