// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_provider_settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPushProviderSettings = `-- name: GetPushProviderSettings :one
SELECT id, tenant_id, provider, is_enabled, project_id, client_email, private_key, private_key_id, auth_uri, token_uri, android_enabled, ios_enabled, web_enabled, default_click_action, default_image_url, ttl_seconds, collapse_key, last_test_at, last_test_status, last_test_message, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.push_provider_settings
WHERE tenant_id = $1 AND NOT inactive
LIMIT 1
`

func (q *Queries) GetPushProviderSettings(ctx context.Context, tenantID uuid.UUID) (HrmsPushProviderSetting, error) {
	row := q.db.QueryRow(ctx, getPushProviderSettings, tenantID)
	var i HrmsPushProviderSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.IsEnabled,
		&i.ProjectID,
		&i.ClientEmail,
		&i.PrivateKey,
		&i.PrivateKeyID,
		&i.AuthUri,
		&i.TokenUri,
		&i.AndroidEnabled,
		&i.IosEnabled,
		&i.WebEnabled,
		&i.DefaultClickAction,
		&i.DefaultImageUrl,
		&i.TtlSeconds,
		&i.CollapseKey,
		&i.LastTestAt,
		&i.LastTestStatus,
		&i.LastTestMessage,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const softDeletePushProviderSettings = `-- name: SoftDeletePushProviderSettings :exec
UPDATE hrms.push_provider_settings
SET inactive = TRUE,
    is_enabled = FALSE,
    updated_at = NOW(),
    updated_by = $3
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
`

type SoftDeletePushProviderSettingsParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeletePushProviderSettings(ctx context.Context, arg SoftDeletePushProviderSettingsParams) error {
	_, err := q.db.Exec(ctx, softDeletePushProviderSettings, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const updatePushProviderTestResult = `-- name: UpdatePushProviderTestResult :one
UPDATE hrms.push_provider_settings
SET last_test_at = NOW(),
    last_test_status = $3,
    last_test_message = $4,
    updated_at = NOW(),
    updated_by = $5
WHERE tenant_id = $1 AND id = $2 AND NOT inactive
RETURNING id, tenant_id, provider, is_enabled, project_id, client_email, private_key, private_key_id, auth_uri, token_uri, android_enabled, ios_enabled, web_enabled, default_click_action, default_image_url, ttl_seconds, collapse_key, last_test_at, last_test_status, last_test_message, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdatePushProviderTestResultParams struct {
	TenantID        uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID              uuid.UUID   `db:"id" json:"id"`
	LastTestStatus  pgtype.Text `db:"last_test_status" json:"last_test_status"`
	LastTestMessage pgtype.Text `db:"last_test_message" json:"last_test_message"`
	UpdatedBy       pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdatePushProviderTestResult(ctx context.Context, arg UpdatePushProviderTestResultParams) (HrmsPushProviderSetting, error) {
	row := q.db.QueryRow(ctx, updatePushProviderTestResult,
		arg.TenantID,
		arg.ID,
		arg.LastTestStatus,
		arg.LastTestMessage,
		arg.UpdatedBy,
	)
	var i HrmsPushProviderSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.IsEnabled,
		&i.ProjectID,
		&i.ClientEmail,
		&i.PrivateKey,
		&i.PrivateKeyID,
		&i.AuthUri,
		&i.TokenUri,
		&i.AndroidEnabled,
		&i.IosEnabled,
		&i.WebEnabled,
		&i.DefaultClickAction,
		&i.DefaultImageUrl,
		&i.TtlSeconds,
		&i.CollapseKey,
		&i.LastTestAt,
		&i.LastTestStatus,
		&i.LastTestMessage,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertPushProviderSettings = `-- name: UpsertPushProviderSettings :one
INSERT INTO hrms.push_provider_settings (
    tenant_id, provider, is_enabled, project_id, client_email, private_key, private_key_id,
    auth_uri, token_uri, android_enabled, ios_enabled, web_enabled, default_click_action,
    default_image_url, ttl_seconds, collapse_key, metadata, created_by
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, COALESCE($17, '{}'::jsonb), $18
)
ON CONFLICT (tenant_id) WHERE NOT inactive
DO UPDATE SET
    provider = EXCLUDED.provider,
    is_enabled = EXCLUDED.is_enabled,
    project_id = EXCLUDED.project_id,
    client_email = EXCLUDED.client_email,
    private_key = COALESCE(EXCLUDED.private_key, hrms.push_provider_settings.private_key),
    private_key_id = EXCLUDED.private_key_id,
    auth_uri = EXCLUDED.auth_uri,
    token_uri = EXCLUDED.token_uri,
    android_enabled = EXCLUDED.android_enabled,
    ios_enabled = EXCLUDED.ios_enabled,
    web_enabled = EXCLUDED.web_enabled,
    default_click_action = EXCLUDED.default_click_action,
    default_image_url = EXCLUDED.default_image_url,
    ttl_seconds = EXCLUDED.ttl_seconds,
    collapse_key = EXCLUDED.collapse_key,
    metadata = EXCLUDED.metadata,
    updated_at = NOW(),
    updated_by = $18
RETURNING id, tenant_id, provider, is_enabled, project_id, client_email, private_key, private_key_id, auth_uri, token_uri, android_enabled, ios_enabled, web_enabled, default_click_action, default_image_url, ttl_seconds, collapse_key, last_test_at, last_test_status, last_test_message, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpsertPushProviderSettingsParams struct {
	TenantID           uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Provider           string      `db:"provider" json:"provider"`
	IsEnabled          bool        `db:"is_enabled" json:"is_enabled"`
	ProjectID          pgtype.Text `db:"project_id" json:"project_id"`
	ClientEmail        pgtype.Text `db:"client_email" json:"client_email"`
	PrivateKey         pgtype.Text `db:"private_key" json:"private_key"`
	PrivateKeyID       pgtype.Text `db:"private_key_id" json:"private_key_id"`
	AuthUri            pgtype.Text `db:"auth_uri" json:"auth_uri"`
	TokenUri           pgtype.Text `db:"token_uri" json:"token_uri"`
	AndroidEnabled     bool        `db:"android_enabled" json:"android_enabled"`
	IosEnabled         bool        `db:"ios_enabled" json:"ios_enabled"`
	WebEnabled         bool        `db:"web_enabled" json:"web_enabled"`
	DefaultClickAction pgtype.Text `db:"default_click_action" json:"default_click_action"`
	DefaultImageUrl    pgtype.Text `db:"default_image_url" json:"default_image_url"`
	TtlSeconds         int32       `db:"ttl_seconds" json:"ttl_seconds"`
	CollapseKey        pgtype.Text `db:"collapse_key" json:"collapse_key"`
	Column17           interface{} `db:"column_17" json:"column_17"`
	CreatedBy          pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) UpsertPushProviderSettings(ctx context.Context, arg UpsertPushProviderSettingsParams) (HrmsPushProviderSetting, error) {
	row := q.db.QueryRow(ctx, upsertPushProviderSettings,
		arg.TenantID,
		arg.Provider,
		arg.IsEnabled,
		arg.ProjectID,
		arg.ClientEmail,
		arg.PrivateKey,
		arg.PrivateKeyID,
		arg.AuthUri,
		arg.TokenUri,
		arg.AndroidEnabled,
		arg.IosEnabled,
		arg.WebEnabled,
		arg.DefaultClickAction,
		arg.DefaultImageUrl,
		arg.TtlSeconds,
		arg.CollapseKey,
		arg.Column17,
		arg.CreatedBy,
	)
	var i HrmsPushProviderSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.IsEnabled,
		&i.ProjectID,
		&i.ClientEmail,
		&i.PrivateKey,
		&i.PrivateKeyID,
		&i.AuthUri,
		&i.TokenUri,
		&i.AndroidEnabled,
		&i.IosEnabled,
		&i.WebEnabled,
		&i.DefaultClickAction,
		&i.DefaultImageUrl,
		&i.TtlSeconds,
		&i.CollapseKey,
		&i.LastTestAt,
		&i.LastTestStatus,
		&i.LastTestMessage,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
