// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shift_scheduling.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShiftScheduleAssignment = `-- name: CreateShiftScheduleAssignment :one
INSERT INTO hrms.shift_schedule_assignments (
  tenant_id, schedule_date, worker_profile_id, employee_user_id, shift_template_id, attendance_policy_id,
  attendance_location_id, attendance_roster_id, branch_id, department_id, start_time, end_time, break_minutes,
  work_mode, location_type, role_label, team_label, status, source, overtime_planned_minutes, has_conflict,
  conflict_reason, payroll_blocking, notes, metadata, created_by
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26
) RETURNING id, tenant_id, schedule_date, worker_profile_id, employee_user_id, shift_template_id, attendance_policy_id, attendance_location_id, attendance_roster_id, branch_id, department_id, start_time, end_time, break_minutes, work_mode, location_type, role_label, team_label, status, source, overtime_planned_minutes, has_conflict, conflict_reason, payroll_blocking, notes, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateShiftScheduleAssignmentParams struct {
	TenantID               uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ScheduleDate           pgtype.Date `db:"schedule_date" json:"schedule_date"`
	WorkerProfileID        pgtype.UUID `db:"worker_profile_id" json:"worker_profile_id"`
	EmployeeUserID         pgtype.UUID `db:"employee_user_id" json:"employee_user_id"`
	ShiftTemplateID        pgtype.UUID `db:"shift_template_id" json:"shift_template_id"`
	AttendancePolicyID     pgtype.UUID `db:"attendance_policy_id" json:"attendance_policy_id"`
	AttendanceLocationID   pgtype.UUID `db:"attendance_location_id" json:"attendance_location_id"`
	AttendanceRosterID     pgtype.UUID `db:"attendance_roster_id" json:"attendance_roster_id"`
	BranchID               pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID           pgtype.UUID `db:"department_id" json:"department_id"`
	StartTime              pgtype.Time `db:"start_time" json:"start_time"`
	EndTime                pgtype.Time `db:"end_time" json:"end_time"`
	BreakMinutes           int32       `db:"break_minutes" json:"break_minutes"`
	WorkMode               string      `db:"work_mode" json:"work_mode"`
	LocationType           string      `db:"location_type" json:"location_type"`
	RoleLabel              pgtype.Text `db:"role_label" json:"role_label"`
	TeamLabel              pgtype.Text `db:"team_label" json:"team_label"`
	Status                 string      `db:"status" json:"status"`
	Source                 string      `db:"source" json:"source"`
	OvertimePlannedMinutes int32       `db:"overtime_planned_minutes" json:"overtime_planned_minutes"`
	HasConflict            bool        `db:"has_conflict" json:"has_conflict"`
	ConflictReason         pgtype.Text `db:"conflict_reason" json:"conflict_reason"`
	PayrollBlocking        bool        `db:"payroll_blocking" json:"payroll_blocking"`
	Notes                  pgtype.Text `db:"notes" json:"notes"`
	Metadata               []byte      `db:"metadata" json:"metadata"`
	CreatedBy              pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateShiftScheduleAssignment(ctx context.Context, arg CreateShiftScheduleAssignmentParams) (HrmsShiftScheduleAssignment, error) {
	row := q.db.QueryRow(ctx, createShiftScheduleAssignment,
		arg.TenantID,
		arg.ScheduleDate,
		arg.WorkerProfileID,
		arg.EmployeeUserID,
		arg.ShiftTemplateID,
		arg.AttendancePolicyID,
		arg.AttendanceLocationID,
		arg.AttendanceRosterID,
		arg.BranchID,
		arg.DepartmentID,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMinutes,
		arg.WorkMode,
		arg.LocationType,
		arg.RoleLabel,
		arg.TeamLabel,
		arg.Status,
		arg.Source,
		arg.OvertimePlannedMinutes,
		arg.HasConflict,
		arg.ConflictReason,
		arg.PayrollBlocking,
		arg.Notes,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsShiftScheduleAssignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScheduleDate,
		&i.WorkerProfileID,
		&i.EmployeeUserID,
		&i.ShiftTemplateID,
		&i.AttendancePolicyID,
		&i.AttendanceLocationID,
		&i.AttendanceRosterID,
		&i.BranchID,
		&i.DepartmentID,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.WorkMode,
		&i.LocationType,
		&i.RoleLabel,
		&i.TeamLabel,
		&i.Status,
		&i.Source,
		&i.OvertimePlannedMinutes,
		&i.HasConflict,
		&i.ConflictReason,
		&i.PayrollBlocking,
		&i.Notes,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createShiftScheduleEvent = `-- name: CreateShiftScheduleEvent :one
INSERT INTO hrms.shift_schedule_events (
  tenant_id, source_type, source_id, action, from_status, to_status, actor_user_id, remarks, metadata, created_by
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10
) RETURNING id, tenant_id, source_type, source_id, action, from_status, to_status, actor_user_id, remarks, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateShiftScheduleEventParams struct {
	TenantID    uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	SourceType  string      `db:"source_type" json:"source_type"`
	SourceID    uuid.UUID   `db:"source_id" json:"source_id"`
	Action      string      `db:"action" json:"action"`
	FromStatus  pgtype.Text `db:"from_status" json:"from_status"`
	ToStatus    pgtype.Text `db:"to_status" json:"to_status"`
	ActorUserID pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	Remarks     pgtype.Text `db:"remarks" json:"remarks"`
	Metadata    []byte      `db:"metadata" json:"metadata"`
	CreatedBy   pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateShiftScheduleEvent(ctx context.Context, arg CreateShiftScheduleEventParams) (HrmsShiftScheduleEvent, error) {
	row := q.db.QueryRow(ctx, createShiftScheduleEvent,
		arg.TenantID,
		arg.SourceType,
		arg.SourceID,
		arg.Action,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorUserID,
		arg.Remarks,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsShiftScheduleEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceType,
		&i.SourceID,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.ActorUserID,
		&i.Remarks,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createShiftSwapRequest = `-- name: CreateShiftSwapRequest :one
INSERT INTO hrms.shift_swap_requests (
  tenant_id, requester_assignment_id, requester_worker_profile_id, requester_user_id, target_worker_profile_id,
  target_user_id, offered_assignment_id, requested_date, requested_shift_template_id, reason, status,
  payroll_blocking, metadata, created_by
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14
) RETURNING id, tenant_id, requester_assignment_id, requester_worker_profile_id, requester_user_id, target_worker_profile_id, target_user_id, offered_assignment_id, requested_date, requested_shift_template_id, reason, status, reviewed_by, reviewed_at, review_remarks, payroll_blocking, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateShiftSwapRequestParams struct {
	TenantID                 uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	RequesterAssignmentID    uuid.UUID   `db:"requester_assignment_id" json:"requester_assignment_id"`
	RequesterWorkerProfileID pgtype.UUID `db:"requester_worker_profile_id" json:"requester_worker_profile_id"`
	RequesterUserID          pgtype.UUID `db:"requester_user_id" json:"requester_user_id"`
	TargetWorkerProfileID    pgtype.UUID `db:"target_worker_profile_id" json:"target_worker_profile_id"`
	TargetUserID             pgtype.UUID `db:"target_user_id" json:"target_user_id"`
	OfferedAssignmentID      pgtype.UUID `db:"offered_assignment_id" json:"offered_assignment_id"`
	RequestedDate            pgtype.Date `db:"requested_date" json:"requested_date"`
	RequestedShiftTemplateID pgtype.UUID `db:"requested_shift_template_id" json:"requested_shift_template_id"`
	Reason                   pgtype.Text `db:"reason" json:"reason"`
	Status                   string      `db:"status" json:"status"`
	PayrollBlocking          bool        `db:"payroll_blocking" json:"payroll_blocking"`
	Metadata                 []byte      `db:"metadata" json:"metadata"`
	CreatedBy                pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateShiftSwapRequest(ctx context.Context, arg CreateShiftSwapRequestParams) (HrmsShiftSwapRequest, error) {
	row := q.db.QueryRow(ctx, createShiftSwapRequest,
		arg.TenantID,
		arg.RequesterAssignmentID,
		arg.RequesterWorkerProfileID,
		arg.RequesterUserID,
		arg.TargetWorkerProfileID,
		arg.TargetUserID,
		arg.OfferedAssignmentID,
		arg.RequestedDate,
		arg.RequestedShiftTemplateID,
		arg.Reason,
		arg.Status,
		arg.PayrollBlocking,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsShiftSwapRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterAssignmentID,
		&i.RequesterWorkerProfileID,
		&i.RequesterUserID,
		&i.TargetWorkerProfileID,
		&i.TargetUserID,
		&i.OfferedAssignmentID,
		&i.RequestedDate,
		&i.RequestedShiftTemplateID,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewRemarks,
		&i.PayrollBlocking,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createShiftTemplate = `-- name: CreateShiftTemplate :one
INSERT INTO hrms.shift_templates (
  tenant_id, code, name, description, start_time, end_time, break_minutes, paid_minutes, work_mode, location_type,
  attendance_policy_id, attendance_location_id, allow_overtime, payroll_code, metadata, is_active, created_by
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17
) RETURNING id, tenant_id, code, name, description, start_time, end_time, break_minutes, paid_minutes, work_mode, location_type, attendance_policy_id, attendance_location_id, allow_overtime, payroll_code, metadata, is_active, inactive, created_at, created_by, updated_at, updated_by
`

type CreateShiftTemplateParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Code                 string      `db:"code" json:"code"`
	Name                 string      `db:"name" json:"name"`
	Description          pgtype.Text `db:"description" json:"description"`
	StartTime            pgtype.Time `db:"start_time" json:"start_time"`
	EndTime              pgtype.Time `db:"end_time" json:"end_time"`
	BreakMinutes         int32       `db:"break_minutes" json:"break_minutes"`
	PaidMinutes          int32       `db:"paid_minutes" json:"paid_minutes"`
	WorkMode             string      `db:"work_mode" json:"work_mode"`
	LocationType         string      `db:"location_type" json:"location_type"`
	AttendancePolicyID   pgtype.UUID `db:"attendance_policy_id" json:"attendance_policy_id"`
	AttendanceLocationID pgtype.UUID `db:"attendance_location_id" json:"attendance_location_id"`
	AllowOvertime        bool        `db:"allow_overtime" json:"allow_overtime"`
	PayrollCode          pgtype.Text `db:"payroll_code" json:"payroll_code"`
	Metadata             []byte      `db:"metadata" json:"metadata"`
	IsActive             bool        `db:"is_active" json:"is_active"`
	CreatedBy            pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateShiftTemplate(ctx context.Context, arg CreateShiftTemplateParams) (HrmsShiftTemplate, error) {
	row := q.db.QueryRow(ctx, createShiftTemplate,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMinutes,
		arg.PaidMinutes,
		arg.WorkMode,
		arg.LocationType,
		arg.AttendancePolicyID,
		arg.AttendanceLocationID,
		arg.AllowOvertime,
		arg.PayrollCode,
		arg.Metadata,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i HrmsShiftTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.PaidMinutes,
		&i.WorkMode,
		&i.LocationType,
		&i.AttendancePolicyID,
		&i.AttendanceLocationID,
		&i.AllowOvertime,
		&i.PayrollCode,
		&i.Metadata,
		&i.IsActive,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createStaffingRequirement = `-- name: CreateStaffingRequirement :one
INSERT INTO hrms.staffing_requirements (
  tenant_id, name, requirement_date, start_date, end_date, day_of_week, branch_id, department_id,
  attendance_location_id, role_label, team_label, shift_template_id, required_count, min_count, max_count,
  priority, status, payroll_blocking, notes, metadata, created_by
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21
) RETURNING id, tenant_id, name, requirement_date, start_date, end_date, day_of_week, branch_id, department_id, attendance_location_id, role_label, team_label, shift_template_id, required_count, min_count, max_count, priority, status, payroll_blocking, notes, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateStaffingRequirementParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Name                 string      `db:"name" json:"name"`
	RequirementDate      pgtype.Date `db:"requirement_date" json:"requirement_date"`
	StartDate            pgtype.Date `db:"start_date" json:"start_date"`
	EndDate              pgtype.Date `db:"end_date" json:"end_date"`
	DayOfWeek            pgtype.Int4 `db:"day_of_week" json:"day_of_week"`
	BranchID             pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID         pgtype.UUID `db:"department_id" json:"department_id"`
	AttendanceLocationID pgtype.UUID `db:"attendance_location_id" json:"attendance_location_id"`
	RoleLabel            pgtype.Text `db:"role_label" json:"role_label"`
	TeamLabel            pgtype.Text `db:"team_label" json:"team_label"`
	ShiftTemplateID      pgtype.UUID `db:"shift_template_id" json:"shift_template_id"`
	RequiredCount        int32       `db:"required_count" json:"required_count"`
	MinCount             int32       `db:"min_count" json:"min_count"`
	MaxCount             pgtype.Int4 `db:"max_count" json:"max_count"`
	Priority             string      `db:"priority" json:"priority"`
	Status               string      `db:"status" json:"status"`
	PayrollBlocking      bool        `db:"payroll_blocking" json:"payroll_blocking"`
	Notes                pgtype.Text `db:"notes" json:"notes"`
	Metadata             []byte      `db:"metadata" json:"metadata"`
	CreatedBy            pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateStaffingRequirement(ctx context.Context, arg CreateStaffingRequirementParams) (HrmsStaffingRequirement, error) {
	row := q.db.QueryRow(ctx, createStaffingRequirement,
		arg.TenantID,
		arg.Name,
		arg.RequirementDate,
		arg.StartDate,
		arg.EndDate,
		arg.DayOfWeek,
		arg.BranchID,
		arg.DepartmentID,
		arg.AttendanceLocationID,
		arg.RoleLabel,
		arg.TeamLabel,
		arg.ShiftTemplateID,
		arg.RequiredCount,
		arg.MinCount,
		arg.MaxCount,
		arg.Priority,
		arg.Status,
		arg.PayrollBlocking,
		arg.Notes,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsStaffingRequirement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RequirementDate,
		&i.StartDate,
		&i.EndDate,
		&i.DayOfWeek,
		&i.BranchID,
		&i.DepartmentID,
		&i.AttendanceLocationID,
		&i.RoleLabel,
		&i.TeamLabel,
		&i.ShiftTemplateID,
		&i.RequiredCount,
		&i.MinCount,
		&i.MaxCount,
		&i.Priority,
		&i.Status,
		&i.PayrollBlocking,
		&i.Notes,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getShiftScheduleAssignment = `-- name: GetShiftScheduleAssignment :one
SELECT id, tenant_id, schedule_date, worker_profile_id, employee_user_id, shift_template_id, attendance_policy_id, attendance_location_id, attendance_roster_id, branch_id, department_id, start_time, end_time, break_minutes, work_mode, location_type, role_label, team_label, status, source, overtime_planned_minutes, has_conflict, conflict_reason, payroll_blocking, notes, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.shift_schedule_assignments
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
`

type GetShiftScheduleAssignmentParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetShiftScheduleAssignment(ctx context.Context, arg GetShiftScheduleAssignmentParams) (HrmsShiftScheduleAssignment, error) {
	row := q.db.QueryRow(ctx, getShiftScheduleAssignment, arg.TenantID, arg.ID)
	var i HrmsShiftScheduleAssignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScheduleDate,
		&i.WorkerProfileID,
		&i.EmployeeUserID,
		&i.ShiftTemplateID,
		&i.AttendancePolicyID,
		&i.AttendanceLocationID,
		&i.AttendanceRosterID,
		&i.BranchID,
		&i.DepartmentID,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.WorkMode,
		&i.LocationType,
		&i.RoleLabel,
		&i.TeamLabel,
		&i.Status,
		&i.Source,
		&i.OvertimePlannedMinutes,
		&i.HasConflict,
		&i.ConflictReason,
		&i.PayrollBlocking,
		&i.Notes,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getShiftScheduleSummary = `-- name: GetShiftScheduleSummary :many
WITH assignments AS (
  SELECT a.id, a.tenant_id, a.schedule_date, a.worker_profile_id, a.employee_user_id, a.shift_template_id, a.attendance_policy_id, a.attendance_location_id, a.attendance_roster_id, a.branch_id, a.department_id, a.start_time, a.end_time, a.break_minutes, a.work_mode, a.location_type, a.role_label, a.team_label, a.status, a.source, a.overtime_planned_minutes, a.has_conflict, a.conflict_reason, a.payroll_blocking, a.notes, a.metadata, a.inactive, a.created_at, a.created_by, a.updated_at, a.updated_by
  FROM hrms.shift_schedule_assignments a
  WHERE a.tenant_id=$1
    AND NOT a.inactive
    AND a.schedule_date BETWEEN $2 AND $3
),
swaps AS (
  SELECT sw.id, sw.tenant_id, sw.requester_assignment_id, sw.requester_worker_profile_id, sw.requester_user_id, sw.target_worker_profile_id, sw.target_user_id, sw.offered_assignment_id, sw.requested_date, sw.requested_shift_template_id, sw.reason, sw.status, sw.reviewed_by, sw.reviewed_at, sw.review_remarks, sw.payroll_blocking, sw.metadata, sw.inactive, sw.created_at, sw.created_by, sw.updated_at, sw.updated_by
  FROM hrms.shift_swap_requests sw
  WHERE sw.tenant_id=$1
    AND NOT sw.inactive
    AND sw.created_at::date BETWEEN $2 AND $3
),
requirements AS (
  SELECT r.id, r.tenant_id, r.name, r.requirement_date, r.start_date, r.end_date, r.day_of_week, r.branch_id, r.department_id, r.attendance_location_id, r.role_label, r.team_label, r.shift_template_id, r.required_count, r.min_count, r.max_count, r.priority, r.status, r.payroll_blocking, r.notes, r.metadata, r.inactive, r.created_at, r.created_by, r.updated_at, r.updated_by
  FROM hrms.staffing_requirements r
  WHERE r.tenant_id=$1
    AND NOT r.inactive
    AND r.status='active'
),
gap_rows AS (
  SELECT
    r.id,
    GREATEST(r.required_count - COALESCE(COUNT(a.id), 0)::int, 0) AS gap_count
  FROM requirements r
  LEFT JOIN assignments a ON a.status IN ('published','locked')
    AND (r.requirement_date IS NULL OR a.schedule_date = r.requirement_date)
    AND (r.start_date IS NULL OR a.schedule_date >= r.start_date)
    AND (r.end_date IS NULL OR a.schedule_date <= r.end_date)
    AND (r.day_of_week IS NULL OR EXTRACT(DOW FROM a.schedule_date)::int = r.day_of_week)
    AND (r.branch_id IS NULL OR a.branch_id = r.branch_id)
    AND (r.department_id IS NULL OR a.department_id = r.department_id)
    AND (r.attendance_location_id IS NULL OR a.attendance_location_id = r.attendance_location_id)
    AND (r.shift_template_id IS NULL OR a.shift_template_id = r.shift_template_id)
  GROUP BY r.id, r.required_count
)
SELECT 'assignments_total'::text AS metric, COUNT(*)::int AS metric_count FROM assignments
UNION ALL SELECT 'assignments_published', COUNT(*)::int FROM assignments WHERE status='published'
UNION ALL SELECT 'assignments_locked', COUNT(*)::int FROM assignments WHERE status='locked'
UNION ALL SELECT 'assignments_conflict', COUNT(*)::int FROM assignments WHERE has_conflict
UNION ALL SELECT 'payroll_blockers', COUNT(*)::int FROM assignments WHERE payroll_blocking
UNION ALL SELECT 'swap_requests_pending', COUNT(*)::int FROM swaps WHERE status='pending'
UNION ALL SELECT 'staffing_gap_positions', COUNT(*)::int FROM gap_rows WHERE gap_count > 0
UNION ALL SELECT 'staffing_gap_people', COALESCE(SUM(gap_count), 0)::int FROM gap_rows
`

type GetShiftScheduleSummaryParams struct {
	TenantID       uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ScheduleDate   pgtype.Date `db:"schedule_date" json:"schedule_date"`
	ScheduleDate_2 pgtype.Date `db:"schedule_date_2" json:"schedule_date_2"`
}

type GetShiftScheduleSummaryRow struct {
	Metric      string `db:"metric" json:"metric"`
	MetricCount int32  `db:"metric_count" json:"metric_count"`
}

func (q *Queries) GetShiftScheduleSummary(ctx context.Context, arg GetShiftScheduleSummaryParams) ([]GetShiftScheduleSummaryRow, error) {
	rows, err := q.db.Query(ctx, getShiftScheduleSummary, arg.TenantID, arg.ScheduleDate, arg.ScheduleDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShiftScheduleSummaryRow
	for rows.Next() {
		var i GetShiftScheduleSummaryRow
		if err := rows.Scan(&i.Metric, &i.MetricCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShiftSwapRequest = `-- name: GetShiftSwapRequest :one
SELECT id, tenant_id, requester_assignment_id, requester_worker_profile_id, requester_user_id, target_worker_profile_id, target_user_id, offered_assignment_id, requested_date, requested_shift_template_id, reason, status, reviewed_by, reviewed_at, review_remarks, payroll_blocking, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.shift_swap_requests
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
`

type GetShiftSwapRequestParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetShiftSwapRequest(ctx context.Context, arg GetShiftSwapRequestParams) (HrmsShiftSwapRequest, error) {
	row := q.db.QueryRow(ctx, getShiftSwapRequest, arg.TenantID, arg.ID)
	var i HrmsShiftSwapRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterAssignmentID,
		&i.RequesterWorkerProfileID,
		&i.RequesterUserID,
		&i.TargetWorkerProfileID,
		&i.TargetUserID,
		&i.OfferedAssignmentID,
		&i.RequestedDate,
		&i.RequestedShiftTemplateID,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewRemarks,
		&i.PayrollBlocking,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getShiftTemplate = `-- name: GetShiftTemplate :one
SELECT id, tenant_id, code, name, description, start_time, end_time, break_minutes, paid_minutes, work_mode, location_type, attendance_policy_id, attendance_location_id, allow_overtime, payroll_code, metadata, is_active, inactive, created_at, created_by, updated_at, updated_by FROM hrms.shift_templates
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
`

type GetShiftTemplateParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetShiftTemplate(ctx context.Context, arg GetShiftTemplateParams) (HrmsShiftTemplate, error) {
	row := q.db.QueryRow(ctx, getShiftTemplate, arg.TenantID, arg.ID)
	var i HrmsShiftTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.PaidMinutes,
		&i.WorkMode,
		&i.LocationType,
		&i.AttendancePolicyID,
		&i.AttendanceLocationID,
		&i.AllowOvertime,
		&i.PayrollCode,
		&i.Metadata,
		&i.IsActive,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getStaffingRequirement = `-- name: GetStaffingRequirement :one
SELECT id, tenant_id, name, requirement_date, start_date, end_date, day_of_week, branch_id, department_id, attendance_location_id, role_label, team_label, shift_template_id, required_count, min_count, max_count, priority, status, payroll_blocking, notes, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.staffing_requirements
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
`

type GetStaffingRequirementParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetStaffingRequirement(ctx context.Context, arg GetStaffingRequirementParams) (HrmsStaffingRequirement, error) {
	row := q.db.QueryRow(ctx, getStaffingRequirement, arg.TenantID, arg.ID)
	var i HrmsStaffingRequirement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RequirementDate,
		&i.StartDate,
		&i.EndDate,
		&i.DayOfWeek,
		&i.BranchID,
		&i.DepartmentID,
		&i.AttendanceLocationID,
		&i.RoleLabel,
		&i.TeamLabel,
		&i.ShiftTemplateID,
		&i.RequiredCount,
		&i.MinCount,
		&i.MaxCount,
		&i.Priority,
		&i.Status,
		&i.PayrollBlocking,
		&i.Notes,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listShiftAssignmentsForWorkerDate = `-- name: ListShiftAssignmentsForWorkerDate :many
SELECT id, tenant_id, schedule_date, worker_profile_id, employee_user_id, shift_template_id, attendance_policy_id, attendance_location_id, attendance_roster_id, branch_id, department_id, start_time, end_time, break_minutes, work_mode, location_type, role_label, team_label, status, source, overtime_planned_minutes, has_conflict, conflict_reason, payroll_blocking, notes, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.shift_schedule_assignments
WHERE tenant_id=$1
  AND NOT inactive
  AND schedule_date=$2
  AND status <> 'cancelled'
  AND (worker_profile_id = $3::uuid OR employee_user_id = $4::uuid)
ORDER BY start_time ASC
`

type ListShiftAssignmentsForWorkerDateParams struct {
	TenantID        uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ScheduleDate    pgtype.Date `db:"schedule_date" json:"schedule_date"`
	WorkerProfileID pgtype.UUID `db:"worker_profile_id" json:"worker_profile_id"`
	EmployeeUserID  pgtype.UUID `db:"employee_user_id" json:"employee_user_id"`
}

func (q *Queries) ListShiftAssignmentsForWorkerDate(ctx context.Context, arg ListShiftAssignmentsForWorkerDateParams) ([]HrmsShiftScheduleAssignment, error) {
	rows, err := q.db.Query(ctx, listShiftAssignmentsForWorkerDate,
		arg.TenantID,
		arg.ScheduleDate,
		arg.WorkerProfileID,
		arg.EmployeeUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsShiftScheduleAssignment
	for rows.Next() {
		var i HrmsShiftScheduleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ScheduleDate,
			&i.WorkerProfileID,
			&i.EmployeeUserID,
			&i.ShiftTemplateID,
			&i.AttendancePolicyID,
			&i.AttendanceLocationID,
			&i.AttendanceRosterID,
			&i.BranchID,
			&i.DepartmentID,
			&i.StartTime,
			&i.EndTime,
			&i.BreakMinutes,
			&i.WorkMode,
			&i.LocationType,
			&i.RoleLabel,
			&i.TeamLabel,
			&i.Status,
			&i.Source,
			&i.OvertimePlannedMinutes,
			&i.HasConflict,
			&i.ConflictReason,
			&i.PayrollBlocking,
			&i.Notes,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftScheduleAssignments = `-- name: ListShiftScheduleAssignments :many
SELECT id, tenant_id, schedule_date, worker_profile_id, employee_user_id, shift_template_id, attendance_policy_id, attendance_location_id, attendance_roster_id, branch_id, department_id, start_time, end_time, break_minutes, work_mode, location_type, role_label, team_label, status, source, overtime_planned_minutes, has_conflict, conflict_reason, payroll_blocking, notes, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.shift_schedule_assignments
WHERE tenant_id=$1
  AND NOT inactive
  AND schedule_date BETWEEN $2 AND $3
  AND ($6::text IS NULL OR status = $6::text)
  AND ($7::uuid IS NULL OR worker_profile_id = $7::uuid)
  AND ($8::uuid IS NULL OR employee_user_id = $8::uuid)
  AND ($9::uuid IS NULL OR branch_id = $9::uuid)
  AND ($10::uuid IS NULL OR department_id = $10::uuid)
  AND ($11::uuid IS NULL OR attendance_location_id = $11::uuid)
ORDER BY schedule_date ASC, start_time ASC, created_at ASC
LIMIT $4 OFFSET $5
`

type ListShiftScheduleAssignmentsParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ScheduleDate         pgtype.Date `db:"schedule_date" json:"schedule_date"`
	ScheduleDate_2       pgtype.Date `db:"schedule_date_2" json:"schedule_date_2"`
	Limit                int32       `db:"limit" json:"limit"`
	Offset               int32       `db:"offset" json:"offset"`
	Status               pgtype.Text `db:"status" json:"status"`
	WorkerProfileID      pgtype.UUID `db:"worker_profile_id" json:"worker_profile_id"`
	EmployeeUserID       pgtype.UUID `db:"employee_user_id" json:"employee_user_id"`
	BranchID             pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID         pgtype.UUID `db:"department_id" json:"department_id"`
	AttendanceLocationID pgtype.UUID `db:"attendance_location_id" json:"attendance_location_id"`
}

func (q *Queries) ListShiftScheduleAssignments(ctx context.Context, arg ListShiftScheduleAssignmentsParams) ([]HrmsShiftScheduleAssignment, error) {
	rows, err := q.db.Query(ctx, listShiftScheduleAssignments,
		arg.TenantID,
		arg.ScheduleDate,
		arg.ScheduleDate_2,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.WorkerProfileID,
		arg.EmployeeUserID,
		arg.BranchID,
		arg.DepartmentID,
		arg.AttendanceLocationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsShiftScheduleAssignment
	for rows.Next() {
		var i HrmsShiftScheduleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ScheduleDate,
			&i.WorkerProfileID,
			&i.EmployeeUserID,
			&i.ShiftTemplateID,
			&i.AttendancePolicyID,
			&i.AttendanceLocationID,
			&i.AttendanceRosterID,
			&i.BranchID,
			&i.DepartmentID,
			&i.StartTime,
			&i.EndTime,
			&i.BreakMinutes,
			&i.WorkMode,
			&i.LocationType,
			&i.RoleLabel,
			&i.TeamLabel,
			&i.Status,
			&i.Source,
			&i.OvertimePlannedMinutes,
			&i.HasConflict,
			&i.ConflictReason,
			&i.PayrollBlocking,
			&i.Notes,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftScheduleEvents = `-- name: ListShiftScheduleEvents :many
SELECT id, tenant_id, source_type, source_id, action, from_status, to_status, actor_user_id, remarks, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.shift_schedule_events
WHERE tenant_id=$1
  AND NOT inactive
  AND ($4::text IS NULL OR source_type = $4::text)
  AND ($5::uuid IS NULL OR source_id = $5::uuid)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListShiftScheduleEventsParams struct {
	TenantID   uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
	SourceType pgtype.Text `db:"source_type" json:"source_type"`
	SourceID   pgtype.UUID `db:"source_id" json:"source_id"`
}

func (q *Queries) ListShiftScheduleEvents(ctx context.Context, arg ListShiftScheduleEventsParams) ([]HrmsShiftScheduleEvent, error) {
	rows, err := q.db.Query(ctx, listShiftScheduleEvents,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.SourceType,
		arg.SourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsShiftScheduleEvent
	for rows.Next() {
		var i HrmsShiftScheduleEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceType,
			&i.SourceID,
			&i.Action,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorUserID,
			&i.Remarks,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftStaffingGaps = `-- name: ListShiftStaffingGaps :many
WITH assignments AS (
  SELECT a.id, a.tenant_id, a.schedule_date, a.worker_profile_id, a.employee_user_id, a.shift_template_id, a.attendance_policy_id, a.attendance_location_id, a.attendance_roster_id, a.branch_id, a.department_id, a.start_time, a.end_time, a.break_minutes, a.work_mode, a.location_type, a.role_label, a.team_label, a.status, a.source, a.overtime_planned_minutes, a.has_conflict, a.conflict_reason, a.payroll_blocking, a.notes, a.metadata, a.inactive, a.created_at, a.created_by, a.updated_at, a.updated_by
  FROM hrms.shift_schedule_assignments a
  WHERE a.tenant_id=$1
    AND NOT a.inactive
    AND a.schedule_date BETWEEN $2 AND $3
    AND a.status IN ('published','locked')
)
SELECT
  r.id AS requirement_id,
  r.name AS requirement_name,
  r.branch_id,
  r.department_id,
  r.attendance_location_id,
  r.shift_template_id,
  r.required_count,
  COALESCE(COUNT(a.id), 0)::int AS assigned_count,
  GREATEST(r.required_count - COALESCE(COUNT(a.id), 0)::int, 0)::int AS gap_count,
  r.priority,
  r.payroll_blocking
FROM hrms.staffing_requirements r
LEFT JOIN assignments a ON (r.requirement_date IS NULL OR a.schedule_date = r.requirement_date)
  AND (r.start_date IS NULL OR a.schedule_date >= r.start_date)
  AND (r.end_date IS NULL OR a.schedule_date <= r.end_date)
  AND (r.day_of_week IS NULL OR EXTRACT(DOW FROM a.schedule_date)::int = r.day_of_week)
  AND (r.branch_id IS NULL OR a.branch_id = r.branch_id)
  AND (r.department_id IS NULL OR a.department_id = r.department_id)
  AND (r.attendance_location_id IS NULL OR a.attendance_location_id = r.attendance_location_id)
  AND (r.shift_template_id IS NULL OR a.shift_template_id = r.shift_template_id)
WHERE r.tenant_id=$1
  AND NOT r.inactive
  AND r.status='active'
GROUP BY r.id, r.name, r.branch_id, r.department_id, r.attendance_location_id, r.shift_template_id, r.required_count, r.priority, r.payroll_blocking
HAVING GREATEST(r.required_count - COALESCE(COUNT(a.id), 0)::int, 0) > 0
ORDER BY r.payroll_blocking DESC, r.priority DESC, gap_count DESC, r.name ASC
`

type ListShiftStaffingGapsParams struct {
	TenantID       uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ScheduleDate   pgtype.Date `db:"schedule_date" json:"schedule_date"`
	ScheduleDate_2 pgtype.Date `db:"schedule_date_2" json:"schedule_date_2"`
}

type ListShiftStaffingGapsRow struct {
	RequirementID        uuid.UUID   `db:"requirement_id" json:"requirement_id"`
	RequirementName      string      `db:"requirement_name" json:"requirement_name"`
	BranchID             pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID         pgtype.UUID `db:"department_id" json:"department_id"`
	AttendanceLocationID pgtype.UUID `db:"attendance_location_id" json:"attendance_location_id"`
	ShiftTemplateID      pgtype.UUID `db:"shift_template_id" json:"shift_template_id"`
	RequiredCount        int32       `db:"required_count" json:"required_count"`
	AssignedCount        int32       `db:"assigned_count" json:"assigned_count"`
	GapCount             int32       `db:"gap_count" json:"gap_count"`
	Priority             string      `db:"priority" json:"priority"`
	PayrollBlocking      bool        `db:"payroll_blocking" json:"payroll_blocking"`
}

func (q *Queries) ListShiftStaffingGaps(ctx context.Context, arg ListShiftStaffingGapsParams) ([]ListShiftStaffingGapsRow, error) {
	rows, err := q.db.Query(ctx, listShiftStaffingGaps, arg.TenantID, arg.ScheduleDate, arg.ScheduleDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShiftStaffingGapsRow
	for rows.Next() {
		var i ListShiftStaffingGapsRow
		if err := rows.Scan(
			&i.RequirementID,
			&i.RequirementName,
			&i.BranchID,
			&i.DepartmentID,
			&i.AttendanceLocationID,
			&i.ShiftTemplateID,
			&i.RequiredCount,
			&i.AssignedCount,
			&i.GapCount,
			&i.Priority,
			&i.PayrollBlocking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftSwapRequests = `-- name: ListShiftSwapRequests :many
SELECT id, tenant_id, requester_assignment_id, requester_worker_profile_id, requester_user_id, target_worker_profile_id, target_user_id, offered_assignment_id, requested_date, requested_shift_template_id, reason, status, reviewed_by, reviewed_at, review_remarks, payroll_blocking, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.shift_swap_requests
WHERE tenant_id=$1
  AND NOT inactive
  AND ($4::text IS NULL OR status = $4::text)
  AND ($5::uuid IS NULL OR requester_user_id = $5::uuid)
  AND ($6::uuid IS NULL OR target_user_id = $6::uuid)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListShiftSwapRequestsParams struct {
	TenantID        uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit           int32       `db:"limit" json:"limit"`
	Offset          int32       `db:"offset" json:"offset"`
	Status          pgtype.Text `db:"status" json:"status"`
	RequesterUserID pgtype.UUID `db:"requester_user_id" json:"requester_user_id"`
	TargetUserID    pgtype.UUID `db:"target_user_id" json:"target_user_id"`
}

func (q *Queries) ListShiftSwapRequests(ctx context.Context, arg ListShiftSwapRequestsParams) ([]HrmsShiftSwapRequest, error) {
	rows, err := q.db.Query(ctx, listShiftSwapRequests,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.RequesterUserID,
		arg.TargetUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsShiftSwapRequest
	for rows.Next() {
		var i HrmsShiftSwapRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RequesterAssignmentID,
			&i.RequesterWorkerProfileID,
			&i.RequesterUserID,
			&i.TargetWorkerProfileID,
			&i.TargetUserID,
			&i.OfferedAssignmentID,
			&i.RequestedDate,
			&i.RequestedShiftTemplateID,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewRemarks,
			&i.PayrollBlocking,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftTemplates = `-- name: ListShiftTemplates :many
SELECT id, tenant_id, code, name, description, start_time, end_time, break_minutes, paid_minutes, work_mode, location_type, attendance_policy_id, attendance_location_id, allow_overtime, payroll_code, metadata, is_active, inactive, created_at, created_by, updated_at, updated_by FROM hrms.shift_templates
WHERE tenant_id=$1
  AND NOT inactive
  AND ($4::boolean IS NULL OR is_active = $4::boolean)
  AND ($5::text IS NULL OR code ILIKE '%' || $5::text || '%' OR name ILIKE '%' || $5::text || '%')
ORDER BY name ASC, code ASC
LIMIT $2 OFFSET $3
`

type ListShiftTemplatesParams struct {
	TenantID   uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
	ActiveOnly pgtype.Bool `db:"active_only" json:"active_only"`
	Search     pgtype.Text `db:"search" json:"search"`
}

func (q *Queries) ListShiftTemplates(ctx context.Context, arg ListShiftTemplatesParams) ([]HrmsShiftTemplate, error) {
	rows, err := q.db.Query(ctx, listShiftTemplates,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.ActiveOnly,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsShiftTemplate
	for rows.Next() {
		var i HrmsShiftTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.BreakMinutes,
			&i.PaidMinutes,
			&i.WorkMode,
			&i.LocationType,
			&i.AttendancePolicyID,
			&i.AttendanceLocationID,
			&i.AllowOvertime,
			&i.PayrollCode,
			&i.Metadata,
			&i.IsActive,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffingRequirements = `-- name: ListStaffingRequirements :many
SELECT id, tenant_id, name, requirement_date, start_date, end_date, day_of_week, branch_id, department_id, attendance_location_id, role_label, team_label, shift_template_id, required_count, min_count, max_count, priority, status, payroll_blocking, notes, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.staffing_requirements
WHERE tenant_id=$1
  AND NOT inactive
  AND ($4::text IS NULL OR status = $4::text)
  AND (
    $5::date IS NULL
    OR requirement_date IS NULL
    OR requirement_date BETWEEN $5::date AND COALESCE($6::date, $5::date)
    OR start_date IS NULL
    OR COALESCE(end_date, start_date) >= $5::date
  )
ORDER BY COALESCE(requirement_date, start_date, created_at::date) DESC, name ASC
LIMIT $2 OFFSET $3
`

type ListStaffingRequirementsParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
	Status    pgtype.Text `db:"status" json:"status"`
	StartDate pgtype.Date `db:"start_date" json:"start_date"`
	EndDate   pgtype.Date `db:"end_date" json:"end_date"`
}

func (q *Queries) ListStaffingRequirements(ctx context.Context, arg ListStaffingRequirementsParams) ([]HrmsStaffingRequirement, error) {
	rows, err := q.db.Query(ctx, listStaffingRequirements,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsStaffingRequirement
	for rows.Next() {
		var i HrmsStaffingRequirement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.RequirementDate,
			&i.StartDate,
			&i.EndDate,
			&i.DayOfWeek,
			&i.BranchID,
			&i.DepartmentID,
			&i.AttendanceLocationID,
			&i.RoleLabel,
			&i.TeamLabel,
			&i.ShiftTemplateID,
			&i.RequiredCount,
			&i.MinCount,
			&i.MaxCount,
			&i.Priority,
			&i.Status,
			&i.PayrollBlocking,
			&i.Notes,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteShiftScheduleAssignment = `-- name: SoftDeleteShiftScheduleAssignment :exec
UPDATE hrms.shift_schedule_assignments
SET inactive=TRUE, updated_by=$3
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
`

type SoftDeleteShiftScheduleAssignmentParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteShiftScheduleAssignment(ctx context.Context, arg SoftDeleteShiftScheduleAssignmentParams) error {
	_, err := q.db.Exec(ctx, softDeleteShiftScheduleAssignment, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteShiftTemplate = `-- name: SoftDeleteShiftTemplate :exec
UPDATE hrms.shift_templates
SET inactive=TRUE, is_active=FALSE, updated_by=$3
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
`

type SoftDeleteShiftTemplateParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteShiftTemplate(ctx context.Context, arg SoftDeleteShiftTemplateParams) error {
	_, err := q.db.Exec(ctx, softDeleteShiftTemplate, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteStaffingRequirement = `-- name: SoftDeleteStaffingRequirement :exec
UPDATE hrms.staffing_requirements
SET inactive=TRUE, status='archived', updated_by=$3
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
`

type SoftDeleteStaffingRequirementParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID        uuid.UUID   `db:"id" json:"id"`
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SoftDeleteStaffingRequirement(ctx context.Context, arg SoftDeleteStaffingRequirementParams) error {
	_, err := q.db.Exec(ctx, softDeleteStaffingRequirement, arg.TenantID, arg.ID, arg.UpdatedBy)
	return err
}

const updateShiftScheduleAssignment = `-- name: UpdateShiftScheduleAssignment :one
UPDATE hrms.shift_schedule_assignments
SET schedule_date=$3, worker_profile_id=$4, employee_user_id=$5, shift_template_id=$6, attendance_policy_id=$7,
    attendance_location_id=$8, attendance_roster_id=$9, branch_id=$10, department_id=$11, start_time=$12,
    end_time=$13, break_minutes=$14, work_mode=$15, location_type=$16, role_label=$17, team_label=$18,
    status=$19, source=$20, overtime_planned_minutes=$21, has_conflict=$22, conflict_reason=$23,
    payroll_blocking=$24, notes=$25, metadata=$26, updated_by=$27
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
RETURNING id, tenant_id, schedule_date, worker_profile_id, employee_user_id, shift_template_id, attendance_policy_id, attendance_location_id, attendance_roster_id, branch_id, department_id, start_time, end_time, break_minutes, work_mode, location_type, role_label, team_label, status, source, overtime_planned_minutes, has_conflict, conflict_reason, payroll_blocking, notes, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateShiftScheduleAssignmentParams struct {
	TenantID               uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID                     uuid.UUID   `db:"id" json:"id"`
	ScheduleDate           pgtype.Date `db:"schedule_date" json:"schedule_date"`
	WorkerProfileID        pgtype.UUID `db:"worker_profile_id" json:"worker_profile_id"`
	EmployeeUserID         pgtype.UUID `db:"employee_user_id" json:"employee_user_id"`
	ShiftTemplateID        pgtype.UUID `db:"shift_template_id" json:"shift_template_id"`
	AttendancePolicyID     pgtype.UUID `db:"attendance_policy_id" json:"attendance_policy_id"`
	AttendanceLocationID   pgtype.UUID `db:"attendance_location_id" json:"attendance_location_id"`
	AttendanceRosterID     pgtype.UUID `db:"attendance_roster_id" json:"attendance_roster_id"`
	BranchID               pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID           pgtype.UUID `db:"department_id" json:"department_id"`
	StartTime              pgtype.Time `db:"start_time" json:"start_time"`
	EndTime                pgtype.Time `db:"end_time" json:"end_time"`
	BreakMinutes           int32       `db:"break_minutes" json:"break_minutes"`
	WorkMode               string      `db:"work_mode" json:"work_mode"`
	LocationType           string      `db:"location_type" json:"location_type"`
	RoleLabel              pgtype.Text `db:"role_label" json:"role_label"`
	TeamLabel              pgtype.Text `db:"team_label" json:"team_label"`
	Status                 string      `db:"status" json:"status"`
	Source                 string      `db:"source" json:"source"`
	OvertimePlannedMinutes int32       `db:"overtime_planned_minutes" json:"overtime_planned_minutes"`
	HasConflict            bool        `db:"has_conflict" json:"has_conflict"`
	ConflictReason         pgtype.Text `db:"conflict_reason" json:"conflict_reason"`
	PayrollBlocking        bool        `db:"payroll_blocking" json:"payroll_blocking"`
	Notes                  pgtype.Text `db:"notes" json:"notes"`
	Metadata               []byte      `db:"metadata" json:"metadata"`
	UpdatedBy              pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateShiftScheduleAssignment(ctx context.Context, arg UpdateShiftScheduleAssignmentParams) (HrmsShiftScheduleAssignment, error) {
	row := q.db.QueryRow(ctx, updateShiftScheduleAssignment,
		arg.TenantID,
		arg.ID,
		arg.ScheduleDate,
		arg.WorkerProfileID,
		arg.EmployeeUserID,
		arg.ShiftTemplateID,
		arg.AttendancePolicyID,
		arg.AttendanceLocationID,
		arg.AttendanceRosterID,
		arg.BranchID,
		arg.DepartmentID,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMinutes,
		arg.WorkMode,
		arg.LocationType,
		arg.RoleLabel,
		arg.TeamLabel,
		arg.Status,
		arg.Source,
		arg.OvertimePlannedMinutes,
		arg.HasConflict,
		arg.ConflictReason,
		arg.PayrollBlocking,
		arg.Notes,
		arg.Metadata,
		arg.UpdatedBy,
	)
	var i HrmsShiftScheduleAssignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScheduleDate,
		&i.WorkerProfileID,
		&i.EmployeeUserID,
		&i.ShiftTemplateID,
		&i.AttendancePolicyID,
		&i.AttendanceLocationID,
		&i.AttendanceRosterID,
		&i.BranchID,
		&i.DepartmentID,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.WorkMode,
		&i.LocationType,
		&i.RoleLabel,
		&i.TeamLabel,
		&i.Status,
		&i.Source,
		&i.OvertimePlannedMinutes,
		&i.HasConflict,
		&i.ConflictReason,
		&i.PayrollBlocking,
		&i.Notes,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateShiftScheduleAssignmentStatus = `-- name: UpdateShiftScheduleAssignmentStatus :one
UPDATE hrms.shift_schedule_assignments
SET status=$3, has_conflict=$4, conflict_reason=$5, payroll_blocking=$6, updated_by=$7
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
RETURNING id, tenant_id, schedule_date, worker_profile_id, employee_user_id, shift_template_id, attendance_policy_id, attendance_location_id, attendance_roster_id, branch_id, department_id, start_time, end_time, break_minutes, work_mode, location_type, role_label, team_label, status, source, overtime_planned_minutes, has_conflict, conflict_reason, payroll_blocking, notes, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateShiftScheduleAssignmentStatusParams struct {
	TenantID        uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID              uuid.UUID   `db:"id" json:"id"`
	Status          string      `db:"status" json:"status"`
	HasConflict     bool        `db:"has_conflict" json:"has_conflict"`
	ConflictReason  pgtype.Text `db:"conflict_reason" json:"conflict_reason"`
	PayrollBlocking bool        `db:"payroll_blocking" json:"payroll_blocking"`
	UpdatedBy       pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateShiftScheduleAssignmentStatus(ctx context.Context, arg UpdateShiftScheduleAssignmentStatusParams) (HrmsShiftScheduleAssignment, error) {
	row := q.db.QueryRow(ctx, updateShiftScheduleAssignmentStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.HasConflict,
		arg.ConflictReason,
		arg.PayrollBlocking,
		arg.UpdatedBy,
	)
	var i HrmsShiftScheduleAssignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScheduleDate,
		&i.WorkerProfileID,
		&i.EmployeeUserID,
		&i.ShiftTemplateID,
		&i.AttendancePolicyID,
		&i.AttendanceLocationID,
		&i.AttendanceRosterID,
		&i.BranchID,
		&i.DepartmentID,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.WorkMode,
		&i.LocationType,
		&i.RoleLabel,
		&i.TeamLabel,
		&i.Status,
		&i.Source,
		&i.OvertimePlannedMinutes,
		&i.HasConflict,
		&i.ConflictReason,
		&i.PayrollBlocking,
		&i.Notes,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateShiftSwapRequestReview = `-- name: UpdateShiftSwapRequestReview :one
UPDATE hrms.shift_swap_requests
SET status=$3, reviewed_by=$4, reviewed_at=now(), review_remarks=$5, payroll_blocking=$6, updated_by=$4
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
RETURNING id, tenant_id, requester_assignment_id, requester_worker_profile_id, requester_user_id, target_worker_profile_id, target_user_id, offered_assignment_id, requested_date, requested_shift_template_id, reason, status, reviewed_by, reviewed_at, review_remarks, payroll_blocking, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateShiftSwapRequestReviewParams struct {
	TenantID        uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID              uuid.UUID   `db:"id" json:"id"`
	Status          string      `db:"status" json:"status"`
	ReviewedBy      pgtype.UUID `db:"reviewed_by" json:"reviewed_by"`
	ReviewRemarks   pgtype.Text `db:"review_remarks" json:"review_remarks"`
	PayrollBlocking bool        `db:"payroll_blocking" json:"payroll_blocking"`
}

func (q *Queries) UpdateShiftSwapRequestReview(ctx context.Context, arg UpdateShiftSwapRequestReviewParams) (HrmsShiftSwapRequest, error) {
	row := q.db.QueryRow(ctx, updateShiftSwapRequestReview,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewRemarks,
		arg.PayrollBlocking,
	)
	var i HrmsShiftSwapRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterAssignmentID,
		&i.RequesterWorkerProfileID,
		&i.RequesterUserID,
		&i.TargetWorkerProfileID,
		&i.TargetUserID,
		&i.OfferedAssignmentID,
		&i.RequestedDate,
		&i.RequestedShiftTemplateID,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewRemarks,
		&i.PayrollBlocking,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateShiftTemplate = `-- name: UpdateShiftTemplate :one
UPDATE hrms.shift_templates
SET code=$3, name=$4, description=$5, start_time=$6, end_time=$7, break_minutes=$8, paid_minutes=$9,
    work_mode=$10, location_type=$11, attendance_policy_id=$12, attendance_location_id=$13,
    allow_overtime=$14, payroll_code=$15, metadata=$16, is_active=$17, updated_by=$18
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
RETURNING id, tenant_id, code, name, description, start_time, end_time, break_minutes, paid_minutes, work_mode, location_type, attendance_policy_id, attendance_location_id, allow_overtime, payroll_code, metadata, is_active, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateShiftTemplateParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID                   uuid.UUID   `db:"id" json:"id"`
	Code                 string      `db:"code" json:"code"`
	Name                 string      `db:"name" json:"name"`
	Description          pgtype.Text `db:"description" json:"description"`
	StartTime            pgtype.Time `db:"start_time" json:"start_time"`
	EndTime              pgtype.Time `db:"end_time" json:"end_time"`
	BreakMinutes         int32       `db:"break_minutes" json:"break_minutes"`
	PaidMinutes          int32       `db:"paid_minutes" json:"paid_minutes"`
	WorkMode             string      `db:"work_mode" json:"work_mode"`
	LocationType         string      `db:"location_type" json:"location_type"`
	AttendancePolicyID   pgtype.UUID `db:"attendance_policy_id" json:"attendance_policy_id"`
	AttendanceLocationID pgtype.UUID `db:"attendance_location_id" json:"attendance_location_id"`
	AllowOvertime        bool        `db:"allow_overtime" json:"allow_overtime"`
	PayrollCode          pgtype.Text `db:"payroll_code" json:"payroll_code"`
	Metadata             []byte      `db:"metadata" json:"metadata"`
	IsActive             bool        `db:"is_active" json:"is_active"`
	UpdatedBy            pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateShiftTemplate(ctx context.Context, arg UpdateShiftTemplateParams) (HrmsShiftTemplate, error) {
	row := q.db.QueryRow(ctx, updateShiftTemplate,
		arg.TenantID,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMinutes,
		arg.PaidMinutes,
		arg.WorkMode,
		arg.LocationType,
		arg.AttendancePolicyID,
		arg.AttendanceLocationID,
		arg.AllowOvertime,
		arg.PayrollCode,
		arg.Metadata,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i HrmsShiftTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.PaidMinutes,
		&i.WorkMode,
		&i.LocationType,
		&i.AttendancePolicyID,
		&i.AttendanceLocationID,
		&i.AllowOvertime,
		&i.PayrollCode,
		&i.Metadata,
		&i.IsActive,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateStaffingRequirement = `-- name: UpdateStaffingRequirement :one
UPDATE hrms.staffing_requirements
SET name=$3, requirement_date=$4, start_date=$5, end_date=$6, day_of_week=$7, branch_id=$8,
    department_id=$9, attendance_location_id=$10, role_label=$11, team_label=$12, shift_template_id=$13,
    required_count=$14, min_count=$15, max_count=$16, priority=$17, status=$18, payroll_blocking=$19,
    notes=$20, metadata=$21, updated_by=$22
WHERE tenant_id=$1 AND id=$2 AND NOT inactive
RETURNING id, tenant_id, name, requirement_date, start_date, end_date, day_of_week, branch_id, department_id, attendance_location_id, role_label, team_label, shift_template_id, required_count, min_count, max_count, priority, status, payroll_blocking, notes, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateStaffingRequirementParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID                   uuid.UUID   `db:"id" json:"id"`
	Name                 string      `db:"name" json:"name"`
	RequirementDate      pgtype.Date `db:"requirement_date" json:"requirement_date"`
	StartDate            pgtype.Date `db:"start_date" json:"start_date"`
	EndDate              pgtype.Date `db:"end_date" json:"end_date"`
	DayOfWeek            pgtype.Int4 `db:"day_of_week" json:"day_of_week"`
	BranchID             pgtype.UUID `db:"branch_id" json:"branch_id"`
	DepartmentID         pgtype.UUID `db:"department_id" json:"department_id"`
	AttendanceLocationID pgtype.UUID `db:"attendance_location_id" json:"attendance_location_id"`
	RoleLabel            pgtype.Text `db:"role_label" json:"role_label"`
	TeamLabel            pgtype.Text `db:"team_label" json:"team_label"`
	ShiftTemplateID      pgtype.UUID `db:"shift_template_id" json:"shift_template_id"`
	RequiredCount        int32       `db:"required_count" json:"required_count"`
	MinCount             int32       `db:"min_count" json:"min_count"`
	MaxCount             pgtype.Int4 `db:"max_count" json:"max_count"`
	Priority             string      `db:"priority" json:"priority"`
	Status               string      `db:"status" json:"status"`
	PayrollBlocking      bool        `db:"payroll_blocking" json:"payroll_blocking"`
	Notes                pgtype.Text `db:"notes" json:"notes"`
	Metadata             []byte      `db:"metadata" json:"metadata"`
	UpdatedBy            pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateStaffingRequirement(ctx context.Context, arg UpdateStaffingRequirementParams) (HrmsStaffingRequirement, error) {
	row := q.db.QueryRow(ctx, updateStaffingRequirement,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.RequirementDate,
		arg.StartDate,
		arg.EndDate,
		arg.DayOfWeek,
		arg.BranchID,
		arg.DepartmentID,
		arg.AttendanceLocationID,
		arg.RoleLabel,
		arg.TeamLabel,
		arg.ShiftTemplateID,
		arg.RequiredCount,
		arg.MinCount,
		arg.MaxCount,
		arg.Priority,
		arg.Status,
		arg.PayrollBlocking,
		arg.Notes,
		arg.Metadata,
		arg.UpdatedBy,
	)
	var i HrmsStaffingRequirement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RequirementDate,
		&i.StartDate,
		&i.EndDate,
		&i.DayOfWeek,
		&i.BranchID,
		&i.DepartmentID,
		&i.AttendanceLocationID,
		&i.RoleLabel,
		&i.TeamLabel,
		&i.ShiftTemplateID,
		&i.RequiredCount,
		&i.MinCount,
		&i.MaxCount,
		&i.Priority,
		&i.Status,
		&i.PayrollBlocking,
		&i.Notes,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
