// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_profiles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantProfile = `-- name: GetTenantProfile :one
SELECT tenant_id, subdomain, mobile_activation_code, display_name, logo_object_key, created_at, updated_at FROM hrms.tenant_profiles
WHERE tenant_id = $1
`

func (q *Queries) GetTenantProfile(ctx context.Context, tenantID uuid.UUID) (HrmsTenantProfile, error) {
	row := q.db.QueryRow(ctx, getTenantProfile, tenantID)
	var i HrmsTenantProfile
	err := row.Scan(
		&i.TenantID,
		&i.Subdomain,
		&i.MobileActivationCode,
		&i.DisplayName,
		&i.LogoObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantProfileByActivationCode = `-- name: GetTenantProfileByActivationCode :one
SELECT tenant_id, subdomain, mobile_activation_code, display_name, logo_object_key, created_at, updated_at FROM hrms.tenant_profiles
WHERE mobile_activation_code = $1
`

func (q *Queries) GetTenantProfileByActivationCode(ctx context.Context, mobileActivationCode string) (HrmsTenantProfile, error) {
	row := q.db.QueryRow(ctx, getTenantProfileByActivationCode, mobileActivationCode)
	var i HrmsTenantProfile
	err := row.Scan(
		&i.TenantID,
		&i.Subdomain,
		&i.MobileActivationCode,
		&i.DisplayName,
		&i.LogoObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantProfileBySubdomain = `-- name: GetTenantProfileBySubdomain :one
SELECT tenant_id, subdomain, mobile_activation_code, display_name, logo_object_key, created_at, updated_at FROM hrms.tenant_profiles
WHERE subdomain = $1
`

func (q *Queries) GetTenantProfileBySubdomain(ctx context.Context, subdomain string) (HrmsTenantProfile, error) {
	row := q.db.QueryRow(ctx, getTenantProfileBySubdomain, subdomain)
	var i HrmsTenantProfile
	err := row.Scan(
		&i.TenantID,
		&i.Subdomain,
		&i.MobileActivationCode,
		&i.DisplayName,
		&i.LogoObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantProfile = `-- name: UpsertTenantProfile :one
INSERT INTO hrms.tenant_profiles (
    tenant_id, subdomain, mobile_activation_code, display_name, logo_object_key
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id) DO UPDATE SET
    subdomain = EXCLUDED.subdomain,
    mobile_activation_code = EXCLUDED.mobile_activation_code,
    display_name = EXCLUDED.display_name,
    logo_object_key = EXCLUDED.logo_object_key
RETURNING tenant_id, subdomain, mobile_activation_code, display_name, logo_object_key, created_at, updated_at
`

type UpsertTenantProfileParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Subdomain            string      `db:"subdomain" json:"subdomain"`
	MobileActivationCode string      `db:"mobile_activation_code" json:"mobile_activation_code"`
	DisplayName          pgtype.Text `db:"display_name" json:"display_name"`
	LogoObjectKey        pgtype.Text `db:"logo_object_key" json:"logo_object_key"`
}

func (q *Queries) UpsertTenantProfile(ctx context.Context, arg UpsertTenantProfileParams) (HrmsTenantProfile, error) {
	row := q.db.QueryRow(ctx, upsertTenantProfile,
		arg.TenantID,
		arg.Subdomain,
		arg.MobileActivationCode,
		arg.DisplayName,
		arg.LogoObjectKey,
	)
	var i HrmsTenantProfile
	err := row.Scan(
		&i.TenantID,
		&i.Subdomain,
		&i.MobileActivationCode,
		&i.DisplayName,
		&i.LogoObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
