// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_operation_governance.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenantOperationEvent = `-- name: CreateTenantOperationEvent :one
INSERT INTO hrms.tenant_operation_events (
    request_id, action, from_status, to_status, actor_user_id, remarks, metadata, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $5, $5
)
RETURNING id, request_id, action, from_status, to_status, actor_user_id, remarks, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateTenantOperationEventParams struct {
	RequestID  uuid.UUID   `db:"request_id" json:"request_id"`
	Action     string      `db:"action" json:"action"`
	FromStatus pgtype.Text `db:"from_status" json:"from_status"`
	ToStatus   pgtype.Text `db:"to_status" json:"to_status"`
	ActorID    pgtype.UUID `db:"actor_id" json:"actor_id"`
	Remarks    pgtype.Text `db:"remarks" json:"remarks"`
	Metadata   []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateTenantOperationEvent(ctx context.Context, arg CreateTenantOperationEventParams) (HrmsTenantOperationEvent, error) {
	row := q.db.QueryRow(ctx, createTenantOperationEvent,
		arg.RequestID,
		arg.Action,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorID,
		arg.Remarks,
		arg.Metadata,
	)
	var i HrmsTenantOperationEvent
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.ActorUserID,
		&i.Remarks,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createTenantOperationRequest = `-- name: CreateTenantOperationRequest :one
INSERT INTO hrms.tenant_operation_requests (
    operation_number, operation_type, title, target_tenant_id, target_tenant_name, target_tenant_code,
    status, risk_level, reason, requested_by, approval_required, backup_required, backup_confirmed,
    retention_until, request_payload, validation_results, rollback_metadata, metadata, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $10, $10
)
RETURNING id, operation_number, operation_type, title, target_tenant_id, target_tenant_name, target_tenant_code, status, risk_level, reason, requested_by, approved_by, approved_at, completed_by, completed_at, approval_required, backup_required, backup_confirmed, retention_until, request_payload, validation_results, rollback_metadata, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateTenantOperationRequestParams struct {
	OperationNumber   string             `db:"operation_number" json:"operation_number"`
	OperationType     string             `db:"operation_type" json:"operation_type"`
	Title             string             `db:"title" json:"title"`
	TargetTenantID    pgtype.UUID        `db:"target_tenant_id" json:"target_tenant_id"`
	TargetTenantName  pgtype.Text        `db:"target_tenant_name" json:"target_tenant_name"`
	TargetTenantCode  pgtype.Text        `db:"target_tenant_code" json:"target_tenant_code"`
	Status            string             `db:"status" json:"status"`
	RiskLevel         string             `db:"risk_level" json:"risk_level"`
	Reason            string             `db:"reason" json:"reason"`
	ActorID           pgtype.UUID        `db:"actor_id" json:"actor_id"`
	ApprovalRequired  bool               `db:"approval_required" json:"approval_required"`
	BackupRequired    bool               `db:"backup_required" json:"backup_required"`
	BackupConfirmed   bool               `db:"backup_confirmed" json:"backup_confirmed"`
	RetentionUntil    pgtype.Timestamptz `db:"retention_until" json:"retention_until"`
	RequestPayload    []byte             `db:"request_payload" json:"request_payload"`
	ValidationResults []byte             `db:"validation_results" json:"validation_results"`
	RollbackMetadata  []byte             `db:"rollback_metadata" json:"rollback_metadata"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateTenantOperationRequest(ctx context.Context, arg CreateTenantOperationRequestParams) (HrmsTenantOperationRequest, error) {
	row := q.db.QueryRow(ctx, createTenantOperationRequest,
		arg.OperationNumber,
		arg.OperationType,
		arg.Title,
		arg.TargetTenantID,
		arg.TargetTenantName,
		arg.TargetTenantCode,
		arg.Status,
		arg.RiskLevel,
		arg.Reason,
		arg.ActorID,
		arg.ApprovalRequired,
		arg.BackupRequired,
		arg.BackupConfirmed,
		arg.RetentionUntil,
		arg.RequestPayload,
		arg.ValidationResults,
		arg.RollbackMetadata,
		arg.Metadata,
	)
	var i HrmsTenantOperationRequest
	err := row.Scan(
		&i.ID,
		&i.OperationNumber,
		&i.OperationType,
		&i.Title,
		&i.TargetTenantID,
		&i.TargetTenantName,
		&i.TargetTenantCode,
		&i.Status,
		&i.RiskLevel,
		&i.Reason,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.ApprovalRequired,
		&i.BackupRequired,
		&i.BackupConfirmed,
		&i.RetentionUntil,
		&i.RequestPayload,
		&i.ValidationResults,
		&i.RollbackMetadata,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getTenantOperationRequest = `-- name: GetTenantOperationRequest :one
SELECT id, operation_number, operation_type, title, target_tenant_id, target_tenant_name, target_tenant_code, status, risk_level, reason, requested_by, approved_by, approved_at, completed_by, completed_at, approval_required, backup_required, backup_confirmed, retention_until, request_payload, validation_results, rollback_metadata, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.tenant_operation_requests
WHERE id = $1 AND NOT inactive
`

func (q *Queries) GetTenantOperationRequest(ctx context.Context, id uuid.UUID) (HrmsTenantOperationRequest, error) {
	row := q.db.QueryRow(ctx, getTenantOperationRequest, id)
	var i HrmsTenantOperationRequest
	err := row.Scan(
		&i.ID,
		&i.OperationNumber,
		&i.OperationType,
		&i.Title,
		&i.TargetTenantID,
		&i.TargetTenantName,
		&i.TargetTenantCode,
		&i.Status,
		&i.RiskLevel,
		&i.Reason,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.ApprovalRequired,
		&i.BackupRequired,
		&i.BackupConfirmed,
		&i.RetentionUntil,
		&i.RequestPayload,
		&i.ValidationResults,
		&i.RollbackMetadata,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listTenantOperationEvents = `-- name: ListTenantOperationEvents :many
SELECT id, request_id, action, from_status, to_status, actor_user_id, remarks, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.tenant_operation_events
WHERE request_id = $1 AND NOT inactive
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListTenantOperationEvents(ctx context.Context, requestID uuid.UUID) ([]HrmsTenantOperationEvent, error) {
	rows, err := q.db.Query(ctx, listTenantOperationEvents, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsTenantOperationEvent
	for rows.Next() {
		var i HrmsTenantOperationEvent
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Action,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorUserID,
			&i.Remarks,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantOperationRequests = `-- name: ListTenantOperationRequests :many
SELECT id, operation_number, operation_type, title, target_tenant_id, target_tenant_name, target_tenant_code, status, risk_level, reason, requested_by, approved_by, approved_at, completed_by, completed_at, approval_required, backup_required, backup_confirmed, retention_until, request_payload, validation_results, rollback_metadata, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.tenant_operation_requests
WHERE NOT inactive
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR operation_type = $2::text)
  AND ($3::text IS NULL OR risk_level = $3::text)
  AND ($4::uuid IS NULL OR target_tenant_id = $4::uuid)
  AND (
      $5::text IS NULL
      OR operation_number ILIKE '%' || $5::text || '%'
      OR title ILIKE '%' || $5::text || '%'
      OR reason ILIKE '%' || $5::text || '%'
      OR COALESCE(target_tenant_name, '') ILIKE '%' || $5::text || '%'
      OR COALESCE(target_tenant_code, '') ILIKE '%' || $5::text || '%'
  )
ORDER BY
  CASE status WHEN 'pending_validation' THEN 0 WHEN 'pending_approval' THEN 1 WHEN 'approved' THEN 2 WHEN 'in_progress' THEN 3 ELSE 4 END,
  CASE risk_level WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
  created_at DESC
LIMIT $7 OFFSET $6
`

type ListTenantOperationRequestsParams struct {
	Status         pgtype.Text `db:"status" json:"status"`
	OperationType  pgtype.Text `db:"operation_type" json:"operation_type"`
	RiskLevel      pgtype.Text `db:"risk_level" json:"risk_level"`
	TargetTenantID pgtype.UUID `db:"target_tenant_id" json:"target_tenant_id"`
	Search         pgtype.Text `db:"search" json:"search"`
	RowOffset      int32       `db:"row_offset" json:"row_offset"`
	RowLimit       int32       `db:"row_limit" json:"row_limit"`
}

func (q *Queries) ListTenantOperationRequests(ctx context.Context, arg ListTenantOperationRequestsParams) ([]HrmsTenantOperationRequest, error) {
	rows, err := q.db.Query(ctx, listTenantOperationRequests,
		arg.Status,
		arg.OperationType,
		arg.RiskLevel,
		arg.TargetTenantID,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsTenantOperationRequest
	for rows.Next() {
		var i HrmsTenantOperationRequest
		if err := rows.Scan(
			&i.ID,
			&i.OperationNumber,
			&i.OperationType,
			&i.Title,
			&i.TargetTenantID,
			&i.TargetTenantName,
			&i.TargetTenantCode,
			&i.Status,
			&i.RiskLevel,
			&i.Reason,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CompletedBy,
			&i.CompletedAt,
			&i.ApprovalRequired,
			&i.BackupRequired,
			&i.BackupConfirmed,
			&i.RetentionUntil,
			&i.RequestPayload,
			&i.ValidationResults,
			&i.RollbackMetadata,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantOperationRequestStatus = `-- name: UpdateTenantOperationRequestStatus :one
UPDATE hrms.tenant_operation_requests
SET status = $1,
    approved_by = COALESCE($2, approved_by),
    approved_at = CASE WHEN $1 = 'approved' THEN now() ELSE approved_at END,
    completed_by = COALESCE($3, completed_by),
    completed_at = CASE WHEN $1 IN ('completed','failed','cancelled','rejected') THEN now() ELSE completed_at END,
    backup_confirmed = COALESCE($4, backup_confirmed),
    validation_results = COALESCE($5, validation_results),
    rollback_metadata = COALESCE($6, rollback_metadata),
    metadata = metadata || COALESCE($7, '{}'::jsonb),
    updated_by = $8
WHERE id = $9 AND NOT inactive
RETURNING id, operation_number, operation_type, title, target_tenant_id, target_tenant_name, target_tenant_code, status, risk_level, reason, requested_by, approved_by, approved_at, completed_by, completed_at, approval_required, backup_required, backup_confirmed, retention_until, request_payload, validation_results, rollback_metadata, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateTenantOperationRequestStatusParams struct {
	Status            string      `db:"status" json:"status"`
	ApprovedBy        pgtype.UUID `db:"approved_by" json:"approved_by"`
	CompletedBy       pgtype.UUID `db:"completed_by" json:"completed_by"`
	BackupConfirmed   pgtype.Bool `db:"backup_confirmed" json:"backup_confirmed"`
	ValidationResults []byte      `db:"validation_results" json:"validation_results"`
	RollbackMetadata  []byte      `db:"rollback_metadata" json:"rollback_metadata"`
	Metadata          []byte      `db:"metadata" json:"metadata"`
	ActorID           pgtype.UUID `db:"actor_id" json:"actor_id"`
	ID                uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateTenantOperationRequestStatus(ctx context.Context, arg UpdateTenantOperationRequestStatusParams) (HrmsTenantOperationRequest, error) {
	row := q.db.QueryRow(ctx, updateTenantOperationRequestStatus,
		arg.Status,
		arg.ApprovedBy,
		arg.CompletedBy,
		arg.BackupConfirmed,
		arg.ValidationResults,
		arg.RollbackMetadata,
		arg.Metadata,
		arg.ActorID,
		arg.ID,
	)
	var i HrmsTenantOperationRequest
	err := row.Scan(
		&i.ID,
		&i.OperationNumber,
		&i.OperationType,
		&i.Title,
		&i.TargetTenantID,
		&i.TargetTenantName,
		&i.TargetTenantCode,
		&i.Status,
		&i.RiskLevel,
		&i.Reason,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.ApprovalRequired,
		&i.BackupRequired,
		&i.BackupConfirmed,
		&i.RetentionUntil,
		&i.RequestPayload,
		&i.ValidationResults,
		&i.RollbackMetadata,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
