// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteTenantSetting = `-- name: DeleteTenantSetting :exec
DELETE FROM hrms.tenant_settings
WHERE tenant_id = $1 AND key = $2
`

type DeleteTenantSettingParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Key      string    `db:"key" json:"key"`
}

func (q *Queries) DeleteTenantSetting(ctx context.Context, arg DeleteTenantSettingParams) error {
	_, err := q.db.Exec(ctx, deleteTenantSetting, arg.TenantID, arg.Key)
	return err
}

const getTenantSetting = `-- name: GetTenantSetting :one
SELECT tenant_id, key, value, created_at, updated_at FROM hrms.tenant_settings
WHERE tenant_id = $1 AND key = $2
`

type GetTenantSettingParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Key      string    `db:"key" json:"key"`
}

func (q *Queries) GetTenantSetting(ctx context.Context, arg GetTenantSettingParams) (HrmsTenantSetting, error) {
	row := q.db.QueryRow(ctx, getTenantSetting, arg.TenantID, arg.Key)
	var i HrmsTenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantSettings = `-- name: ListTenantSettings :many
SELECT tenant_id, key, value, created_at, updated_at FROM hrms.tenant_settings
WHERE tenant_id = $1
ORDER BY key ASC
`

func (q *Queries) ListTenantSettings(ctx context.Context, tenantID uuid.UUID) ([]HrmsTenantSetting, error) {
	rows, err := q.db.Query(ctx, listTenantSettings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsTenantSetting
	for rows.Next() {
		var i HrmsTenantSetting
		if err := rows.Scan(
			&i.TenantID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTenantSetting = `-- name: UpsertTenantSetting :one
INSERT INTO hrms.tenant_settings (tenant_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, key) DO UPDATE SET
    value = EXCLUDED.value
RETURNING tenant_id, key, value, created_at, updated_at
`

type UpsertTenantSettingParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Key      string    `db:"key" json:"key"`
	Value    []byte    `db:"value" json:"value"`
}

func (q *Queries) UpsertTenantSetting(ctx context.Context, arg UpsertTenantSettingParams) (HrmsTenantSetting, error) {
	row := q.db.QueryRow(ctx, upsertTenantSetting, arg.TenantID, arg.Key, arg.Value)
	var i HrmsTenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
