// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_brandings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantBrandingByTenantID = `-- name: GetTenantBrandingByTenantID :one
SELECT
    p.tenant_id,
    p.subdomain,
    p.display_name,
    b.logo_path,
    b.favicon_path,
    COALESCE(b.layout, 'vertical')::text AS layout,
    COALESCE(b.color_mode, 'light')::text AS color_mode,
    COALESCE(b.sidebar_size, 'default')::text AS sidebar_size,
    COALESCE(b.layout_width, 'fluid')::text AS layout_width,
    COALESCE(b.card_layout, 'bordered')::text AS card_layout,
    COALESCE(b.theme_color, '#588368')::text AS theme_color,
    COALESCE(b.primary_color, '#588368')::text AS primary_color,
    COALESCE(b.secondary_color, '#e87839')::text AS secondary_color,
    COALESCE(b.tertiary_color, '#f2b36d')::text AS tertiary_color,
    COALESCE(b.topbar_color, '#fffaf4')::text AS topbar_color,
    COALESCE(b.sidebar_color, '#426b53')::text AS sidebar_color,
    COALESCE(b.topbar_background, 'none')::text AS topbar_background,
    COALESCE(b.sidebar_background, 'solid')::text AS sidebar_background,
    COALESCE(b.font_family, '"Plus Jakarta Sans", "Segoe UI", sans-serif')::text AS font_family,
    COALESCE(b.preloader, true)::boolean AS preloader
FROM hrms.tenant_profiles p
LEFT JOIN hrms.tenant_brandings b ON b.tenant_id = p.tenant_id AND NOT b.inactive
WHERE p.tenant_id = $1
`

type GetTenantBrandingByTenantIDRow struct {
	TenantID          uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Subdomain         string      `db:"subdomain" json:"subdomain"`
	DisplayName       pgtype.Text `db:"display_name" json:"display_name"`
	LogoPath          pgtype.Text `db:"logo_path" json:"logo_path"`
	FaviconPath       pgtype.Text `db:"favicon_path" json:"favicon_path"`
	Layout            string      `db:"layout" json:"layout"`
	ColorMode         string      `db:"color_mode" json:"color_mode"`
	SidebarSize       string      `db:"sidebar_size" json:"sidebar_size"`
	LayoutWidth       string      `db:"layout_width" json:"layout_width"`
	CardLayout        string      `db:"card_layout" json:"card_layout"`
	ThemeColor        string      `db:"theme_color" json:"theme_color"`
	PrimaryColor      string      `db:"primary_color" json:"primary_color"`
	SecondaryColor    string      `db:"secondary_color" json:"secondary_color"`
	TertiaryColor     string      `db:"tertiary_color" json:"tertiary_color"`
	TopbarColor       string      `db:"topbar_color" json:"topbar_color"`
	SidebarColor      string      `db:"sidebar_color" json:"sidebar_color"`
	TopbarBackground  string      `db:"topbar_background" json:"topbar_background"`
	SidebarBackground string      `db:"sidebar_background" json:"sidebar_background"`
	FontFamily        string      `db:"font_family" json:"font_family"`
	Preloader         bool        `db:"preloader" json:"preloader"`
}

func (q *Queries) GetTenantBrandingByTenantID(ctx context.Context, tenantID uuid.UUID) (GetTenantBrandingByTenantIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantBrandingByTenantID, tenantID)
	var i GetTenantBrandingByTenantIDRow
	err := row.Scan(
		&i.TenantID,
		&i.Subdomain,
		&i.DisplayName,
		&i.LogoPath,
		&i.FaviconPath,
		&i.Layout,
		&i.ColorMode,
		&i.SidebarSize,
		&i.LayoutWidth,
		&i.CardLayout,
		&i.ThemeColor,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.TertiaryColor,
		&i.TopbarColor,
		&i.SidebarColor,
		&i.TopbarBackground,
		&i.SidebarBackground,
		&i.FontFamily,
		&i.Preloader,
	)
	return i, err
}

const resolveTenantBrandingBySubdomain = `-- name: ResolveTenantBrandingBySubdomain :one
SELECT
    p.tenant_id,
    p.subdomain,
    p.display_name,
    b.logo_path,
    b.favicon_path,
    COALESCE(b.layout, 'vertical')::text AS layout,
    COALESCE(b.color_mode, 'light')::text AS color_mode,
    COALESCE(b.sidebar_size, 'default')::text AS sidebar_size,
    COALESCE(b.layout_width, 'fluid')::text AS layout_width,
    COALESCE(b.card_layout, 'bordered')::text AS card_layout,
    COALESCE(b.theme_color, '#588368')::text AS theme_color,
    COALESCE(b.primary_color, '#588368')::text AS primary_color,
    COALESCE(b.secondary_color, '#e87839')::text AS secondary_color,
    COALESCE(b.tertiary_color, '#f2b36d')::text AS tertiary_color,
    COALESCE(b.topbar_color, '#fffaf4')::text AS topbar_color,
    COALESCE(b.sidebar_color, '#426b53')::text AS sidebar_color,
    COALESCE(b.topbar_background, 'none')::text AS topbar_background,
    COALESCE(b.sidebar_background, 'solid')::text AS sidebar_background,
    COALESCE(b.font_family, '"Plus Jakarta Sans", "Segoe UI", sans-serif')::text AS font_family,
    COALESCE(b.preloader, true)::boolean AS preloader
FROM hrms.tenant_profiles p
LEFT JOIN hrms.tenant_brandings b ON b.tenant_id = p.tenant_id AND NOT b.inactive
WHERE p.subdomain = $1
`

type ResolveTenantBrandingBySubdomainRow struct {
	TenantID          uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Subdomain         string      `db:"subdomain" json:"subdomain"`
	DisplayName       pgtype.Text `db:"display_name" json:"display_name"`
	LogoPath          pgtype.Text `db:"logo_path" json:"logo_path"`
	FaviconPath       pgtype.Text `db:"favicon_path" json:"favicon_path"`
	Layout            string      `db:"layout" json:"layout"`
	ColorMode         string      `db:"color_mode" json:"color_mode"`
	SidebarSize       string      `db:"sidebar_size" json:"sidebar_size"`
	LayoutWidth       string      `db:"layout_width" json:"layout_width"`
	CardLayout        string      `db:"card_layout" json:"card_layout"`
	ThemeColor        string      `db:"theme_color" json:"theme_color"`
	PrimaryColor      string      `db:"primary_color" json:"primary_color"`
	SecondaryColor    string      `db:"secondary_color" json:"secondary_color"`
	TertiaryColor     string      `db:"tertiary_color" json:"tertiary_color"`
	TopbarColor       string      `db:"topbar_color" json:"topbar_color"`
	SidebarColor      string      `db:"sidebar_color" json:"sidebar_color"`
	TopbarBackground  string      `db:"topbar_background" json:"topbar_background"`
	SidebarBackground string      `db:"sidebar_background" json:"sidebar_background"`
	FontFamily        string      `db:"font_family" json:"font_family"`
	Preloader         bool        `db:"preloader" json:"preloader"`
}

func (q *Queries) ResolveTenantBrandingBySubdomain(ctx context.Context, subdomain string) (ResolveTenantBrandingBySubdomainRow, error) {
	row := q.db.QueryRow(ctx, resolveTenantBrandingBySubdomain, subdomain)
	var i ResolveTenantBrandingBySubdomainRow
	err := row.Scan(
		&i.TenantID,
		&i.Subdomain,
		&i.DisplayName,
		&i.LogoPath,
		&i.FaviconPath,
		&i.Layout,
		&i.ColorMode,
		&i.SidebarSize,
		&i.LayoutWidth,
		&i.CardLayout,
		&i.ThemeColor,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.TertiaryColor,
		&i.TopbarColor,
		&i.SidebarColor,
		&i.TopbarBackground,
		&i.SidebarBackground,
		&i.FontFamily,
		&i.Preloader,
	)
	return i, err
}

const upsertTenantBranding = `-- name: UpsertTenantBranding :one
WITH profile AS (
    INSERT INTO hrms.tenant_profiles (
        tenant_id,
        subdomain,
        mobile_activation_code,
        display_name
    ) VALUES (
        $1, $20, $21, $22
    )
    ON CONFLICT (tenant_id) DO UPDATE SET
        display_name = COALESCE(hrms.tenant_profiles.display_name, EXCLUDED.display_name)
    RETURNING tenant_id, subdomain, display_name
), upserted AS (
    INSERT INTO hrms.tenant_brandings (
        tenant_id,
        logo_path,
        favicon_path,
        layout,
        color_mode,
        sidebar_size,
        layout_width,
        card_layout,
        theme_color,
        primary_color,
        secondary_color,
        tertiary_color,
        topbar_color,
        sidebar_color,
        topbar_background,
        sidebar_background,
        font_family,
        preloader,
        inactive,
        created_by,
        updated_by
    ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16, $17, $18, false, $19, $19
    )
    ON CONFLICT (tenant_id) DO UPDATE SET
        logo_path = EXCLUDED.logo_path,
        favicon_path = EXCLUDED.favicon_path,
        layout = EXCLUDED.layout,
        color_mode = EXCLUDED.color_mode,
        sidebar_size = EXCLUDED.sidebar_size,
        layout_width = EXCLUDED.layout_width,
        card_layout = EXCLUDED.card_layout,
        theme_color = EXCLUDED.theme_color,
        primary_color = EXCLUDED.primary_color,
        secondary_color = EXCLUDED.secondary_color,
        tertiary_color = EXCLUDED.tertiary_color,
        topbar_color = EXCLUDED.topbar_color,
        sidebar_color = EXCLUDED.sidebar_color,
        topbar_background = EXCLUDED.topbar_background,
        sidebar_background = EXCLUDED.sidebar_background,
        font_family = EXCLUDED.font_family,
        preloader = EXCLUDED.preloader,
        inactive = false,
        updated_by = EXCLUDED.updated_by
    RETURNING tenant_id, logo_path, favicon_path, layout, color_mode, sidebar_size, layout_width, card_layout, theme_color, primary_color, secondary_color, tertiary_color, topbar_color, sidebar_color, topbar_background, sidebar_background, font_family, preloader, inactive, created_at, created_by, updated_at, updated_by
)
SELECT
    p.tenant_id,
    p.subdomain,
    p.display_name,
    u.logo_path,
    u.favicon_path,
    u.layout::text AS layout,
    u.color_mode::text AS color_mode,
    u.sidebar_size::text AS sidebar_size,
    u.layout_width::text AS layout_width,
    u.card_layout::text AS card_layout,
    u.theme_color::text AS theme_color,
    u.primary_color::text AS primary_color,
    u.secondary_color::text AS secondary_color,
    u.tertiary_color::text AS tertiary_color,
    u.topbar_color::text AS topbar_color,
    u.sidebar_color::text AS sidebar_color,
    u.topbar_background,
    u.sidebar_background,
    u.font_family::text AS font_family,
    u.preloader
FROM profile p
JOIN upserted u ON u.tenant_id = p.tenant_id
`

type UpsertTenantBrandingParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	LogoPath             pgtype.Text `db:"logo_path" json:"logo_path"`
	FaviconPath          pgtype.Text `db:"favicon_path" json:"favicon_path"`
	Layout               string      `db:"layout" json:"layout"`
	ColorMode            string      `db:"color_mode" json:"color_mode"`
	SidebarSize          string      `db:"sidebar_size" json:"sidebar_size"`
	LayoutWidth          string      `db:"layout_width" json:"layout_width"`
	CardLayout           string      `db:"card_layout" json:"card_layout"`
	ThemeColor           string      `db:"theme_color" json:"theme_color"`
	PrimaryColor         string      `db:"primary_color" json:"primary_color"`
	SecondaryColor       string      `db:"secondary_color" json:"secondary_color"`
	TertiaryColor        string      `db:"tertiary_color" json:"tertiary_color"`
	TopbarColor          string      `db:"topbar_color" json:"topbar_color"`
	SidebarColor         string      `db:"sidebar_color" json:"sidebar_color"`
	TopbarBackground     string      `db:"topbar_background" json:"topbar_background"`
	SidebarBackground    string      `db:"sidebar_background" json:"sidebar_background"`
	FontFamily           string      `db:"font_family" json:"font_family"`
	Preloader            bool        `db:"preloader" json:"preloader"`
	CreatedBy            pgtype.UUID `db:"created_by" json:"created_by"`
	Subdomain            string      `db:"subdomain" json:"subdomain"`
	MobileActivationCode string      `db:"mobile_activation_code" json:"mobile_activation_code"`
	DisplayName          pgtype.Text `db:"display_name" json:"display_name"`
}

type UpsertTenantBrandingRow struct {
	TenantID          uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Subdomain         string      `db:"subdomain" json:"subdomain"`
	DisplayName       pgtype.Text `db:"display_name" json:"display_name"`
	LogoPath          pgtype.Text `db:"logo_path" json:"logo_path"`
	FaviconPath       pgtype.Text `db:"favicon_path" json:"favicon_path"`
	Layout            string      `db:"layout" json:"layout"`
	ColorMode         string      `db:"color_mode" json:"color_mode"`
	SidebarSize       string      `db:"sidebar_size" json:"sidebar_size"`
	LayoutWidth       string      `db:"layout_width" json:"layout_width"`
	CardLayout        string      `db:"card_layout" json:"card_layout"`
	ThemeColor        string      `db:"theme_color" json:"theme_color"`
	PrimaryColor      string      `db:"primary_color" json:"primary_color"`
	SecondaryColor    string      `db:"secondary_color" json:"secondary_color"`
	TertiaryColor     string      `db:"tertiary_color" json:"tertiary_color"`
	TopbarColor       string      `db:"topbar_color" json:"topbar_color"`
	SidebarColor      string      `db:"sidebar_color" json:"sidebar_color"`
	TopbarBackground  string      `db:"topbar_background" json:"topbar_background"`
	SidebarBackground string      `db:"sidebar_background" json:"sidebar_background"`
	FontFamily        string      `db:"font_family" json:"font_family"`
	Preloader         bool        `db:"preloader" json:"preloader"`
}

func (q *Queries) UpsertTenantBranding(ctx context.Context, arg UpsertTenantBrandingParams) (UpsertTenantBrandingRow, error) {
	row := q.db.QueryRow(ctx, upsertTenantBranding,
		arg.TenantID,
		arg.LogoPath,
		arg.FaviconPath,
		arg.Layout,
		arg.ColorMode,
		arg.SidebarSize,
		arg.LayoutWidth,
		arg.CardLayout,
		arg.ThemeColor,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.TertiaryColor,
		arg.TopbarColor,
		arg.SidebarColor,
		arg.TopbarBackground,
		arg.SidebarBackground,
		arg.FontFamily,
		arg.Preloader,
		arg.CreatedBy,
		arg.Subdomain,
		arg.MobileActivationCode,
		arg.DisplayName,
	)
	var i UpsertTenantBrandingRow
	err := row.Scan(
		&i.TenantID,
		&i.Subdomain,
		&i.DisplayName,
		&i.LogoPath,
		&i.FaviconPath,
		&i.Layout,
		&i.ColorMode,
		&i.SidebarSize,
		&i.LayoutWidth,
		&i.CardLayout,
		&i.ThemeColor,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.TertiaryColor,
		&i.TopbarColor,
		&i.SidebarColor,
		&i.TopbarBackground,
		&i.SidebarBackground,
		&i.FontFamily,
		&i.Preloader,
	)
	return i, err
}
