// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_task_engine.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOperationTemplate = `-- name: CreateOperationTemplate :one
INSERT INTO hrms.operation_templates (
    tenant_id, template_key, name, category, source_module, source_type, workflow_definition_id,
    default_priority, default_severity, allowed_actions, launch_schema, is_active, metadata, created_by, updated_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$14)
RETURNING id, tenant_id, template_key, name, category, source_module, source_type, workflow_definition_id, default_priority, default_severity, allowed_actions, launch_schema, is_active, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateOperationTemplateParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	TemplateKey          string      `db:"template_key" json:"template_key"`
	Name                 string      `db:"name" json:"name"`
	Category             string      `db:"category" json:"category"`
	SourceModule         string      `db:"source_module" json:"source_module"`
	SourceType           string      `db:"source_type" json:"source_type"`
	WorkflowDefinitionID pgtype.UUID `db:"workflow_definition_id" json:"workflow_definition_id"`
	DefaultPriority      int32       `db:"default_priority" json:"default_priority"`
	DefaultSeverity      string      `db:"default_severity" json:"default_severity"`
	AllowedActions       []byte      `db:"allowed_actions" json:"allowed_actions"`
	LaunchSchema         []byte      `db:"launch_schema" json:"launch_schema"`
	IsActive             bool        `db:"is_active" json:"is_active"`
	Metadata             []byte      `db:"metadata" json:"metadata"`
	CreatedBy            pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateOperationTemplate(ctx context.Context, arg CreateOperationTemplateParams) (HrmsOperationTemplate, error) {
	row := q.db.QueryRow(ctx, createOperationTemplate,
		arg.TenantID,
		arg.TemplateKey,
		arg.Name,
		arg.Category,
		arg.SourceModule,
		arg.SourceType,
		arg.WorkflowDefinitionID,
		arg.DefaultPriority,
		arg.DefaultSeverity,
		arg.AllowedActions,
		arg.LaunchSchema,
		arg.IsActive,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsOperationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TemplateKey,
		&i.Name,
		&i.Category,
		&i.SourceModule,
		&i.SourceType,
		&i.WorkflowDefinitionID,
		&i.DefaultPriority,
		&i.DefaultSeverity,
		&i.AllowedActions,
		&i.LaunchSchema,
		&i.IsActive,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createWorkflowDefinition = `-- name: CreateWorkflowDefinition :one
INSERT INTO hrms.workflow_definitions (
    tenant_id, workflow_key, name, module_key, description, status, visibility_scope, metadata, created_by, updated_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$9)
RETURNING id, tenant_id, workflow_key, name, module_key, description, status, visibility_scope, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateWorkflowDefinitionParams struct {
	TenantID        uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	WorkflowKey     string      `db:"workflow_key" json:"workflow_key"`
	Name            string      `db:"name" json:"name"`
	ModuleKey       string      `db:"module_key" json:"module_key"`
	Description     pgtype.Text `db:"description" json:"description"`
	Status          string      `db:"status" json:"status"`
	VisibilityScope string      `db:"visibility_scope" json:"visibility_scope"`
	Metadata        []byte      `db:"metadata" json:"metadata"`
	CreatedBy       pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateWorkflowDefinition(ctx context.Context, arg CreateWorkflowDefinitionParams) (HrmsWorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, createWorkflowDefinition,
		arg.TenantID,
		arg.WorkflowKey,
		arg.Name,
		arg.ModuleKey,
		arg.Description,
		arg.Status,
		arg.VisibilityScope,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsWorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowKey,
		&i.Name,
		&i.ModuleKey,
		&i.Description,
		&i.Status,
		&i.VisibilityScope,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createWorkflowDefinitionStep = `-- name: CreateWorkflowDefinitionStep :one
INSERT INTO hrms.workflow_definition_steps (
    tenant_id, workflow_definition_id, step_order, step_key, name, step_type, assignment_type,
    assignment_value, required, due_offset_hours, allowed_actions, metadata, created_by, updated_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13)
RETURNING id, tenant_id, workflow_definition_id, step_order, step_key, name, step_type, assignment_type, assignment_value, required, due_offset_hours, allowed_actions, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateWorkflowDefinitionStepParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	WorkflowDefinitionID uuid.UUID   `db:"workflow_definition_id" json:"workflow_definition_id"`
	StepOrder            int32       `db:"step_order" json:"step_order"`
	StepKey              string      `db:"step_key" json:"step_key"`
	Name                 string      `db:"name" json:"name"`
	StepType             string      `db:"step_type" json:"step_type"`
	AssignmentType       string      `db:"assignment_type" json:"assignment_type"`
	AssignmentValue      pgtype.Text `db:"assignment_value" json:"assignment_value"`
	Required             bool        `db:"required" json:"required"`
	DueOffsetHours       int32       `db:"due_offset_hours" json:"due_offset_hours"`
	AllowedActions       []byte      `db:"allowed_actions" json:"allowed_actions"`
	Metadata             []byte      `db:"metadata" json:"metadata"`
	CreatedBy            pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateWorkflowDefinitionStep(ctx context.Context, arg CreateWorkflowDefinitionStepParams) (HrmsWorkflowDefinitionStep, error) {
	row := q.db.QueryRow(ctx, createWorkflowDefinitionStep,
		arg.TenantID,
		arg.WorkflowDefinitionID,
		arg.StepOrder,
		arg.StepKey,
		arg.Name,
		arg.StepType,
		arg.AssignmentType,
		arg.AssignmentValue,
		arg.Required,
		arg.DueOffsetHours,
		arg.AllowedActions,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsWorkflowDefinitionStep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowDefinitionID,
		&i.StepOrder,
		&i.StepKey,
		&i.Name,
		&i.StepType,
		&i.AssignmentType,
		&i.AssignmentValue,
		&i.Required,
		&i.DueOffsetHours,
		&i.AllowedActions,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createWorkflowTask = `-- name: CreateWorkflowTask :one
INSERT INTO hrms.workflow_tasks (
    tenant_id, task_number, template_id, workflow_definition_id, workflow_step_id, parent_task_id,
    source_module, source_type, source_id, source_record_label, title, description, requester_user_id,
    assignee_user_id, assignee_role, assignee_team, delegated_from_user_id, status, priority,
    severity, visibility_scope, due_at, action_schema, metadata, created_by, updated_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$25)
RETURNING id, tenant_id, task_number, template_id, workflow_definition_id, workflow_step_id, parent_task_id, source_module, source_type, source_id, source_record_label, title, description, requester_user_id, assignee_user_id, assignee_role, assignee_team, delegated_from_user_id, status, priority, severity, visibility_scope, due_at, completed_at, completed_by, action_schema, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateWorkflowTaskParams struct {
	TenantID             uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	TaskNumber           string             `db:"task_number" json:"task_number"`
	TemplateID           pgtype.UUID        `db:"template_id" json:"template_id"`
	WorkflowDefinitionID pgtype.UUID        `db:"workflow_definition_id" json:"workflow_definition_id"`
	WorkflowStepID       pgtype.UUID        `db:"workflow_step_id" json:"workflow_step_id"`
	ParentTaskID         pgtype.UUID        `db:"parent_task_id" json:"parent_task_id"`
	SourceModule         string             `db:"source_module" json:"source_module"`
	SourceType           string             `db:"source_type" json:"source_type"`
	SourceID             pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceRecordLabel    pgtype.Text        `db:"source_record_label" json:"source_record_label"`
	Title                string             `db:"title" json:"title"`
	Description          pgtype.Text        `db:"description" json:"description"`
	RequesterUserID      pgtype.UUID        `db:"requester_user_id" json:"requester_user_id"`
	AssigneeUserID       pgtype.UUID        `db:"assignee_user_id" json:"assignee_user_id"`
	AssigneeRole         pgtype.Text        `db:"assignee_role" json:"assignee_role"`
	AssigneeTeam         pgtype.Text        `db:"assignee_team" json:"assignee_team"`
	DelegatedFromUserID  pgtype.UUID        `db:"delegated_from_user_id" json:"delegated_from_user_id"`
	Status               string             `db:"status" json:"status"`
	Priority             int32              `db:"priority" json:"priority"`
	Severity             string             `db:"severity" json:"severity"`
	VisibilityScope      string             `db:"visibility_scope" json:"visibility_scope"`
	DueAt                pgtype.Timestamptz `db:"due_at" json:"due_at"`
	ActionSchema         []byte             `db:"action_schema" json:"action_schema"`
	Metadata             []byte             `db:"metadata" json:"metadata"`
	CreatedBy            pgtype.UUID        `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateWorkflowTask(ctx context.Context, arg CreateWorkflowTaskParams) (HrmsWorkflowTask, error) {
	row := q.db.QueryRow(ctx, createWorkflowTask,
		arg.TenantID,
		arg.TaskNumber,
		arg.TemplateID,
		arg.WorkflowDefinitionID,
		arg.WorkflowStepID,
		arg.ParentTaskID,
		arg.SourceModule,
		arg.SourceType,
		arg.SourceID,
		arg.SourceRecordLabel,
		arg.Title,
		arg.Description,
		arg.RequesterUserID,
		arg.AssigneeUserID,
		arg.AssigneeRole,
		arg.AssigneeTeam,
		arg.DelegatedFromUserID,
		arg.Status,
		arg.Priority,
		arg.Severity,
		arg.VisibilityScope,
		arg.DueAt,
		arg.ActionSchema,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsWorkflowTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskNumber,
		&i.TemplateID,
		&i.WorkflowDefinitionID,
		&i.WorkflowStepID,
		&i.ParentTaskID,
		&i.SourceModule,
		&i.SourceType,
		&i.SourceID,
		&i.SourceRecordLabel,
		&i.Title,
		&i.Description,
		&i.RequesterUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.AssigneeTeam,
		&i.DelegatedFromUserID,
		&i.Status,
		&i.Priority,
		&i.Severity,
		&i.VisibilityScope,
		&i.DueAt,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.ActionSchema,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createWorkflowTaskAttachment = `-- name: CreateWorkflowTaskAttachment :one
INSERT INTO hrms.workflow_task_attachments (
    tenant_id, task_id, comment_id, file_name, content_type, storage_path, checksum_sha256,
    size_bytes, visibility, metadata, created_by, updated_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11)
RETURNING id, tenant_id, task_id, comment_id, file_name, content_type, storage_path, checksum_sha256, size_bytes, visibility, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateWorkflowTaskAttachmentParams struct {
	TenantID       uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	TaskID         uuid.UUID   `db:"task_id" json:"task_id"`
	CommentID      pgtype.UUID `db:"comment_id" json:"comment_id"`
	FileName       string      `db:"file_name" json:"file_name"`
	ContentType    string      `db:"content_type" json:"content_type"`
	StoragePath    string      `db:"storage_path" json:"storage_path"`
	ChecksumSha256 pgtype.Text `db:"checksum_sha256" json:"checksum_sha256"`
	SizeBytes      int64       `db:"size_bytes" json:"size_bytes"`
	Visibility     string      `db:"visibility" json:"visibility"`
	Metadata       []byte      `db:"metadata" json:"metadata"`
	CreatedBy      pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateWorkflowTaskAttachment(ctx context.Context, arg CreateWorkflowTaskAttachmentParams) (HrmsWorkflowTaskAttachment, error) {
	row := q.db.QueryRow(ctx, createWorkflowTaskAttachment,
		arg.TenantID,
		arg.TaskID,
		arg.CommentID,
		arg.FileName,
		arg.ContentType,
		arg.StoragePath,
		arg.ChecksumSha256,
		arg.SizeBytes,
		arg.Visibility,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsWorkflowTaskAttachment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.CommentID,
		&i.FileName,
		&i.ContentType,
		&i.StoragePath,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.Visibility,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createWorkflowTaskComment = `-- name: CreateWorkflowTaskComment :one
INSERT INTO hrms.workflow_task_comments (tenant_id, task_id, visibility, body, metadata, created_by, updated_by)
VALUES ($1,$2,$3,$4,$5,$6,$6)
RETURNING id, tenant_id, task_id, visibility, body, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateWorkflowTaskCommentParams struct {
	TenantID   uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	TaskID     uuid.UUID   `db:"task_id" json:"task_id"`
	Visibility string      `db:"visibility" json:"visibility"`
	Body       string      `db:"body" json:"body"`
	Metadata   []byte      `db:"metadata" json:"metadata"`
	CreatedBy  pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateWorkflowTaskComment(ctx context.Context, arg CreateWorkflowTaskCommentParams) (HrmsWorkflowTaskComment, error) {
	row := q.db.QueryRow(ctx, createWorkflowTaskComment,
		arg.TenantID,
		arg.TaskID,
		arg.Visibility,
		arg.Body,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsWorkflowTaskComment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.Visibility,
		&i.Body,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createWorkflowTaskEvent = `-- name: CreateWorkflowTaskEvent :one
INSERT INTO hrms.workflow_task_events (
    tenant_id, task_id, action, from_status, to_status, actor_user_id, remarks, metadata, created_by, updated_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$9)
RETURNING id, tenant_id, task_id, action, from_status, to_status, actor_user_id, remarks, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type CreateWorkflowTaskEventParams struct {
	TenantID    uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	TaskID      uuid.UUID   `db:"task_id" json:"task_id"`
	Action      string      `db:"action" json:"action"`
	FromStatus  pgtype.Text `db:"from_status" json:"from_status"`
	ToStatus    pgtype.Text `db:"to_status" json:"to_status"`
	ActorUserID pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	Remarks     pgtype.Text `db:"remarks" json:"remarks"`
	Metadata    []byte      `db:"metadata" json:"metadata"`
	CreatedBy   pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateWorkflowTaskEvent(ctx context.Context, arg CreateWorkflowTaskEventParams) (HrmsWorkflowTaskEvent, error) {
	row := q.db.QueryRow(ctx, createWorkflowTaskEvent,
		arg.TenantID,
		arg.TaskID,
		arg.Action,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorUserID,
		arg.Remarks,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i HrmsWorkflowTaskEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.ActorUserID,
		&i.Remarks,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createWorkflowTaskWatcher = `-- name: CreateWorkflowTaskWatcher :one
INSERT INTO hrms.workflow_task_watchers (tenant_id, task_id, watcher_user_id, watch_reason, created_by, updated_by)
VALUES ($1,$2,$3,$4,$5,$5)
ON CONFLICT (tenant_id, task_id, watcher_user_id) WHERE inactive = FALSE DO UPDATE SET
    watch_reason = EXCLUDED.watch_reason,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING id, tenant_id, task_id, watcher_user_id, watch_reason, inactive, created_at, created_by, updated_at, updated_by
`

type CreateWorkflowTaskWatcherParams struct {
	TenantID      uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	TaskID        uuid.UUID   `db:"task_id" json:"task_id"`
	WatcherUserID uuid.UUID   `db:"watcher_user_id" json:"watcher_user_id"`
	WatchReason   pgtype.Text `db:"watch_reason" json:"watch_reason"`
	CreatedBy     pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateWorkflowTaskWatcher(ctx context.Context, arg CreateWorkflowTaskWatcherParams) (HrmsWorkflowTaskWatcher, error) {
	row := q.db.QueryRow(ctx, createWorkflowTaskWatcher,
		arg.TenantID,
		arg.TaskID,
		arg.WatcherUserID,
		arg.WatchReason,
		arg.CreatedBy,
	)
	var i HrmsWorkflowTaskWatcher
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.WatcherUserID,
		&i.WatchReason,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getOperationTemplate = `-- name: GetOperationTemplate :one
SELECT id, tenant_id, template_key, name, category, source_module, source_type, workflow_definition_id, default_priority, default_severity, allowed_actions, launch_schema, is_active, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.operation_templates
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
`

type GetOperationTemplateParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetOperationTemplate(ctx context.Context, arg GetOperationTemplateParams) (HrmsOperationTemplate, error) {
	row := q.db.QueryRow(ctx, getOperationTemplate, arg.TenantID, arg.ID)
	var i HrmsOperationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TemplateKey,
		&i.Name,
		&i.Category,
		&i.SourceModule,
		&i.SourceType,
		&i.WorkflowDefinitionID,
		&i.DefaultPriority,
		&i.DefaultSeverity,
		&i.AllowedActions,
		&i.LaunchSchema,
		&i.IsActive,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getWorkflowDefinition = `-- name: GetWorkflowDefinition :one
SELECT id, tenant_id, workflow_key, name, module_key, description, status, visibility_scope, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.workflow_definitions
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
`

type GetWorkflowDefinitionParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetWorkflowDefinition(ctx context.Context, arg GetWorkflowDefinitionParams) (HrmsWorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, getWorkflowDefinition, arg.TenantID, arg.ID)
	var i HrmsWorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowKey,
		&i.Name,
		&i.ModuleKey,
		&i.Description,
		&i.Status,
		&i.VisibilityScope,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getWorkflowTask = `-- name: GetWorkflowTask :one
SELECT id, tenant_id, task_number, template_id, workflow_definition_id, workflow_step_id, parent_task_id, source_module, source_type, source_id, source_record_label, title, description, requester_user_id, assignee_user_id, assignee_role, assignee_team, delegated_from_user_id, status, priority, severity, visibility_scope, due_at, completed_at, completed_by, action_schema, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.workflow_tasks
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
`

type GetWorkflowTaskParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetWorkflowTask(ctx context.Context, arg GetWorkflowTaskParams) (HrmsWorkflowTask, error) {
	row := q.db.QueryRow(ctx, getWorkflowTask, arg.TenantID, arg.ID)
	var i HrmsWorkflowTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskNumber,
		&i.TemplateID,
		&i.WorkflowDefinitionID,
		&i.WorkflowStepID,
		&i.ParentTaskID,
		&i.SourceModule,
		&i.SourceType,
		&i.SourceID,
		&i.SourceRecordLabel,
		&i.Title,
		&i.Description,
		&i.RequesterUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.AssigneeTeam,
		&i.DelegatedFromUserID,
		&i.Status,
		&i.Priority,
		&i.Severity,
		&i.VisibilityScope,
		&i.DueAt,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.ActionSchema,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getWorkflowTaskSummary = `-- name: GetWorkflowTaskSummary :many
SELECT 'open_total'::text AS metric, COUNT(*)::bigint AS metric_count
FROM hrms.workflow_tasks wt
WHERE wt.tenant_id = $1 AND wt.inactive = FALSE AND wt.status NOT IN ('approved','rejected','completed','cancelled')
UNION ALL
SELECT 'overdue', COUNT(*)::bigint
FROM hrms.workflow_tasks wt
WHERE wt.tenant_id = $1 AND wt.inactive = FALSE AND wt.status NOT IN ('approved','rejected','completed','cancelled') AND wt.due_at IS NOT NULL AND wt.due_at < now()
UNION ALL
SELECT 'completed', COUNT(*)::bigint
FROM hrms.workflow_tasks wt
WHERE wt.tenant_id = $1 AND wt.inactive = FALSE AND wt.status IN ('approved','rejected','completed','cancelled')
UNION ALL
SELECT 'delegated', COUNT(*)::bigint
FROM hrms.workflow_tasks wt
WHERE wt.tenant_id = $1 AND wt.inactive = FALSE AND wt.status = 'delegated'
UNION ALL
SELECT 'confidential', COUNT(*)::bigint
FROM hrms.workflow_tasks wt
WHERE wt.tenant_id = $1 AND wt.inactive = FALSE AND wt.visibility_scope = 'confidential'
`

type GetWorkflowTaskSummaryRow struct {
	Metric      string `db:"metric" json:"metric"`
	MetricCount int64  `db:"metric_count" json:"metric_count"`
}

func (q *Queries) GetWorkflowTaskSummary(ctx context.Context, tenantID uuid.UUID) ([]GetWorkflowTaskSummaryRow, error) {
	rows, err := q.db.Query(ctx, getWorkflowTaskSummary, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkflowTaskSummaryRow
	for rows.Next() {
		var i GetWorkflowTaskSummaryRow
		if err := rows.Scan(&i.Metric, &i.MetricCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationTemplates = `-- name: ListOperationTemplates :many
SELECT id, tenant_id, template_key, name, category, source_module, source_type, workflow_definition_id, default_priority, default_severity, allowed_actions, launch_schema, is_active, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.operation_templates
WHERE tenant_id = $1
  AND inactive = FALSE
  AND ($4::text IS NULL OR category = $4::text)
  AND ($5::text IS NULL OR source_module = $5::text)
  AND ($6::boolean IS NULL OR is_active = $6::boolean)
  AND ($7::text IS NULL OR template_key ILIKE '%' || $7::text || '%' OR name ILIKE '%' || $7::text || '%')
ORDER BY category ASC, name ASC
LIMIT $2 OFFSET $3
`

type ListOperationTemplatesParams struct {
	TenantID     uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit        int32       `db:"limit" json:"limit"`
	Offset       int32       `db:"offset" json:"offset"`
	Category     pgtype.Text `db:"category" json:"category"`
	SourceModule pgtype.Text `db:"source_module" json:"source_module"`
	ActiveOnly   pgtype.Bool `db:"active_only" json:"active_only"`
	Search       pgtype.Text `db:"search" json:"search"`
}

func (q *Queries) ListOperationTemplates(ctx context.Context, arg ListOperationTemplatesParams) ([]HrmsOperationTemplate, error) {
	rows, err := q.db.Query(ctx, listOperationTemplates,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Category,
		arg.SourceModule,
		arg.ActiveOnly,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsOperationTemplate
	for rows.Next() {
		var i HrmsOperationTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TemplateKey,
			&i.Name,
			&i.Category,
			&i.SourceModule,
			&i.SourceType,
			&i.WorkflowDefinitionID,
			&i.DefaultPriority,
			&i.DefaultSeverity,
			&i.AllowedActions,
			&i.LaunchSchema,
			&i.IsActive,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowDefinitionSteps = `-- name: ListWorkflowDefinitionSteps :many
SELECT id, tenant_id, workflow_definition_id, step_order, step_key, name, step_type, assignment_type, assignment_value, required, due_offset_hours, allowed_actions, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.workflow_definition_steps
WHERE tenant_id = $1 AND workflow_definition_id = $2 AND inactive = FALSE
ORDER BY step_order ASC, created_at ASC
`

type ListWorkflowDefinitionStepsParams struct {
	TenantID             uuid.UUID `db:"tenant_id" json:"tenant_id"`
	WorkflowDefinitionID uuid.UUID `db:"workflow_definition_id" json:"workflow_definition_id"`
}

func (q *Queries) ListWorkflowDefinitionSteps(ctx context.Context, arg ListWorkflowDefinitionStepsParams) ([]HrmsWorkflowDefinitionStep, error) {
	rows, err := q.db.Query(ctx, listWorkflowDefinitionSteps, arg.TenantID, arg.WorkflowDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsWorkflowDefinitionStep
	for rows.Next() {
		var i HrmsWorkflowDefinitionStep
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowDefinitionID,
			&i.StepOrder,
			&i.StepKey,
			&i.Name,
			&i.StepType,
			&i.AssignmentType,
			&i.AssignmentValue,
			&i.Required,
			&i.DueOffsetHours,
			&i.AllowedActions,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowDefinitions = `-- name: ListWorkflowDefinitions :many
SELECT id, tenant_id, workflow_key, name, module_key, description, status, visibility_scope, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.workflow_definitions
WHERE tenant_id = $1
  AND inactive = FALSE
  AND ($4::text IS NULL OR status = $4::text)
  AND ($5::text IS NULL OR module_key = $5::text)
  AND ($6::text IS NULL OR workflow_key ILIKE '%' || $6::text || '%' OR name ILIKE '%' || $6::text || '%')
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkflowDefinitionsParams struct {
	TenantID  uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
	Status    pgtype.Text `db:"status" json:"status"`
	ModuleKey pgtype.Text `db:"module_key" json:"module_key"`
	Search    pgtype.Text `db:"search" json:"search"`
}

func (q *Queries) ListWorkflowDefinitions(ctx context.Context, arg ListWorkflowDefinitionsParams) ([]HrmsWorkflowDefinition, error) {
	rows, err := q.db.Query(ctx, listWorkflowDefinitions,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.ModuleKey,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsWorkflowDefinition
	for rows.Next() {
		var i HrmsWorkflowDefinition
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowKey,
			&i.Name,
			&i.ModuleKey,
			&i.Description,
			&i.Status,
			&i.VisibilityScope,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTaskAttachments = `-- name: ListWorkflowTaskAttachments :many
SELECT id, tenant_id, task_id, comment_id, file_name, content_type, storage_path, checksum_sha256, size_bytes, visibility, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.workflow_task_attachments
WHERE tenant_id = $1 AND task_id = $2 AND inactive = FALSE
ORDER BY created_at DESC
`

type ListWorkflowTaskAttachmentsParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	TaskID   uuid.UUID `db:"task_id" json:"task_id"`
}

func (q *Queries) ListWorkflowTaskAttachments(ctx context.Context, arg ListWorkflowTaskAttachmentsParams) ([]HrmsWorkflowTaskAttachment, error) {
	rows, err := q.db.Query(ctx, listWorkflowTaskAttachments, arg.TenantID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsWorkflowTaskAttachment
	for rows.Next() {
		var i HrmsWorkflowTaskAttachment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TaskID,
			&i.CommentID,
			&i.FileName,
			&i.ContentType,
			&i.StoragePath,
			&i.ChecksumSha256,
			&i.SizeBytes,
			&i.Visibility,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTaskComments = `-- name: ListWorkflowTaskComments :many
SELECT id, tenant_id, task_id, visibility, body, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.workflow_task_comments
WHERE tenant_id = $1 AND task_id = $2 AND inactive = FALSE
ORDER BY created_at ASC
`

type ListWorkflowTaskCommentsParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	TaskID   uuid.UUID `db:"task_id" json:"task_id"`
}

func (q *Queries) ListWorkflowTaskComments(ctx context.Context, arg ListWorkflowTaskCommentsParams) ([]HrmsWorkflowTaskComment, error) {
	rows, err := q.db.Query(ctx, listWorkflowTaskComments, arg.TenantID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsWorkflowTaskComment
	for rows.Next() {
		var i HrmsWorkflowTaskComment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TaskID,
			&i.Visibility,
			&i.Body,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTaskEvents = `-- name: ListWorkflowTaskEvents :many
SELECT id, tenant_id, task_id, action, from_status, to_status, actor_user_id, remarks, metadata, inactive, created_at, created_by, updated_at, updated_by FROM hrms.workflow_task_events
WHERE tenant_id = $1 AND task_id = $2 AND inactive = FALSE
ORDER BY created_at ASC
`

type ListWorkflowTaskEventsParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	TaskID   uuid.UUID `db:"task_id" json:"task_id"`
}

func (q *Queries) ListWorkflowTaskEvents(ctx context.Context, arg ListWorkflowTaskEventsParams) ([]HrmsWorkflowTaskEvent, error) {
	rows, err := q.db.Query(ctx, listWorkflowTaskEvents, arg.TenantID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsWorkflowTaskEvent
	for rows.Next() {
		var i HrmsWorkflowTaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TaskID,
			&i.Action,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorUserID,
			&i.Remarks,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTaskWatchers = `-- name: ListWorkflowTaskWatchers :many
SELECT id, tenant_id, task_id, watcher_user_id, watch_reason, inactive, created_at, created_by, updated_at, updated_by FROM hrms.workflow_task_watchers
WHERE tenant_id = $1 AND task_id = $2 AND inactive = FALSE
ORDER BY created_at ASC
`

type ListWorkflowTaskWatchersParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	TaskID   uuid.UUID `db:"task_id" json:"task_id"`
}

func (q *Queries) ListWorkflowTaskWatchers(ctx context.Context, arg ListWorkflowTaskWatchersParams) ([]HrmsWorkflowTaskWatcher, error) {
	rows, err := q.db.Query(ctx, listWorkflowTaskWatchers, arg.TenantID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrmsWorkflowTaskWatcher
	for rows.Next() {
		var i HrmsWorkflowTaskWatcher
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TaskID,
			&i.WatcherUserID,
			&i.WatchReason,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTasks = `-- name: ListWorkflowTasks :many
SELECT wt.id, wt.tenant_id, wt.task_number, wt.template_id, wt.workflow_definition_id, wt.workflow_step_id, wt.parent_task_id, wt.source_module, wt.source_type, wt.source_id, wt.source_record_label, wt.title, wt.description, wt.requester_user_id, wt.assignee_user_id, wt.assignee_role, wt.assignee_team, wt.delegated_from_user_id, wt.status, wt.priority, wt.severity, wt.visibility_scope, wt.due_at, wt.completed_at, wt.completed_by, wt.action_schema, wt.metadata, wt.inactive, wt.created_at, wt.created_by, wt.updated_at, wt.updated_by,
       (SELECT COUNT(*)::int FROM hrms.workflow_task_comments c WHERE c.tenant_id = wt.tenant_id AND c.task_id = wt.id AND c.inactive = FALSE) AS comment_count,
       (SELECT COUNT(*)::int FROM hrms.workflow_task_attachments a WHERE a.tenant_id = wt.tenant_id AND a.task_id = wt.id AND a.inactive = FALSE) AS attachment_count,
       EXISTS (
           SELECT 1 FROM hrms.workflow_task_watchers w
           WHERE w.tenant_id = wt.tenant_id AND w.task_id = wt.id AND w.watcher_user_id = $4::uuid AND w.inactive = FALSE
       ) AS watched_by_viewer
FROM hrms.workflow_tasks wt
WHERE wt.tenant_id = $1
  AND wt.inactive = FALSE
  AND ($5::text IS NULL OR wt.status = $5::text)
  AND ($6::text IS NULL OR wt.severity = $6::text)
  AND ($7::text IS NULL OR wt.source_module = $7::text)
  AND ($8::text IS NULL OR wt.task_number ILIKE '%' || $8::text || '%' OR wt.title ILIKE '%' || $8::text || '%' OR COALESCE(wt.source_record_label, '') ILIKE '%' || $8::text || '%')
  AND (
      $9::text IS NULL OR $9::text = 'all'
      OR ($9::text = 'inbox' AND wt.status NOT IN ('approved','rejected','completed','cancelled') AND (wt.assignee_user_id = $4::uuid OR $4::uuid IS NULL OR wt.assignee_role = $10::text OR wt.assignee_team = $11::text))
      OR ($9::text = 'my_requests' AND wt.requester_user_id = $4::uuid)
      OR ($9::text = 'team' AND (wt.assignee_role = $10::text OR wt.assignee_team = $11::text))
      OR ($9::text = 'watching' AND EXISTS (SELECT 1 FROM hrms.workflow_task_watchers w WHERE w.tenant_id = wt.tenant_id AND w.task_id = wt.id AND w.watcher_user_id = $4::uuid AND w.inactive = FALSE))
      OR ($9::text = 'completed' AND wt.status IN ('approved','rejected','completed','cancelled'))
      OR ($9::text = 'delegated' AND (wt.delegated_from_user_id = $4::uuid OR wt.status = 'delegated'))
  )
ORDER BY
  CASE WHEN wt.status IN ('approved','rejected','completed','cancelled') THEN 1 ELSE 0 END,
  wt.due_at ASC NULLS LAST,
  wt.priority ASC,
  wt.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkflowTasksParams struct {
	TenantID     uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Limit        int32       `db:"limit" json:"limit"`
	Offset       int32       `db:"offset" json:"offset"`
	ViewerUserID pgtype.UUID `db:"viewer_user_id" json:"viewer_user_id"`
	Status       pgtype.Text `db:"status" json:"status"`
	Severity     pgtype.Text `db:"severity" json:"severity"`
	SourceModule pgtype.Text `db:"source_module" json:"source_module"`
	Search       pgtype.Text `db:"search" json:"search"`
	ViewKey      pgtype.Text `db:"view_key" json:"view_key"`
	ViewerRole   pgtype.Text `db:"viewer_role" json:"viewer_role"`
	ViewerTeam   pgtype.Text `db:"viewer_team" json:"viewer_team"`
}

type ListWorkflowTasksRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	TenantID             uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	TaskNumber           string             `db:"task_number" json:"task_number"`
	TemplateID           pgtype.UUID        `db:"template_id" json:"template_id"`
	WorkflowDefinitionID pgtype.UUID        `db:"workflow_definition_id" json:"workflow_definition_id"`
	WorkflowStepID       pgtype.UUID        `db:"workflow_step_id" json:"workflow_step_id"`
	ParentTaskID         pgtype.UUID        `db:"parent_task_id" json:"parent_task_id"`
	SourceModule         string             `db:"source_module" json:"source_module"`
	SourceType           string             `db:"source_type" json:"source_type"`
	SourceID             pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceRecordLabel    pgtype.Text        `db:"source_record_label" json:"source_record_label"`
	Title                string             `db:"title" json:"title"`
	Description          pgtype.Text        `db:"description" json:"description"`
	RequesterUserID      pgtype.UUID        `db:"requester_user_id" json:"requester_user_id"`
	AssigneeUserID       pgtype.UUID        `db:"assignee_user_id" json:"assignee_user_id"`
	AssigneeRole         pgtype.Text        `db:"assignee_role" json:"assignee_role"`
	AssigneeTeam         pgtype.Text        `db:"assignee_team" json:"assignee_team"`
	DelegatedFromUserID  pgtype.UUID        `db:"delegated_from_user_id" json:"delegated_from_user_id"`
	Status               string             `db:"status" json:"status"`
	Priority             int32              `db:"priority" json:"priority"`
	Severity             string             `db:"severity" json:"severity"`
	VisibilityScope      string             `db:"visibility_scope" json:"visibility_scope"`
	DueAt                pgtype.Timestamptz `db:"due_at" json:"due_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CompletedBy          pgtype.UUID        `db:"completed_by" json:"completed_by"`
	ActionSchema         []byte             `db:"action_schema" json:"action_schema"`
	Metadata             []byte             `db:"metadata" json:"metadata"`
	Inactive             bool               `db:"inactive" json:"inactive"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy            pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy            pgtype.UUID        `db:"updated_by" json:"updated_by"`
	CommentCount         int32              `db:"comment_count" json:"comment_count"`
	AttachmentCount      int32              `db:"attachment_count" json:"attachment_count"`
	WatchedByViewer      bool               `db:"watched_by_viewer" json:"watched_by_viewer"`
}

func (q *Queries) ListWorkflowTasks(ctx context.Context, arg ListWorkflowTasksParams) ([]ListWorkflowTasksRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowTasks,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.ViewerUserID,
		arg.Status,
		arg.Severity,
		arg.SourceModule,
		arg.Search,
		arg.ViewKey,
		arg.ViewerRole,
		arg.ViewerTeam,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowTasksRow
	for rows.Next() {
		var i ListWorkflowTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TaskNumber,
			&i.TemplateID,
			&i.WorkflowDefinitionID,
			&i.WorkflowStepID,
			&i.ParentTaskID,
			&i.SourceModule,
			&i.SourceType,
			&i.SourceID,
			&i.SourceRecordLabel,
			&i.Title,
			&i.Description,
			&i.RequesterUserID,
			&i.AssigneeUserID,
			&i.AssigneeRole,
			&i.AssigneeTeam,
			&i.DelegatedFromUserID,
			&i.Status,
			&i.Priority,
			&i.Severity,
			&i.VisibilityScope,
			&i.DueAt,
			&i.CompletedAt,
			&i.CompletedBy,
			&i.ActionSchema,
			&i.Metadata,
			&i.Inactive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.CommentCount,
			&i.AttachmentCount,
			&i.WatchedByViewer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkflowTaskWatcher = `-- name: RemoveWorkflowTaskWatcher :exec
UPDATE hrms.workflow_task_watchers
SET inactive = TRUE, updated_by = $4, updated_at = now()
WHERE tenant_id = $1 AND task_id = $2 AND watcher_user_id = $3 AND inactive = FALSE
`

type RemoveWorkflowTaskWatcherParams struct {
	TenantID      uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	TaskID        uuid.UUID   `db:"task_id" json:"task_id"`
	WatcherUserID uuid.UUID   `db:"watcher_user_id" json:"watcher_user_id"`
	UpdatedBy     pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) RemoveWorkflowTaskWatcher(ctx context.Context, arg RemoveWorkflowTaskWatcherParams) error {
	_, err := q.db.Exec(ctx, removeWorkflowTaskWatcher,
		arg.TenantID,
		arg.TaskID,
		arg.WatcherUserID,
		arg.UpdatedBy,
	)
	return err
}

const updateOperationTemplate = `-- name: UpdateOperationTemplate :one
UPDATE hrms.operation_templates
SET template_key = $3,
    name = $4,
    category = $5,
    source_module = $6,
    source_type = $7,
    workflow_definition_id = $8,
    default_priority = $9,
    default_severity = $10,
    allowed_actions = $11,
    launch_schema = $12,
    is_active = $13,
    metadata = $14,
    updated_by = $15,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
RETURNING id, tenant_id, template_key, name, category, source_module, source_type, workflow_definition_id, default_priority, default_severity, allowed_actions, launch_schema, is_active, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateOperationTemplateParams struct {
	TenantID             uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID                   uuid.UUID   `db:"id" json:"id"`
	TemplateKey          string      `db:"template_key" json:"template_key"`
	Name                 string      `db:"name" json:"name"`
	Category             string      `db:"category" json:"category"`
	SourceModule         string      `db:"source_module" json:"source_module"`
	SourceType           string      `db:"source_type" json:"source_type"`
	WorkflowDefinitionID pgtype.UUID `db:"workflow_definition_id" json:"workflow_definition_id"`
	DefaultPriority      int32       `db:"default_priority" json:"default_priority"`
	DefaultSeverity      string      `db:"default_severity" json:"default_severity"`
	AllowedActions       []byte      `db:"allowed_actions" json:"allowed_actions"`
	LaunchSchema         []byte      `db:"launch_schema" json:"launch_schema"`
	IsActive             bool        `db:"is_active" json:"is_active"`
	Metadata             []byte      `db:"metadata" json:"metadata"`
	UpdatedBy            pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateOperationTemplate(ctx context.Context, arg UpdateOperationTemplateParams) (HrmsOperationTemplate, error) {
	row := q.db.QueryRow(ctx, updateOperationTemplate,
		arg.TenantID,
		arg.ID,
		arg.TemplateKey,
		arg.Name,
		arg.Category,
		arg.SourceModule,
		arg.SourceType,
		arg.WorkflowDefinitionID,
		arg.DefaultPriority,
		arg.DefaultSeverity,
		arg.AllowedActions,
		arg.LaunchSchema,
		arg.IsActive,
		arg.Metadata,
		arg.UpdatedBy,
	)
	var i HrmsOperationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TemplateKey,
		&i.Name,
		&i.Category,
		&i.SourceModule,
		&i.SourceType,
		&i.WorkflowDefinitionID,
		&i.DefaultPriority,
		&i.DefaultSeverity,
		&i.AllowedActions,
		&i.LaunchSchema,
		&i.IsActive,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateWorkflowDefinition = `-- name: UpdateWorkflowDefinition :one
UPDATE hrms.workflow_definitions
SET workflow_key = $3,
    name = $4,
    module_key = $5,
    description = $6,
    status = $7,
    visibility_scope = $8,
    metadata = $9,
    updated_by = $10,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
RETURNING id, tenant_id, workflow_key, name, module_key, description, status, visibility_scope, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateWorkflowDefinitionParams struct {
	TenantID        uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID              uuid.UUID   `db:"id" json:"id"`
	WorkflowKey     string      `db:"workflow_key" json:"workflow_key"`
	Name            string      `db:"name" json:"name"`
	ModuleKey       string      `db:"module_key" json:"module_key"`
	Description     pgtype.Text `db:"description" json:"description"`
	Status          string      `db:"status" json:"status"`
	VisibilityScope string      `db:"visibility_scope" json:"visibility_scope"`
	Metadata        []byte      `db:"metadata" json:"metadata"`
	UpdatedBy       pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateWorkflowDefinition(ctx context.Context, arg UpdateWorkflowDefinitionParams) (HrmsWorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, updateWorkflowDefinition,
		arg.TenantID,
		arg.ID,
		arg.WorkflowKey,
		arg.Name,
		arg.ModuleKey,
		arg.Description,
		arg.Status,
		arg.VisibilityScope,
		arg.Metadata,
		arg.UpdatedBy,
	)
	var i HrmsWorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowKey,
		&i.Name,
		&i.ModuleKey,
		&i.Description,
		&i.Status,
		&i.VisibilityScope,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateWorkflowDefinitionStep = `-- name: UpdateWorkflowDefinitionStep :one
UPDATE hrms.workflow_definition_steps
SET step_order = $3,
    step_key = $4,
    name = $5,
    step_type = $6,
    assignment_type = $7,
    assignment_value = $8,
    required = $9,
    due_offset_hours = $10,
    allowed_actions = $11,
    metadata = $12,
    updated_by = $13,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
RETURNING id, tenant_id, workflow_definition_id, step_order, step_key, name, step_type, assignment_type, assignment_value, required, due_offset_hours, allowed_actions, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateWorkflowDefinitionStepParams struct {
	TenantID        uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID              uuid.UUID   `db:"id" json:"id"`
	StepOrder       int32       `db:"step_order" json:"step_order"`
	StepKey         string      `db:"step_key" json:"step_key"`
	Name            string      `db:"name" json:"name"`
	StepType        string      `db:"step_type" json:"step_type"`
	AssignmentType  string      `db:"assignment_type" json:"assignment_type"`
	AssignmentValue pgtype.Text `db:"assignment_value" json:"assignment_value"`
	Required        bool        `db:"required" json:"required"`
	DueOffsetHours  int32       `db:"due_offset_hours" json:"due_offset_hours"`
	AllowedActions  []byte      `db:"allowed_actions" json:"allowed_actions"`
	Metadata        []byte      `db:"metadata" json:"metadata"`
	UpdatedBy       pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateWorkflowDefinitionStep(ctx context.Context, arg UpdateWorkflowDefinitionStepParams) (HrmsWorkflowDefinitionStep, error) {
	row := q.db.QueryRow(ctx, updateWorkflowDefinitionStep,
		arg.TenantID,
		arg.ID,
		arg.StepOrder,
		arg.StepKey,
		arg.Name,
		arg.StepType,
		arg.AssignmentType,
		arg.AssignmentValue,
		arg.Required,
		arg.DueOffsetHours,
		arg.AllowedActions,
		arg.Metadata,
		arg.UpdatedBy,
	)
	var i HrmsWorkflowDefinitionStep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowDefinitionID,
		&i.StepOrder,
		&i.StepKey,
		&i.Name,
		&i.StepType,
		&i.AssignmentType,
		&i.AssignmentValue,
		&i.Required,
		&i.DueOffsetHours,
		&i.AllowedActions,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateWorkflowTask = `-- name: UpdateWorkflowTask :one
UPDATE hrms.workflow_tasks
SET title = $3,
    description = $4,
    assignee_user_id = $5,
    assignee_role = $6,
    assignee_team = $7,
    priority = $8,
    severity = $9,
    visibility_scope = $10,
    due_at = $11,
    action_schema = $12,
    metadata = $13,
    updated_by = $14,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
RETURNING id, tenant_id, task_number, template_id, workflow_definition_id, workflow_step_id, parent_task_id, source_module, source_type, source_id, source_record_label, title, description, requester_user_id, assignee_user_id, assignee_role, assignee_team, delegated_from_user_id, status, priority, severity, visibility_scope, due_at, completed_at, completed_by, action_schema, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateWorkflowTaskParams struct {
	TenantID        uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	ID              uuid.UUID          `db:"id" json:"id"`
	Title           string             `db:"title" json:"title"`
	Description     pgtype.Text        `db:"description" json:"description"`
	AssigneeUserID  pgtype.UUID        `db:"assignee_user_id" json:"assignee_user_id"`
	AssigneeRole    pgtype.Text        `db:"assignee_role" json:"assignee_role"`
	AssigneeTeam    pgtype.Text        `db:"assignee_team" json:"assignee_team"`
	Priority        int32              `db:"priority" json:"priority"`
	Severity        string             `db:"severity" json:"severity"`
	VisibilityScope string             `db:"visibility_scope" json:"visibility_scope"`
	DueAt           pgtype.Timestamptz `db:"due_at" json:"due_at"`
	ActionSchema    []byte             `db:"action_schema" json:"action_schema"`
	Metadata        []byte             `db:"metadata" json:"metadata"`
	UpdatedBy       pgtype.UUID        `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateWorkflowTask(ctx context.Context, arg UpdateWorkflowTaskParams) (HrmsWorkflowTask, error) {
	row := q.db.QueryRow(ctx, updateWorkflowTask,
		arg.TenantID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AssigneeUserID,
		arg.AssigneeRole,
		arg.AssigneeTeam,
		arg.Priority,
		arg.Severity,
		arg.VisibilityScope,
		arg.DueAt,
		arg.ActionSchema,
		arg.Metadata,
		arg.UpdatedBy,
	)
	var i HrmsWorkflowTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskNumber,
		&i.TemplateID,
		&i.WorkflowDefinitionID,
		&i.WorkflowStepID,
		&i.ParentTaskID,
		&i.SourceModule,
		&i.SourceType,
		&i.SourceID,
		&i.SourceRecordLabel,
		&i.Title,
		&i.Description,
		&i.RequesterUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.AssigneeTeam,
		&i.DelegatedFromUserID,
		&i.Status,
		&i.Priority,
		&i.Severity,
		&i.VisibilityScope,
		&i.DueAt,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.ActionSchema,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateWorkflowTaskStatus = `-- name: UpdateWorkflowTaskStatus :one
UPDATE hrms.workflow_tasks
SET status = $3,
    assignee_user_id = COALESCE($4, assignee_user_id),
    assignee_role = COALESCE($5, assignee_role),
    assignee_team = COALESCE($6, assignee_team),
    delegated_from_user_id = $7,
    completed_at = CASE WHEN $3 IN ('approved','rejected','completed','cancelled') THEN now() ELSE completed_at END,
    completed_by = CASE WHEN $3 IN ('approved','rejected','completed','cancelled') THEN $8 ELSE completed_by END,
    updated_by = $8,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND inactive = FALSE
RETURNING id, tenant_id, task_number, template_id, workflow_definition_id, workflow_step_id, parent_task_id, source_module, source_type, source_id, source_record_label, title, description, requester_user_id, assignee_user_id, assignee_role, assignee_team, delegated_from_user_id, status, priority, severity, visibility_scope, due_at, completed_at, completed_by, action_schema, metadata, inactive, created_at, created_by, updated_at, updated_by
`

type UpdateWorkflowTaskStatusParams struct {
	TenantID            uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	ID                  uuid.UUID   `db:"id" json:"id"`
	Status              string      `db:"status" json:"status"`
	AssigneeUserID      pgtype.UUID `db:"assignee_user_id" json:"assignee_user_id"`
	AssigneeRole        pgtype.Text `db:"assignee_role" json:"assignee_role"`
	AssigneeTeam        pgtype.Text `db:"assignee_team" json:"assignee_team"`
	DelegatedFromUserID pgtype.UUID `db:"delegated_from_user_id" json:"delegated_from_user_id"`
	UpdatedBy           pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateWorkflowTaskStatus(ctx context.Context, arg UpdateWorkflowTaskStatusParams) (HrmsWorkflowTask, error) {
	row := q.db.QueryRow(ctx, updateWorkflowTaskStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.AssigneeUserID,
		arg.AssigneeRole,
		arg.AssigneeTeam,
		arg.DelegatedFromUserID,
		arg.UpdatedBy,
	)
	var i HrmsWorkflowTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskNumber,
		&i.TemplateID,
		&i.WorkflowDefinitionID,
		&i.WorkflowStepID,
		&i.ParentTaskID,
		&i.SourceModule,
		&i.SourceType,
		&i.SourceID,
		&i.SourceRecordLabel,
		&i.Title,
		&i.Description,
		&i.RequesterUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.AssigneeTeam,
		&i.DelegatedFromUserID,
		&i.Status,
		&i.Priority,
		&i.Severity,
		&i.VisibilityScope,
		&i.DueAt,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.ActionSchema,
		&i.Metadata,
		&i.Inactive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
