package ports

import (
	"context"

	"github.com/google/uuid"
	"github.com/ranakdinesh/spur-hrms/core/domain"
)

type TenantService interface {
	RunAsSystem(ctx context.Context, fn func(context.Context) error) error
	VerifyLegacyPBKDF2Password(password string, encodedHash string) (bool, error)
	MigrateLegacyPassword(ctx context.Context, cmd LegacyPasswordMigrationCommand) (*LegacyPasswordMigrationResult, error)
	UpsertTenantProfile(ctx context.Context, cmd UpsertTenantProfileCmd) (*domain.TenantProfile, error)
	GetTenantProfile(ctx context.Context, tenantID uuid.UUID) (*domain.TenantProfile, error)
	ResolveTenantBySubdomain(ctx context.Context, subdomain string) (*domain.TenantProfile, error)
	ResolveTenantByActivationCode(ctx context.Context, code string) (*domain.TenantProfile, error)
	ProvisionTenant(ctx context.Context, cmd ProvisionTenantCommand) (*domain.TenantProvisioning, error)
	GetTenantProvisioningStatus(ctx context.Context, tenantID uuid.UUID) (*TenantProvisioningStatus, error)
	GetTenantBranding(ctx context.Context, tenantID uuid.UUID) (*domain.TenantBranding, error)
	UpsertTenantBranding(ctx context.Context, cmd UpsertTenantBrandingCmd) (*domain.TenantBranding, error)
	ResolveTenantBrandingByHost(ctx context.Context, host string) (*domain.TenantBranding, error)
	UpsertTenantSetting(ctx context.Context, cmd UpsertTenantSettingCmd) (*domain.TenantSetting, error)
	GetTenantSetting(ctx context.Context, tenantID uuid.UUID, key string) (*domain.TenantSetting, error)
	ListTenantSettings(ctx context.Context, tenantID uuid.UUID) ([]*domain.TenantSetting, error)
	DeleteTenantSetting(ctx context.Context, tenantID uuid.UUID, key string) error
	CreateBranch(ctx context.Context, cmd BranchCommand) (*domain.Branch, error)
	ListBranches(ctx context.Context, tenantID uuid.UUID) ([]*domain.Branch, error)
	GetBranch(ctx context.Context, tenantID uuid.UUID, branchID uuid.UUID) (*domain.Branch, error)
	UpdateBranch(ctx context.Context, cmd BranchCommand) (*domain.Branch, error)
	DeleteBranch(ctx context.Context, tenantID uuid.UUID, branchID uuid.UUID, actorID *uuid.UUID) error
	CreateDepartment(ctx context.Context, cmd DepartmentCommand) (*domain.Department, error)
	ListDepartments(ctx context.Context, tenantID uuid.UUID) ([]*domain.Department, error)
	GetDepartment(ctx context.Context, tenantID uuid.UUID, departmentID uuid.UUID) (*domain.Department, error)
	UpdateDepartment(ctx context.Context, cmd DepartmentCommand) (*domain.Department, error)
	DeleteDepartment(ctx context.Context, tenantID uuid.UUID, departmentID uuid.UUID, actorID *uuid.UUID) error
	CreateDesignation(ctx context.Context, cmd DesignationCommand) (*domain.Designation, error)
	ListDesignations(ctx context.Context, tenantID uuid.UUID) ([]*domain.Designation, error)
	GetDesignation(ctx context.Context, tenantID uuid.UUID, designationID uuid.UUID) (*domain.Designation, error)
	UpdateDesignation(ctx context.Context, cmd DesignationCommand) (*domain.Designation, error)
	DeleteDesignation(ctx context.Context, tenantID uuid.UUID, designationID uuid.UUID, actorID *uuid.UUID) error
	CreateDesignationLevelCode(ctx context.Context, cmd DesignationLevelCodeCommand) (*domain.DesignationLevelCode, error)
	ListDesignationLevelCodes(ctx context.Context, tenantID uuid.UUID, actorID *uuid.UUID) ([]*domain.DesignationLevelCode, error)
	UpdateDesignationLevelCode(ctx context.Context, cmd DesignationLevelCodeCommand) (*domain.DesignationLevelCode, error)
	DeleteDesignationLevelCode(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateDesignationSeniorityRank(ctx context.Context, cmd DesignationSeniorityRankCommand) (*domain.DesignationSeniorityRank, error)
	ListDesignationSeniorityRanks(ctx context.Context, tenantID uuid.UUID, actorID *uuid.UUID) ([]*domain.DesignationSeniorityRank, error)
	UpdateDesignationSeniorityRank(ctx context.Context, cmd DesignationSeniorityRankCommand) (*domain.DesignationSeniorityRank, error)
	DeleteDesignationSeniorityRank(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateWorkerType(ctx context.Context, cmd WorkerTypeCommand) (*domain.WorkerType, error)
	ListWorkerTypes(ctx context.Context, tenantID uuid.UUID, actorID *uuid.UUID) ([]*domain.WorkerType, error)
	GetWorkerType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.WorkerType, error)
	GetWorkerTypeByCode(ctx context.Context, tenantID uuid.UUID, code string) (*domain.WorkerType, error)
	UpdateWorkerType(ctx context.Context, cmd WorkerTypeCommand) (*domain.WorkerType, error)
	DeleteWorkerType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateWorkerClassificationRule(ctx context.Context, cmd WorkerClassificationRuleCommand) (*domain.WorkerClassificationRule, error)
	ListWorkerClassificationRules(ctx context.Context, tenantID uuid.UUID, workerTypeID *uuid.UUID) ([]*domain.WorkerClassificationRule, error)
	GetWorkerClassificationRule(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.WorkerClassificationRule, error)
	UpdateWorkerClassificationRule(ctx context.Context, cmd WorkerClassificationRuleCommand) (*domain.WorkerClassificationRule, error)
	DeleteWorkerClassificationRule(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateWorkerProfile(ctx context.Context, cmd WorkerProfileCommand) (*domain.WorkerProfile, error)
	UpdateWorkerProfile(ctx context.Context, cmd WorkerProfileCommand) (*domain.WorkerProfile, error)
	GetWorkerProfile(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.WorkerProfile, error)
	GetWorkerProfileByEmployeeID(ctx context.Context, tenantID uuid.UUID, employeeID uuid.UUID) (*domain.WorkerProfile, error)
	ListWorkerProfiles(ctx context.Context, filter domain.WorkerProfileFilter) ([]*domain.WorkerProfileListItem, error)
	DeleteWorkerProfile(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateEngagement(ctx context.Context, cmd EngagementCommand) (*domain.Engagement, error)
	UpdateEngagement(ctx context.Context, cmd EngagementCommand) (*domain.Engagement, error)
	UpdateEngagementStatus(ctx context.Context, cmd EngagementStatusCommand) (*domain.Engagement, error)
	GetEngagement(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Engagement, error)
	ListEngagements(ctx context.Context, filter domain.EngagementFilter) ([]*domain.EngagementListItem, error)
	DeleteEngagement(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateWorkLog(ctx context.Context, cmd WorkLogCommand) (*domain.WorkLog, error)
	UpdateWorkLog(ctx context.Context, cmd WorkLogCommand) (*domain.WorkLog, error)
	SubmitWorkLog(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) (*domain.WorkLog, error)
	ReviewWorkLog(ctx context.Context, cmd WorkLogStatusCommand) (*domain.WorkLog, error)
	GetWorkLog(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.WorkLog, error)
	ListWorkLogs(ctx context.Context, filter domain.WorkLogFilter) ([]*domain.WorkLogListItem, error)
	ListWorkLogRollups(ctx context.Context, filter domain.WorkLogFilter) ([]*domain.WorkLogRollup, error)
	DeleteWorkLog(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateProject(ctx context.Context, cmd ProjectCommand) (*domain.Project, error)
	UpdateProject(ctx context.Context, cmd ProjectCommand) (*domain.Project, error)
	UpdateProjectStatus(ctx context.Context, cmd ProjectStatusCommand) (*domain.Project, error)
	GetProject(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Project, error)
	ListProjects(ctx context.Context, filter domain.ProjectFilter) ([]*domain.ProjectListItem, error)
	DeleteProject(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateComplianceRule(ctx context.Context, cmd ComplianceRuleCommand) (*domain.ComplianceRule, error)
	UpdateComplianceRule(ctx context.Context, cmd ComplianceRuleCommand) (*domain.ComplianceRule, error)
	GetComplianceRule(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.ComplianceRule, error)
	ListComplianceRules(ctx context.Context, filter domain.ComplianceRuleFilter) ([]*domain.ComplianceRule, error)
	DeleteComplianceRule(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	SeedDefaultComplianceRules(ctx context.Context, tenantID uuid.UUID, actorID *uuid.UUID) ([]*domain.ComplianceRule, error)
	GenerateComplianceChecklist(ctx context.Context, cmd ComplianceChecklistGenerateCommand) ([]*domain.ComplianceChecklistItem, error)
	ListComplianceChecklistItems(ctx context.Context, filter domain.ComplianceChecklistFilter) ([]*domain.ComplianceChecklistItem, error)
	UpdateComplianceChecklistStatus(ctx context.Context, cmd ComplianceChecklistStatusCommand) (*domain.ComplianceChecklistItem, error)
	UpdateComplianceChecklistEvidence(ctx context.Context, cmd ComplianceEvidenceCommand) (*domain.ComplianceChecklistItem, error)
	WaiveComplianceChecklistItem(ctx context.Context, cmd ComplianceWaiverCommand) (*domain.ComplianceChecklistItem, error)
	DeleteComplianceChecklistItem(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	GetComplianceSummary(ctx context.Context, tenantID uuid.UUID) ([]*domain.ComplianceSummaryRow, error)
	ListComplianceEvents(ctx context.Context, tenantID uuid.UUID, checklistItemID *uuid.UUID, ruleID *uuid.UUID) ([]*domain.ComplianceEvent, error)
	CreateHRCaseCategory(ctx context.Context, cmd HRCaseCategoryCommand) (*domain.HRCaseCategory, error)
	UpdateHRCaseCategory(ctx context.Context, cmd HRCaseCategoryCommand) (*domain.HRCaseCategory, error)
	ListHRCaseCategories(ctx context.Context, tenantID uuid.UUID, activeOnly *bool) ([]*domain.HRCaseCategory, error)
	DeleteHRCaseCategory(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateHRCaseSLAPolicy(ctx context.Context, cmd HRCaseSLAPolicyCommand) (*domain.HRCaseSLAPolicy, error)
	UpdateHRCaseSLAPolicy(ctx context.Context, cmd HRCaseSLAPolicyCommand) (*domain.HRCaseSLAPolicy, error)
	ListHRCaseSLAPolicies(ctx context.Context, tenantID uuid.UUID, categoryID *uuid.UUID, priority *string) ([]*domain.HRCaseSLAPolicy, error)
	DeleteHRCaseSLAPolicy(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateHRCase(ctx context.Context, cmd HRCaseCommand) (*domain.HRCase, error)
	UpdateHRCase(ctx context.Context, cmd HRCaseCommand) (*domain.HRCase, error)
	ListHRCases(ctx context.Context, filter domain.HRCaseFilter) (*domain.HRCasePage, error)
	GetHRCaseWorkspace(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, includeInternal bool) (*domain.HRCaseWorkspace, error)
	UpdateHRCaseStatus(ctx context.Context, cmd HRCaseStatusCommand) (*domain.HRCase, error)
	AssignHRCase(ctx context.Context, cmd HRCaseAssignmentCommand) (*domain.HRCase, error)
	CreateHRCaseComment(ctx context.Context, cmd HRCaseCommentCommand) (*domain.HRCaseComment, error)
	CreateHRCaseAttachment(ctx context.Context, cmd HRCaseAttachmentCommand) (*domain.HRCaseAttachment, error)
	CreateERCaseCategory(ctx context.Context, cmd ERCaseCategoryCommand) (*domain.ERCaseCategory, error)
	UpdateERCaseCategory(ctx context.Context, cmd ERCaseCategoryCommand) (*domain.ERCaseCategory, error)
	ListERCaseCategories(ctx context.Context, tenantID uuid.UUID, activeOnly *bool) ([]*domain.ERCaseCategory, error)
	DeleteERCaseCategory(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateERCase(ctx context.Context, cmd ERCaseCommand) (*domain.ERCase, error)
	UpdateERCase(ctx context.Context, cmd ERCaseCommand) (*domain.ERCase, error)
	UpdateERCaseStatus(ctx context.Context, cmd ERCaseStatusCommand) (*domain.ERCase, error)
	UpdateERCaseLegalHold(ctx context.Context, cmd ERCaseLegalHoldCommand) (*domain.ERCase, error)
	ListERCases(ctx context.Context, filter domain.ERCaseFilter) (*domain.ERCasePage, error)
	GetERCaseWorkspace(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.ERCaseWorkspace, error)
	CreateERCaseParty(ctx context.Context, cmd ERCasePartyCommand) (*domain.ERCaseParty, error)
	CreateERAllegation(ctx context.Context, cmd ERAllegationCommand) (*domain.ERAllegation, error)
	CreateERInvestigationStep(ctx context.Context, cmd ERInvestigationStepCommand) (*domain.ERInvestigationStep, error)
	UpdateERInvestigationStepStatus(ctx context.Context, cmd ERInvestigationStepCommand) (*domain.ERInvestigationStep, error)
	CreateERWitnessNote(ctx context.Context, cmd ERWitnessNoteCommand) (*domain.ERWitnessNote, error)
	CreateEREvidenceAttachment(ctx context.Context, cmd EREvidenceAttachmentCommand) (*domain.EREvidenceAttachment, error)
	CreateERFinding(ctx context.Context, cmd ERFindingCommand) (*domain.ERFinding, error)
	CreateERActionPlan(ctx context.Context, cmd ERActionPlanCommand) (*domain.ERActionPlan, error)
	UpdateERActionPlanStatus(ctx context.Context, cmd ERActionPlanCommand) (*domain.ERActionPlan, error)
	CreateSkillCategory(ctx context.Context, cmd SkillCategoryCommand) (*domain.SkillCategory, error)
	UpdateSkillCategory(ctx context.Context, cmd SkillCategoryCommand) (*domain.SkillCategory, error)
	GetSkillCategory(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.SkillCategory, error)
	ListSkillCategories(ctx context.Context, filter domain.SkillCategoryFilter) ([]*domain.SkillCategory, error)
	DeleteSkillCategory(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateSkill(ctx context.Context, cmd SkillCommand) (*domain.Skill, error)
	UpdateSkill(ctx context.Context, cmd SkillCommand) (*domain.Skill, error)
	GetSkill(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Skill, error)
	ListSkills(ctx context.Context, filter domain.SkillFilter) ([]*domain.Skill, error)
	DeleteSkill(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateWorkerSkill(ctx context.Context, cmd WorkerSkillCommand) (*domain.WorkerSkill, error)
	UpdateWorkerSkill(ctx context.Context, cmd WorkerSkillCommand) (*domain.WorkerSkill, error)
	GetWorkerSkill(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.WorkerSkill, error)
	ListWorkerSkills(ctx context.Context, filter domain.WorkerSkillFilter) ([]*domain.WorkerSkill, error)
	UpdateWorkerSkillVerification(ctx context.Context, cmd WorkerSkillVerificationCommand) (*domain.WorkerSkill, error)
	DeleteWorkerSkill(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateWorkerSkillAssessment(ctx context.Context, cmd WorkerSkillAssessmentCommand) (*domain.WorkerSkillAssessment, error)
	ListWorkerSkillAssessments(ctx context.Context, tenantID uuid.UUID, workerSkillID *uuid.UUID) ([]*domain.WorkerSkillAssessment, error)
	GetSkillsSummary(ctx context.Context, tenantID uuid.UUID) ([]*domain.SkillsSummaryRow, error)
	CreateProjectSkillRequirement(ctx context.Context, cmd ProjectSkillRequirementCommand) (*domain.ProjectSkillRequirement, error)
	UpdateProjectSkillRequirement(ctx context.Context, cmd ProjectSkillRequirementCommand) (*domain.ProjectSkillRequirement, error)
	GetProjectSkillRequirement(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.ProjectSkillRequirement, error)
	ListProjectSkillRequirements(ctx context.Context, filter domain.ProjectSkillRequirementFilter) ([]*domain.ProjectSkillRequirement, error)
	DeleteProjectSkillRequirement(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListProjectSkillGapRows(ctx context.Context, filter domain.ProjectSkillRequirementFilter) ([]*domain.ProjectSkillGapRow, error)
	ListSkillGapSummary(ctx context.Context, tenantID uuid.UUID, projectID *uuid.UUID) ([]*domain.SkillGapSummaryRow, error)
	ListSinglePersonSkillDependencies(ctx context.Context, tenantID uuid.UUID, projectID *uuid.UUID) ([]*domain.SinglePersonSkillDependency, error)
	CreateLearningCourse(ctx context.Context, cmd LearningCourseCommand) (*domain.LearningCourse, error)
	UpdateLearningCourse(ctx context.Context, cmd LearningCourseCommand) (*domain.LearningCourse, error)
	GetLearningCourse(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.LearningCourse, error)
	ListLearningCourses(ctx context.Context, filter domain.LearningCourseFilter) ([]*domain.LearningCourse, error)
	DeleteLearningCourse(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateLearningPath(ctx context.Context, cmd LearningPathCommand) (*domain.LearningPath, error)
	UpdateLearningPath(ctx context.Context, cmd LearningPathCommand) (*domain.LearningPath, error)
	GetLearningPath(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.LearningPath, error)
	ListLearningPaths(ctx context.Context, filter domain.LearningPathFilter) ([]*domain.LearningPath, error)
	DeleteLearningPath(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	UpsertLearningPathCourse(ctx context.Context, cmd LearningPathCourseCommand) (*domain.LearningPathCourse, error)
	ListLearningPathCourses(ctx context.Context, tenantID uuid.UUID, pathID uuid.UUID) ([]*domain.LearningPathCourse, error)
	DeleteLearningPathCourse(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateLearningEnrollment(ctx context.Context, cmd LearningEnrollmentCommand) (*domain.LearningEnrollment, error)
	UpdateLearningEnrollmentStatus(ctx context.Context, cmd LearningEnrollmentStatusCommand) (*domain.LearningEnrollment, error)
	UploadLearningCertificate(ctx context.Context, cmd LearningCertificateCommand) (*domain.LearningEnrollment, error)
	ListLearningEnrollments(ctx context.Context, filter domain.LearningEnrollmentFilter) ([]*domain.LearningEnrollment, error)
	DeleteLearningEnrollment(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateLearningRecommendation(ctx context.Context, cmd LearningRecommendationCommand) (*domain.LearningRecommendation, error)
	UpdateLearningRecommendationStatus(ctx context.Context, cmd LearningRecommendationStatusCommand) (*domain.LearningRecommendation, error)
	ListLearningRecommendations(ctx context.Context, filter domain.LearningRecommendationFilter) ([]*domain.LearningRecommendation, error)
	GenerateSkillGapLearningRecommendations(ctx context.Context, tenantID uuid.UUID, actorID *uuid.UUID) ([]*domain.LearningRecommendation, error)
	GetLearningSummary(ctx context.Context, tenantID uuid.UUID) ([]*domain.LearningSummaryRow, error)
	CreateCompensationPayBand(ctx context.Context, cmd CompensationPayBandCommand) (*domain.CompensationPayBand, error)
	UpdateCompensationPayBand(ctx context.Context, cmd CompensationPayBandCommand) (*domain.CompensationPayBand, error)
	ListCompensationPayBands(ctx context.Context, filter domain.CompensationPayBandFilter) ([]*domain.CompensationPayBand, error)
	DeleteCompensationPayBand(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateCompensationCycle(ctx context.Context, cmd CompensationCycleCommand) (*domain.CompensationCycle, error)
	UpdateCompensationCycle(ctx context.Context, cmd CompensationCycleCommand) (*domain.CompensationCycle, error)
	UpdateCompensationCycleStatus(ctx context.Context, cmd CompensationStatusCommand) (*domain.CompensationCycle, error)
	ListCompensationCycles(ctx context.Context, filter domain.CompensationFilter) ([]*domain.CompensationCycle, error)
	CreateCompensationBudgetPool(ctx context.Context, cmd CompensationBudgetPoolCommand) (*domain.CompensationBudgetPool, error)
	UpdateCompensationBudgetPool(ctx context.Context, cmd CompensationBudgetPoolCommand) (*domain.CompensationBudgetPool, error)
	ListCompensationBudgetPools(ctx context.Context, tenantID uuid.UUID, cycleID uuid.UUID) ([]*domain.CompensationBudgetPool, error)
	DeleteCompensationBudgetPool(ctx context.Context, tenantID uuid.UUID, cycleID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateCompensationRecommendation(ctx context.Context, cmd CompensationRecommendationCommand) (*domain.CompensationRecommendation, error)
	UpdateCompensationRecommendation(ctx context.Context, cmd CompensationRecommendationCommand) (*domain.CompensationRecommendation, error)
	UpdateCompensationRecommendationStatus(ctx context.Context, cmd CompensationStatusCommand) (*domain.CompensationRecommendation, error)
	ListCompensationRecommendations(ctx context.Context, filter domain.CompensationFilter) ([]*domain.CompensationRecommendation, error)
	DeleteCompensationRecommendation(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	GenerateCompensationEquityChecks(ctx context.Context, tenantID uuid.UUID, cycleID uuid.UUID, actorID *uuid.UUID) ([]*domain.CompensationEquityCheck, error)
	ListCompensationEquityChecks(ctx context.Context, filter domain.CompensationFilter) ([]*domain.CompensationEquityCheck, error)
	UpdateCompensationEquityCheckStatus(ctx context.Context, cmd CompensationStatusCommand) (*domain.CompensationEquityCheck, error)
	ListCompensationEvents(ctx context.Context, filter domain.CompensationFilter, sourceType *string, sourceID *uuid.UUID) ([]*domain.CompensationEvent, error)
	GetCompensationSummary(ctx context.Context, tenantID uuid.UUID) ([]*domain.CompensationSummaryRow, error)
	CreateSuccessionReviewCycle(ctx context.Context, cmd SuccessionReviewCycleCommand) (*domain.SuccessionReviewCycle, error)
	UpdateSuccessionReviewCycle(ctx context.Context, cmd SuccessionReviewCycleCommand) (*domain.SuccessionReviewCycle, error)
	UpdateSuccessionReviewCycleStatus(ctx context.Context, cmd SuccessionStatusCommand) (*domain.SuccessionReviewCycle, error)
	ListSuccessionReviewCycles(ctx context.Context, filter domain.SuccessionFilter) ([]*domain.SuccessionReviewCycle, error)
	CreateSuccessionCriticalRole(ctx context.Context, cmd SuccessionCriticalRoleCommand) (*domain.SuccessionCriticalRole, error)
	UpdateSuccessionCriticalRole(ctx context.Context, cmd SuccessionCriticalRoleCommand) (*domain.SuccessionCriticalRole, error)
	UpdateSuccessionCriticalRoleStatus(ctx context.Context, cmd SuccessionStatusCommand) (*domain.SuccessionCriticalRole, error)
	ListSuccessionCriticalRoles(ctx context.Context, filter domain.SuccessionFilter) ([]*domain.SuccessionCriticalRole, error)
	DeleteSuccessionCriticalRole(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateSuccessionSuccessorNomination(ctx context.Context, cmd SuccessionSuccessorNominationCommand) (*domain.SuccessionSuccessorNomination, error)
	UpdateSuccessionSuccessorNomination(ctx context.Context, cmd SuccessionSuccessorNominationCommand) (*domain.SuccessionSuccessorNomination, error)
	UpdateSuccessionSuccessorNominationStatus(ctx context.Context, cmd SuccessionStatusCommand) (*domain.SuccessionSuccessorNomination, error)
	ListSuccessionSuccessorNominations(ctx context.Context, filter domain.SuccessionFilter) ([]*domain.SuccessionSuccessorNomination, error)
	CreateSuccessionDevelopmentAction(ctx context.Context, cmd SuccessionDevelopmentActionCommand) (*domain.SuccessionDevelopmentAction, error)
	UpdateSuccessionDevelopmentAction(ctx context.Context, cmd SuccessionDevelopmentActionCommand) (*domain.SuccessionDevelopmentAction, error)
	UpdateSuccessionDevelopmentActionStatus(ctx context.Context, cmd SuccessionStatusCommand) (*domain.SuccessionDevelopmentAction, error)
	ListSuccessionDevelopmentActions(ctx context.Context, filter domain.SuccessionFilter) ([]*domain.SuccessionDevelopmentAction, error)
	ListSuccessionEvents(ctx context.Context, filter domain.SuccessionFilter, sourceType *string, sourceID *uuid.UUID) ([]*domain.SuccessionEvent, error)
	GetSuccessionSummary(ctx context.Context, tenantID uuid.UUID) ([]*domain.SuccessionSummaryRow, error)
	CreateAssetItem(ctx context.Context, cmd AssetItemCommand) (*domain.AssetItem, error)
	UpdateAssetItem(ctx context.Context, cmd AssetItemCommand) (*domain.AssetItem, error)
	UpdateAssetItemStatus(ctx context.Context, cmd AssetAccessStatusCommand) (*domain.AssetItem, error)
	ListAssetItems(ctx context.Context, filter domain.AssetAccessFilter) ([]*domain.AssetItem, error)
	DeleteAssetItem(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateAccessCatalogItem(ctx context.Context, cmd AccessCatalogItemCommand) (*domain.AccessCatalogItem, error)
	UpdateAccessCatalogItem(ctx context.Context, cmd AccessCatalogItemCommand) (*domain.AccessCatalogItem, error)
	ListAccessCatalogItems(ctx context.Context, filter domain.AssetAccessFilter) ([]*domain.AccessCatalogItem, error)
	DeleteAccessCatalogItem(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateAssetAssignment(ctx context.Context, cmd AssetAssignmentCommand) (*domain.AssetAssignment, error)
	UpdateAssetAssignment(ctx context.Context, cmd AssetAssignmentCommand) (*domain.AssetAssignment, error)
	UpdateAssetAssignmentStatus(ctx context.Context, cmd AssetAccessStatusCommand) (*domain.AssetAssignment, error)
	ListAssetAssignments(ctx context.Context, filter domain.AssetAccessFilter) ([]*domain.AssetAssignment, error)
	CreateAccessLifecycleTask(ctx context.Context, cmd AccessLifecycleTaskCommand) (*domain.AccessLifecycleTask, error)
	UpdateAccessLifecycleTask(ctx context.Context, cmd AccessLifecycleTaskCommand) (*domain.AccessLifecycleTask, error)
	UpdateAccessLifecycleTaskStatus(ctx context.Context, cmd AssetAccessStatusCommand) (*domain.AccessLifecycleTask, error)
	ListAccessLifecycleTasks(ctx context.Context, filter domain.AssetAccessFilter) ([]*domain.AccessLifecycleTask, error)
	ListAssetAccessEvents(ctx context.Context, filter domain.AssetAccessFilter, sourceType *string, sourceID *uuid.UUID) ([]*domain.AssetAccessEvent, error)
	GetAssetAccessSummary(ctx context.Context, tenantID uuid.UUID) ([]*domain.AssetAccessSummaryRow, error)
	CreateTalentMarketplaceOpportunity(ctx context.Context, cmd TalentMarketplaceOpportunityCommand) (*domain.TalentMarketplaceOpportunity, error)
	UpdateTalentMarketplaceOpportunity(ctx context.Context, cmd TalentMarketplaceOpportunityCommand) (*domain.TalentMarketplaceOpportunity, error)
	ActivateTalentMarketplaceFallback(ctx context.Context, cmd TalentMarketplaceFallbackCommand) (*domain.TalentMarketplaceOpportunity, error)
	GetTalentMarketplaceOpportunity(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.TalentMarketplaceOpportunity, error)
	ListTalentMarketplaceOpportunities(ctx context.Context, filter domain.TalentMarketplaceOpportunityFilter) ([]*domain.TalentMarketplaceOpportunity, error)
	DeleteTalentMarketplaceOpportunity(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateTalentMarketplaceApplication(ctx context.Context, cmd TalentMarketplaceApplicationCommand) (*domain.TalentMarketplaceApplication, error)
	UpdateTalentMarketplaceApplicationStatus(ctx context.Context, cmd TalentMarketplaceApplicationStatusCommand) (*domain.TalentMarketplaceApplication, error)
	GetTalentMarketplaceApplication(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.TalentMarketplaceApplication, error)
	ListTalentMarketplaceApplications(ctx context.Context, filter domain.TalentMarketplaceApplicationFilter) ([]*domain.TalentMarketplaceApplication, error)
	ListTalentMarketplaceRecommendations(ctx context.Context, tenantID uuid.UUID, opportunityID uuid.UUID) ([]*domain.TalentMarketplaceRecommendation, error)
	ListTalentMarketplaceEvents(ctx context.Context, filter domain.TalentMarketplaceEventFilter) ([]*domain.TalentMarketplaceEvent, error)
	CreateOKRCycle(ctx context.Context, cmd OKRCycleCommand) (*domain.OKRCycle, error)
	UpdateOKRCycle(ctx context.Context, cmd OKRCycleCommand) (*domain.OKRCycle, error)
	UpdateOKRCycleStatus(ctx context.Context, cmd OKRStatusCommand) (*domain.OKRCycle, error)
	GetOKRCycle(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.OKRCycle, error)
	ListOKRCycles(ctx context.Context, filter domain.OKRCycleFilter) ([]*domain.OKRCycle, error)
	DeleteOKRCycle(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateObjective(ctx context.Context, cmd ObjectiveCommand) (*domain.Objective, error)
	UpdateObjective(ctx context.Context, cmd ObjectiveCommand) (*domain.Objective, error)
	UpdateObjectiveStatus(ctx context.Context, cmd OKRStatusCommand) (*domain.Objective, error)
	GetObjective(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Objective, error)
	ListObjectives(ctx context.Context, filter domain.ObjectiveFilter) ([]*domain.Objective, error)
	DeleteObjective(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateKeyResult(ctx context.Context, cmd KeyResultCommand) (*domain.KeyResult, error)
	UpdateKeyResult(ctx context.Context, cmd KeyResultCommand) (*domain.KeyResult, error)
	GetKeyResult(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.KeyResult, error)
	ListKeyResults(ctx context.Context, filter domain.KeyResultFilter) ([]*domain.KeyResult, error)
	DeleteKeyResult(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateKeyResultCheckIn(ctx context.Context, cmd KeyResultCheckInCommand) (*domain.KeyResultCheckIn, error)
	ListKeyResultCheckIns(ctx context.Context, filter domain.KeyResultCheckInFilter) ([]*domain.KeyResultCheckIn, error)
	GetOKRSummary(ctx context.Context, tenantID uuid.UUID, cycleID *uuid.UUID) ([]*domain.OKRSummaryRow, error)
	CreatePerformanceCheckIn(ctx context.Context, cmd PerformanceCheckInCommand) (*domain.PerformanceCheckIn, error)
	UpdatePerformanceCheckIn(ctx context.Context, cmd PerformanceCheckInCommand) (*domain.PerformanceCheckIn, error)
	SubmitPerformanceCheckIn(ctx context.Context, cmd PerformanceStatusCommand) (*domain.PerformanceCheckIn, error)
	ReviewPerformanceCheckIn(ctx context.Context, cmd PerformanceCheckInReviewCommand) (*domain.PerformanceCheckIn, error)
	GetPerformanceCheckIn(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.PerformanceCheckIn, error)
	ListPerformanceCheckIns(ctx context.Context, filter domain.PerformanceCheckInFilter) ([]*domain.PerformanceCheckIn, error)
	DeletePerformanceCheckIn(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	GetPerformanceCheckInSummary(ctx context.Context, tenantID uuid.UUID, cycleID *uuid.UUID) ([]*domain.PerformanceCheckInSummaryRow, error)
	CreateFeedbackRequest(ctx context.Context, cmd FeedbackRequestCommand) (*domain.FeedbackRequest, error)
	UpdateFeedbackRequest(ctx context.Context, cmd FeedbackRequestCommand) (*domain.FeedbackRequest, error)
	UpdateFeedbackRequestStatus(ctx context.Context, cmd FeedbackStatusCommand) (*domain.FeedbackRequest, error)
	GetFeedbackRequest(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.FeedbackRequest, error)
	ListFeedbackRequests(ctx context.Context, filter domain.FeedbackRequestFilter) ([]*domain.FeedbackRequest, error)
	CreateFeedbackResponse(ctx context.Context, cmd FeedbackResponseCommand) (*domain.FeedbackResponse, error)
	ListFeedbackResponses(ctx context.Context, filter domain.FeedbackResponseFilter) ([]*domain.FeedbackResponse, error)
	ListPerformanceTimelineEvents(ctx context.Context, filter domain.PerformanceTimelineFilter) ([]*domain.PerformanceTimelineEvent, error)
	ListPerformanceCalibrationRows(ctx context.Context, filter domain.PerformanceCalibrationFilter) ([]*domain.PerformanceCalibrationRow, error)
	CreatePulseSurvey(ctx context.Context, cmd PulseSurveyCommand) (*domain.PulseSurvey, error)
	UpdatePulseSurvey(ctx context.Context, cmd PulseSurveyCommand) (*domain.PulseSurvey, error)
	UpdatePulseSurveyStatus(ctx context.Context, cmd PulseSurveyStatusCommand) (*domain.PulseSurvey, error)
	GetPulseSurvey(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.PulseSurvey, error)
	ListPulseSurveys(ctx context.Context, filter domain.PulseSurveyFilter) ([]*domain.PulseSurvey, error)
	DeletePulseSurvey(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreatePulseQuestion(ctx context.Context, cmd PulseQuestionCommand) (*domain.PulseQuestion, error)
	UpdatePulseQuestion(ctx context.Context, cmd PulseQuestionCommand) (*domain.PulseQuestion, error)
	GetPulseQuestion(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.PulseQuestion, error)
	ListPulseQuestions(ctx context.Context, tenantID uuid.UUID, surveyID *uuid.UUID) ([]*domain.PulseQuestion, error)
	DeletePulseQuestion(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreatePulseResponse(ctx context.Context, cmd PulseResponseCommand) (*domain.PulseResponse, error)
	ListPulseResponses(ctx context.Context, filter domain.PulseResponseFilter) ([]*domain.PulseResponse, error)
	UpsertWellbeingScore(ctx context.Context, cmd WellbeingScoreCommand) (*domain.WellbeingScore, error)
	ListWellbeingScores(ctx context.Context, filter domain.WellbeingScoreFilter) ([]*domain.WellbeingScore, error)
	UpdateWellbeingAlertStatus(ctx context.Context, cmd WellbeingAlertStatusCommand) (*domain.WellbeingAlert, error)
	ListWellbeingAlerts(ctx context.Context, filter domain.WellbeingAlertFilter) ([]*domain.WellbeingAlert, error)
	ListWellbeingAggregateRows(ctx context.Context, tenantID uuid.UUID, surveyID *uuid.UUID) ([]*domain.WellbeingAggregateRow, error)
	CreateProjectMilestone(ctx context.Context, cmd ProjectMilestoneCommand) (*domain.ProjectMilestone, error)
	UpdateProjectMilestone(ctx context.Context, cmd ProjectMilestoneCommand) (*domain.ProjectMilestone, error)
	SubmitProjectMilestone(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) (*domain.ProjectMilestone, error)
	ReviewProjectMilestone(ctx context.Context, cmd ProjectMilestoneStatusCommand) (*domain.ProjectMilestone, error)
	GetProjectMilestone(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.ProjectMilestone, error)
	ListProjectMilestones(ctx context.Context, filter domain.ProjectMilestoneFilter) ([]*domain.ProjectMilestoneListItem, error)
	DeleteProjectMilestone(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListProjectMilestoneEvents(ctx context.Context, tenantID uuid.UUID, milestoneID uuid.UUID) ([]*domain.ProjectMilestoneEvent, error)
	CreateAgreementTemplate(ctx context.Context, cmd AgreementTemplateCommand) (*domain.AgreementTemplate, error)
	ListAgreementTemplates(ctx context.Context, tenantID uuid.UUID, agreementType *string) ([]*domain.AgreementTemplate, error)
	GetAgreementTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.AgreementTemplate, error)
	UpdateAgreementTemplate(ctx context.Context, cmd AgreementTemplateCommand) (*domain.AgreementTemplate, error)
	DeleteAgreementTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	GenerateAgreement(ctx context.Context, cmd AgreementCommand) (*domain.Agreement, error)
	ListAgreements(ctx context.Context, filter domain.AgreementFilter) ([]*domain.Agreement, error)
	GetAgreement(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Agreement, error)
	GetAgreementBySignatureToken(ctx context.Context, token string) (*domain.Agreement, error)
	UpdateAgreementStatus(ctx context.Context, cmd AgreementStatusCommand) (*domain.Agreement, error)
	SignAgreement(ctx context.Context, cmd AgreementSignatureCommand) (*domain.Agreement, error)
	DeleteAgreement(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListAgreementEvents(ctx context.Context, tenantID uuid.UUID, agreementID uuid.UUID) ([]*domain.AgreementEvent, error)
	RenderAgreementPDF(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) ([]byte, string, error)
	CreateWorkingHour(ctx context.Context, cmd WorkingHourCommand) (*domain.WorkingHour, error)
	ListWorkingHours(ctx context.Context, tenantID uuid.UUID) ([]*domain.WorkingHour, error)
	GetWorkingHour(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.WorkingHour, error)
	ResolveWorkingHour(ctx context.Context, cmd ResolveWorkingHourCommand) (*domain.WorkingHour, error)
	UpdateWorkingHour(ctx context.Context, cmd WorkingHourCommand) (*domain.WorkingHour, error)
	DeleteWorkingHour(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CopyTenantWorkingHoursToBranch(ctx context.Context, cmd CopyWorkingHoursCommand) ([]*domain.WorkingHour, error)
	CreateFinancialYear(ctx context.Context, cmd FinancialYearCommand) (*domain.FinancialYear, error)
	ListFinancialYears(ctx context.Context, tenantID uuid.UUID) ([]*domain.FinancialYear, error)
	GetFinancialYear(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.FinancialYear, error)
	GetActiveFinancialYear(ctx context.Context, tenantID uuid.UUID) (*domain.FinancialYear, error)
	UpdateFinancialYear(ctx context.Context, cmd FinancialYearCommand) (*domain.FinancialYear, error)
	DeleteFinancialYear(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	SetActiveFinancialYear(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) (*domain.FinancialYear, error)
	SetFinancialYearLock(ctx context.Context, cmd FinancialYearLockCommand) (*domain.FinancialYear, error)
	CreateHoliday(ctx context.Context, cmd HolidayCommand) (*domain.Holiday, error)
	ListHolidays(ctx context.Context, cmd ListHolidaysCommand) ([]*domain.Holiday, error)
	GetHoliday(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Holiday, error)
	UpdateHoliday(ctx context.Context, cmd HolidayCommand) (*domain.Holiday, error)
	DeleteHoliday(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreatePolicySet(ctx context.Context, cmd PolicySetCommand) (*domain.PolicySet, error)
	UpdatePolicySet(ctx context.Context, cmd PolicySetCommand) (*domain.PolicySet, error)
	ListPolicySets(ctx context.Context, tenantID uuid.UUID, policyKind string) ([]*domain.PolicySet, error)
	DeletePolicySet(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreatePolicyAssignment(ctx context.Context, cmd PolicyAssignmentCommand) (*domain.PolicyAssignment, error)
	UpdatePolicyAssignment(ctx context.Context, cmd PolicyAssignmentCommand) (*domain.PolicyAssignment, error)
	ListPolicyAssignments(ctx context.Context, tenantID uuid.UUID, policyKind string) ([]*domain.PolicyAssignment, error)
	DeletePolicyAssignment(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateLeavePolicyRule(ctx context.Context, cmd LeavePolicyRuleCommand) (*domain.LeavePolicyRule, error)
	UpdateLeavePolicyRule(ctx context.Context, cmd LeavePolicyRuleCommand) (*domain.LeavePolicyRule, error)
	ListLeavePolicyRules(ctx context.Context, tenantID uuid.UUID, policySetID uuid.UUID) ([]*domain.LeavePolicyRule, error)
	DeleteLeavePolicyRule(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ResolveEffectivePolicySet(ctx context.Context, subject domain.PolicyResolutionSubject, policyKind string) (*domain.PolicyResolutionResult, error)
	ResolveEmployeeAttendancePolicySet(ctx context.Context, tenantID uuid.UUID, employeeUserID uuid.UUID, date string, roleCodes []string) (*domain.PolicyResolutionResult, error)
	ResolveEmployeeLeavePolicySet(ctx context.Context, tenantID uuid.UUID, employeeUserID uuid.UUID, date string, roleCodes []string) (*domain.PolicyResolutionResult, error)
	CreateLeaveType(ctx context.Context, cmd LeaveTypeCommand) (*domain.LeaveType, error)
	ListLeaveTypes(ctx context.Context, tenantID uuid.UUID) ([]*domain.LeaveType, error)
	GetLeaveType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.LeaveType, error)
	UpdateLeaveType(ctx context.Context, cmd LeaveTypeCommand) (*domain.LeaveType, error)
	DeleteLeaveType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateLeavePolicy(ctx context.Context, cmd LeavePolicyCommand) (*domain.LeavePolicy, error)
	ListLeavePolicies(ctx context.Context, tenantID uuid.UUID) ([]*domain.LeavePolicy, error)
	GetLeavePolicy(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.LeavePolicy, error)
	UpdateLeavePolicy(ctx context.Context, cmd LeavePolicyCommand) (*domain.LeavePolicy, error)
	DeleteLeavePolicy(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	RunMonthlyLeaveAllocation(ctx context.Context, cmd MonthlyLeaveAllocationCommand) ([]*domain.MonthlyLeaveAllocation, error)
	CreateLeavePolicyTemplate(ctx context.Context, cmd LeavePolicyTemplateCommand) (*domain.LeavePolicyTemplate, error)
	ListLeavePolicyTemplates(ctx context.Context, tenantID uuid.UUID) ([]*domain.LeavePolicyTemplate, error)
	GetLeavePolicyTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.LeavePolicyTemplate, error)
	UpdateLeavePolicyTemplate(ctx context.Context, cmd LeavePolicyTemplateCommand) (*domain.LeavePolicyTemplate, error)
	DeleteLeavePolicyTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateLeavePolicyTemplateRule(ctx context.Context, cmd LeavePolicyTemplateRuleCommand) (*domain.LeavePolicyTemplateRule, error)
	ListLeavePolicyTemplateRules(ctx context.Context, tenantID uuid.UUID, templateID uuid.UUID) ([]*domain.LeavePolicyTemplateRule, error)
	UpdateLeavePolicyTemplateRule(ctx context.Context, cmd LeavePolicyTemplateRuleCommand) (*domain.LeavePolicyTemplateRule, error)
	DeleteLeavePolicyTemplateRule(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	UpsertEmployeeLeavePolicyAssignment(ctx context.Context, cmd EmployeeLeavePolicyAssignmentCommand) (*domain.EmployeeLeavePolicyAssignment, error)
	ListEmployeeLeavePolicyAssignments(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) ([]*domain.EmployeeLeavePolicyAssignment, error)
	DeleteEmployeeLeavePolicyAssignment(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	UpsertLeaveBalance(ctx context.Context, cmd LeaveBalanceCommand) (*domain.LeaveBalance, error)
	ListLeaveBalancesByUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) ([]*domain.LeaveBalance, error)
	ListLeaveBalancesByTenantFY(ctx context.Context, tenantID uuid.UUID, fyID uuid.UUID) ([]*domain.LeaveBalance, error)
	AdjustLeaveBalance(ctx context.Context, cmd LeaveBalanceAdjustmentCommand) (*domain.LeaveBalance, error)
	ListLeaveLedgerByUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) ([]*domain.LeaveLedgerEntry, error)
	RunLeaveAccrual(ctx context.Context, cmd RunLeaveAccrualCommand) ([]*domain.LeaveLedgerEntry, error)
	CreateCompOffRequest(ctx context.Context, cmd CompOffRequestCommand) (*domain.CompOffRequest, error)
	ListCompOffRequestsByUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) ([]*domain.CompOffRequest, error)
	ListCompOffRequestsByStatus(ctx context.Context, tenantID uuid.UUID, status string) ([]*domain.CompOffRequest, error)
	ReviewCompOffRequest(ctx context.Context, cmd CompOffReviewCommand) (*domain.CompOffRequest, error)
	PreviewLeave(ctx context.Context, cmd ApplyLeaveCommand) (*domain.LeavePreview, error)
	ApplyLeave(ctx context.Context, cmd ApplyLeaveCommand) (*domain.LeaveApplication, error)
	ListLeavesByUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) ([]*domain.Leave, error)
	ListLeavesByFY(ctx context.Context, tenantID uuid.UUID, fyID uuid.UUID) ([]*domain.Leave, error)
	PunchAttendance(ctx context.Context, cmd AttendancePunchCommand) (*domain.AttendancePunch, error)
	ListAttendancesByUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, startDate string, endDate string) ([]*domain.Attendance, error)
	ListAttendancesByUserDate(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, date string) ([]*domain.Attendance, error)
	CreateAttendanceWorkdaySegment(ctx context.Context, cmd AttendanceSegmentCommand) (*domain.AttendanceWorkdaySegment, error)
	ListAttendanceWorkdaySegmentsByUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, startDate string, endDate string) ([]*domain.AttendanceWorkdaySegment, error)
	ListAttendanceWorkdaySegmentsByUserDate(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, date string) ([]*domain.AttendanceWorkdaySegment, error)
	ListAttendanceDailyStatuses(ctx context.Context, query AttendanceStatusQuery) ([]*domain.AttendanceDailyStatus, error)
	GetAttendanceStatusSummary(ctx context.Context, query AttendanceStatusQuery) (*domain.AttendanceStatusSummary, error)
	GetAttendanceReport(ctx context.Context, query AttendanceReportQuery) (*domain.AttendanceReport, error)
	CreateAttendancePolicy(ctx context.Context, cmd AttendancePolicyCommand) (*domain.AttendancePolicy, error)
	ListAttendancePolicies(ctx context.Context, tenantID uuid.UUID) ([]*domain.AttendancePolicy, error)
	UpdateAttendancePolicy(ctx context.Context, cmd AttendancePolicyCommand) (*domain.AttendancePolicy, error)
	DeleteAttendancePolicy(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateAttendanceRoster(ctx context.Context, cmd AttendanceRosterCommand) (*domain.AttendanceRoster, error)
	ListAttendanceRostersByDateRange(ctx context.Context, tenantID uuid.UUID, startDate string, endDate string) ([]*domain.AttendanceRoster, error)
	ListAttendanceRostersByUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, startDate string, endDate string) ([]*domain.AttendanceRoster, error)
	UpdateAttendanceRoster(ctx context.Context, cmd AttendanceRosterCommand) (*domain.AttendanceRoster, error)
	DeleteAttendanceRoster(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateAttendanceRequest(ctx context.Context, cmd AttendanceRequestCommand) (*domain.AttendanceRequest, error)
	ListAttendanceRequestsByUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) ([]*domain.AttendanceRequest, error)
	ListAttendanceRequestsByStatus(ctx context.Context, tenantID uuid.UUID, status string) ([]*domain.AttendanceRequest, error)
	ReviewAttendanceRequest(ctx context.Context, cmd AttendanceReviewCommand) (*domain.AttendanceRequest, error)
	CreateAttendanceExceptionWorkflow(ctx context.Context, cmd AttendanceExceptionWorkflowCommand) (*domain.AttendanceExceptionWorkflow, error)
	ListAttendanceExceptionWorkflows(ctx context.Context, tenantID uuid.UUID) ([]*domain.AttendanceExceptionWorkflow, error)
	UpdateAttendanceExceptionWorkflow(ctx context.Context, cmd AttendanceExceptionWorkflowCommand) (*domain.AttendanceExceptionWorkflow, error)
	DeleteAttendanceExceptionWorkflow(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListAttendanceExceptionEvents(ctx context.Context, tenantID uuid.UUID, attendanceRequestID uuid.UUID) ([]*domain.AttendanceExceptionEvent, error)
	ListPayrollBlockingAttendanceRequests(ctx context.Context, tenantID uuid.UUID, startDate string, endDate string) ([]*domain.AttendanceRequest, error)
	CreateAttendanceLocation(ctx context.Context, cmd AttendanceLocationCommand) (*domain.AttendanceLocation, error)
	ListAttendanceLocations(ctx context.Context, tenantID uuid.UUID) ([]*domain.AttendanceLocation, error)
	UpdateAttendanceLocation(ctx context.Context, cmd AttendanceLocationCommand) (*domain.AttendanceLocation, error)
	DeleteAttendanceLocation(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateAttendanceLocationAssignment(ctx context.Context, cmd AttendanceLocationAssignmentCommand) (*domain.AttendanceLocationAssignment, error)
	ListAttendanceLocationAssignments(ctx context.Context, tenantID uuid.UUID, locationID *uuid.UUID) ([]*domain.AttendanceLocationAssignment, error)
	UpdateAttendanceLocationAssignment(ctx context.Context, cmd AttendanceLocationAssignmentCommand) (*domain.AttendanceLocationAssignment, error)
	DeleteAttendanceLocationAssignment(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateAttendanceDevice(ctx context.Context, cmd AttendanceDeviceCommand) (*domain.AttendanceDevice, error)
	ListAttendanceDevices(ctx context.Context, tenantID uuid.UUID) ([]*domain.AttendanceDevice, error)
	UpdateAttendanceDevice(ctx context.Context, cmd AttendanceDeviceCommand) (*domain.AttendanceDevice, error)
	DeleteAttendanceDevice(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateEmployeeAttendanceDevice(ctx context.Context, cmd EmployeeAttendanceDeviceCommand) (*domain.EmployeeAttendanceDevice, error)
	ListEmployeeAttendanceDevices(ctx context.Context, tenantID uuid.UUID, userID *uuid.UUID) ([]*domain.EmployeeAttendanceDevice, error)
	UpdateEmployeeAttendanceDevice(ctx context.Context, cmd EmployeeAttendanceDeviceCommand) (*domain.EmployeeAttendanceDevice, error)
	DeleteEmployeeAttendanceDevice(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateShiftTemplate(ctx context.Context, cmd ShiftTemplateCommand) (*domain.ShiftTemplate, error)
	UpdateShiftTemplate(ctx context.Context, cmd ShiftTemplateCommand) (*domain.ShiftTemplate, error)
	ListShiftTemplates(ctx context.Context, tenantID uuid.UUID, activeOnly *bool, search *string, limit int32, offset int32) ([]*domain.ShiftTemplate, error)
	DeleteShiftTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateStaffingRequirement(ctx context.Context, cmd StaffingRequirementCommand) (*domain.StaffingRequirement, error)
	UpdateStaffingRequirement(ctx context.Context, cmd StaffingRequirementCommand) (*domain.StaffingRequirement, error)
	ListStaffingRequirements(ctx context.Context, filter domain.StaffingRequirementFilter) ([]*domain.StaffingRequirement, error)
	DeleteStaffingRequirement(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateShiftScheduleAssignment(ctx context.Context, cmd ShiftScheduleAssignmentCommand) (*domain.ShiftScheduleAssignment, error)
	UpdateShiftScheduleAssignment(ctx context.Context, cmd ShiftScheduleAssignmentCommand) (*domain.ShiftScheduleAssignment, error)
	UpdateShiftScheduleAssignmentStatus(ctx context.Context, cmd ShiftScheduleStatusCommand) (*domain.ShiftScheduleAssignment, error)
	ListShiftScheduleAssignments(ctx context.Context, filter domain.ShiftScheduleFilter) ([]*domain.ShiftScheduleAssignment, error)
	DeleteShiftScheduleAssignment(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateShiftSwapRequest(ctx context.Context, cmd ShiftSwapRequestCommand) (*domain.ShiftSwapRequest, error)
	ReviewShiftSwapRequest(ctx context.Context, cmd ShiftSwapReviewCommand) (*domain.ShiftSwapRequest, error)
	ListShiftSwapRequests(ctx context.Context, filter domain.ShiftSwapFilter) ([]*domain.ShiftSwapRequest, error)
	ListShiftScheduleEvents(ctx context.Context, filter domain.ShiftScheduleEventFilter) ([]*domain.ShiftScheduleEvent, error)
	GetShiftScheduleSummary(ctx context.Context, tenantID uuid.UUID, startDate string, endDate string) ([]*domain.ShiftScheduleSummaryRow, error)
	ListShiftStaffingGaps(ctx context.Context, tenantID uuid.UUID, startDate string, endDate string) ([]*domain.ShiftStaffingGapRow, error)
	CreateBenefitPlan(ctx context.Context, cmd BenefitPlanCommand) (*domain.BenefitPlan, error)
	UpdateBenefitPlan(ctx context.Context, cmd BenefitPlanCommand) (*domain.BenefitPlan, error)
	ListBenefitPlans(ctx context.Context, filter domain.BenefitFilter) ([]*domain.BenefitPlan, error)
	DeleteBenefitPlan(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateBenefitEnrollmentWindow(ctx context.Context, cmd BenefitEnrollmentWindowCommand) (*domain.BenefitEnrollmentWindow, error)
	UpdateBenefitEnrollmentWindow(ctx context.Context, cmd BenefitEnrollmentWindowCommand) (*domain.BenefitEnrollmentWindow, error)
	ListBenefitEnrollmentWindows(ctx context.Context, filter domain.BenefitFilter) ([]*domain.BenefitEnrollmentWindow, error)
	DeleteBenefitEnrollmentWindow(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateBenefitDependent(ctx context.Context, cmd BenefitDependentCommand) (*domain.BenefitDependent, error)
	UpdateBenefitDependent(ctx context.Context, cmd BenefitDependentCommand) (*domain.BenefitDependent, error)
	ListBenefitDependents(ctx context.Context, filter domain.BenefitFilter) ([]*domain.BenefitDependent, error)
	DeleteBenefitDependent(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateBenefitEnrollment(ctx context.Context, cmd BenefitEnrollmentCommand) (*domain.BenefitEnrollment, error)
	UpdateBenefitEnrollment(ctx context.Context, cmd BenefitEnrollmentCommand) (*domain.BenefitEnrollment, error)
	UpdateBenefitEnrollmentStatus(ctx context.Context, cmd BenefitEnrollmentStatusCommand) (*domain.BenefitEnrollment, error)
	ListBenefitEnrollments(ctx context.Context, filter domain.BenefitFilter) ([]*domain.BenefitEnrollment, error)
	DeleteBenefitEnrollment(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateBenefitClaimType(ctx context.Context, cmd BenefitClaimTypeCommand) (*domain.BenefitClaimType, error)
	UpdateBenefitClaimType(ctx context.Context, cmd BenefitClaimTypeCommand) (*domain.BenefitClaimType, error)
	ListBenefitClaimTypes(ctx context.Context, filter domain.BenefitFilter) ([]*domain.BenefitClaimType, error)
	DeleteBenefitClaimType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateBenefitClaim(ctx context.Context, cmd BenefitClaimCommand) (*domain.BenefitClaim, error)
	UpdateBenefitClaim(ctx context.Context, cmd BenefitClaimCommand) (*domain.BenefitClaim, error)
	UpdateBenefitClaimStatus(ctx context.Context, cmd BenefitClaimStatusCommand) (*domain.BenefitClaim, error)
	ListBenefitClaims(ctx context.Context, filter domain.BenefitFilter) ([]*domain.BenefitClaim, error)
	DeleteBenefitClaim(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateBenefitClaimAttachment(ctx context.Context, cmd BenefitClaimAttachmentCommand) (*domain.BenefitClaimAttachment, error)
	ListBenefitClaimAttachments(ctx context.Context, tenantID uuid.UUID, claimID uuid.UUID) ([]*domain.BenefitClaimAttachment, error)
	ListBenefitEvents(ctx context.Context, filter domain.BenefitFilter) ([]*domain.BenefitEvent, error)
	GetBenefitsSummary(ctx context.Context, tenantID uuid.UUID) ([]*domain.BenefitsSummaryRow, error)
	GetPayCycle(ctx context.Context, tenantID uuid.UUID) (*domain.PayCycle, error)
	UpsertPayCycle(ctx context.Context, cmd PayCycleCommand) (*domain.PayCycle, error)
	DeletePayCycle(ctx context.Context, tenantID uuid.UUID, actorID *uuid.UUID) error
	ResolvePayCyclePeriod(ctx context.Context, query PayCyclePeriodQuery) (*domain.PayCyclePeriod, error)

	CreateSalaryTemplate(ctx context.Context, cmd SalaryTemplateCommand) (*domain.SalaryTemplate, error)
	ListSalaryTemplates(ctx context.Context, tenantID uuid.UUID, fyID *uuid.UUID) ([]*domain.SalaryTemplate, error)
	GetSalaryTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.SalaryTemplate, error)
	GetActiveSalaryTemplate(ctx context.Context, tenantID uuid.UUID, fyID uuid.UUID) (*domain.SalaryTemplate, error)
	UpdateSalaryTemplate(ctx context.Context, cmd SalaryTemplateCommand) (*domain.SalaryTemplate, error)
	DeleteSalaryTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ActivateSalaryTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) (*domain.SalaryTemplate, error)
	CreateSalaryTemplateItem(ctx context.Context, cmd SalaryTemplateItemCommand) (*domain.SalaryTemplateItem, error)
	ListSalaryTemplateItems(ctx context.Context, tenantID uuid.UUID, templateID uuid.UUID) ([]*domain.SalaryTemplateItem, error)
	UpdateSalaryTemplateItem(ctx context.Context, cmd SalaryTemplateItemCommand) (*domain.SalaryTemplateItem, error)
	DeleteSalaryTemplateItem(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	AssignEmployeeSalary(ctx context.Context, cmd EmployeeSalaryCommand) (*domain.EmployeeSalary, error)
	ListEmployeeSalariesByUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) ([]*domain.EmployeeSalary, error)
	GetEmployeeSalary(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.EmployeeSalary, error)
	DeleteEmployeeSalary(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CalculateEmployeeSalary(ctx context.Context, cmd EmployeeSalaryCalculationCommand) (*EmployeeSalaryCalculation, error)
	GetSalarySlipFormat(ctx context.Context, tenantID uuid.UUID) (*domain.SalarySlipFormat, error)
	UpsertSalarySlipFormat(ctx context.Context, cmd SalarySlipFormatCommand) (*domain.SalarySlipFormat, error)
	GenerateSalarySlip(ctx context.Context, cmd GenerateSalarySlipCommand) (*domain.SalarySlip, error)
	BulkGenerateSalarySlips(ctx context.Context, cmd BulkGenerateSalarySlipsCommand) ([]*domain.SalarySlip, error)
	ListSalarySlipsByUser(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) ([]*domain.SalarySlip, error)
	ListSalarySlipsByTenantPeriod(ctx context.Context, tenantID uuid.UUID, month int32, year int32) ([]*domain.SalarySlip, error)
	GetSalarySlip(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.SalarySlip, error)
	RenderSalarySlipPDF(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) ([]byte, string, error)
	RenderRecentSalarySlipsZip(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, months int32) ([]byte, string, error)
	RenderTenantSalarySlipsZip(ctx context.Context, tenantID uuid.UUID, month int32, year int32) ([]byte, string, error)
	UpsertPayrollPeriodLock(ctx context.Context, cmd PayrollPeriodLockCommand) (*domain.PayrollPeriodLock, error)
	ListPayrollPeriodLocks(ctx context.Context, tenantID uuid.UUID) ([]*domain.PayrollPeriodLock, error)
	CreatePayrollStatutoryRule(ctx context.Context, cmd PayrollStatutoryRuleCommand) (*domain.PayrollStatutoryRule, error)
	UpdatePayrollStatutoryRule(ctx context.Context, cmd PayrollStatutoryRuleCommand) (*domain.PayrollStatutoryRule, error)
	ListPayrollStatutoryRules(ctx context.Context, tenantID uuid.UUID, ruleType *string) ([]*domain.PayrollStatutoryRule, error)
	DeletePayrollStatutoryRule(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ImportPayrollData(ctx context.Context, cmd PayrollImportCommand) (*domain.PayrollImportBatch, error)
	ListPayrollImportBatches(ctx context.Context, tenantID uuid.UUID, limit int32, offset int32) ([]*domain.PayrollImportBatch, error)
	GetPayrollImportBatch(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.PayrollImportBatch, error)
	ListConsolidatedSalarySheet(ctx context.Context, tenantID uuid.UUID, month int32, year int32) ([]*domain.ConsolidatedSalarySheetRow, error)
	ExportConsolidatedSalarySheetCSV(ctx context.Context, tenantID uuid.UUID, month int32, year int32) ([]byte, string, error)
	ListPayrollReconciliationRows(ctx context.Context, tenantID uuid.UUID, month int32, year int32) ([]*domain.PayrollReconciliationRow, error)
	CreatePayGroup(ctx context.Context, cmd PayGroupCommand) (*domain.PayGroup, error)
	UpdatePayGroup(ctx context.Context, cmd PayGroupCommand) (*domain.PayGroup, error)
	ListPayGroups(ctx context.Context, tenantID uuid.UUID) ([]*domain.PayGroup, error)
	GetPayGroup(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.PayGroup, error)
	DeletePayGroup(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	UpsertPayGroupMember(ctx context.Context, cmd PayGroupMemberCommand) (*domain.PayGroupMember, error)
	DeletePayGroupMember(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListPayGroupEmployees(ctx context.Context, tenantID uuid.UUID, payGroupID uuid.UUID) ([]*domain.PayGroupEmployee, error)
	CreatePayRun(ctx context.Context, cmd PayRunCommand) (*domain.PayRun, error)
	ListPayRuns(ctx context.Context, query PayRunListQuery) ([]*domain.PayRun, error)
	GetPayRun(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.PayRun, error)
	AssessPayRunReadiness(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) (*domain.PayRun, error)
	FreezePayRun(ctx context.Context, cmd PayRunActionCommand) (*domain.PayRun, error)
	GeneratePayRun(ctx context.Context, cmd PayRunActionCommand) (*domain.PayRun, error)
	LockPayRun(ctx context.Context, cmd PayRunActionCommand) (*domain.PayRun, error)
	UnlockPayRun(ctx context.Context, cmd PayRunActionCommand) (*domain.PayRun, error)
	DeletePayRun(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateFlexPayRun(ctx context.Context, cmd FlexPayRunCommand) (*domain.FlexPayRun, error)
	ListFlexPayRuns(ctx context.Context, filter domain.FlexPayRunFilter) ([]*domain.FlexPayRun, error)
	GetFlexPayRun(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.FlexPayRun, error)
	DeleteFlexPayRun(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	GenerateFlexPayRun(ctx context.Context, cmd FlexPayRunGenerateCommand) (*domain.FlexPayRun, error)
	SubmitFlexPayRun(ctx context.Context, cmd FlexPayRunActionCommand) (*domain.FlexPayRun, error)
	ApproveFlexPayRun(ctx context.Context, cmd FlexPayRunActionCommand) (*domain.FlexPayRun, error)
	RejectFlexPayRun(ctx context.Context, cmd FlexPayRunActionCommand) (*domain.FlexPayRun, error)
	MarkFlexPayRunPaymentPending(ctx context.Context, cmd FlexPayRunActionCommand) (*domain.FlexPayRun, error)
	MarkFlexPayRunPaid(ctx context.Context, cmd FlexPayRunActionCommand) (*domain.FlexPayRun, error)
	ExportFlexPayRunCSV(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) ([]byte, string, error)
	CreateContractorInvoice(ctx context.Context, cmd ContractorInvoiceCommand) (*domain.ContractorInvoice, error)
	UpdateContractorInvoice(ctx context.Context, cmd ContractorInvoiceCommand) (*domain.ContractorInvoice, error)
	ListContractorInvoices(ctx context.Context, filter domain.ContractorInvoiceFilter) ([]*domain.ContractorInvoice, error)
	GetContractorInvoice(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.ContractorInvoice, error)
	DeleteContractorInvoice(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	SubmitContractorInvoice(ctx context.Context, cmd ContractorInvoiceActionCommand) (*domain.ContractorInvoice, error)
	ApproveContractorInvoice(ctx context.Context, cmd ContractorInvoiceActionCommand) (*domain.ContractorInvoice, error)
	RejectContractorInvoice(ctx context.Context, cmd ContractorInvoiceActionCommand) (*domain.ContractorInvoice, error)
	MarkContractorInvoicePaid(ctx context.Context, cmd ContractorInvoiceActionCommand) (*domain.ContractorInvoice, error)
	CreateFlexPayRunItem(ctx context.Context, cmd FlexPayRunItemCommand) (*domain.FlexPayRunItem, error)
	ListFlexPayRunItems(ctx context.Context, tenantID uuid.UUID, flexPayRunID uuid.UUID) ([]*domain.FlexPayRunItem, error)
	ListFlexPayRunEvents(ctx context.Context, tenantID uuid.UUID, flexPayRunID *uuid.UUID, invoiceID *uuid.UUID) ([]*domain.FlexPayRunEvent, error)
	GetEmployeeDashboard(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) (*domain.EmployeeDashboard, error)
	GetHRDashboard(ctx context.Context, query domain.HRDashboardQuery) (*domain.HRDashboard, error)
	ListReportCatalog(ctx context.Context, query ReportCatalogQuery) ([]*domain.ReportCatalogItem, error)
	UpsertReportSavedView(ctx context.Context, cmd ReportSavedViewCommand) (*domain.ReportSavedView, error)
	ListReportSavedViews(ctx context.Context, query ReportListQuery) ([]*domain.ReportSavedView, error)
	DeleteReportSavedView(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateReportExportJob(ctx context.Context, cmd ReportExportJobCommand) (*domain.ReportExportJob, error)
	ListReportExportJobs(ctx context.Context, query ReportListQuery) ([]*domain.ReportExportJob, error)
	UpdateReportExportJobStatus(ctx context.Context, cmd ReportExportJobStatusCommand) (*domain.ReportExportJob, error)
	UpsertReportSchedule(ctx context.Context, cmd ReportScheduleCommand) (*domain.ReportSchedule, error)
	ListReportSchedules(ctx context.Context, query ReportListQuery) ([]*domain.ReportSchedule, error)
	DeleteReportSchedule(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateReportSnapshot(ctx context.Context, cmd ReportSnapshotCommand) (*domain.ReportSnapshot, error)
	ListReportSnapshots(ctx context.Context, query ReportListQuery) ([]*domain.ReportSnapshot, error)
	BuildReportDataset(ctx context.Context, query ReportDatasetQuery) (*domain.ReportDataset, error)
	ExportReportDataset(ctx context.Context, query ReportDatasetQuery, format string) (*ReportDownload, error)
	RefreshInsights(ctx context.Context, tenantID uuid.UUID, actorID *uuid.UUID) (*domain.InsightWorkspace, error)
	ListInsightWorkspace(ctx context.Context, filter domain.InsightFilter) (*domain.InsightWorkspace, error)
	UpdateInsightStatus(ctx context.Context, cmd InsightStatusCommand) (*domain.Insight, error)
	ListInsightEvents(ctx context.Context, tenantID uuid.UUID, insightID uuid.UUID) ([]*domain.InsightEvent, error)
	ListAIActionWorkspace(ctx context.Context, filter domain.AIActionFilter) (*domain.AIActionWorkspace, error)
	EmitAIWorkflowEvent(ctx context.Context, cmd AIWorkflowEventCommand) (*domain.AISignalLog, error)
	CreateAISignal(ctx context.Context, cmd AISignalCommand) (*domain.AISignalLog, error)
	UpdateAISignalStatus(ctx context.Context, cmd AIStatusCommand) (*domain.AISignalLog, error)
	CreateAIAgentAction(ctx context.Context, cmd AIActionCommand) (*domain.AIAgentActionLog, error)
	UpdateAIAgentActionStatus(ctx context.Context, cmd AIStatusCommand) (*domain.AIAgentActionLog, error)
	OverrideAIAction(ctx context.Context, cmd AIOverrideCommand) (*domain.AIHumanOverride, error)
	ListBoundedAIAgents(ctx context.Context, tenantID uuid.UUID) ([]domain.BoundedAIAgentDefinition, error)
	RunBoundedAIAgents(ctx context.Context, cmd BoundedAIAgentRunCommand) (*domain.BoundedAIAgentRunResult, error)
	GetPeopleAnalyticsWorkspace(ctx context.Context, tenantID uuid.UUID) (*domain.PeopleAnalyticsWorkspace, error)
	ListPrivacyEcosystemWorkspace(ctx context.Context, filter domain.PrivacyEcosystemFilter) (*domain.PrivacyEcosystemWorkspace, error)
	GetOperationsWorkbench(ctx context.Context, query OperationsWorkbenchQuery) (*domain.OperationsWorkbench, error)
	ActOperationsWorkbenchCard(ctx context.Context, cmd OperationsWorkbenchActionCommand) (*domain.OperationsWorkbenchActionResult, error)
	GetHRCommandCenter(ctx context.Context, query HRCommandCenterQuery) (*domain.HRCommandCenter, error)
	ListOperationCatalog(ctx context.Context, query OperationCatalogQuery) (*domain.OperationCatalog, error)
	CreateTenantOperationRequest(ctx context.Context, cmd TenantOperationCommand) (*domain.TenantOperationRequest, error)
	ListTenantOperationRequests(ctx context.Context, filter domain.TenantOperationFilter) (*domain.TenantOperationWorkspace, error)
	GetTenantOperationDetail(ctx context.Context, id uuid.UUID) (*domain.TenantOperationDetail, error)
	ActTenantOperationRequest(ctx context.Context, cmd TenantOperationActionCommand) (*domain.TenantOperationRequest, error)
	CreateWorkflowDefinition(ctx context.Context, cmd WorkflowDefinitionCommand) (*domain.WorkflowDefinition, error)
	UpdateWorkflowDefinition(ctx context.Context, cmd WorkflowDefinitionCommand) (*domain.WorkflowDefinition, error)
	ListWorkflowDefinitions(ctx context.Context, tenantID uuid.UUID, status *string, moduleKey *string, search *string, limit int32, offset int32) ([]*domain.WorkflowDefinition, error)
	CreateWorkflowDefinitionStep(ctx context.Context, cmd WorkflowDefinitionStepCommand) (*domain.WorkflowDefinitionStep, error)
	UpdateWorkflowDefinitionStep(ctx context.Context, cmd WorkflowDefinitionStepCommand) (*domain.WorkflowDefinitionStep, error)
	ListWorkflowDefinitionSteps(ctx context.Context, tenantID uuid.UUID, workflowDefinitionID uuid.UUID) ([]*domain.WorkflowDefinitionStep, error)
	CreateOperationTemplate(ctx context.Context, cmd OperationTemplateCommand) (*domain.OperationTemplate, error)
	UpdateOperationTemplate(ctx context.Context, cmd OperationTemplateCommand) (*domain.OperationTemplate, error)
	ListOperationTemplates(ctx context.Context, tenantID uuid.UUID, category *string, sourceModule *string, activeOnly *bool, search *string, limit int32, offset int32) ([]*domain.OperationTemplate, error)
	CreateWorkflowTask(ctx context.Context, cmd WorkflowTaskCommand) (*domain.WorkflowTask, error)
	UpdateWorkflowTask(ctx context.Context, cmd WorkflowTaskCommand) (*domain.WorkflowTask, error)
	ListWorkflowTasks(ctx context.Context, filter domain.WorkflowTaskFilter) ([]*domain.WorkflowTask, error)
	GetWorkflowTaskWorkspace(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.WorkflowTaskWorkspace, error)
	ActWorkflowTask(ctx context.Context, cmd WorkflowTaskActionCommand) (*domain.WorkflowTask, error)
	CreateWorkflowTaskComment(ctx context.Context, cmd WorkflowTaskCommentCommand) (*domain.WorkflowTaskComment, error)
	CreateWorkflowTaskAttachment(ctx context.Context, cmd WorkflowTaskAttachmentCommand) (*domain.WorkflowTaskAttachment, error)
	WatchWorkflowTask(ctx context.Context, cmd WorkflowTaskWatchCommand) (*domain.WorkflowTaskWatcher, error)
	UnwatchWorkflowTask(ctx context.Context, cmd WorkflowTaskWatchCommand) error
	GetWorkflowTaskSummary(ctx context.Context, tenantID uuid.UUID) ([]*domain.WorkflowTaskSummaryRow, error)
	UpsertPrivacyConsent(ctx context.Context, cmd PrivacyConsentCommand) (*domain.PrivacyConsent, error)
	CreateDataErasureRequest(ctx context.Context, cmd DataErasureRequestCommand) (*domain.DataErasureRequest, error)
	UpdateDataErasureRequestStatus(ctx context.Context, cmd DataErasureStatusCommand) (*domain.DataErasureRequest, error)
	UpsertEcosystemIntegrationHook(ctx context.Context, cmd EcosystemIntegrationHookCommand) (*domain.EcosystemIntegrationHook, error)
	UpsertMobileAPIConstraint(ctx context.Context, cmd MobileAPIConstraintCommand) (*domain.MobileAPIConstraint, error)
	CreateCelebrationType(ctx context.Context, cmd CelebrationTypeCommand) (*domain.CelebrationType, error)
	ListCelebrationTypes(ctx context.Context, tenantID uuid.UUID, actorID *uuid.UUID) ([]*domain.CelebrationType, error)
	GetCelebrationType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.CelebrationType, error)
	UpdateCelebrationType(ctx context.Context, cmd CelebrationTypeCommand) (*domain.CelebrationType, error)
	DeleteCelebrationType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateCelebration(ctx context.Context, cmd CelebrationCommand) (*domain.CelebrationListItem, error)
	ListCelebrations(ctx context.Context, tenantID uuid.UUID) ([]*domain.CelebrationListItem, error)
	GetCelebration(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.CelebrationListItem, error)
	UpdateCelebration(ctx context.Context, cmd CelebrationCommand) (*domain.CelebrationListItem, error)
	DeleteCelebration(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	RunCelebrationDailyJob(ctx context.Context, cmd RunCelebrationDailyJobCommand) (*domain.CelebrationJobResult, error)
	ListCelebrationDailyJobRuns(ctx context.Context, tenantID uuid.UUID, limit int32, offset int32) ([]*domain.ScheduledJobRun, error)
	ListRegisteredScheduledJobs(ctx context.Context) ([]domain.RegisteredScheduledJob, error)
	RunScheduledJob(ctx context.Context, cmd RunScheduledJobCommand) (*domain.ScheduledJobResult, error)
	ListScheduledJobRuns(ctx context.Context, tenantID uuid.UUID, jobKey string, limit int32, offset int32) ([]*domain.ScheduledJobRun, error)
	CreateNotificationMaster(ctx context.Context, cmd NotificationMasterCommand) (*domain.NotificationMaster, error)
	ListNotificationMasters(ctx context.Context, tenantID uuid.UUID, actorID *uuid.UUID) ([]*domain.NotificationMaster, error)
	GetNotificationMaster(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.NotificationMaster, error)
	UpdateNotificationMaster(ctx context.Context, cmd NotificationMasterCommand) (*domain.NotificationMaster, error)
	DeleteNotificationMaster(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListEffectiveNotificationPreferences(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, actorID *uuid.UUID) ([]*domain.EffectiveNotificationPreference, error)
	UpsertNotificationPreference(ctx context.Context, cmd NotificationPreferenceCommand) (*domain.NotificationPreference, error)
	DeleteNotificationPreference(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	SendNotification(ctx context.Context, cmd SendNotificationCommand) (*domain.NotificationSendResult, error)
	GetEmailProviderSettings(ctx context.Context, tenantID uuid.UUID) (*domain.EmailProviderSettings, error)
	UpsertEmailProviderSettings(ctx context.Context, cmd EmailProviderSettingsCommand) (*domain.EmailProviderSettings, error)
	TestEmailProviderSettings(ctx context.Context, cmd EmailProviderTestCommand) (*domain.EmailProviderSettings, error)
	DeleteEmailProviderSettings(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	GetCommunicationProviderSettings(ctx context.Context, tenantID uuid.UUID) (*domain.CommunicationProviderSettings, error)
	UpsertCommunicationProviderSettings(ctx context.Context, cmd CommunicationProviderSettingsCommand) (*domain.CommunicationProviderSettings, error)
	TestCommunicationProviderSettings(ctx context.Context, cmd CommunicationProviderTestCommand) (*domain.CommunicationProviderSettings, error)
	DeleteCommunicationProviderSettings(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	GetStorageProviderSettings(ctx context.Context, tenantID uuid.UUID) (*domain.StorageProviderSettings, error)
	UpsertStorageProviderSettings(ctx context.Context, cmd StorageProviderSettingsCommand) (*domain.StorageProviderSettings, error)
	TestStorageProviderSettings(ctx context.Context, cmd StorageProviderTestCommand) (*domain.StorageProviderSettings, error)
	DeleteStorageProviderSettings(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	GetPushProviderSettings(ctx context.Context, tenantID uuid.UUID) (*domain.PushProviderSettings, error)
	UpsertPushProviderSettings(ctx context.Context, cmd PushProviderSettingsCommand) (*domain.PushProviderSettings, error)
	TestPushProviderSettings(ctx context.Context, cmd PushProviderTestCommand) (*domain.PushProviderSettings, error)
	DeletePushProviderSettings(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListNotificationInbox(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, isRead *bool, notificationMasterID *uuid.UUID, limit int32, offset int32) ([]*domain.NotificationInboxItem, error)
	ListNotificationInboxPage(ctx context.Context, filter domain.NotificationInboxFilter) (*domain.NotificationInboxPage, error)
	CountUnreadNotifications(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) (int64, error)
	MarkNotificationRead(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	MarkNotificationUnread(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	MarkAllNotificationsRead(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, actorID *uuid.UUID) error
	DeleteNotificationInboxItem(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListNotificationLogs(ctx context.Context, tenantID uuid.UUID, userID *uuid.UUID, status *string, channel *string, bulkID *uuid.UUID, limit int32, offset int32) ([]*domain.NotificationLog, error)
	UpsertDeviceToken(ctx context.Context, cmd DeviceTokenCommand) (*domain.DeviceToken, error)
	ListDeviceTokens(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) ([]*domain.DeviceToken, error)
	ListDeviceTokensByDeviceID(ctx context.Context, tenantID uuid.UUID, deviceID string) ([]*domain.DeviceToken, error)
	DeleteDeviceToken(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateJobPosition(ctx context.Context, cmd JobPositionCommand) (*domain.JobPosition, error)
	ListJobPositions(ctx context.Context, filter domain.JobPositionFilter) (*domain.JobPositionPage, error)
	GetJobPosition(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.JobPosition, error)
	UpdateJobPosition(ctx context.Context, cmd JobPositionCommand) (*domain.JobPosition, error)
	DeleteJobPosition(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateJobPositionLocation(ctx context.Context, cmd JobPositionLocationCommand) (*domain.JobPositionLocation, error)
	ListJobPositionLocations(ctx context.Context, tenantID uuid.UUID, jobPositionID uuid.UUID) ([]*domain.JobPositionLocation, error)
	GetJobPositionLocation(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.JobPositionLocation, error)
	UpdateJobPositionLocation(ctx context.Context, cmd JobPositionLocationCommand) (*domain.JobPositionLocation, error)
	DeleteJobPositionLocation(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateJobRequisition(ctx context.Context, cmd JobRequisitionCommand) (*domain.JobRequisition, error)
	ListJobRequisitions(ctx context.Context, filter domain.JobRequisitionFilter) (*domain.JobRequisitionPage, error)
	GetJobRequisition(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.JobRequisition, error)
	UpdateJobRequisition(ctx context.Context, cmd JobRequisitionCommand) (*domain.JobRequisition, error)
	SubmitJobRequisition(ctx context.Context, cmd JobRequisitionActionCommand) (*domain.JobRequisition, error)
	ApproveJobRequisition(ctx context.Context, cmd JobRequisitionActionCommand) (*domain.JobRequisition, error)
	RejectJobRequisition(ctx context.Context, cmd JobRequisitionActionCommand) (*domain.JobRequisition, error)
	CloseJobRequisition(ctx context.Context, cmd JobRequisitionActionCommand) (*domain.JobRequisition, error)
	DeleteJobRequisition(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListJobRequisitionLogs(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) ([]*domain.JobRequisitionLog, error)
	CreateJobPosting(ctx context.Context, cmd JobPostingCommand) (*domain.JobPosting, error)
	ListJobPostings(ctx context.Context, filter domain.JobPostingFilter) (*domain.JobPostingPage, error)
	ListPublishedJobPostings(ctx context.Context, tenantID uuid.UUID) ([]*domain.JobPosting, error)
	GetJobPosting(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.JobPosting, error)
	UpdateJobPosting(ctx context.Context, cmd JobPostingCommand) (*domain.JobPosting, error)
	PublishJobPosting(ctx context.Context, cmd JobPostingPublishCommand) (*domain.JobPosting, error)
	ExpireJobPostings(ctx context.Context, tenantID uuid.UUID) ([]*domain.JobPosting, error)
	CloseJobPosting(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) (*domain.JobPosting, error)
	DeleteJobPosting(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateCandidate(ctx context.Context, cmd CandidateCommand) (*domain.Candidate, error)
	ListCandidates(ctx context.Context, filter domain.CandidateFilter) (*domain.CandidatePage, error)
	GetCandidate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Candidate, error)
	UpdateCandidate(ctx context.Context, cmd CandidateCommand) (*domain.Candidate, error)
	DeleteCandidate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	LinkCandidateApplicantAccount(ctx context.Context, cmd CandidateApplicantAccountCommand) (*domain.CandidateApplicantAccount, error)
	GetApplicantPortal(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) (*domain.ApplicantPortal, error)
	CreateCandidateApplication(ctx context.Context, cmd CandidateApplicationCommand) (*domain.CandidateApplication, error)
	ListCandidateApplications(ctx context.Context, filter domain.CandidateApplicationFilter) (*domain.CandidateApplicationPage, error)
	GetCandidateApplication(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.CandidateApplication, error)
	UpdateCandidateApplication(ctx context.Context, cmd CandidateApplicationCommand) (*domain.CandidateApplication, error)
	MoveCandidateApplicationStatus(ctx context.Context, cmd CandidateApplicationMoveCommand) (*domain.CandidateApplication, error)
	DeleteCandidateApplication(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListCandidateApplicationEvents(ctx context.Context, tenantID uuid.UUID, applicationID uuid.UUID) ([]*domain.CandidateApplicationEvent, error)
	CreateInterviewRound(ctx context.Context, cmd InterviewRoundCommand) (*domain.InterviewRound, error)
	ListInterviewRounds(ctx context.Context, filter domain.InterviewRoundFilter) (*domain.InterviewRoundPage, error)
	GetInterviewRound(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.InterviewRound, error)
	UpdateInterviewRound(ctx context.Context, cmd InterviewRoundCommand) (*domain.InterviewRound, error)
	UpdateInterviewRoundStatus(ctx context.Context, cmd InterviewRoundStatusCommand) (*domain.InterviewRound, error)
	DeleteInterviewRound(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateOfferLetterTemplate(ctx context.Context, cmd OfferLetterTemplateCommand) (*domain.OfferLetterTemplate, error)
	ListOfferLetterTemplates(ctx context.Context, tenantID uuid.UUID) ([]*domain.OfferLetterTemplate, error)
	GetOfferLetterTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.OfferLetterTemplate, error)
	UpdateOfferLetterTemplate(ctx context.Context, cmd OfferLetterTemplateCommand) (*domain.OfferLetterTemplate, error)
	DeleteOfferLetterTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateOfferLetter(ctx context.Context, cmd OfferLetterCommand) (*domain.OfferLetter, error)
	ListOfferLetters(ctx context.Context, filter domain.OfferLetterFilter) (*domain.OfferLetterPage, error)
	ListOfferLettersByApplication(ctx context.Context, tenantID uuid.UUID, applicationID uuid.UUID) ([]*domain.OfferLetter, error)
	GetLatestOfferLetterByApplication(ctx context.Context, tenantID uuid.UUID, applicationID uuid.UUID) (*domain.OfferLetter, error)
	GetOfferLetter(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.OfferLetter, error)
	GetOfferLetterBySignatureToken(ctx context.Context, token string) (*domain.OfferLetter, error)
	UpdateOfferLetter(ctx context.Context, cmd OfferLetterCommand) (*domain.OfferLetter, error)
	UpdateOfferLetterStatus(ctx context.Context, cmd OfferLetterStatusCommand) (*domain.OfferLetter, error)
	SignOfferLetter(ctx context.Context, cmd OfferLetterSignatureCommand) (*domain.OfferLetter, error)
	DeleteOfferLetter(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListOfferLetterEvents(ctx context.Context, tenantID uuid.UUID, offerLetterID uuid.UUID) ([]*domain.OfferLetterEvent, error)
	CreateEmployeeLetterTemplate(ctx context.Context, cmd EmployeeLetterTemplateCommand) (*domain.EmployeeLetterTemplate, error)
	ListEmployeeLetterTemplates(ctx context.Context, tenantID uuid.UUID, letterType *string) ([]*domain.EmployeeLetterTemplate, error)
	GetEmployeeLetterTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.EmployeeLetterTemplate, error)
	UpdateEmployeeLetterTemplate(ctx context.Context, cmd EmployeeLetterTemplateCommand) (*domain.EmployeeLetterTemplate, error)
	DeleteEmployeeLetterTemplate(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	GenerateEmployeeLetter(ctx context.Context, cmd EmployeeLetterCommand) (*domain.EmployeeLetter, error)
	ListEmployeeLetters(ctx context.Context, filter domain.EmployeeLetterFilter) (*domain.EmployeeLetterPage, error)
	GetEmployeeLetter(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.EmployeeLetter, error)
	GetEmployeeLetterBySignatureToken(ctx context.Context, token string) (*domain.EmployeeLetter, error)
	UpdateEmployeeLetterStatus(ctx context.Context, cmd EmployeeLetterStatusCommand) (*domain.EmployeeLetter, error)
	SignEmployeeLetter(ctx context.Context, cmd EmployeeLetterSignatureCommand) (*domain.EmployeeLetter, error)
	DeleteEmployeeLetter(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListEmployeeLetterEvents(ctx context.Context, tenantID uuid.UUID, employeeLetterID uuid.UUID) ([]*domain.EmployeeLetterEvent, error)
	RenderEmployeeLetterPDF(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) ([]byte, string, error)
	CreateOnboardingWorkflow(ctx context.Context, cmd OnboardingWorkflowCommand) (*domain.OnboardingWorkflow, error)
	ListOnboardingWorkflows(ctx context.Context, tenantID uuid.UUID) ([]*domain.OnboardingWorkflow, error)
	GetOnboardingWorkflow(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.OnboardingWorkflow, error)
	UpdateOnboardingWorkflow(ctx context.Context, cmd OnboardingWorkflowCommand) (*domain.OnboardingWorkflow, error)
	DeleteOnboardingWorkflow(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateOnboardingTask(ctx context.Context, cmd OnboardingTaskCommand) (*domain.OnboardingTask, error)
	ListOnboardingTasks(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID) ([]*domain.OnboardingTask, error)
	GetOnboardingTask(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.OnboardingTask, error)
	UpdateOnboardingTask(ctx context.Context, cmd OnboardingTaskCommand) (*domain.OnboardingTask, error)
	DeleteOnboardingTask(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateOnboardingWorkflowAssignment(ctx context.Context, cmd OnboardingAssignmentCommand) (*domain.OnboardingWorkflowAssignment, error)
	ListOnboardingWorkflowAssignments(ctx context.Context, tenantID uuid.UUID) ([]*domain.OnboardingWorkflowAssignment, error)
	UpdateOnboardingWorkflowAssignment(ctx context.Context, cmd OnboardingAssignmentCommand) (*domain.OnboardingWorkflowAssignment, error)
	DeleteOnboardingWorkflowAssignment(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	StartCandidateOnboarding(ctx context.Context, cmd StartCandidateOnboardingCommand) (*domain.CandidateOnboarding, error)
	ListCandidateOnboardings(ctx context.Context, filter domain.CandidateOnboardingFilter) (*domain.CandidateOnboardingPage, error)
	GetCandidateOnboarding(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.CandidateOnboarding, error)
	GetCandidateOnboardingByCandidate(ctx context.Context, tenantID uuid.UUID, candidateID uuid.UUID) (*domain.CandidateOnboarding, error)
	UpdateCandidateOnboardingTaskStatus(ctx context.Context, cmd CandidateOnboardingTaskStatusCommand) (*domain.CandidateOnboarding, error)
	DeleteCandidateOnboarding(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListCandidateOnboardingEvents(ctx context.Context, tenantID uuid.UUID, candidateOnboardingID uuid.UUID) ([]*domain.CandidateOnboardingEvent, error)
	ListLeaveReportRows(ctx context.Context, filter domain.LeaveReportFilter) ([]*domain.LeaveReportRow, error)
	GetLeaveReportSummary(ctx context.Context, filter domain.LeaveReportFilter) (*domain.LeaveReportSummary, error)
	CreateLeaveApprovalWorkflow(ctx context.Context, cmd LeaveApprovalWorkflowCommand) (*domain.LeaveApprovalWorkflow, error)
	ListLeaveApprovalWorkflows(ctx context.Context, tenantID uuid.UUID) ([]*domain.LeaveApprovalWorkflow, error)
	UpdateLeaveApprovalWorkflow(ctx context.Context, cmd LeaveApprovalWorkflowCommand) (*domain.LeaveApprovalWorkflow, error)
	DeleteLeaveApprovalWorkflow(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateLeaveApprovalWorkflowStep(ctx context.Context, cmd LeaveApprovalWorkflowStepCommand) (*domain.LeaveApprovalWorkflowStep, error)
	ListLeaveApprovalWorkflowSteps(ctx context.Context, tenantID uuid.UUID, workflowID uuid.UUID) ([]*domain.LeaveApprovalWorkflowStep, error)
	UpdateLeaveApprovalWorkflowStep(ctx context.Context, cmd LeaveApprovalWorkflowStepCommand) (*domain.LeaveApprovalWorkflowStep, error)
	DeleteLeaveApprovalWorkflowStep(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	ListPendingApprovalsByApprover(ctx context.Context, tenantID uuid.UUID, approverID uuid.UUID) ([]*domain.LeaveApproval, error)
	ApproveLeave(ctx context.Context, cmd ApproveLeaveCommand) (*domain.LeaveApplication, error)
	RejectLeave(ctx context.Context, cmd RejectLeaveCommand) (*domain.LeaveApplication, error)
	CancelLeave(ctx context.Context, cmd CancelLeaveCommand) (*domain.LeaveApplication, error)
	CreateEmploymentType(ctx context.Context, cmd EmploymentTypeCommand) (*domain.EmploymentType, error)
	ListEmploymentTypes(ctx context.Context, tenantID uuid.UUID, actorID *uuid.UUID) ([]*domain.EmploymentType, error)
	GetEmploymentType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.EmploymentType, error)
	UpdateEmploymentType(ctx context.Context, cmd EmploymentTypeCommand) (*domain.EmploymentType, error)
	DeleteEmploymentType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateMaritalStatus(ctx context.Context, cmd MaritalStatusCommand) (*domain.MaritalStatus, error)
	ListMaritalStatuses(ctx context.Context, tenantID uuid.UUID, actorID *uuid.UUID) ([]*domain.MaritalStatus, error)
	GetMaritalStatus(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.MaritalStatus, error)
	UpdateMaritalStatus(ctx context.Context, cmd MaritalStatusCommand) (*domain.MaritalStatus, error)
	DeleteMaritalStatus(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreatePolicyType(ctx context.Context, cmd PolicyTypeCommand) (*domain.PolicyType, error)
	ListPolicyTypes(ctx context.Context, tenantID uuid.UUID) ([]*domain.PolicyType, error)
	GetPolicyType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.PolicyType, error)
	UpdatePolicyType(ctx context.Context, cmd PolicyTypeCommand) (*domain.PolicyType, error)
	DeletePolicyType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateCompanyPolicy(ctx context.Context, cmd CompanyPolicyCommand) (*domain.CompanyPolicy, error)
	ListCompanyPolicies(ctx context.Context, tenantID uuid.UUID, policyTypeID *uuid.UUID) ([]*domain.CompanyPolicy, error)
	GetCompanyPolicy(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.CompanyPolicy, error)
	UpdateCompanyPolicy(ctx context.Context, cmd CompanyPolicyCommand) (*domain.CompanyPolicy, error)
	DeleteCompanyPolicy(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateSubscriptionPlan(ctx context.Context, cmd SubscriptionPlanCommand) (*domain.SubscriptionPlan, error)
	ListSubscriptionPlans(ctx context.Context) ([]*domain.SubscriptionPlan, error)
	ListActiveSubscriptionPlans(ctx context.Context) ([]*domain.SubscriptionPlan, error)
	GetSubscriptionPlan(ctx context.Context, id uuid.UUID) (*domain.SubscriptionPlan, error)
	UpdateSubscriptionPlan(ctx context.Context, cmd SubscriptionPlanCommand) (*domain.SubscriptionPlan, error)
	DeleteSubscriptionPlan(ctx context.Context, id uuid.UUID, actorID *uuid.UUID) error
	CreateTenantSubscription(ctx context.Context, cmd TenantSubscriptionCommand) (*domain.TenantSubscription, error)
	ListTenantSubscriptions(ctx context.Context, tenantID uuid.UUID) ([]*domain.TenantSubscription, error)
	GetTenantSubscription(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.TenantSubscription, error)
	GetCurrentTenantSubscription(ctx context.Context, tenantID uuid.UUID) (*domain.TenantSubscription, error)
	UpdateTenantSubscription(ctx context.Context, cmd TenantSubscriptionCommand) (*domain.TenantSubscription, error)
	DeleteTenantSubscription(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateEmployee(ctx context.Context, cmd CreateEmployeeCommand) (*domain.Employee, error)
	ListEmployees(ctx context.Context, tenantID uuid.UUID) ([]*domain.EmployeeListItem, error)
	GetEmployeeProfile(ctx context.Context, tenantID uuid.UUID, employeeID uuid.UUID, actorID *uuid.UUID) (*domain.EmployeeProfile, error)
	GetEmployeeSelfProfile(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID, actorID *uuid.UUID) (*domain.EmployeeProfile, error)
	UpdateEmployee(ctx context.Context, cmd UpdateEmployeeCommand) (*domain.EmployeeProfile, error)
	DeactivateEmployee(ctx context.Context, tenantID uuid.UUID, employeeID uuid.UUID, actorID *uuid.UUID) error
	ResendEmployeeCredentials(ctx context.Context, cmd EmployeeCredentialActionCommand) (*domain.EmployeeCredentialEvent, error)
	ResetEmployeeTemporaryPassword(ctx context.Context, cmd EmployeeCredentialActionCommand) (*domain.EmployeeCredentialEvent, error)
	ListEmployeeCredentialEvents(ctx context.Context, tenantID uuid.UUID, employeeID uuid.UUID, limit int32) ([]*domain.EmployeeCredentialEvent, error)
	CreateEmployeeExit(ctx context.Context, cmd CreateEmployeeExitCommand) (*domain.EmployeeExitRequest, error)
	ListEmployeeExits(ctx context.Context, filter domain.EmployeeExitFilter) (*domain.EmployeeExitPage, error)
	GetEmployeeExit(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.EmployeeExitRequest, error)
	ApproveEmployeeExit(ctx context.Context, cmd EmployeeExitActionCommand) (*domain.EmployeeExitRequest, error)
	RejectEmployeeExit(ctx context.Context, cmd EmployeeExitActionCommand) (*domain.EmployeeExitRequest, error)
	CancelEmployeeExit(ctx context.Context, cmd EmployeeExitActionCommand) (*domain.EmployeeExitRequest, error)
	CompleteEmployeeExit(ctx context.Context, cmd EmployeeExitActionCommand) (*domain.EmployeeExitRequest, error)
	UpdateEmployeeExitTaskStatus(ctx context.Context, cmd EmployeeExitTaskStatusCommand) (*domain.EmployeeExitRequest, error)
	CreateDocumentType(ctx context.Context, cmd DocumentTypeCommand) (*domain.DocumentType, error)
	ListDocumentTypes(ctx context.Context, tenantID uuid.UUID) ([]*domain.DocumentType, error)
	GetDocumentType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.DocumentType, error)
	UpdateDocumentType(ctx context.Context, cmd DocumentTypeCommand) (*domain.DocumentType, error)
	DeleteDocumentType(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, actorID *uuid.UUID) error
	CreateEmployeeDocument(ctx context.Context, cmd EmployeeDocumentCommand) (*domain.EmployeeDocument, error)
	UpdateEmployeeDocument(ctx context.Context, cmd EmployeeDocumentCommand) (*domain.EmployeeDocument, error)
	ReviewEmployeeDocument(ctx context.Context, cmd EmployeeDocumentReviewCommand) (*domain.EmployeeDocument, error)
	DeleteEmployeeDocument(ctx context.Context, tenantID uuid.UUID, employeeID uuid.UUID, documentID uuid.UUID, actorID *uuid.UUID) error
}

type SystemRunner interface {
	RunAsSystem(ctx context.Context, fn func(context.Context) error) error
}
